### ISSUE TITLE
Out of memory. Cannot allocate

### ISSUE THREAD

**Issue by WhitePassRanger** [OpenTTD/OpenTTD#8343] opened 2020-11-23 13:50 UTC
## Version of OpenTTD
1.10.3 (0)
## Expected result
No crash
## Actual result
Game crashed, shut down, generated report.
## Steps to reproduce
Unknown
[crash.log](https://github.com/OpenTTD/OpenTTD/files/5583352/crash.log)
![crash](https://user-images.githubusercontent.com/44106778/99969667-09d10f80-2d58-11eb-80fa-0c1be9d39c3d.png)

**Comment by James103** [comment] 2020-11-23 13:54
1. Have you tried closing other apps/programs on the computer OpenTTD was running on?
2. How much RAM do you have on said computer?
3. Do you have the crash.sav? If so, can you please post it here?

**Comment by WhitePassRanger** [comment] 2020-11-23 14:11
1. No I have not, so far running similar programs without another crash.
2. 8 GB
3. github does not recognize .sav files so it is zipped
[crash.zip](https://github.com/OpenTTD/OpenTTD/files/5583508/crash.zip)

**Comment by LordAro** [comment] 2020-11-23 14:23
Working out the causes of out of memory errors is a Hard problem, especially on Windows.
As it's a one-off, I'm going to say that your computer was out of memory.

"Running similar programs" not producing similar crashes isn't a particularly repeatable scenario that we can do anything about. Especially in today's world of browsers running many separate processes with arbitrarily large amounts of memory depending on what they've got open, how long they've been open and the phase of the moon.

The number to watch in Task Manager is "Committed" - when that hits 100%, things will start crashing.
![image](https://user-images.githubusercontent.com/4007992/99973017-37897900-2d97-11eb-8488-a869e77b7ec3.png)

**Closed as completed by LordAro** 2020-11-23 14:23 UTC

**Comment by WhitePassRanger** [comment] 2020-11-23 14:28
That's kind of what I figured.  I didn't intend this to be a complaint, I just figured I would submit the crash data in case there was any useful information there.  I do appreciate the quick responses!

Thank you for your time!
