### ISSUE TITLE
Low framerate on macOS

### ISSUE THREAD

**Issue by darrenrhs** [OpenTTD/OpenTTD#8300] opened 2020-08-31 01:08 UTC
## Version of OpenTTD

1.9.0 and later, at least

## Expected result

All operating systems have comparable performance when running on comparable hardware.

## Actual result

the macOS version of OpenTTD has unreasonably poor performance

## Steps to reproduce

Run official OpenTTD builds on a macOS system

## Misc

 This is a revival of [this](https://github.com/OpenTTD/OpenTTD/issues/7644#issue-465444378) bug (#7644) which was closed without being resolved. The 'fix' does not work and has not been contributed to the main build in any case.

I've found that the game runs better under 32-bit wine than it does natively. This is of course not a solution since 32-bit support was dropped in Catalina.

**Comment by FLHerne** [comment] 2020-08-31 13:16
> This is a revival of this bug (#7644) which was closed without being resolved. The 'fix' does not work and has not been contributed to the main build in any case.

#7741 (and #7721, which it superseded) have been included since 1.9.3, and fixed this for most people who reported the issue.

What macOS version and device do you have? Did you use a build from the OpenTTD website or compile locally, and if so with which SDK version?

**Comment by newtrashcan** [comment] 2020-09-26 11:39
I have this problem too.
OpenTTD 1.10.3 downloaded from website.
macos 10.14.6 (Mojave) iMAC 27'' 5K i5 -6 cores, 8Gb RAM, Radeon 575X 4 GB
When you launch app it's speed is terrible (fps is less than 10-15 per second) and cursor is laggy. 
It I try to set resolution in game options screen to native it does not do it (and image is stayed pixelated x2 from 1440 resolution).
If I set "Launch in low resolution" option in Finder  and launch app it work as intended with very good speed, but the picture quality is bad due to upscalling.

**Comment by Cin316** [comment] 2020-10-03 18:07
I also have this problem.
I'm using OpenTTD 1.10.3 downloaded from the website.
macOS 10.14.6 on a Mac Book Pro (2018), 8GB RAM, 2.3 GHz Intel Core i5, Intel Iris Plus Graphics 655
Every version of OpenTTD after 1.8 has been unplayable laggy.  I have the exact same issues that @newtrashcan reported.
Checking the "Launch in low resolution" option in Finder doesn't help much for me.

Because of these issues I've been stuck playing OpenTTD 1.8.0 for a long time now.

I'm willing to look into the code and try to fix it.  But I've never worked in the OpenTTD codebase before, so I could use some direction.

**Comment by andythenorth** [comment] 2020-10-08 19:42
Tried turning off full animation?
Makes a 10x fps difference for me in FFWD in a new map.  

Try changing your colorspace (Displays) between Color LCD, sRGB, or other settings - it can make a difference.

Neither are long-term solutions.

I don't currently have lag in recent games using OpenTTD 1.10.2, playing retina, not low resolution.

macOS 10.15.6 Macbook Pro 16" 2019 16GB 2.3Ghz i9, AMD Radeon Pro 5500M / Intel UHD Graphics 630
I also have older 13" Macbook Pros that don't have noticeably worse peformance.

I have seen poor OpenTTD performance on mac in last 2-4 years, and multiple genuine issues have been addressed, but nothing conclusive recently.  E.g. https://github.com/OpenTTD/OpenTTD/issues/7644#issuecomment-509379775 and similar are recent issues/fixes.

Behaviours I've seen but can't diagnose / repro reliably:
* having the train window open cause fps to
* there's something odd with news messages, where game fps lags for unknown reason, then opening a recent news message bumps fps back up

**Comment by Cin316** [comment] 2020-10-18 00:56
Turning off full animation boosts me from 18 fps to 32 fps, on a blank, new OpenTTD world in 1.10.3.  I launched OpenTTD with the "Launch in low resolution" option checked.

Again, OpenTTD 1.8.0 runs great with the exact same settings.

I'm using the OpenGFX graphics pack for those tests.

I'm suspicious that this problem may be specific to Mojave, since I just tested on a computer running Catalina and it runs OpenTTD 1.10.3 great.

**Comment by newtrashcan** [comment] 2020-10-24 19:05
I can confirm that turning off "full animation" make game playable on Mojave 30-31 fps. Low resolution works too.
If the resolution is set to full and full animations in emabled info panel shows that it takes signifially more tome on "rendering ..." about 0,2 s meanwhile all other parameters les then 0,01.
AN I found that if ther is no water tiles in the view speed on simulation increases.
CPU load bu the game is about 100% (but only single core is used), GPU load is about 20-30%.
(OpenTTD 1.10.3 downloaded from website. macos 10.14.6 (Mojave) iMAC 27'' 5K i5 -6 cores, 8Gb RAM, Radeon 575X 4 GB)

**Comment by LordAro** [comment] 2021-02-21 17:07
Closing this. There have been lots of fixes in this area in the last few weeks, with other macOS users reporting significant speed ups, mostly thanks to #8652

**Closed as completed by LordAro** 2021-02-21 17:07 UTC
Labels: OS: MacOS
