### ISSUE TITLE
[Bug]: [Station] no longer accepts [Goods]. For just about all Desert stations with 14.0-beta2

### ISSUE THREAD

**Issue by Bekofz** [OpenTTD/OpenTTD#11998] opened 2024-02-05 07:58 UTC
### Version of OpenTTD

14.0-beta2, Win11

### Expected result

Not having messages about not accepting goods

### Actual result

Message for most(all?) stations aboutr not accepting [goods] no longer.

![2024-02-05_085658](https://github.com/OpenTTD/OpenTTD/assets/158836489/a3418531-3478-4e7c-ae21-b2958f1acb93)

### Steps to reproduce

1 Load old save in new beta2
2. When month switches, all stations report not accepting goods

**Comment by James103** [comment] 2024-02-05 08:00
Same issue as #11995. Furthermore, this means banks in sub-tropical climates are cosmetics only, which should not be the case.

**Comment by Bekofz** [comment] 2024-02-05 08:00
Bank is (half?) in coveraga.
![2024-02-05_090016](https://github.com/OpenTTD/OpenTTD/assets/158836489/edea077c-35ab-43fc-8234-ca167c7927bf)

**Comment by LordAro** [comment] 2024-02-05 10:09
Yup, duplicate of #11995, fix coming soon!

**Closed as not planned by LordAro** 2024-02-05 10:09 UTC
