### ISSUE TITLE
Linkgraph takes a very long time to recalculate on large save, causing hangs

### ISSUE THREAD

**Issue by Awizonosz** [OpenTTD/OpenTTD#7842] opened 2019-11-23 13:11 UTC
Can you do something with OpenTTD so j could again play on my save?

[Save that crach in every version of OpenTTD.zip](https://github.com/OpenTTD/OpenTTD/files/3882457/Save.that.crach.in.every.version.of.OpenTTD.zip)

**Comment by LordAro** [comment] 2019-11-23 13:18
We require some more details. Which versions have you tried? What are the symptoms of the crash? Can you upload all the associated crash.* files ?

**Comment by Awizonosz** [comment] 2019-11-23 13:43
When j am doing anything like watching or creating new train line on that save approximately every 20 minutes it's crash like that how it is on screenshot.

![Bug](https://user-images.githubusercontent.com/58109358/69479571-07fc0580-0dff-11ea-8b7c-8158a99616c4.png)

**Comment by LordAro** [comment] 2019-11-23 13:52
When running the save myself, the game actually deadlocks (hangs) at 20 May, a few ingame days after loading. This appears to be occurring inside the Linkgraph code.

If the game is actually crashing for you, that's a separate issue that we need those crash files to be able to diagnose. These will be in your "personal directory" - most likely `C:\Users\<username>\Documents\OpenTTD`, or next to openttd.exe

**Comment by Awizonosz** [comment] 2019-11-23 14:02
J find that in C:\Users\<username>\Documents\OpenTTD named as crash

[crash.log](https://github.com/OpenTTD/OpenTTD/files/3882514/crash.log)

**Comment by LordAro** [comment] 2019-11-23 14:12
OK, that's unrelated to this issue - that file is from 1.9.1. When you say the game crashes, what do you mean? Is the game hanging, or exiting to desktop?

**Comment by Awizonosz** [comment] 2019-11-23 14:17
Its hanging for 3-7 minutes mostly

**Comment by JGRennison** [comment] 2019-11-24 15:36
Your save game is set to take 16 days to recalculate each the cargo distribution graph.
Your largest cargo distribution graph has 1516 stations, and as the time taken to recalculate each graph is roughly proportional to N² log(N) in the number of stations, it takes significantly more than 16 days to calculate.
As your network is heavily overloaded anyway, you should probably set the distribution accuracy setting to its minimum value (2), and drastically increase the values of the settings for how often the distribution graph is updated and how many days are taken for it to be recalculated, until it no longer hangs periodically. These are in "environment" -> "cargo distribution" in the settings window. You will need to set the settings category to "advanced" or "expert".

**Comment by James103** [comment] 2019-11-24 15:50
Is it possible to optimize the link graph calculation so that it takes less than O(N² log(N)) time (N proportional to station count)? If so, what's the lowest amount of time you can optimize towards?

**Comment by Awizonosz** [comment] 2019-11-24 16:02
Thanks

**Comment by JGRennison** [comment] 2019-11-24 16:57
> Is it possible to optimize the link graph calculation so that it takes less than O(N² log(N)) time (N proportional to station count)? If so, what's the lowest amount of time you can optimize towards?

The existing algorithm can be optimised a bit to reduce the constants, but it doesn't make a huge difference. You still get O(N² log(N)) behaviour. It's more pragmatic to change the scheduler to be aware of the how long the recalculation is likely to take.

**Comment by James103** [comment] 2019-12-16 23:42
For large networks and/or when fast-forwarding, I suggest the following for performance reasons:
* "Take **60** days for recalculation of distribution graph"
* "Update distribution graph every **14** days"

**Comment by TrueBrain** [comment] 2021-01-01 19:06
Recently we added a change where the game pauses if linkgraph is taking too long. This at least makes it visible to the user what is going on, instead of just freezing up. Hopefully that helps a bit with mitigating this issue. It should make the game more playable, but of course it is still annoying, as instead of hanging, it pauses the game. One is slightly better, but still not good.

This as a FYI.

**Comment by 2TallTyler** [comment] 2023-04-21 16:17
Automatic linkgraph scheduling is still a valid feature request, but I think we've solved the cause of this bug report, and mitigated it by pausing instead of freezing. I'm going to close it to keep the issue tracker down. 🙂

**Closed as completed by 2TallTyler** 2023-04-21 16:17 UTC
Labels: bug
