### ISSUE TITLE
GUI custom scale

### ISSUE THREAD

**Issue by raitocz** [OpenTTD/OpenTTD#7387] opened 2019-03-19 14:24 UTC
## Version of OpenTTD
Any
## Expected result
Ability to specify the GUI scale by any float from 1 to 4, for example: 1.25, 1.5 or 2.24.. or at least add more values to select (1x, 1.25x, 1.5x, 1.75x...)
## Actual result
When playing on smaller screens, like 15,3" laptop with FULLHD resolution 1920x1080 the game UI is very tiny. But options to scale GUI are only: 2x and 4x. When using the 2x option, the game UI is large and ugly and it is just too much. Windows & icons are unnecessarily big and it is not possible to fit many of them on screen. 
## Steps to reproduce
...

**Comment by PeterN** [comment] 2019-03-19 14:26
Duplicate of #6797

**Closed as completed by PeterN** 2019-03-19 14:26 UTC
