### ISSUE TITLE
[Crash]: Crash on Mac OSX when using 32-bpp basest

### ISSUE THREAD

**Issue by JGRennison** [OpenTTD/OpenTTD#9788] opened 2022-01-11 17:57 UTC
### Version of OpenTTD

Nightly: 20220108-master-gad54d08abd

### Steps to reproduce

User reports crash at startup when using 32-bpp basest such as abase/zbase.

This appears to be related to Apple touchbar support and #9743

This is forwarded from: https://github.com/JGRennison/OpenTTD-patches/issues/358

### Upload crash files

https://github.com/JGRennison/OpenTTD-patches/files/7844796/Archive.zip

(The stack trace in the above is a bit rubbish, so this non-vanilla one may be more useful: https://github.com/JGRennison/OpenTTD-patches/files/7844783/Archive.zip)

**Comment by LordAro** [comment] 2022-08-29 17:35
Closing as duplicate of #9876 - I know this is the wrong way round, but the other has more discussion

**Closed as not planned by LordAro** 2022-08-29 17:35 UTC
Labels: bug
