### ISSUE TITLE
Can't zoom minimap in any further when at 1x scale

### ISSUE THREAD

**Issue by James103** [OpenTTD/OpenTTD#9173] opened 2021-05-01 23:59 UTC
## Version of OpenTTD
1.11.1

## Expected result
You should be able to zoom further in when the minimap is at 1x scale. Ideally a 2x and 4x scale should be provided (just like in the main viewport).

## Actual result
You are unable to zoom further in when the minimap is at 1x scale. This can result in players on big screens not being able to see as enough detail as they want, especially concerning #9167 and similar issues.

## Steps to reproduce
1. Start the game on a 1080p screen or higher.
2. Create a new world.
3. Open the minimap.
4. Try to zoom in.
5. Notice that you can't zoom in further than 1x scale.

**Comment by glx22** [comment] 2021-05-02 00:16
Duplicate of #8998 ;)

**Closed as completed by glx22** 2021-05-02 00:16 UTC
