### ISSUE TITLE
Segmentation fault when searching for internet servers

### ISSUE THREAD

**Issue by scovit** [OpenTTD/OpenTTD#8807] opened 2021-03-06 00:38 UTC
## Version of OpenTTD
1.11.0-beta2

## Expected result
Game keeps working

## Actual result
Segmentation fault

## Steps to reproduce
Click on "multiplayer" on the main menu, click on "search internet"

[crash.log](https://github.com/OpenTTD/OpenTTD/files/6094313/crash.log)
![crash](https://user-images.githubusercontent.com/15249203/110188576-7f9b4b80-7e1c-11eb-9ae4-746dca0ac012.png)

**Comment by LordAro** [comment] 2021-03-06 07:23
Duplicate of #8799 (though your title is definitely better at describing the issue, rather than guessing at the cause)

**Closed as completed by LordAro** 2021-03-06 07:23 UTC
