### ISSUE TITLE
Improvements for online content

### ISSUE THREAD

**Issue by radek-sprta** [OpenTTD/OpenTTD#6853] opened 2018-07-15 09:04 UTC
Hello OpenTTD team,

first of all, mad props for all your hard work. I have recently installed the game and it's better than ever. Keep it up.

That said, I think the online content area could see some improvements. The number of addons has grown extensively and it's becoming increasingly hard for a newcomer to choose among them. I have some ideas, that might remedy the situation:

- show the number of download or, ideally, some kind of rating system for the content
- show when was the content last updated, to differentiate between maintained and unmaintained content
- this might be a bit controversial, but rename gamescripts and newgrfs to, say, mods and extensions, as right now, it might be a bit consuming for the newcomers to know what is the content doing.

And some ideas specific to scenarios:
- put the size of the map in description, so you don't have to download and try the scenarios just to see how big the maps are
- mark the scenarios, that require newgrfs not available on bananas. Or, perhaps, remove them entirely.

**Comment by TrueBrain** [comment] 2018-07-15 11:45
Thank you for your suggestions; I think everyone agrees the online content service can use some work. What work exactly, widely difference between who you ask. Internally, the online content service is called BaNaNaS, and the current version is roughly 10 years old.

There have been some efforts to completely rewrite the current version with something new, that can support a bit more, and is a bit more user friendly. It also addresses several of the points mentioned by you. If you like to participate in those efforts (either by ideas, by code, by design, ..), best you can do is drop by our IRC (irc.oftc.net, #openttd), or you can checkout out the initial start for this at @frosch123 his repo:

https://github.com/frosch123/bananas2

Any help is welcome! In the meantime I am going to close this ticket, as most (all?) your points are already addressed in the design document of the above mentioned repository. If you feel they are not, please do contribute in that repository! Thank you! :)

**Closed as completed by TrueBrain** 2018-07-15 11:45 UTC

**Comment by radek-sprta** [comment] 2018-07-15 18:40
Good to hear about BaNaNaS2. I will definitely check out the linked repository and see if I can help in any way!
