### ISSUE TITLE
[Bug]: no SDL xrandr support in linux-generic

### ISSUE THREAD

**Issue by pv2b** [OpenTTD/OpenTTD#11767] opened 2024-01-13 13:11 UTC
### Version of OpenTTD

OpenTTD 13.4, Ubuntu 22.04

### Expected result

When running fullscreen, I expect the UI to be centered on screen. 

### Actual result

Instead, that the UI is centered on the right edge of my screen, so that only half of the toolbar is visible.

This is happening on an Nvidia Geforce RTX 3070. I have 2 monitors set up, both with a resolution of 2560x1440. My primary monitor is on the right. 

### Steps to reproduce

This probably will only happen on a multi-monitor setup. To match my setup exactly, use an Nvidia graphics card, have two monitors in 2560x1440, and have the right monitor as your primary. Then try to run fullscreen. The problem is evident already on the splash screen, because the main menu won't be centered, it'll be offset to the right.

Also note that for some reason the resolution is detected as 5120x1440, so for some reason it thinks my vertical resolution is twice, probably because it's getting the resolution for the entire desktop instead of the monitor it's playing on.

Driver: sdl-opengl (x11) with NVIDIA (proprietary)  driver 535.146.02.

Finally, this appears to be new for version 13.4, version 13.3 does not exhibit this problem.

**Comment by Lamrr** [comment] 2024-01-13 13:27
This might be related to #11353, in which multi-monitor setups under Wayland and X11 result in OpenTTD getting the wrong resolution

**Comment by pv2b** [comment] 2024-01-13 15:27
I agree, looking at the issue it appears this one is a duplicate.

**Comment by ldpl** [comment] 2024-01-14 18:23
Have the same issue and it doesn't seem to be a duplicate of #11353 as not just 13.4 but even 5d2ed80c95673dc73f390c3b5d007caffc8bb17d worked fine for me, so it's a very recent change that caused it.

**Comment by ldpl** [comment] 2024-01-14 21:58
Ok, nvm, apparently this only happens on linux-generic nightly and not on self-built openttd of the same revision so it is duplicate.

**Comment by TrueBrain** [comment] 2024-01-14 22:02
@pv2b 

To spare you reading through a massive comment I wrote in the other ticket, on X11 it sadly enough is common that with multi-monitor a virtual desktop is created which has the two displays combined. This means that if we ask SDL: what displays are there? It tells us 1. And it is HUGE.

There is very little we can do about that, and requires changes in X11 configuration to fix. Wayland reports this information better to SDL (and in result, to us), and should use the right resolution. To force SDL to use Wayland, start OpenTTD with:

`SDL_VIDEODRIVER=wayland ./openttd`

I am still figuring out if our Linux build actually contains Wayland, but that is a separate bug :)

**Comment by pv2b** [comment] 2024-01-15 06:12
> @pv2b
> 
> To spare you reading through a massive comment I wrote in the other ticket, on X11 it sadly enough is common that with multi-monitor a virtual desktop is created which has the two displays combined. This means that if we ask SDL: what displays are there? It tells us 1. And it is HUGE.
> 
> There is very little we can do about that, and requires changes in X11 configuration to fix. Wayland reports this information better to SDL (and in result, to us), and should use the right resolution. To force SDL to use Wayland, start OpenTTD with:
> 
> `SDL_VIDEODRIVER=wayland ./openttd`
> 
> I am still figuring out if our Linux build actually contains Wayland, but that is a separate bug :)

It makes no sense to me for you to say that there's little you can do about it when 13.3 doesn't exhibit the same behaviour, and other games on my system don't act this way. What has changed? Anyway, this is what I get when I try to run the game as you suggest:

```
pvz@pvz-ryzen:~$ SDL_VIDEODRIVER=wayland /opt/openttd/openttd 
Error: Couldn't find any suitable video driver
pvz@pvz-ryzen:~$ 
```

The other suggestion to try with `/opt/openttd/openttd -v sdl-opengl` also doesn't seem to fix it on my system either.

Also, FYI, since I created the ticket, I've updated my system from Ubuntu 22.04 LTS to Ubuntu 23.10.

**Comment by pv2b** [comment] 2024-01-15 08:46
Okay, so if I understand this correctly, the issue isn't with OpenTTD 13.4 in itself, but rather specific to the Linux binaries on the web site, and if I build this myself with the right libraries (hopefully the distro-provided ones will work) this problem will go away for me.

Do you intend on building new binaries for 13.4 any time soon? If so, that'd save me the effort of figuring out how to build them, and it'd also let me confirm that your new build fixes the issue. If not, I'll probably see if I can build new binaries for myself some time this week, whenever I feel like playing this game again.

**Comment by TrueBrain** [comment] 2024-01-15 08:49
We will not re-release 13.4, but we are on track for a new major release (but that will take at least 3 more months). So it depends on your definition of "soon" :D

And yes, self-compiling should resolve the issue (and if not, do let us know).

Another solution btw is to not use fullscreen, but maximize the window. You do lose a bit of screen, but it is a simple workaround for now.

**Closed as completed** 2024-01-15 20:59 UTC
Labels: OS: Linux
