### ISSUE TITLE
Can't type non-latin symbols from keyboard in game on linux

### ISSUE THREAD

**Issue by Nik-mmzd** [OpenTTD/OpenTTD#7296] opened 2019-02-28 12:31 UTC
## Version of OpenTTD
Compiled from adb50cebcc8e2dec65c8e0bc67762763e75176e3
Also 1.8.0 from openttd.org ("Linux Generic Binaries (x86_64, 64bit)" package)

## Expected result
Russian letters in textbox (e.g. vehicle name)

## Actual result
Nothing in textbox, keys act as hotkeys

## Steps to reproduce
Set keyboard layout to russian

## Additional info
```
#  cat /etc/os-release 
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
...
#  uname -a
Linux Raxacoricofallapatorius 4.20.12-arch1-1-ARCH #1 SMP PREEMPT Sat Feb 23 15:11:34 UTC 2019 x86_64 GNU/Linux
#  echo $LC_CTYPE 
ru_RU.UTF-8
#  echo $LANG    
ru_RU.UTF-8
#  echo $XDG_SESSION_TYPE 
x11
#  echo $XDG_SESSION_DESKTOP 
gnome
```
libinput 1.12.6, gnome 3.30.2

Any workaround? If I need to provide more data, just ask

**Comment by PeterN** [comment] 2019-02-28 12:53
I can type non-latin characters using the compose key. That doesn't give me cyrillic characters though.

**Comment by Nik-mmzd** [comment] 2019-02-28 12:56
![image](https://user-images.githubusercontent.com/19509291/53567786-54b4f780-3b71-11e9-8bbd-3f2650b12649.png)
There should be only © symbol... :thinking: 

UPD tried to manually type a letter using char code...
![image](https://user-images.githubusercontent.com/19509291/53567914-baa17f00-3b71-11e9-825b-e8106af043f9.png)
It allows to write a letter, but also writes all keys I typed except ctrl + shift + u.

Maybe something works incorrectly on my side or all should be as on screenshots above?

**Comment by PeterN** [comment] 2019-02-28 13:07
Hmm, the ctrl-shift-u input method doesn't work at all for me in OpenTTD.

**Comment by Nik-mmzd** [comment] 2019-02-28 13:09
ctrl - shift - u (just press), keycode (424 on screenshot above), space. Works for me.

**Comment by Eddi-z** [comment] 2019-02-28 13:11
ctrl+shift+u doesn't do anything here either. must be some external program intercepting your input? that might cause weird effects like this.

**Comment by nielsmh** [comment] 2019-02-28 13:16
Can the game otherwise show these characters? E.g. via language pack or town names generated/in a scenario?

**Comment by Nik-mmzd** [comment] 2019-02-28 13:18
...Xorg?... ctrl-shift-u and compose key are X features, AFAIK
But main question is "how to fix typing russian letters from keyboard", I don't think anybody really will write symbols using ctrl-shift-u/compose key/smth like it

Yes, game can show this characters.
![image](https://user-images.githubusercontent.com/19509291/53568978-474d3c80-3b74-11e9-9536-8f8a08fb133d.png)
![image](https://user-images.githubusercontent.com/19509291/53569003-559b5880-3b74-11e9-8a85-785ad7ca0b9f.png)
![image](https://user-images.githubusercontent.com/19509291/53569103-6e0b7300-3b74-11e9-9ae8-9109392670b3.png)
...and https://github.com/OpenTTD/OpenTTD/blob/master/src/lang/russian.txt

**Comment by Eddi-z** [comment] 2019-02-28 13:20
maybe this is related? https://superuser.com/questions/358749/how-to-disable-ctrlshiftu-in-ubuntu-linux

**Comment by PeterN** [comment] 2019-02-28 13:20
No indeed, but it might be related. Not all Xorg keyboard layouts enable the compose-key the same way, but I'm pretty sure ctrl-shift-u is not handled by Xorg but elsewhere.

**Comment by Eddi-z** [comment] 2019-02-28 13:23
In my setup (opensuse, german keyboard) i can input all kinds of characters using AltGr key. (although most of them display as ? with sprite font)

For example `AltGr+Shift+C` gives me ©

**Comment by Nik-mmzd** [comment] 2019-02-28 13:31
But the problem is typing russian letters from _physical keyboard_ with russian keyboard layout in system...
Why we are talking about compose keys? I'm really confused a bit

**Comment by PeterN** [comment] 2019-02-28 13:33
Yeah, so maybe something else is intercepting it?

**Comment by Eddi-z** [comment] 2019-02-28 13:36
> Why we are talking about compose keys?

Because most of us won't have a physical russian keyboard lying around to test this.

**Comment by nielsmh** [comment] 2019-02-28 13:37
As far as I know, Cyrillic keyboards typically work via a hardware Cyrillic Lock key similar to Caps Lock on Latin-only keyboards?

**Comment by Nik-mmzd** [comment] 2019-02-28 13:41
IDK because russian keyboard layout works in entire system including TTYs...
OpenTTD is first program that is'n able to handle russian input
PS it may be caused by some software upgrade like gnome or libinput... I will try with older software version

@nielsmh no =)
It is usual keyboard, without any additional keys =)
![image](https://user-images.githubusercontent.com/19509291/53570600-f5a6b100-3b77-11e9-80ea-7add134accb8.png)

I mean I can't write russian letters from physical keyboard using russian keyboard layout in system while latin layout works well

**Comment by PeterN** [comment] 2019-02-28 13:45
I've tested with my keyboard set to "ru" in Gnome, and I am able to enter cyrillic characters into OpenTTD.

**Comment by Nik-mmzd** [comment] 2019-02-28 13:54
@PeterN I tried with older system and all works too
Maybe it caused by some library update? I'll try to downgrade libinput, but if it'll not help... IDK what package update could do this thing

**Comment by Eddi-z** [comment] 2019-02-28 13:56
Have you tried looking at the link i posted? it might help isolating the problem if you could try that out

**Comment by ldpl** [comment] 2019-02-28 14:10
I also had this bug at some point (I don't atm). And I spent some trying to fix it and was even reading X11 code for reference. Sadly, I don't remember the details anymore but I came to a conclusion that it's an SDL 1.2 bug that was fixed in SDL2. I can't find that exact bug on sdl bugtracker right now but I recall it was described is some technical terms as it's something to do with X11 sending those symbols differently and SDL failing to handle them correctly.

P.S. I was using -v allegro as a workaround.

**Comment by Nik-mmzd** [comment] 2019-02-28 14:16
> P.S. I was using -v allegro as a workaround.

You mean launching OpenTTD with this argument?

**Comment by ldpl** [comment] 2019-02-28 14:19
@Nik-mmzd yeah, you can select allegro video driver if your openttd is compiled with it.
Ofc allegro has it's own issues but at least non-lating symbols work.

**Comment by Nik-mmzd** [comment] 2019-02-28 14:21
> if your openttd is compiled with it.

How to compile oTTD with allegro support?

**Comment by ldpl** [comment] 2019-02-28 14:27
@Nik-mmzd you need to install allegro dev libraries and re-run `./configure`, which should pick them up automatically and say `checking allegro... found`

Btw, check  `openttd --help` first in case you already have it. It should look like that:
```
List of video drivers:
               sdl: SDL Video Driver
           allegro: Allegro Video Driver
         dedicated: Dedicated Video Driver
              null: Null Video Driver
```

**Comment by Nik-mmzd** [comment] 2019-02-28 14:27
Also. I found one thing. If I'll press a key **really fast** it **will** sometimes print russian letters in input fields O_o
![image](https://user-images.githubusercontent.com/19509291/53573237-11ad5100-3b7e-11e9-9a3c-41dd9ca8ebfb.png)

> Btw, check `openttd --help` first in case you already have it. It should look like that:

Already checked =(

**Comment by Nik-mmzd** [comment] 2019-02-28 14:53
@ldpl yes, all works with allegro =)
Thanks, will use it as work-around

**Comment by nikolas** [comment] 2019-02-28 20:28
@Nik-mmzd you can also try using my SDL 2 branch if you want to experiment: https://github.com/nikolas/OpenTTD/tree/sdl2

I don't have a Russian keyboard to test this, so I'm curious if it works for you, or breaks in a different way. Text input is handled differently in SDL 2.

SDL 2 text input: https://github.com/nikolas/OpenTTD/blob/sdl2/src/video/sdl_v.cpp#L617
SDL 1.2: https://github.com/OpenTTD/OpenTTD/blob/master/src/video/sdl_v.cpp#L592

**Comment by nikolas** [comment] 2019-02-28 20:54
By the way, I can get "ctrl-shift-u-4-2-4-space" to display Ф here in my browser (on Linux/XFCE), but not in OpenTTD. I'll see if I can find a way to reproduce this in OpenTTD..

**Comment by Nik-mmzd** [comment] 2019-02-28 21:20
@nikolas your SDL2 branch just "freeses" at first "frame"
![image](https://user-images.githubusercontent.com/19509291/53598952-1fcb9380-3bb7-11e9-849d-960005162d45.png)
With empty ~/.openttd

![image](https://i.imgur.com/d9JEZex.jpg)
With ~/.openttd contains files from "usual" version. Music is playing, but nothing moves in game window

Nothing interesting in logs (just some warnings about ALSA and JACK)... Nothing happens on screen...

**Comment by nikolas** [comment] 2019-03-04 15:23
@Nik-mmzd wow.. I haven't seen that before. Thanks for giving this a try.

There have been some significant changes with video rendering on this branch, so if you're up to it, you could try again with the latest code.

**Comment by Nik-mmzd** [comment] 2019-03-04 15:46
@nikolas nothing changed for me: stuck at first rendered frame
Still nothing in the logs except ALSA/JACK warnings
Compiled from your SDL2 branch, commit 20a7e0c8a768782f0f55fc333c5410cb2d616162
Git log shows 3c94bddbc221a604dab184f6f1133764bfef03e1, ebc3934ee642e2528768d6747ce6c09869f32b76, 20a7e0c8a768782f0f55fc333c5410cb2d616162 as three last commits

**Comment by Nik-mmzd** [comment] 2019-05-03 16:52
No, bot, no!
It still not working

**Closed as completed** 2019-09-19 15:18 UTC
