### ISSUE TITLE
Visual Studio/OpenTTD Baseset installation folder vs Regression build

### ISSUE THREAD

**Issue by SamuXarick** [OpenTTD/OpenTTD#8018] opened 2020-02-23 12:30 UTC
## Version of OpenTTD
OpenTTD 20200222-master-gea7044a74b
OpenTTD 1.10.0-RC1
## Expected result
Not fail to find a graphic set
## Actual result
Fail to find a graphic set
## Steps to reproduce
Install OpenTTD 1.10.0-RC1, and include OpenGFX, OpenMSX, OpenSFX, copy files from Transport Tycoon CD.
Load OpenTTD master version in visual studio
Right click 'regression' project -> Build

It fails to find a graphic set because it was installed in C:\Program Files\OpenTTD\baseset while the openttd.cfg is in C:\Users\dj_sa\Documents\OpenTTD

If I move C:\Program Files\OpenTTD\baseset into C:\Users\dj_sa\Documents\OpenTTD\baseset the problem disappears.

**Comment by glx22** [comment] 2020-02-23 13:51
Regression uses its own `openttd.cfg`
Seems to be a duplicate of #7311

**Comment by LordAro** [comment] 2020-04-04 13:00
Yeah, duplicate of #7311 (which I'm still not convinced is an actual issue)

**Closed as completed by LordAro** 2020-04-04 13:00 UTC
