### ISSUE TITLE
Very long stalls during town generation

### ISSUE THREAD

**Issue by SamuXarick** [OpenTTD/OpenTTD#7274] opened 2019-02-24 16:06 UTC
## Version of OpenTTD
1.9.0-beta2
## Expected result
Don't take/stall too long
## Actual result
Very long stalls during town generation
## Steps to reproduce
Launch OpenTTD
Click Settings, set these settings:
- Landscape: Temperate landscape
- Land generator: Original
- Proportion of towns that will become cities: 1 in 1
- Initial city size multiplier: 10
Close window
Click New Game, set these values:
- Map size: 4096 * 4096
- No. of towns: High
- Sea level: Medium
Click Generate

Notice the number of stalls occuring during Town generation, usually past 3500. The frequency keeps increasing and increasing...

**Comment by SamuXarick** [comment] 2019-02-24 16:08
town names are english

**Comment by Eddi-z** [comment] 2019-02-24 16:09
most likely the town name generator running out of names.

**Comment by andythenorth** [comment] 2019-02-24 16:34
Duplicate of https://github.com/OpenTTD/OpenTTD/issues/5864

Related to 
- https://github.com/OpenTTD/OpenTTD/issues/6640
- https://github.com/OpenTTD/OpenTTD/issues/6309

May or may not be resolved by https://github.com/OpenTTD/OpenTTD/issues/7059

**Comment by andythenorth** [comment] 2019-02-25 07:23
@SamuXarick found causes for this which aren't the name issue.  Needs the issue updating, thanks.

See https://github.com/OpenTTD/OpenTTD/pull/7250#issuecomment-466908472

**Closed as completed** 2019-03-03 22:29 UTC
