### ISSUE TITLE
Linking error while trying to build openTTD on Raspbian buster

### ISSUE THREAD

**Issue by Milanisius** [OpenTTD/OpenTTD#9058] opened 2021-04-19 01:07 UTC
Hello there,

as there seem to be no 1.11 binaries for Linux on ARM available (Or did I just miss them?),
I tried to build openTTD from source on my Raspberry Pi.

I have little experience with building from source and even less experience with cmake, so maybe the problem is just my incompetence. The error occurs while "Linking CXX executable openttd", errors are listed below. I believe the problem might have something to do with cmake.

Please let me know if you need any more info and thank you for your help!

## Version of OpenTTD
1.11.0

## Expected result
OpenTTD builds successfully.

## Actual result
Error in linking???

The Error:

````
[100%] Linking CXX executable openttd
/usr/bin/ld: CMakeFiles/openttd.dir/src/industry_cmd.cpp.o: in function `GetNumberOfIndustries':
/home/pi/OpenTTD/src/industry_cmd.cpp:2219: undefined reference to `Pool<Industry, unsigned short, 64u, 64000u, (PoolType)1, false, true>::MAX_SIZE'
/usr/bin/ld: CMakeFiles/openttd.dir/src/town_cmd.cpp.o: in function `GenerateTowns(TownLayout)':
/home/pi/OpenTTD/src/town_cmd.cpp:2247: undefined reference to `Pool<Town, unsigned short, 64u, 64000u, (PoolType)1, false,true>::MAX_SIZE'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/openttd.dir/build.make:6000: openttd] Error 1
make[1]: *** [CMakeFiles/Makefile2:1122: CMakeFiles/openttd.dir/all] Error 2
make: *** [Makefile:163: all] Error 2
````

## Steps to reproduce
Try to build OpenTTD on the newest Raspbian Buster, following the steps in COMPILING.md.

**Comment by James103** [comment] 2021-04-19 01:11
Did you try building OpenTTD 1.11.1?

**Comment by FLHerne** [comment] 2021-04-19 01:18
Thanks for the report.

This is indeed an OpenTTD bug (duplicate report of #8962) and fixed by #8924, which was included in the 1.11.1 release a few hours ago.

**Comment by Milanisius** [comment] 2021-04-19 01:34
I did not try it with 1.11.1 yet, i missed that release. Thank you!

**Comment by LordAro** [comment] 2021-04-19 05:30
Duplicate of #8962

**Closed as completed by LordAro** 2021-04-19 05:30 UTC
