### ISSUE TITLE
[Bug]: Lumber Mills not generated on desert maps

### ISSUE THREAD

**Issue by MountSeleya** [OpenTTD/OpenTTD#12899] opened 2024-08-14 15:27 UTC
### Version of OpenTTD

14.1

### Expected result

Lumber Mills on random desert climate maps are not being generated.

### Actual result

Lumber Mills on random desert climate maps are not being generated.

### Steps to reproduce

Just start any random desert map. There will be zero Lumber Mills, even is enough woodland is available.

**Comment by PikkaBird** [comment] 2024-08-14 15:28
This goes back to the original TTD. Lumber mills do not generate naturally - Chris Sawyer's intention was that the player has to save up money and build them.

**Comment by MountSeleya** [comment] 2024-08-14 15:35
They do generate in the old Transport Tycoon Deluxe game, but not in OpenTTD.

**Comment by PikkaBird** [comment] 2024-08-14 15:51
They certainly don't - you must be misremembering, or have played a somehow modified game, or played scenarios which had the mills pre-placed.

p.46 of the TTD manual: "Rainforest areas are very expensive to clear, but can be cleared for profit by funding a lumber mill."

**Comment by PikkaBird** [comment] 2024-08-14 16:35
As I say, it's possible your version of the game is somehow modified. There were a number of different versions over the years from different publishers.

In any case, see, eg, https://newgrf-specs.tt-wiki.net/wiki/IndustryDefaultProps#Appearance_Chances for confirmation that lumber mills are intended to have 0 natural generation chance.

**Comment by 2TallTyler** [comment] 2024-09-01 17:16
I am closing this ticket as "not a bug." Lumber Mills are not intended to spawn naturally in OpenTTD.

If someone wants to argue that they did in some version of TTD, and that behavior should be changed in OpenTTD, I think a Pull Request would be a suitable place for that discussion (and likely archeology).

**Closed as completed by 2TallTyler** 2024-09-01 17:16 UTC
