### ISSUE TITLE
Purchase land tool lacks by-area

### ISSUE THREAD

**Issue by floodious** [OpenTTD/OpenTTD#7920] opened 2020-01-08 03:50 UTC
## Version of OpenTTD
Current rev, 5a31efd98d1dc1ebccbddb926a9ee0d5e45c51ed

## Expected result
This tool should allow selection of areas like the demolish tool to allow quick purchase of regions or strips of land.

A common solution to reserving land in cities or regions is to be assigned a right-of-way in advance, generally with some predicate that must be filled by a date (building a rail line and servicing stations) and sometimes with rewards upon completion (mineral and resource rights within 1 mile of the right-of-way, where any mine or timber operation would owe shares to the transport company.)

Reserving contracts with a regional authority is a feature openttd currently has no implementation to support. In order to work around this limitation it is possible to buy individual rights to land tiles to reserve space for later rails which towns and industries must then "build around". Unfortunately achieving this result is incredibly labor-intensive with having to purchase every individual tile one-by-one.

## Actual result
Each tile must be clicked one at a time to reserve large strips of land, making the process almost totally impractical on all but the smallest scales.

## Steps to reproduce
Attempt to select an area to purchase with the tool.

**Comment by James103** [comment] 2020-01-08 03:53
If purchasing lang in large areas at a time is added, then the following protective measures would also need to be added: 
* A setting to disallow land purchasing, allow purchasing land only one tile at a time, or allow purchasing land in large areas at a time.
* Some config settings to control how fast players can purchase land (similar to terraforming, clearing land, or planting trees).

**Comment by floodious** [comment] 2020-01-08 03:56
I agree. 

Since town authorities do by default "dislike" purchases which clear land (I assume == demolish) your rating automatically drops as it should. 

There are a number of other issues however, including the fact that due to inflation and no land-tax or maintenance fee, it is possible to purchase large tracts of land early in the game and use the demolish tool when funds are needed after inflation has had a radical effect.

That all said... while it's possible to abuse and this must be dealt with; it's an awful lack of a feature that makes the game harder to play in a fair way, far less enjoyable and very frustrating in some situations.

**Comment by James103** [comment] 2020-01-08 04:31
I think that there should be a setting to require companies to pay yearly maintenance fees on the land they own equal to a configurable percentage of the cost to purchase land. "Yearly maintenance fee per tile of company-owned land: x%" Default value would be 0% maintenance fee on company owned land (same as before). This would encourage companies to use the land they purchase quickly and prevent them from just holding land until they sell it many years later.

**Comment by nielsmh** [comment] 2020-01-08 07:24
Yes the reason bulk land purchase is not implemented is not because it's hard or nobody ever thought of it, it's to (somewhat) limit the abuse potential in multiplayer.

Limiting land purchase via the existing landscaping limits counter could be possible, possibly such that land purchase counts for 100 (or even more) regular landscaping actions so you hit the limit earlier, possibly that kind of multiplier should be a setting.

**Comment by JGRennison** [comment] 2020-01-08 08:56
There's an implementation of this here: https://github.com/JGRennison/OpenTTD-patches/commit/e3207a77fb871ad9074a383df36c2250098212aa and https://github.com/JGRennison/OpenTTD-patches/commit/46b1ea81e4ed73a3a785784bfe74ad01043316d1, which could be a reasonable starting point.

**Comment by floodious** [comment] 2020-01-09 22:11
>@James103 commented Jan 8, 2020
>I think that there should be a setting to require companies to pay yearly maintenance fees on the land they own equal to a configurable percentage of the cost to purchase land.

This would be like a property tax, but more efficient if it took into account the location and value of the land tiles. For example land tiles near an industry or within town authority might be valued significantly higher than isolated tiles on top of a near-by mountain.

https://en.wikipedia.org/wiki/Land_value_tax (re: taxing percentage of assessed land value without considering asset values, to prevent hording land parcels and encourage efficient use of land.)
https://en.wikipedia.org/wiki/Deadweight_loss (re: sales taxes and resultant economic inefficiencies)

**Comment by Phx01** [comment] 2020-01-15 19:12
Apart from maintenance costs and other balancing acts, I vote for this feature to allow every second/third/fourth tile to be filled (similar to dragging signals).  That way you can keep your path clear for larger constructions like industries, which cannot be bulldozed or relocated, but still allows town houses or roads, which are less cumbersome to deal with.  Just to throw in my 2¢.

**Comment by techgeeknz** [comment] 2020-06-04 08:41
I like the idea of land value taxes on all tiles owned by a company; although it would have to be balanced against "infrastructure costs", which attempts to solve the same problem.

If this were to be implemented, it would be nice if land could then be bought without clearing it; i.e. save the trees, rocks, etc. for when the bulldozer comes along.

**Comment by 2TallTyler** [comment] 2020-06-04 19:46
> If this were to be implemented, it would be nice if land could then be bought without clearing it; i.e. save the trees, rocks, etc. for when the bulldozer comes along.

We may be diverging from OpenTTD's aim of following the original Transport Tycoon Deluxe, but this is a good idea otherwise. Graphically, I'd even suggest building company-color fences on the perimeter of the purchased area rather than placing a sign marker on a cleared land tile. The ugliness of purchased land is one of the reasons I don't often use the mechanic.

**Comment by TrueBrain** [comment] 2021-01-02 16:06
To sum it up: this is indeed not a bug, but fully working as intended, to prevent abuse in multiplayer games. The suggestions to bring alternatives to how land-buying should work sound awesome, and we would love it if someone could work on it. So if you feel up for it, please do make a Pull Request for this (now) feature request.

In the mean time I am going to close this bug-report, as we tend to not let feature-requests open. [Our forums](https://tt-forums.net) is a much better place for feature-requests and discussions related to them.

Thank you for the report, and awesome suggestions to solve this very old problem :D

**Closed as completed by TrueBrain** 2021-01-02 16:06 UTC
