### ISSUE TITLE
Cannot rebuild just buildozed dock

### ISSUE THREAD

**Issue by Yexo** [OpenTTD/OpenTTD#8121] opened 2020-05-06 22:16 UTC
## Version of OpenTTD
1.10.1, also head as of bc83337
## Expected result
When buildozing a dock, it's possible to rebuild immediately.
## Actual result
Cannot rebuild in some scenarios.
## Steps to reproduce
Load savegame from https://github.com/OpenTTD/OpenTTD/issues/8119, delete dock from Benfingford Docks. Try to rebuild it. Get "...site unsuitable error".

Comments from frosch on irc:
<frosch123> yes, that's an old issue
<frosch123> it was like that in ttd, since ships headed to the tile  in line with the dock
<frosch123> but apparently IsValidDockingDirectionForDock now does the opposite
<frosch123> so the builddock check should be changed as well

**Comment by SamuXarick** [comment] 2020-05-07 09:20
If you're going to change that, it will break some AIs that rely on that behaviour. They may end up building docks that will be blocking some paths and ships get lost.

**Comment by Yexo** [comment] 2020-05-07 09:55
Please start fixing those AIs now rather than later. Given that nobody has complained about this, it probably isn't a high priority fix nor will a backport to 1.10 be required, but imo potentially breaking some AIs is not a reason not to fix this for 1.11.

**Comment by TrueBrain** [comment] 2021-01-07 09:11
Is this really a bug? I mean, I found other ways to build a dock, terraform, and no longer being able to build the dock if I removed it. It is a bit how dock building works .. it expects the second tile out from where you place also to be valid, but it is easy to create cases after the fact where it no longer is valid. As example:

![image](https://user-images.githubusercontent.com/1663690/103873768-92b9c580-50d0-11eb-920d-6bc0f045165c.png)

There is never going to be a way anymore that I can rebuild that dock if I remove it.

I can, however, imagine it is a bug that you cannot build a dock in the following situation (it currently is not):

![image](https://user-images.githubusercontent.com/1663690/103873663-7027ac80-50d0-11eb-8595-5d7a373ba78c.png)

But that has nothing to do with rebuilding ofc :)

Looking for input here, what is expected behaviour :)

**Comment by TrueBrain** [comment] 2021-01-08 21:31
How it currently stands, this is fully intended behaviour.

With the changes to docks, an argument can be made the "3rd tile" restriction of docks can be lifted, which would also resolve this problem, but that is something for another day.

Going to close this issue, as "as intended". Sorry.

**Closed as completed by TrueBrain** 2021-01-08 21:31 UTC
Labels: bug
