### ISSUE TITLE
"medium_font" setting is not applied properly in korean

### ISSUE THREAD

**Issue by telk5093** [OpenTTD/OpenTTD#7615] opened 2019-06-04 17:58 UTC
## Version of OpenTTD
1.9.1 and recent nightlies

## Expected result
![image](https://user-images.githubusercontent.com/10726524/58900148-9093c600-8739-11e9-9ba4-a73e79dc28fe.png)
Font must be seemed like readme's fonts (="mono_font" setting)

## Actual result
![image](https://user-images.githubusercontent.com/10726524/58932684-a9cf5d80-879f-11e9-9e04-a817ce1d2e63.png)

## Steps to reproduce
* Used fonts: [Fonts.zip](https://github.com/OpenTTD/OpenTTD/files/3253732/Fonts.zip)
  * NanumGothic.ttf
  * KoPubBatangLight.ttf

and both ttf files stored into ./font/ directory under the directory which openttd.exe is.

* openttd.cfg (that works):
```
(...)
small_font = ./font/KoPubBatangLight.ttf
medium_font = ./font/NanumGothic.ttf
large_font = ./font/KoPubBatangLight.ttf
mono_font = ./font/KoPubBatangLight.ttf
(...)
```

* openttd.cfg (that occurs errors):
```
(...)
small_font = ./font/KoPubBatangLight.ttf
medium_font = ./font/KoPubBatangLight.ttf
large_font = ./font/KoPubBatangLight.ttf
mono_font = ./font/KoPubBatangLight.ttf
(...)
```

It's been a long time problem as korean users to set fonts correctly in OpenTTD, and I have provided korean users to proper openttd.cfg file to users who suffer as font errors.

But recently, I have noticed that only _medium_font_ setting in openttd.cfg works differently.

I had tried to change my game font as **KoPubBatangLight** (by someone's request), 
but the only _medium_font_ is not applied.
The only korean fonts that is applied as _medium_font_ are default Windows fonts such as **Gulim**, **Dotum** or **NanumGothic** (which I attached, not a default) as I know.

As you can see above _actual result_, small/large/mono_font setting works very fine for me, but not for _medium_font_.

The questions are:
1. I have no idea why **NanumGothic** doesn't make errors while other fonts including **KoPubBatangLight** does.
1. Why only _medium_font_ setting's are not applied while small/large/mono_font setting are applied.

* I'm using Windows 10, but lots of errors without openttd.cfg has been occured since OpenTTD supports korean.
* I've also installed the font file, it was the same.
* I've setted ```medium_font = C:\\Windows\\Fonts\\KoPubBatangLight.ttf```, it was the same. Single backslash was the same.

**Comment by glx22** [comment] 2019-06-04 19:57
Please also test with nightlies, some changes related to fonts on windows are not in releases

**Comment by telk5093** [comment] 2019-06-05 05:38
@glx22 Thanks for noticing me, I forgot that nightlies has been changed about fonts.
Nightly does not returns lots of errors, so I'll edit the context of this issue.
However, _medium_font_ is still not applied as below image.
You can see that _mono_font_ in the readme is applied correctly, and _medium_font_ is not.
![image](https://user-images.githubusercontent.com/10726524/58932629-6d9bfd00-879f-11e9-89a6-859b81cf97b4.png)

**Comment by TrueBrain** [comment] 2021-01-11 21:50
Hi @telk5093 ,

Sorry it took us so long to get back to you. I looked into your issue, and either it is already fixed over the years, or I do not understand the problem correctly :) If I use your font and start the game with 1 config over the other, I can clearly see that `medium_font` is correctly loaded:

`NanumGothic.ttf`:
![image](https://user-images.githubusercontent.com/1663690/104242247-2f78bc00-545f-11eb-8c37-bfea78b1b324.png)

`KoPubBatangLight.ttf`:
![image](https://user-images.githubusercontent.com/1663690/104242271-3b647e00-545f-11eb-9bce-acd048cb3d70.png)

(forgive me doing this in English; I am pretty sure I get lost in Korean :D).

Would you be able to test this with latest nightly: https://www.openttd.org/downloads/openttd-nightlies/latest.html
And see if the problem still exists?

If so, can you help me out exactly what you expect to happen and what happens? The screenshots are not all that clear to me, in what you expect vs what you get, sorry about that :)

Thank you!

**Comment by telk5093** [comment] 2021-01-12 17:43
@TrueBrain Thanks for reviewing this issue even time has flowed.
From your attached screenshots, ``NanumGothic.ttf`` is correctly applied but ``KoPubBatangLight.ttf`` isn't applied.
KoPubBatangLight.ttf should be like this (with anti-aliasing on):
![image](https://user-images.githubusercontent.com/10726524/104351044-34fe0100-5548-11eb-8b00-654d1172d131.png)


But the above image is made by Photoshop, not the actual game screenshot.
I was trying to check this issue still exists in the latest nightly but I couldn't since all TrueTypeFont are not applied whatever it is.
I changed the value of ``small_font``, ``medium_font``, ``large_font``, ``mono_font`` like below and none worked, every try showed ``MalgunGothic`` (default font in Korea after Vista) instead.

1. ``./font/KoPubBatangLight.ttf`` (while this ttf file is stored at ``C:\(blahblah)\OpenTTDnightly\font\KoPubBatangLight.ttf``)
2. ``font/KoPubBatangLight.ttf``
3. ``.\font\KoPubBatangLight.ttf``
2. ``KoPubBatangLight.ttf``
3. ``KoPubBatangLight``
3. ``C:\WINDOWS\Fonts\KoPubBatangLight.ttf``
4. ``C:\\WINDOWS\\Fonts\\KoPubBatangLight.ttf``

Not only ``KoPubBatangLight`` but also all korean ttf file did not work, except for ``NanumGothic``.
I think all truetype font is ignored and considered as ``MalgunGothic``.

Font settings what was successful were these:
- ``Gulim``, ``Dotum``, ``Batang``, ``Gungsuh`` (which are basic fonts in Korean Windows)
- ``NanumGothic``, ``./font/NanumGothic.ttf`` (with file exists)

I have no idea why truetype font setting is not working at 1.10.x while it worked in the past.
I'm so sorry that I'm not replying what you want but saying another issue. Please let me know if you think this should be an another issue.

Thank you :)

**Comment by TrueBrain** [comment] 2021-01-12 19:32
Thank you for this much detail, that is really appreciated.

After some digging and looking around, the problem is a bit complicated.

On start-up, OpenTTD validates fonts to see if it has all the glyphs of all the strings we will be rendering. If it finds any glyph missing, it doesn't tell you, but loads the system fallback. This is very confusing, and results in you trying different paths to the font, while the font itself is the problem. Sorry about that ...

The real problem: your `KoPubBatangLight.ttf` is missing certain glyphs: NBSP (0xA0), Pound sign (0xA3) and copyright sign (0xA9) on medium font-size. And this is the reason it is not picking up your font when you use it as `medium_font`.

I am preparing a change in the code, that gives a bit more helpful indication what is going on. First, it will display this to the console:

`dbg: [freetype] Font is missing glyphs to display char 0xA0 in normal font size`

Second, in-game it will show you a window:

![image](https://user-images.githubusercontent.com/1663690/104362561-3f060c80-5514-11eb-8ef2-4f4b6b0fd74c.png)

That hopefully helps you a bit more what is going on, and that it has little to do with where the font is located. This hopefully also helps you to resolve this issue.
We find it extremely odd there is a font that does not implement NBSP btw .. or copyright for that matter :D You would think that is one of the first glyphs they add :P But yeah .. seems you need to look for another font or see if you can contact the author to add a few basic glyphs there. Or do it yourself of course :D (be mindful of the license!)

For the difference between 1.9 and the nightly, that I do not understand fully. It might be that we now also use a NBSP for small or large font; that might explain why `KoPubBatangLight.ttf` is rejected in all cases. When my PR is accepted into master, with the nightly after that, we can see what the error is, and if that sheds some light on this.

Sorry for the trouble, and let me know if there is anything else I can help you with :)

**Comment by telk5093** [comment] 2021-01-13 05:17
If so, most of true type fonts what I tested might have missing glyphs, it sounds too bad.
Such fonts are not personal made, usually made for business (with legal license for personal use) so it would be hard to contact authors 😅

Would it be impossible to use the way using some alternative font if such glyphs are missing?

Anyway thanks again!

**Comment by TrueBrain** [comment] 2021-01-13 08:25
Well, I am as surprised as you are that these things are not supplied, I have to admit :D

![image](https://user-images.githubusercontent.com/1663690/104425016-6db9cc80-5580-11eb-93cc-b43d45717654.png)

I had to look it up in the TTF itself to ensure myself they are really not there :P You can see A3 and A9 really are not in the font :D Silly, really.

~~I did not really check out earlier why other fonts won't load for you, so I just downloaded Gulim from ufonts.com (first hit I got from searching for it); that font does load correct for me, without any issues, both on Windows and Linux. I simply put the file next to my `openttd.cfg`, in the same folder, and used:~~

```
small_font = gulim.ttf
medium_font = gulim.ttf
large_font = gulim.ttf
mono_font = gulim.ttf
```

~~If this is not working for you, would you mind start OpenTTD with `-dfreetype=2` as argument to the application, and let me know what the console is telling you? That would allow me to get a peek what your system is doing :) Tnx!~~

Oops, misread you. Gulim was one that was working. Do you have any other font for me that isn't?

**Comment by telk5093** [comment] 2021-01-13 12:50
Here's some fonts that does not work:
``이롭게바탕체(IropkeBatang)`` [IropkeBatangM.zip](https://github.com/OpenTTD/OpenTTD/files/5808639/IropkeBatangM.zip)
``잘풀리는오늘(Jalpullineun)`` [JalpullineunFonts.zip](https://github.com/OpenTTD/OpenTTD/files/5808641/JalpullineunFonts.zip)
``나눔명조(NanumMyeongjo)`` [NanumFontSetup_TTF_MYUNGJO.zip](https://github.com/OpenTTD/OpenTTD/files/5808650/NanumFontSetup_TTF_MYUNGJO.zip)

**Comment by TrueBrain** [comment] 2021-01-13 12:55
I tested `IropkeBatang`, which works fine for me. So that means I need a bit more information from you after all :)

Would you mind start OpenTTD with -dfreetype=2 as argument to the application, and let me know what the console is telling you? That would allow me to get a peek what your system is doing :) Tnx!

**Comment by telk5093** [comment] 2021-01-13 13:12
Tried to ``./fonts/NanumMyeongjo.ttf`` in nightly
```
dbg: [freetype] Loaded font '3.01;RIXF;NanumMyeongjo' with size 14
dbg: [freetype] Loaded font '3.01;RIXF;NanumMyeongjo' with size 12
dbg: [freetype] Loaded font '3.01;RIXF;NanumMyeongjo' with size 16
dbg: [freetype] Loaded font '3.01;RIXF;NanumMyeongjo' with size 14
dbg: [freetype] Loaded font '3.01;RIXF;NanumMyeongjo' with size 12
dbg: [freetype] Loaded font '3.01;RIXF;NanumMyeongjo' with size 16
dbg: [freetype] Loaded font '3.01;RIXF;NanumMyeongjo' with size 14
dbg: [freetype] Loaded font '3.01;RIXF;NanumMyeongjo' with size 12
dbg: [freetype] Loaded font '3.01;RIXF;NanumMyeongjo' with size 16
dbg: [freetype] Loaded font '3.01;RIXF;NanumMyeongjo' with size 14
dbg: [freetype] Loaded font '3.01;RIXF;NanumMyeongjo' with size 12
dbg: [freetype] Loaded font '3.01;RIXF;NanumMyeongjo' with size 16
dbg: [freetype] Loaded font '3.01;RIXF;NanumMyeongjo' with size 14
dbg: [freetype] Loaded font '3.01;RIXF;NanumMyeongjo' with size 12
dbg: [freetype] Loaded font '3.01;RIXF;NanumMyeongjo' with size 16
dbg: [freetype] Loaded font '3.01;RIXF;NanumMyeongjo' with size 14
dbg: [freetype] Loaded font '3.01;RIXF;NanumMyeongjo' with size 14
dbg: [freetype] Loaded font '3.01;RIXF;NanumMyeongjo' with size 12
dbg: [freetype] Loaded font '3.01;RIXF;NanumMyeongjo' with size 12
dbg: [freetype] Loaded font '3.01;RIXF;NanumMyeongjo' with size 16
dbg: [freetype] Loaded font '3.01;RIXF;NanumMyeongjo' with size 16
dbg: [freetype] Trying fallback fonts
dbg: [freetype] Loaded font '3.01;RIXF;NanumMyeongjo' with size 14
dbg: [freetype] Loaded font 'dbg: [freetype] Loaded font '3.01;RIXF;NanumMyeongjo' with size 12
dbg: [freetype] Loaded font 'dbg: [freetype] Loaded font '3.01;RIXF;NanumMyeongjo' with size 16
dbg: [freetype] Loaded font 'dbg: [freetype] Fallback font: dbg: [freetype] Loaded font 'dbg: [freetype] Loaded font 'dbg: [freetype] Loaded font 'dbg: [freetype] Loaded font 'dbg: [freetype] Loaded font '3.01;RIXF;NanumMyeongjo' with size 14
dbg: [freetype] Loaded font 'dbg: [freetype] Loaded font '3.01;RIXF;NanumMyeongjo' with size 12
dbg: [freetype] Loaded font 'dbg: [freetype] Loaded font '3.01;RIXF;NanumMyeongjo' with size 16
dbg: [freetype] Trying fallback fonts
dbg: [freetype] Loaded font '3.01;RIXF;NanumMyeongjo' with size 14
dbg: [freetype] Loaded font 'dbg: [freetype] Loaded font '3.01;RIXF;NanumMyeongjo' with size 12
dbg: [freetype] Loaded font 'dbg: [freetype] Loaded font '3.01;RIXF;NanumMyeongjo' with size 16
dbg: [freetype] Loaded font 'dbg: [freetype] Fallback font: dbg: [freetype] Loaded font 'dbg: [freetype] Loaded font 'dbg: [freetype] Loaded font 'dbg: [freetype] Loaded font 'dbg: [freetype] Loaded font 'dbg: [freetype] Loaded font 'dbg: [freetype] Loaded font 'dbg: [freetype] Loaded font 'dbg: [freetype] Loaded font 'dbg: [freetype] Loaded font 'dbg: [freetype] Loaded font '3.01;RIXF;NanumMyeongjo' with size 14
dbg: [freetype] Loaded font 'dbg: [freetype] Loaded font '3.01;RIXF;NanumMyeongjo' with size 12
dbg: [freetype] Loaded font 'dbg: [freetype] Loaded font '3.01;RIXF;NanumMyeongjo' with size 16
dbg: [freetype] Trying fallback fonts
dbg: [freetype] Loaded font '3.01;RIXF;NanumMyeongjo' with size 14
dbg: [freetype] Loaded font 'dbg: [freetype] Loaded font '3.01;RIXF;NanumMyeongjo' with size 12
dbg: [freetype] Loaded font 'dbg: [freetype] Loaded font '3.01;RIXF;NanumMyeongjo' with size 16
dbg: [freetype] Loaded font 'dbg: [freetype] Fallback font: dbg: [freetype] Loaded font 'dbg: [freetype] Loaded font 'dbg: [freetype] Loaded font '
```

**Comment by TrueBrain** [comment] 2021-01-13 13:15
`NanumMyeongjo` is indeed missing glyphs (at least 0xA3, haven't checked for others). Would you mind checking `IropkeBatang`, as that should really work, as far as I can tell?

**Comment by telk5093** [comment] 2021-01-13 13:17
Oh, you meant ``IropkeBatang``, sorry!

```
dbg: [freetype] Loaded font '1.001;IropkeBatangM' with size 14
dbg: [freetype] Loaded font '1.001;IropkeBatangM' with size 12
dbg: [freetype] Loaded font '1.001;IropkeBatangM' with size 16
dbg: [freetype] Loaded font '1.001;IropkeBatangM' with size 14
dbg: [freetype] Loaded font '1.001;IropkeBatangM' with size 12
dbg: [freetype] Loaded font '1.001;IropkeBatangM' with size 16
dbg: [freetype] Loaded font '1.001;IropkeBatangM' with size 14
dbg: [freetype] Loaded font '1.001;IropkeBatangM' with size 12
dbg: [freetype] Loaded font '1.001;IropkeBatangM' with size 16
dbg: [freetype] Loaded font '1.001;IropkeBatangM' with size 14
dbg: [freetype] Loaded font '1.001;IropkeBatangM' with size 12
dbg: [freetype] Loaded font '1.001;IropkeBatangM' with size 16
dbg: [freetype] Loaded font '1.001;IropkeBatangM' with size 14
dbg: [freetype] Loaded font '1.001;IropkeBatangM' with size 12
dbg: [freetype] Loaded font '1.001;IropkeBatangM' with size 16
dbg: [freetype] Loaded font '1.001;IropkeBatangM' with size 14
dbg: [freetype] Loaded font '1.001;IropkeBatangM' with size 14
dbg: [freetype] Loaded font '1.001;IropkeBatangM' with size 12
dbg: [freetype] Loaded font '1.001;IropkeBatangM' with size 12
dbg: [freetype] Loaded font '1.001;IropkeBatangM' with size 16
dbg: [freetype] Loaded font '1.001;IropkeBatangM' with size 16
dbg: [freetype] Trying fallback fonts
dbg: [freetype] Loaded font '1.001;IropkeBatangM' with size 14
dbg: [freetype] Loaded font 'dbg: [freetype] Loaded font '1.001;IropkeBatangM' with size 12
dbg: [freetype] Loaded font 'dbg: [freetype] Loaded font '1.001;IropkeBatangM' with size 16
dbg: [freetype] Loaded font 'dbg: [freetype] Fallback font: dbg: [freetype] Loaded font 'dbg: [freetype] Loaded font 'dbg: [freetype] Loaded font 'dbg: [freetype] Loaded font 'dbg: [freetype] Loaded font '1.001;IropkeBatangM' with size 14
dbg: [freetype] Loaded font 'dbg: [freetype] Loaded font '1.001;IropkeBatangM' with size 12
dbg: [freetype] Loaded font 'dbg: [freetype] Loaded font '1.001;IropkeBatangM' with size 16
dbg: [freetype] Trying fallback fonts
dbg: [freetype] Loaded font '1.001;IropkeBatangM' with size 14
dbg: [freetype] Loaded font 'dbg: [freetype] Loaded font '1.001;IropkeBatangM' with size 12
dbg: [freetype] Loaded font 'dbg: [freetype] Loaded font '1.001;IropkeBatangM' with size 16
dbg: [freetype] Loaded font 'dbg: [freetype] Fallback font: dbg: [freetype] Loaded font 'dbg: [freetype] Loaded font 'dbg: [freetype] Loaded font 'dbg: [freetype] Loaded font 'dbg: [freetype] Loaded font 'dbg: [freetype] Loaded font 'dbg: [freetype] Loaded font 'dbg: [freetype] Loaded font 'dbg: [freetype] Loaded font 'dbg: [freetype] Loaded font 'dbg: [freetype] Loaded font '1.001;IropkeBatangM' with size 14
dbg: [freetype] Loaded font 'dbg: [freetype] Loaded font '1.001;IropkeBatangM' with size 12
dbg: [freetype] Loaded font 'dbg: [freetype] Loaded font '1.001;IropkeBatangM' with size 16
dbg: [freetype] Trying fallback fonts
dbg: [freetype] Loaded font '1.001;IropkeBatangM' with size 14
dbg: [freetype] Loaded font 'dbg: [freetype] Loaded font '1.001;IropkeBatangM' with size 12
dbg: [freetype] Loaded font 'dbg: [freetype] Loaded font '1.001;IropkeBatangM' with size 16
dbg: [freetype] Loaded font 'dbg: [freetype] Fallback font: dbg: [freetype] Loaded font 'dbg: [freetype] Loaded font 'dbg: [freetype] Loaded font '
```

**Comment by TrueBrain** [comment] 2021-01-13 13:24
No worries, it just meant I had to test yet-another-font :P I am just being lazy :)

Okay, I was testing only English language, as I assume such fonts at least do all Korean glyphs. I was wrong:

`dbg: [freetype] Font is missing glyphs to display char 0x20AC in medium font size`
(0x20AC is the euro-sign, it seems: https://www.fileformat.info/info/unicode/char/20ac/index.htm)

Yeah, let me ask if someone can review the PR, so you get these nicer errors too .. :D

**Comment by TrueBrain** [comment] 2021-01-13 13:29
Oops, didn't mean to close this already, but okay. In the new nightly of today (which will run in ~6 hours from now), there is code to tell you why it failed to load the fonts. Hopefully this helps you out a bit finding a font that implements all glyphs.

I understand this is far from ideal, but I also don't really know what to do otherwise. We can't just do a font partial .. can you see if with this extra information you have sufficient information to find a suitable font?

Sorry for the trouble that is called fonts ...

**Comment by telk5093** [comment] 2021-01-13 13:36
Even though it is too sad that it's impossible to use all font, I can find what font is suitable with ``-dtruetype=2``.
Thanks for your great effort 👍

**Comment by TrueBrain** [comment] 2021-01-13 13:37
No problem! If this is sufficient for you, I will be closing the ticket for real now :D Hopefully you can help the Korean community with some nice working fonts :D

**Closed as completed by TrueBrain** 2021-01-13 13:37 UTC
Labels: waiting on author
