### ISSUE TITLE
Upper-case umlauts don't render properly in manager name

### ISSUE THREAD

**Issue by Wuzzy2** [OpenTTD/OpenTTD#8624] opened 2021-01-31 01:43 UTC
## Version of OpenTTD
1.11.0-dev
and
1.9.3

## Expected result
If your manager name contains an upper-case umlaut like “Ä”, “Ö” or “Ü”, the name will display correctly in the company window.

## Actual result
If your manager name contains an upper-case umlaut like “Ä”, “Ö” or “Ü”, the “dots” of the umlaut are cut off halfway.

## Steps to reproduce
Rename your manager. Enter any upper-case umlaut like “Ä”. If you're set the language to German, you can make your life easier by using the on-screen keyboard.

## Screenshot evidence in 1.9.3.

https://satoshiupload.com/images/Q95r3pOhOw.png

Pay only attention to the manager name. I set it to “Ä.Ö.Ü.” in this example. Ignore the other red arrows.

**Comment by LordAro** [comment] 2021-02-13 22:12
Duplicate of #8623 - it's the same issue, the sprite font is too high.

**Closed as completed by LordAro** 2021-02-13 22:12 UTC
