### ISSUE TITLE
Black/red window on startup (macOS 10.15.7)

### ISSUE THREAD

**Issue by Crazor** [OpenTTD/OpenTTD#8855] opened 2021-03-13 09:41 UTC
## Version of OpenTTD
1.11.0-beta2 on macOS 10.15.7

## Expected result
I expect the game's title screen to appear

## Actual result
The game window appears but stays black. Alternatively, it stays red when I launch with cocoa-opengl

## Steps to reproduce
Start the game

## Logs
```
/Applications/OpenTTD.app/Contents/MacOS/openttd -d 9,freetype=0
dbg: [misc] /Users/dhe/Documents/OpenTTD/ added as search path
dbg: [misc] /Library/Application Support/OpenTTD/ added as search path
dbg: [misc] /Applications/ added as search path
dbg: [misc] /Applications/OpenTTD.app/Contents/Resources/ added as search path
dbg: [misc] /Users/dhe/Documents/OpenTTD/content_download/ added as search path
dbg: [misc] /Users/dhe/Documents/OpenTTD/ found as config directory
dbg: [misc] /Users/dhe/Documents/OpenTTD/ found as personal directory
dbg: [misc] Scanning for tars
dbg: [misc] Scan complete, found 0 files
dbg: [grf] Checking /Applications/OpenTTD.app/Contents/Resources/baseset/orig_dos.obg for base graphics set
dbg: [grf] The file TRG1.GRF specified in /Applications/OpenTTD.app/Contents/Resources/baseset/orig_dos.obg is missing
dbg: [grf] The file TRGI.GRF specified in /Applications/OpenTTD.app/Contents/Resources/baseset/orig_dos.obg is missing
dbg: [grf] The file TRGC.GRF specified in /Applications/OpenTTD.app/Contents/Resources/baseset/orig_dos.obg is missing
dbg: [grf] The file TRGH.GRF specified in /Applications/OpenTTD.app/Contents/Resources/baseset/orig_dos.obg is missing
dbg: [grf] The file TRGT.GRF specified in /Applications/OpenTTD.app/Contents/Resources/baseset/orig_dos.obg is missing
dbg: [grf] Adding original_dos (1) as base graphics set
dbg: [grf] Checking /Applications/OpenTTD.app/Contents/Resources/baseset/orig_win.obg for base graphics set
dbg: [grf] The file TRG1R.GRF specified in /Applications/OpenTTD.app/Contents/Resources/baseset/orig_win.obg is missing
dbg: [grf] The file TRGIR.GRF specified in /Applications/OpenTTD.app/Contents/Resources/baseset/orig_win.obg is missing
dbg: [grf] The file TRGCR.GRF specified in /Applications/OpenTTD.app/Contents/Resources/baseset/orig_win.obg is missing
dbg: [grf] The file TRGHR.GRF specified in /Applications/OpenTTD.app/Contents/Resources/baseset/orig_win.obg is missing
dbg: [grf] The file TRGTR.GRF specified in /Applications/OpenTTD.app/Contents/Resources/baseset/orig_win.obg is missing
dbg: [grf] Adding original_windows (0) as base graphics set
dbg: [grf] Checking /Applications/OpenTTD.app/Contents/Resources/baseset/orig_dos_de.obg for base graphics set
dbg: [grf] The file TRG1.GRF specified in /Applications/OpenTTD.app/Contents/Resources/baseset/orig_dos_de.obg is missing
dbg: [grf] The file TRGI.GRF specified in /Applications/OpenTTD.app/Contents/Resources/baseset/orig_dos_de.obg is missing
dbg: [grf] The file TRGC.GRF specified in /Applications/OpenTTD.app/Contents/Resources/baseset/orig_dos_de.obg is missing
dbg: [grf] The file TRGH.GRF specified in /Applications/OpenTTD.app/Contents/Resources/baseset/orig_dos_de.obg is missing
dbg: [grf] The file TRGT.GRF specified in /Applications/OpenTTD.app/Contents/Resources/baseset/orig_dos_de.obg is missing
dbg: [grf] Not adding original_dos_de (0) as base graphics set (duplicate, lower version)
dbg: [misc] Loading blitter...
dbg: [driver] Successfully loaded blitter '32bpp-anim'
dbg: [driver] Could not change to foreground application. Error -50
dbg: [driver] Successfully probed video driver 'cocoa'
dbg: [net] [core] starting network...
dbg: [net] [udp] initializing listeners
dbg: [net] [core] network online, multiplayer available
dbg: [net] Detected broadcast addresses:
dbg: [net] 0) 192.168.0.255
```

**Comment by TrueBrain** [comment] 2021-03-13 09:45
I suspect this is a duplicate of #8785 . Could you try our latest nightly instead? https://www.openttd.org/downloads/openttd-nightlies/latest.html

Tnx!

**Comment by Crazor** [comment] 2021-03-13 09:56
Yeah you're probably right about the dupe. Must have had the wrong search terms. I did look through the open issues though, should have looked at the newest closed ones as well I guess.

So first of all, I downloaded the stable version, only to discover that I forgot about OpenTTD normally coming with a bunch of other files and folders. I don't know if they are needed, but I now tried copying everything from the DMG to `/Applications/OpenTTD`. Release (and also the nightly version) started to a grey screen with a message prompting me to download a graphics pack. However, if I agree, the download progress window pops up for a split second and vanishes, leaving the game window empty.

I will see if I can download the graphics pack by myself and put it in the proper location.

**Comment by TrueBrain** [comment] 2021-03-13 09:57
Would you mind trying the latest nightly, instead of the stable? We made a lot of changes to how this all works :)

And yes, OpenTTD these days ships as a `dmg`, which is just a single file. It used to be a `zip`, which contains a lot of files. Both should work fine. Double-clicking the `dmg` should start the game, prompt you with "you need to download OpenGFX", downloads it for you, and restart the game in working order.

**Comment by Crazor** [comment] 2021-03-13 10:00
Alright then, good to know that the .app bundle is enough these days (as it should be with proper macOS applications ;))

I already tried the nightly, and the download behaviour is the same as with stable unfortunately. Relevant log messages (after agreeing to download):

```
dbg: [net] Connecting to content.openttd.org:3978 (IPv4)
dbg: [net] [tcp] connected to 3.122.55.159:3978 (IPv4)
dbg: [net] Connecting to binaries.openttd.org:80 (IPv4)
dbg: [net] [tcp] connected to 18.193.16.234:80 (IPv4)
dbg: [net] Network revision name is '20210311-master-g9c5a7d3a57'
dbg: [net] [tcp/http] requesting binaries.openttd.org/bananas
dbg: [net] [tcp/http] downloading 138 bytes
```

**Comment by TrueBrain** [comment] 2021-03-13 10:05
Oops, sorry, misread you about testing the nightly. Tnx for doing so!

So our bootstrap is working, it is trying to download the file, but then something breaks. Hmm, interesting.

Although I am very interesting in understanding what is going on, I can imagine you just want to play the game. You can download OpenGFX yourself from https://www.openttd.org/downloads/opengfx-releases/ and unzip the file in `Documents/OpenTTD/baseset` folder. OpenTTD will pick that up and start correctly.

This problem however .. is a bit puzzling to me. I am curious if you can start the game normally, if the "Online Content Service" works for you. If you can download anything from there?

**Comment by Crazor** [comment] 2021-03-13 10:06
Alright, solved the download issue. I had an invalid symlink from `~/Documents/OpenTTD` which I had installed years ago now I guess. Totally my fault!
Nightly and beta work fine now, too. Sorry for the inconvenience, but thumbs up for the quick replies!

**Comment by TrueBrain** [comment] 2021-03-13 10:07
Wow, glad you found that out yourself :D I would not have guessed that!

Leaves for an interesting issue: if we cannot write the bootstrap file, we .. just .. show a black screen. Sounds less then ideal :D Something to fix for us!

**Comment by Crazor** [comment] 2021-03-13 10:10
I used to symlink `~/Documents/OpenTTD` to a folder in my Dropbox to sync between my desktop and laptop... Has been a long time since I played. Very curious to see what's going on these days!
Feel free to close this issue, or leave it open as a reminder for the error handling regarding the bootstrapping.
Have a nice weekend!

**Closed as completed** 2021-03-14 10:04 UTC
