### ISSUE TITLE
[Bug]: Ship tries to go to maintenance at a depot that it doesn't reach

### ISSUE THREAD

**Issue by DonaldDuck313** [OpenTTD/OpenTTD#9849] opened 2022-04-11 15:28 UTC
### Version of OpenTTD

12.2, Windows 11

### Expected result

Ships should only go to maintenance at depots they can reach. If it's close to a depot that it can't reach, it should ignore that depot and continue following its orders as usual until it finds a depot that it can reach.

### Actual result

If a ship is close to a depot but they're separated by a piece of land so it can't reach it (like in the screenshot below), the ship tries to go to maintenance there anyway, and since it can't reach it it ends up going around in circles complaining that it's lost.

<img width="960" alt="Namnlös" src="https://user-images.githubusercontent.com/40611243/162769511-a304954a-953f-4825-b165-73e5c22ccc07.png">

### Steps to reproduce

1. Load the attached saved game.
2. You can see that ship 1 is stuck in an infinite loop trying to go for maintenance to Haghus Hamnterminal which it can't reach. I would expect it to continue its orders as usual and go to Haghus Hamn, then go back to Bruttudde Hamn and then when it's close enough go for maintenance at Bruttudde Hamnterminal instead.

[Haghus Transport, 22 maj 1951.zip](https://github.com/OpenTTD/OpenTTD/files/8465446/Haghus.Transport.22.maj.1951.zip)

**Comment by LordAro** [comment] 2022-04-11 16:30
Duplicate of #5713

**Closed as completed by LordAro** 2022-04-11 16:30 UTC
