### ISSUE TITLE
SDL2: in console, typing _ or + zooms in and out the map

### ISSUE THREAD

**Issue by nikolas** [OpenTTD/OpenTTD#7816] opened 2019-11-01 23:51 UTC
## Version of OpenTTD
1.10.0-beta1

## Expected result
_ or + is entered into the console, but nothing else changes

## Actual result
map zooms

## Steps to reproduce
Go into console and type _ or +

**Comment by James103** [comment] 2019-11-03 23:59
Duplicate of #7783, [according to](https://github.com/OpenTTD/OpenTTD/issues/7810#issuecomment-549190739) @JGRennison.

The general issue here is that in SDL2, typing something not only types the character, but performs actions bound to the hotkey corresponding to the character typed. For example, typing a `T` will perform actions bound to the `SHIFT+T` hotkey, and typing a `a` will perform actions bound to the `A` hotkey. This also means that typing something like `Hello` will also perform the actions bound to the hotkeys `SHIFT+H`, `E`, `L`, `L`, and `O`, in that order.

This issue did not occur in SDL1, which my latest nightly version (2019-10-23) uses.

**Closed as completed** 2019-11-10 17:58 UTC
