### ISSUE TITLE
[Bug]: "Game Load Failed" error message is shorter than other two-line messages

### ISSUE THREAD

**Issue by James103** [OpenTTD/OpenTTD#11055] opened 2023-06-21 20:21 UTC
### Version of OpenTTD

Since c600158c1df336153eb6705eded718f0434fee75, tested on c316d9ecb7

### Expected result

When saving or loading the game to/from a file fails, the resulting error message should have some space between "Game Load Failed" (or "Game Save Failed") and the reason for the save/load failure.

Example: 
![image](https://github.com/OpenTTD/OpenTTD/assets/37945304/9ea1e31d-e97c-4fc4-87d6-407b74dbec01)

### Actual result

When saving or loading the game to/from a file fails, the resulting error message has no additional space between "Game Load Failed" (or "Game Save Failed") and the reason for the save/load failure, unlike other message where there is space.

Example:
![image](https://github.com/OpenTTD/OpenTTD/assets/37945304/af71c1da-8389-478b-88b3-c816e66a508d)

### Steps to reproduce

1. Try to save (or load) the game, such that it fails.
2. Notice the resulting message has no extra space between "Game Save Failed" (or "Game Load Failed") and the reason for failure.
3. Perform any other action (in game) such that it fails.
4. Notice the resulting message has space between the two lines.

**Comment by tarunsamanta2k20** [comment] 2023-06-22 10:07
I'd like to look into this

**Comment by 2TallTyler** [comment] 2023-06-22 10:19
Go for it!

**Comment by PeterN** [comment] 2023-06-22 10:40
This happens because the first error is two parts, an action from issuing a command "Lower land", and a response from that action "already at sea level".

The save error, although chopped up, is then joined into a single string when handed to the error window.

So to fix this you should look at the callers of `GetSaveLoadErrorString()`, and probably replace the calls to `ShowErrorMessage()` with something that preserves the split strings and arguments.

**Comment by glx22** [comment] 2023-06-22 10:56
IIRC from my reading of this code yesterday, commands errors texts are manually merged with spaces, while load/save errors are merged using `{STRING}{}{STRING}` or similar.

**Comment by PeterN** [comment] 2023-06-22 11:09
The command error result text may be merged, but the split between command action (summary_msg) and command result (detailed_msg) is handled by the error window, which draws them separately.

Logically then, "Game save failed" could therefore be considered the summary_msg and the reason could be detailed_msg.

**Comment by Lord-Cinders** [comment] 2023-07-18 23:00
Hello, I'm new to open-source contributions and want to start by contributing to this project, but I'm very confused about a few things. I kind of understand why the issue is happening, but I don't understand why these errors are not being handled like every other error. Is it really important to merge the two strings into a single string? Because I found that the stringids for individual error messages were already defined and were not being used. 
![image](https://github.com/OpenTTD/OpenTTD/assets/53181313/ef52c110-eb45-4d33-b4c3-830d63011383)

I also couldn't understand how the error string was assigned to STR_JUST_RAW_STRING or how the slots were assigned to string ids by the `SetDParamStr` function.
![image](https://github.com/OpenTTD/OpenTTD/assets/53181313/3bab515f-090d-4673-98d4-a00e01be42c9)
 
if we were to do something like this
![image](https://github.com/OpenTTD/OpenTTD/assets/53181313/b0296e21-882e-4eaf-8803-67a1664f5f88)
![image](https://github.com/OpenTTD/OpenTTD/assets/53181313/b0f660d4-c366-43db-94c3-8d71f74e40a1)
it would maintain the same style as the other errors that I've seen and fix the issue

![image](https://github.com/OpenTTD/OpenTTD/assets/53181313/f5a7aba1-77ca-4b32-89ee-3d4f3767e63b)

**Closed as completed** 2024-04-01 16:57 UTC
Labels: good first issue, component: interface, priority: low
