### ISSUE TITLE
Towns don't grow if first tile of station is outside authority area

### ISSUE THREAD

**Issue by slhurst** [OpenTTD/OpenTTD#7011] opened 2019-01-04 22:46 UTC
It appears that whether or not a received cargo contributes to town growth rate is determined by the location of the first-placed station tile, and particularly whether or not that first tile was within the local authority area.

In the attached savegame, one station (Edinborough) has all tiles within the authority area, and the other (Pradhead East) straddles the boundary. 

When Pradhead East is demolished and recreated with an initial tile *in* the local authority area, the town is reported as growing every 38 days, but if the station is built with the first tile *outside* the local authority it is reported as not growing, with the same number of passengers arriving.

[Growth-bug.sav.gz](https://github.com/OpenTTD/OpenTTD/files/2728781/Growth-bug.sav.gz)

**Comment by nielsmh** [comment] 2019-01-04 22:53
This sounds very much like expected behavior. Much of the economic effect of stations is based on which tile the _station sign_ is at. For instance, payments for delivery are based on the Manhattan distance between the pickup station sign and delivery station sign.

It might be possible to change this so the local authority effect of cargo pickup and delivery is based on the actual tile the vehicle transferring cargo is at, rather than the station sign. I think changing this could be controversial, since it's one of the core mechanics inherited from the original game.

**Comment by slhurst** [comment] 2019-01-04 23:10
That makes sense, thanks for the quick response!

At the very least I'll add something to the wiki to explain that nuance, since it's been irritating me on and off for ages as to why some towns were growing and some not.

**Comment by Eddi-z** [comment] 2019-01-04 23:19
well, we could just relocate the station sign so it's always at the center of the station (rectangle) or something, just be aware that that might not be on an actual station tile with certain types of stationwalking/disjoint stations.

**Comment by andythenorth** [comment] 2019-01-07 22:02
Although this would be nice to have, it isn't something we expect to fulfill in the next year, and on that basis I'm closing it.  We do this to keep the project manageable, productive and fun. We hope you do understand. Thanks for contributing though! [Here](https://github.com/OpenTTD/OpenTTD/blob/master/CONTRIBUTING.md#feature-requests) you can find more about how we handle feature requests.

**Closed as completed by andythenorth** 2019-01-07 22:02 UTC
