### ISSUE TITLE
[Crash]: Fatal Application Failure

### ISSUE THREAD

**Issue by WilmerSchouten** [OpenTTD/OpenTTD#12073] opened 2024-02-12 00:40 UTC
### Version of OpenTTD

Windows 11; OpenTTD 14.0-beta3

### Steps to reproduce

No idea, I have many NewGRF's installed and when I clicked on 'Chain Industry', OpenTTD crashed.

### Upload crash files

[crash20240212003017.zip](https://github.com/OpenTTD/OpenTTD/files/14234579/crash20240212003017.zip)

**Comment by PeterN** [comment] 2024-02-12 00:43
Thank you for reporting.

Duplicate of #12057, fixed by #12053.

**Closed as completed by PeterN** 2024-02-12 00:43 UTC
