### ISSUE TITLE
Game crash on exit scenario editor when you build or demolish infrastructure

### ISSUE THREAD

**Issue by James103** [OpenTTD/OpenTTD#7635] opened 2019-07-02 13:46 UTC
## Version of OpenTTD
20190603-master-g846fc8fe09

## Expected result
No crash on exit scenario editor

## Actual result
Game crash on exit scenario editor after doing any of the following*.
[Here is the crash log.](https://github.com/OpenTTD/OpenTTD/files/3350293/scenario.crash.zip)

## Steps to reproduce
1. Load scenario editor.
2. Do any of the following*.
3. Exit scenario editor.
4. Game crash

#### *Commands that crash the game (step 2)
* Building some road (1 piece is enough)
* Clearing some land (1 tile is enough).
* Building some canals or rivers (1 tile is enough).
* Building a bridge (road or aqueduct, 2 tiles are enough)
* Possibly more that haven't been tested yet.
* Edit: Leaving the road or dock toolbar open (by @stormcone)

#### Commands that don't crash the game
* Terraforming/landscaping.
* Doing nothing.
* Planting some trees.
* Building some towns and/or industries.
* Placing rocky land.
* Resetting the landscape (removing company-owned property).
* Configuring AI/GS.
* Possibly more that haven't been tested yet.

**Comment by stormcone** [comment] 2019-07-03 21:03
I can confirm this, but it's easier to reproduce.

- Just go to the scenario editor
- Open the road or the dock toolbar
- Go to the main menu without closing the toolbar
- Crash

The problem is in the following lines:
https://github.com/OpenTTD/OpenTTD/blob/2e23c5ec15efb3342fc1a0365f385cbe5a58999e/src/dock_gui.cpp#L108

https://github.com/OpenTTD/OpenTTD/blob/2e23c5ec15efb3342fc1a0365f385cbe5a58999e/src/road_gui.cpp#L294

Because when you exit from the scenario editor mode, the `_game_mode`'s value is changed to `GM_MENU` before the above mentioned lines are called. So the `_game_mode != GM_EDITOR` condition fails, but it should not. This bug has the same root cause as the one which was fixed with #7551, when you tried to close the toolbars in the scenario editor mode.

**Comment by James103** [comment] 2019-10-03 21:39
Can reproduce on master-20191002, with no crash log (due to #7758). It just says "OpenTTD has stopped working".

**Closed as completed** 2019-10-07 23:21 UTC
