### ISSUE TITLE
1.10.1 crashes on start in macos

### ISSUE THREAD

**Issue by kosibar** [OpenTTD/OpenTTD#8087] opened 2020-04-15 20:50 UTC
## Version of OpenTTD
1.10.1
## Expected result
The game starts.
## Actual result
As soon as I click the icon I get both a black window (with title bar) and a crash report window.
## Steps to reproduce
Try to start the game.
## More details
- Running `openttd -D` appears to work.
- I'm attaching the `crash.log` file and the output from `openttd -d9`.
[crash.log](https://github.com/OpenTTD/OpenTTD/files/4483662/crash.log)
[crash-d9.log](https://github.com/OpenTTD/OpenTTD/files/4483664/crash-d9.log)

**Comment by nielsmh** [comment] 2020-04-15 20:53
Which version of macOS? This may be a duplicate of #8066 .

Please try these two versions, see if either of those crash:
https://cdn.openttd.org/openttd-releases/1.10.0-RC1/
https://cdn.openttd.org/openttd-nightlies/2020/20200327-master-g2cc9afe057/

**Comment by glx22** [comment] 2020-04-15 21:11
crash.log says 10.12.6 so definitely a duplicate of #8066. Discussion will continue there.

**Closed as completed by glx22** 2020-04-15 21:11 UTC

**Comment by kosibar** [comment] 2020-04-15 21:40
You're right. Sorry about that. I saw a lot of "It works!" at the bottom and failed to notice that it was still open.
