### ISSUE TITLE
[Crash]: Fatal Application Failure on startup

### ISSUE THREAD

**Issue by Strudders79** [OpenTTD/OpenTTD#9555] opened 2021-09-14 14:55 UTC
### Version of OpenTTD

1.11.2, Windows 10

### Steps to reproduce

On a new build of my PC with a new install of windows, I now cannot get OpenTTD to start - it crashes on startup.  I get a "Fatal Application Failure" popup before any loading screen or the main menu.  I get the same crash with the most recent stable build, 1.11.2, as well as with 12.0-beta2.  I've tried installing the game via steam, and via the installer from https://www.openttd.org/downloads/openttd-releases/latest.html, both result in OpenTTD crashing on startup.

I'm assuming I'm missing something obvious, but I have no idea what it is.

### Upload crash files

[Uploading OpenTTD.zip…]()

**Comment by Strudders79** [comment] 2021-09-14 14:58
[OpenTTD.zip](https://github.com/OpenTTD/OpenTTD/files/7162982/OpenTTD.zip)

**Comment by glx22** [comment] 2021-09-14 15:03
Probable duplicate of #9224
using `-v win32` as extra start argument should work.

**Closed as completed by glx22** 2021-09-14 15:03 UTC

**Comment by LordAro** [comment] 2021-09-14 15:13
Or in other words, it looks like your graphics drivers are broken, and there is a crash within them when running with OTTD - using `-v win32` forces non-OpenGL mode, therefore not using your GPU

You can try updating your graphics drivers to see if that helps as well.

**Comment by Strudders79** [comment] 2021-09-14 15:25
That worked - many thanks!
