### ISSUE TITLE
Admin port: No synchronisation in NetworkAdminConsole which may be called from any thread

### ISSUE THREAD

**Issue by JGRennison** [OpenTTD/OpenTTD#9388] opened 2021-06-19 19:47 UTC
## Version of OpenTTD
master

## Expected result
No thread safety issues.

## Actual result
NetworkAdminConsole may be called at any time from any thread via the Debug macro.
This iterates ServerNetworkAdminSocketHandler instances and calls ServerNetworkAdminSocketHandler::SendConsole as required without performing any synchronisation.
Iterating ServerNetworkAdminSocketHandler whilst it is being modified could theoretically result in unwanted behaviour.
Concurrent calls to Packet::AddToQueue, or concurrent calls to Packet::AddToQueue and Packet::PopFromQueue, could theoretically result in a malformed packet queue.

I noticed this issue because I received a crash report where the above issue was triggered by debug messages logged from the UDP advertisement thread.

**Comment by rubidium42** [comment] 2021-07-23 18:18
I think the issue is bigger than what you have fixed in your patch. Under the assumption that `_settings_client.gui.developer >= 2` `IConsolePrint` gets called which might also call `NetworkServerSendRcon` and `NetworkServerSendAdminRcon`.

Similarly `send(_debug_socket...` in `DebugPrint` might be prone to the same issue, although that would be more "unintended" behaviour: 'send should not be called on the same stream-oriented socket concurrently from different threads, because some Winsock providers may split a large send request into multiple transmissions, and this may lead to unintended data interleaving from multiple concurrent send requests on the same stream-oriented socket' (winsock2 send() documentation). That might be solved easily with a guard in the actual function.

I am wondering what the effect would be of just queueing those debug messages after `fputs`, and then pushing them to the admins and in-game console from the "safe" thread. In really spammy debug sessions that might create quite a queue in-memory, so we ought to employ a similar check to whether to queue you have added.
That would also have the added benefit of not accidentally passing debug prints as replies to RCons.

**Closed as completed** 2021-09-01 20:40 UTC
