### ISSUE TITLE
[Bug]: Unbearable city ambient sounds

### ISSUE THREAD

**Issue by Shituation** [OpenTTD/OpenTTD#9797] opened 2022-01-21 00:14 UTC
### Version of OpenTTD

12.1 / Windows 10

### Expected result

Can you change the ambient sounds behavior? make them trigger less often? 
Late game needs to be muted because sawmills and docks drives anyone crazy in minutes.

### Actual result

Having to mute ambient sounds.

### Steps to reproduce

Play with ambient sounds on.

**Comment by 2TallTyler** [comment] 2022-01-21 15:51
Related (possible duplicate of): #8957

**Comment by TrueBrain** [comment] 2022-03-10 22:21
Not really a bug, but a feature request. Being able to mute certain sounds feels like an excellent idea to implement :D Or rate-limit the same sound from happening .. something creative is needed here :D

**Comment by nielsmh** [comment] 2022-03-26 06:14
Perhaps make the `SndPlayFx` family of functions also take a "sound category" flag, one of which could be "industry ambient sound". That would let the sound player rate limit ambient sounds and the like.

**Comment by Shituation** [comment] 2022-04-02 19:28
Just wanted to add the vehicle sounds to the mix as well... ships can make anyone crazy in seconds. 
Maybe adding the sound effects as a dedicated submenu with individual settings available to switch on-off... just throwing ideas.

**Comment by andythenorth** [comment] 2022-04-09 10:43
I just do this...
<img width="518" alt="image" src="https://user-images.githubusercontent.com/1780327/162568522-c56121a1-e56e-4bbf-8bd0-9f82c4715322.png">

**Closed as completed** 2024-01-09 16:35 UTC
Labels: enhancement
