### ISSUE TITLE
[Bug]: Map generation fails when no town buildable roads are available

### ISSUE THREAD

**Issue by Ufiby** [OpenTTD/OpenTTD#10574] opened 2023-03-17 16:19 UTC
### Version of OpenTTD

20230316-master-g0bf6d80cd7 (Win10 64)

### Expected result

Without failures of creating a new map

### Actual result

![Message](https://user-images.githubusercontent.com/46504018/225959960-6cbdc6b7-a382-423a-99f0-fdc3d699e269.png)

### Steps to reproduce

1. Download NewGRF: or U&RaTT, or Rattroads
2. Starting game in 1900 year

**Comment by James103** [comment] 2023-03-17 16:26
Can confirm.

**Comment by PeterN** [comment] 2023-03-17 16:34
Bug in the road-type NewGRF, no town-buildable roads exist in 1900.

**Comment by Ufiby** [comment] 2023-03-17 17:57
version 13.0 everything works smoothly, it looks like something you will change. what is forbidden to use with the flag: bitmask(ROADTYPE_FLAG_HIDDEN, ROADTYPE_FLAG_TOWN_BUILD)

**Comment by PeterN** [comment] 2023-03-17 18:52
Hidden types are meant for providing compatibility between otherwise incompatible types, not for placing on the ground.

**Comment by Ufiby** [comment] 2023-03-17 20:51
quick check
ROADTYPE_FLAG_HIDDEN + ROADTYPE_FLAG_TOWN_BUILD = will fail

**Comment by JGRennison** [comment] 2023-03-17 20:53
It was changed here: https://github.com/OpenTTD/OpenTTD/pull/10546

**Comment by PeterN** [comment] 2023-03-28 20:00
#10574 works around RattRoads' issue, however with U&RaTT there are no town-buildable road types in 1900, even when hidden-but-town-buildable roads are allowed.

This means that previously the game was reverting back to the first road type, completely ignoring all of its properties.

**Comment by Ufiby** [comment] 2023-03-29 15:50
You will be able to add a new feature, thanks to which some roads will be built only in cities inaccessible to players. But in the editor, the map is always available and even built by players.
ROADTYPE_FLAG_ONLY_SE ?

**Comment by andythenorth** [comment] 2023-03-29 16:45
The rationale (with no opinion from me for or against or any opinion at all)

> [09:07]Emperor Jake (エコレールマーク): Some roadsets have a town roadtype that updates automatically while the player buildable ones are separate types
> [09:13]andythenorth: updates for decor, surface etc?
> [09:58]reldred: Yup.
> [09:59]reldred: U&RATT most recent version is a good example of this, starts dirt, progresses through various asphalt styles
> [09:59]reldred: the dirt is dirt in certain townzones and the city streets are either cobble/paving stone, etc depending on climate
> [09:59]reldred: it's quite nice
> [09:59]reldred: rattroads also does similar
> [09:59]reldred: basically most of the 'complete' road sets use this technique

**Comment by FLHerne** [comment] 2023-03-29 16:50
Why is it desirable for the 'magic' roadtype to not be player-buildable?

If it isn't, player alterations to town roads (e.g. to repair damage around other construction, improve bus routes, or just for aesthetics) will be mismatched or become so as the town roadtype changes.

**Comment by TheMowgliMan** [comment] 2023-03-29 17:07
> Why is it desirable for the 'magic' roadtype to not be player-buildable?
> 
> If it isn't, player alterations to town roads (e.g. to repair damage around other construction, improve bus routes, or just for aesthetics) will be mismatched or become so as the town roadtype changes.
> 
> I do a lot of 'patching up' town roads like that, often just one or two tiles at a time.

Don't let the player build the magic roadtype.

Instead, have the town replace road with the magic roadtype when it grows. Of course, it's setting controllable.

**Comment by Andrew350** [comment] 2023-03-30 07:51
Apologies for being a bit late to the discussion, but perhaps I can shed some light on our perspective on this roadtype issue.

The reason we NewGRF authors have been using the HIDDEN and TOWN_BUILD flags together is to define a roadtype which can be built by towns on map generation but are not meant to be built by the player. This is used to create a unique aesthetic at game start without cluttering the player's roadtype list with a useless roadtype for the rest of the game.

For example, in RattRoads there are two early roadtypes: dirt and sett pavement. If either of these were set to be town buildable, then all towns big and small would exclusively use only that roadtype on map generation. In order to make early towns look a bit more interesting I introduced a third, hidden, roadtype which displays as dirt road in the outskirts of town, and sett pavement in large city centers. This "magic" roadtype is hidden because the effect it produces is 100% reproducible by the player during gameplay by using the other already implemented roadtypes, thereby making this "special" roadtype completely superfluous to the player. Apparently the other affected NewGRFs have followed suit using a similar effect, as seen in this ticket.

Another example is Wasteland, where I use this same feature to generate "destroyed" roads on map generation, but since allowing the player to build new pre-destroyed roads during gameplay is completely nonsensical, I mark this special roadtype as hidden, again to avoid cluttering the build list with a useless roadtype.

I'll be honest: removal of this ability is a relatively minor issue in the grand scheme of things, basically resulting in an extra useless roadtype being shown in the build list. But the real issue is that we've been using this feature exactly as it was (seemingly) intended for the last 4-5 years or so, and to have it suddenly ripped away, thus breaking our NewGRFs and the game without being given an obvious reasoning as to why, is a little irritating. 

Ultimately I don't care whether this patch is upheld or not - we can always make changes - but we would at least like to see the previously described behavior that we've been using all this time to be kept available in some form or another.

**Comment by rubidium42** [comment] 2023-03-30 10:40
Not that it directly affects the NewGRFs, though a game script has access to essentially all road types, even those you "declared" as "for town only". This as game scripts can build (some things) as owner town.

I previously made a change to allow game scripts to only build road types that are visible to the user or buildable by towns, and enforcing that. As before that it could literally build road types that did not even exist. #10546 was built on top of that.

I do not care whether it's ("user visible" and "town buildable") or only "town buildable" for determining whether a town may use the road. However, if it's only "town buildable", then game scripts will get ("user visible" or "town buildable") as filter to determine whether they are allowed to build that road. This as game scripts can build some things as town.

**Comment by auge8472** [comment] 2023-04-17 08:15
My two cents:

Also in [my road set](https://github.com/auge8472/NewGRF-Auges-Basic-Roadset) the type [`ROAD` is a hidden road type](https://github.com/auge8472/NewGRF-Auges-Basic-Roadset/blob/e70066b17a4a8ef643d583e818a9357a8084df91/auges_basic_roads.nml#L710) (the only one). On the other side there are two road types ([this](https://github.com/auge8472/NewGRF-Auges-Basic-Roadset/blob/e70066b17a4a8ef643d583e818a9357a8084df91/auges_basic_roads.nml#L820) and [that](https://github.com/auge8472/NewGRF-Auges-Basic-Roadset/blob/e70066b17a4a8ef643d583e818a9357a8084df91/auges_basic_roads.nml#L847)), which are the two road types, that are [defined as buildable by towns](https://github.com/auge8472/NewGRF-Auges-Basic-Roadset/blob/e70066b17a4a8ef643d583e818a9357a8084df91/auges_basic_roads.nml#L857) (with `roadtype_flags: bitmask(ROADTYPE_FLAG_TOWN_BUILD);`). Year dependent the towns build the one or the other road. Different from @Andrew350's system, in my set *are these roads also buildable by the players* (and I don't know any reason to forbid it) and therefore are visible. Because of the system with the road types, that are compatible with `ROAD` *and* are buildable by towns *and* are not hidden, my system works with the changes in #10546.

IMHO it is debatable to hide the `ROAD` road from the player. I know, there are road sets with a plenty of types, that really clutter the road type list (the set alone or in combination with further sets). Thatswhy I understand the wish to hide a few types, especially when they are meant to be buildabe by towns only (no entry for the road if the player cannot use the road type). I *for myself* think, that there is no reason to have a road type, that is buildable only by a town but not for me as a player. Other authors and players may judge this differently.

**Comment by PeterN** [comment] 2023-04-19 10:13
63 types.

There is zero player/author feedback on the proposal in #10582 or #10585, so we can probably assume that nobody is interested in having this changed...

**Comment by PeterN** [comment] 2023-04-25 11:42
So far you're up to no comments on #10582 and one comment on #10585...

**Comment by 2TallTyler** [comment] 2023-12-23 22:55
@PeterN Was this resolved by #10585?

**Comment by PeterN** [comment] 2023-12-23 22:57
Nobody has been complaining since, so I assume so.

**Closed as completed** 2023-12-24 00:19 UTC
Labels: component: NewGRF
