### ISSUE TITLE
[Bug]: Wrong capacity for ARV's parts

### ISSUE THREAD

**Issue by George-VB** [OpenTTD/OpenTTD#10320] opened 2023-01-05 12:27 UTC
### Version of OpenTTD

13rc1 win64

### Expected result

I have a train vehicle (ARV), that has several compartments (for passengers and mail, like planes do). 
It is intended, that each one has its own capacity, and it can't be changed, available cargoes lists are [PASS] for the first and [MAIL] for the second compartments.

Train: DP-0, xUSSR railways set, version 0.7 on bananas     

### Actual result

When I choose passenger cargo in the buy menu, it works fine, but when I choose mail cargo, I get the the double capacity of mail. When the vehicle is build, the capacity is correct.

### Steps to reproduce

Create a new game with xUSSR railways set 0,7, cheat the money and change a year to something like 2050-th
Build a depot
Open buy vehicle window and choose DP0
You see the correct capacity 164 passengers and 6 mail
Change the cargo to mail.
You see wrong capacity

**Comment by PeterN** [comment] 2023-01-05 12:57
Duplicate of #10032

**Closed as not planned by PeterN** 2023-01-05 12:57 UTC
