### ISSUE TITLE
New GRF Stations Not Showing Up

### ISSUE THREAD

**Issue by ZJFishy** [OpenTTD/OpenTTD#7466] opened 2019-04-04 16:41 UTC
## Version of OpenTTD
1.9.0
## Expected result
NewGRF stations should show up in the list under the default station when placing a train station.
## Actual result
Entries on the list are blank, but stations themselves still show up
## Steps to reproduce
View the train station placement menu with some station NewGRFs enabled

**Comment by PeterN** [comment] 2019-04-04 16:42
Duplicate of #7447

**Comment by PeterN** [comment] 2019-04-08 22:21
Fixed in 1.9.1

**Closed as completed by PeterN** 2019-04-08 22:21 UTC
