### ISSUE TITLE
[Bug]: Cash register sound is classified as a vehicle sound

### ISSUE THREAD

**Issue by Shituation** [OpenTTD/OpenTTD#9900] opened 2022-05-29 02:33 UTC
### Version of OpenTTD

12.2 / Windows 10

### Expected result

To have miscellaneous FX separated from other sound settings.

### Actual result

Turning off vehicle sounds (which can drive anyone crazy in seconds - specially ships) also turns cash register sound off too.

### Steps to reproduce

Just play with the vehicle sounds on then turn off and compare.

**Comment by Joel-Milligan** [comment] 2022-06-21 08:21
Which setting do you believe the cash register sound should be under instead? Perhaps ambient?
![image](https://user-images.githubusercontent.com/52927756/174752139-2954c351-e8e4-4d86-8480-f61e3dbbec16.png)

**Comment by Shituation** [comment] 2022-06-21 14:42
> Which setting do you believe the cash register sound should be under instead? Perhaps ambient?

Not ambient, since its so annoying that has to be disabled. The game suffers from a really bad sound fx implementation and sadly one has to play it muted. To give a little "life" to it I would like to 'at least' have the cash sound. 
I would separate it into maybe "End of year" since its not intrusive at all and can be left ON.

**Comment by 2TallTyler** [comment] 2023-12-24 00:33
Redoing the sound system would be a helpful project, but the current implementation is not a bug, and I don't think the suggestion of moving the cash register sound to "end of year" is a correct solution. 

Since this is not a bug -- but a feature request, I am closing the bug report. 🙂

**Closed as not planned by 2TallTyler** 2023-12-24 00:33 UTC
Labels: enhancement, priority: low
