### ISSUE TITLE
[Bug]: Server desync when client's player_face is non-zero

### ISSUE THREAD

**Issue by chiizujin** [OpenTTD/OpenTTD#10171] opened 2022-11-14 07:25 UTC
### Version of OpenTTD

13.0-beta1 Linux Mint 20.3

### Expected result

Clients with a favourite face set should not get a desync error.

### Actual result

Setting player_face in the client's openttd.cfg to anything other than zero causes a desync error when creating a new company immediately after a new game game has started ("newgame" or "restart").

Restarting the game and creating a new company seems to be a reliable way to cause the desync to happen immediately.

### Steps to reproduce

1. Start a server.
2. Set a custom face in the client (or set player_face in the config file).
3. Connect to the server with this client.
4. On the server issue the "newgame" or "restart" commands.
5. As soon as the client reconnects, click the button to create a new company.

The desync should happen immediately. In my testing the desync happens every time with a non-zero player_face and never with zero.

**Comment by PeterN** [comment] 2022-11-14 08:29
Dupe of #10154, closed by #10157

**Closed as completed by PeterN** 2022-11-14 08:29 UTC
