### ISSUE TITLE
Server exiting to main menu hangs client

### ISSUE THREAD

**Issue by SamuXarick** [OpenTTD/OpenTTD#7462] opened 2019-04-02 22:53 UTC
## Version of OpenTTD
1.9.0
## Expected result
Client exits to main menu
## Actual result
Client hangs
## Steps to reproduce
(Server) Create a non-dedicated server
(Client) Join server
(Server) Exit to main menu
(Client) hangs

**Comment by SamuXarick** [comment] 2019-04-02 22:55
EDIT: Oh snap, client actually reached main menu as I was typing this. It really took a long time though, and looked like it was hanged.

**Comment by SamuXarick** [comment] 2019-04-03 02:20
It was due to my savegame format, lzma:9 and map size being 4096x4096. It could display a Zzz cursor though.

**Comment by LordAro** [comment] 2019-12-31 13:52
I can confirm this. More so, it would appear that the emergency network save (netsave.sav) happens twice, compounding the issue. (FOO debugs show where `ClientNetworkEmergencySave` is called from)

```
FOO: virtual NetworkRecvStatus ClientNetworkGameSocketHandler::Receive_SERVER_SHUTDOWN(Packet*)
dbg: [net] Client: Performing emergency save (netsave.sav)
FOO: void ClientNetworkGameSocketHandler::ClientError(NetworkRecvStatus)
dbg: [net] Client: Performing emergency save (netsave.sav)
```

Not yet sure why the whole game hangs when it's doing this emergency save - looks like it might just be because it's not threaded?

**Comment by LordAro** [comment] 2020-01-02 15:54
Seems like it might not be possible to thread the save in this case - as nonthreaded would mean that the game goes back to the title screen and loads the title game, which would corrupt the save/saving process. Probably.

Caused by #6796

**Comment by TrueBrain** [comment] 2021-01-02 19:42
I agree with @LordAro's analysis. This simply happens because an emergency save is happening. While normally all saves are done threaded, so you can continue playing, this happens in such a place we don't have that luxury.

I think the only way to solve this, would be to add an additional game-mode. It is a bit complicated, let's see if I can write it down:

- Drawing is done via the main GameLoop. If that is not looping, drawing is not done. (even with threaded drawing, the GameLoop is in control when the thread is allowed to draw again)
- This Emergency Save is added in a place that is busy doing clean-up of the server closing socket. It cannot return to the GameLoop until it is done, as other work needs to be done too

I think the only way out is to make a new game-mode, that knows it is doing an Emergency Save, and knows where to go to after it is done. This is a lot of work for a very rare case. And it will not be pretty.
Other solutions would be to restructure our whole code to be more async .. but that is not happening any time soon :)

As such, I am going to close this ticket with: working-as-intended. I know it is a bit annoying, but better to have the savegame than to not have the savegame at all :)

**Closed as completed by TrueBrain** 2021-01-02 19:42 UTC
Labels: won't fix
