### ISSUE TITLE
[Crash]: Seg fault 11

### ISSUE THREAD

**Issue by sbibauw** [OpenTTD/OpenTTD#9956] opened 2022-07-26 05:06 UTC
### Version of OpenTTD

12.2, macOS 12.4 (Intel)

### Steps to reproduce

1. Had installed some modules + started a scenario.
2. Restarted the game.
3. Installed abase.
4. Activated abase in the options.
5. Crash

### Upload crash files

[Archive.zip](https://github.com/OpenTTD/OpenTTD/files/9186685/Archive.zip)

**Comment by glx22** [comment] 2022-07-28 20:25
Might be a duplicate of #9876

**Comment by LordAro** [comment] 2022-08-29 17:36
Duplicates #9876

**Closed as not planned by LordAro** 2022-08-29 17:36 UTC
