### ISSUE TITLE
[Bug]: Property maitenance cost is very high for airport

### ISSUE THREAD

**Issue by milsa** [OpenTTD/OpenTTD#9923] opened 2022-06-15 20:09 UTC
### Version of OpenTTD

12.2

### Expected result

Normal cost for airport.

### Actual result

400000000 € by month or more
[SládkoviÍovo Transport, 1930-07-01.zip](https://github.com/OpenTTD/OpenTTD/files/8912731/SladkoviIovo.Transport.1930-07-01.zip)
.

### Steps to reproduce

Open saved game and check "Property maintenance". Problem is with airport.

**Comment by nielsmh** [comment] 2022-06-15 20:40
Something is wrong with the configuration of the OpenGFX+ Airports 0.4.2 NewGRF you have in your savegame. It shows a maintenance costs level of "0" which is not one of the possible values. The maintenance costs is not a bug in OpenTTD, but whatever allowed you to start a game with an invalid NewGRF configuration like that might be a bug.

![image](https://user-images.githubusercontent.com/1062071/173922719-a9ef363b-7f0c-41bb-b89c-8c882f68e56c.png)

**Comment by milsa** [comment] 2022-06-16 14:12
Fixing problem will not solve problem with my saved played game?

IMHO, it is problem with uint32 overflow, not?

Why is problem to allow value 0 of costs? This will solve problem with saved games without airports. It will be allowed to build airport in future.

**Comment by nielsmh** [comment] 2022-06-16 14:49
The NewGRF has gotten an invalid configuration somehow, so the code in the NewGRF is behaving outside what the developer planned for. OpenTTD can't know if that's intentional or not, it just does what the NewGRF code says to do.
The way the maintenance costs setting is shown, the calculation internally is probably a bit-shift operation to halve/double the maintenance costs a number of times, and this invalid setting value specifies to double it many more times than it would normally.

The value in the GUI is _shown_ as 0, but I'm quite sure that's just a placeholder for "string not found" of some sort. The setting has 9 valid values, internally numbered 0 to 8 (corresponding to 1/32 up to 32x), and this thing displayed as "zero" maybe has an internal value of 10 or 16 or something outside the range of 0 to 8.

**Comment by nielsmh** [comment] 2022-08-26 11:14
I tried adding some debug printing to the GRF config window and got this output:
```
dbg: [grf] GRF name: opengfx_airports-0.4.2\ogfx-airports.grf
dbg: [grf] GRF parameters: 0 used/3 valid
dbg: [grf] GRF param 0 (bit 0): current=0, min=0, max=1
dbg: [grf] GRF param 0 (bit 1): current=0, min=0, max=1
dbg: [grf] GRF param 1 (bits 0-31): current=0, min=4, max=14
```
The thing shown here is that the third parameter does in fact have a numeric value of 0, but the valid range is 4 to 14, so the value is out of range.

The bug here is not that the GRF is misbehaving because it got fed out-of-range parameters, the bug is that someone, somehow, put an invalid GRF configuration into this savegame. The bug to fix is whatever allowed that invalid GRF configuration to be made.

So my question: Is this a savegame you made yourself from scratch, or is it based on a downloaded scenario, or is it one you got from someone else?
And if it's a game you made from scratch, how did you add the NewGRFs and how did you configure them?

**Comment by Andrew350** [comment] 2022-08-26 20:08
This may be related to #8846

If OP "upgraded" the NewGRF from the main menu (perhaps from an old NewGRF preset) it is possible that that parameter's valid range was changed from an earlier version of the NewGRF, or it was a new parameter entirely, thus OpenTTD simply set it to 0 as seen in the linked issue.

Just my guess anyways :)

**Comment by 2TallTyler** [comment] 2023-12-24 00:30
This report appears to have been caused by changing or adding a NewGRF in an existing game. This is not supported functionality (there's a big red warning before you do it), so I am closing this ticket.

**Closed as not planned by 2TallTyler** 2023-12-24 00:30 UTC
Labels: needs triage

**Comment by milsa** [comment] 2023-12-28 14:48
This is not true:

This report appears to have been caused by changing or adding a NewGRF in an existing game. This is not supported functionality (there's a big red warning before you do it), so I am closing this ticket.

Please add information to saved game about change NewGRF during playing game to avoid these verdicts. It gives me a bad name. Or please check saved game for this information.

**Comment by nielsmh** [comment] 2023-12-28 14:52
We do already store changes to NewGRF configuration in the savegame, in the part called the Gamelog. The Gamelog lists every time the NewGRF configuration is changed in the game, and every time the saved game is loaded in a new version of the game (and thus format-upgraded), and I remember checking that for this saved game and there was nothing odd in the Gamelog.

I'm not sure how it can have happened, but it's definitely a problem with how that NewGRF ended up configured.
