### ISSUE TITLE
[Bug]: Planes still go to hangars even when aging/mantainance are turned off

### ISSUE THREAD

**Issue by Shituation** [OpenTTD/OpenTTD#9806] opened 2022-02-01 22:45 UTC
### Version of OpenTTD

12.1 / Windows 10

### Expected result

That planes do not go to hangars automatically unless ordered.

### Actual result

Planes still go to hangars even when mantainance and aging are turned off globally. They enter and exit immediately. 

### Steps to reproduce

![image](https://user-images.githubusercontent.com/43975882/152064043-15afe649-d8c1-499a-b59b-149875daed62.png)
Then watch airplane behavior closely.

**Comment by PikkaBird** [comment] 2022-02-01 23:21
Planes will go to the hangar to wait if they've landed and there's no available loading space, to avoid deadlocking the airport state machine. Is this what you're seeing?

Otherwise, can you provide a save game? Does it only happen with some airport types, or all of them?

**Comment by elcosomalo1** [comment] 2022-02-02 01:32
It could be what you say, but I can see space on the docks so something is not working well; because I see planes entering and exiting immediately.
 

[autosave14.zip](https://github.com/OpenTTD/OpenTTD/files/7982999/autosave14.zip)

**Comment by PikkaBird** [comment] 2022-02-02 01:45
Yep, that's definitely a feature of that airport's layout's state machine, with the hangar immediately after the touchdown point. If the aircraft can't immediately taxi to a loading point (because another moving aircraft is in the way), it enters the hangar to clear the way for additional planes to land.

**Comment by TrueBrain** [comment] 2022-03-10 22:18
As explained. Working as intended. The alternative is far far worse :D

**Closed as completed by TrueBrain** 2022-03-10 22:18 UTC
