### ISSUE TITLE
[Crash]: openTTD crashes at startup

### ISSUE THREAD

**Issue by Maik1976** [OpenTTD/OpenTTD#9936] opened 2022-06-27 19:16 UTC
### Version of OpenTTD

12.2 Linux 5.18.6 openSuSE tumbleweed

### Steps to reproduce

Start openTTD: window opens an then crash happens within less than 1 second.
creating crash.dmp is aborted. every time.

I tried it now 5 times:

Crash log generated.

Writing crash log to disk...
Crash log written to /home/maik/.openttd/crash20220627190113.log. Please add this file to any bug reports.

Writing crash savegame...
Crash savegame written to /home/maik/.openttd/crash20220627190113.sav. Please add this file and the last (auto)save to any bug reports.

Writing crash screenshot...
Crash screenshot written to /home/maik/.openttd/crash20220627190113.png. Please add this file to any bug reports.

Aborted (Speicherabzug geschrieben)

### Upload crash files

[crash20220627190113..zip](https://github.com/OpenTTD/OpenTTD/files/8994927/crash20220627190113.zip)
[crash20220627185614..zip](https://github.com/OpenTTD/OpenTTD/files/8994928/crash20220627185614.zip)

**Comment by Maik1976** [comment] 2022-06-27 19:24
```
Architektur:                       x86_64
  CPU Operationsmodus:             32-bit, 64-bit
  Adressgrößen:                    48 bits physical, 48 bits virtual
  Byte-Reihenfolge:                Little Endian
CPU(s):                            4
  Liste der Online-CPU(s):         0-3
Anbieterkennung:                   AuthenticAMD
  Modellname:                      AMD Phenom(tm) II X4 955 Processor
    Prozessorfamilie:              16
    Modell:                        4
    Thread(s) pro Kern:            1
    Kern(e) pro Sockel:            4
    Sockel:                        1
    Stepping:                      3
    Maximale Taktfrequenz der CPU: 3200,0000
    Minimale Taktfrequenz der CPU: 800,0000
    BogoMIPS:                      6416.25
    Markierungen:                  fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxex
                                   t fxsr_opt pdpe1gb rdtscp lm 3dnowext 3dnow constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid pni monitor cx16
                                    popcnt lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt hw_pstate v
                                   mmcall npt lbrv svm_lock nrip_save
Virtualisierungsfunktionen:        
  Virtualisierung:                 AMD-V
Caches (Gesamtsumme):              
  L1d:                             256 KiB (4 Instanzen)
  L1i:                             256 KiB (4 Instanzen)
  L2:                              2 MiB (4 Instanzen)
  L3:                              24 MiB (4 Instanzen)
NUMA:                              
  NUMA-Knoten:                     1
  NUMA-Knoten0 CPU(s):             0-3
Schwachstellen:                    
  Itlb multihit:                   Not affected
  L1tf:                            Not affected
  Mds:                             Not affected
  Meltdown:                        Not affected
  Mmio stale data:                 Not affected
  Spec store bypass:               Not affected
  Spectre v1:                      Mitigation; usercopy/swapgs barriers and __user pointer sanitization
  Spectre v2:                      Mitigation; Retpolines, STIBP disabled, RSB filling
  Srbds:                           Not affected
  Tsx async abort:                 Not affected

```

**Comment by nielsmh** [comment] 2022-06-28 15:53
Duplicate of #9935

**Closed as completed by nielsmh** 2022-06-28 15:53 UTC
