### ISSUE TITLE
DPI too high makes UI unusable on Mac OS X catalina

### ISSUE THREAD

**Issue by scovit** [OpenTTD/OpenTTD#8806] opened 2021-03-06 00:26 UTC
## Version of OpenTTD
OpenTTD 1.11.0-beta2 on Mac OS X catalina

## Expected result
UI usable, with a dpi similar to OpenTTD 1.10.3
<img width="453" alt="image" src="https://user-images.githubusercontent.com/15249203/110187996-8c1ea480-7e1a-11eb-860a-7fbc447e8309.png">

## Actual result
UI unusable due to the much higher DPI
<img width="453" alt="image" src="https://user-images.githubusercontent.com/15249203/110188063-bd977000-7e1a-11eb-9b8d-901c523f7ae4.png">

## Steps to reproduce
Download OpenTTD dmg, mount it, execute OpenTTD from the virtual disk

**Comment by James103** [comment] 2021-03-06 00:29
Can't you just set "Font size" and/or "Interface size" to 2x from the "Game Options" window?

**Comment by scovit** [comment] 2021-03-06 00:33
Thank you James103, your suggestion is a correct workaround. I think it should be set by default

**Comment by LordAro** [comment] 2021-03-06 07:21
Duplicate of #8786. As far as I know, "auto" is the default for a fresh config/install

**Closed as completed by LordAro** 2021-03-06 07:21 UTC
