### ISSUE TITLE
Game crashes while opening Towns directory on OS X, 1.11.0 Steam

### ISSUE THREAD

**Issue by xelnod** [OpenTTD/OpenTTD#9036] opened 2021-04-13 09:59 UTC
## Version of OpenTTD
1.11.0 via Steam @ Mac OS X.

## Expected result
Game doesn't crash

## Actual result
Game crashes.

## Steps to reproduce
1. Load the save game
2. Select Town directory
3. Select Sort by: Rating, from highest to lowest.
4. Close Towns directory
5. Open Towns directory — game crashes.

The crash is reproduced if I switch graphic pack to OpenGFX.
The crash doesn't reproduce on my other saved games (including same game saves earlier than ~1955): I suppose might have to do with game progress.
The crash doesn't occur with the same savegame and same app version but on Windows PC.

I am unable to find crash.dmp on my machine, but am attaching .sav and .log in crash.zip

**Comment by xelnod** [comment] 2021-04-13 10:00
[crash.zip](https://github.com/OpenTTD/OpenTTD/files/6302868/crash.zip)
```
*** OpenTTD Crash Report ***

Crash at: Tue Apr 13 09:51:24 2021
In game date: 1959-09-11 (40)

Crash reason:
 Signal:  Segmentation fault: 11 (11)
 Message: <none>

OpenTTD version:
 Version:    1.11.0 (0)
 NewGRF ver: 1b086d64
 Bits:       64
 Endian:     little
 Dedicated:  no
 Build date: Apr  1 2021 12:47:14


Stacktrace:
 [00] openttd              0x0000000103d6918c (Pool<Company, Owner, 1ul, 15ul, (PoolType)1, false, true>::CleanPool() + 156700)
 [01] openttd              0x0000000103c90783 (Pool<ServerNetworkGameSocketHandler, unsigned char, 8ul, 256ul, (PoolType)2, false, true>::CleanPool() + 63523)
 [02] openttd              0x0000000103c90652 (Pool<ServerNetworkGameSocketHandler, unsigned char, 8ul, 256ul, (PoolType)2, false, true>::CleanPool() + 63218)
 [03] libsystem_platform.dylib 0x00007fff20543d7d (_sigtramp + 29)

Operating system:
 Name:     Mac OS X
 Release:  11.2.2
 Machine:  Intel x86-64h Haswell
 Min Ver:  1090
 Max Ver:  110100
 Compiler: GCC 4.2.1 "Apple LLVM 12.0.0 (clang-1200.0.32.29)"

Configuration:
 Blitter:      40bpp-anim
 Graphics set: zBase (5588)
 Language:     /Users/out-zenchenko-sk/Library/Application Support/Steam/steamapps/common/OpenTTD/OpenTTD.app/Contents/Resources/lang/english_US.lng
 Music driver: cocoa
 Music set:    DOOM (1)
 Network:      no
 Sound driver: cocoa
 Sound set:    OpenSFX (7758)
 Video driver: cocoa-opengl

Fonts:
 Small:  Arial Bold
 Medium: sprite
 Large:  Arial Bold
 Mono:   sprite

AI Configuration (local: 0) (current: 0):
  0: Human

Libraries:
 LZMA:       5.2.5
 LZO:        2.10
 PNG:        1.6.37
 Zlib:       1.2.11

---- gamelog start ----
Tick 0: new game started
Revision text changed to 1.11.0, savegame version 290, not modified, _openttd_newgrf_version = 0x1b086d64
New game mode: 1 landscape: 1
Tick 35731: settings changed
Setting changed: vehicle.plane_speed : 4 -> 3
Tick 35731: settings changed
Setting changed: vehicle.plane_speed : 3 -> 2
Tick 35731: settings changed
Setting changed: vehicle.plane_speed : 2 -> 1
Tick 35731: settings changed
Setting changed: vehicle.plane_speed : 1 -> 2
Tick 35731: settings changed
Setting changed: vehicle.plane_speed : 2 -> 3
Tick 35731: settings changed
Setting changed: vehicle.plane_speed : 3 -> 4
---- gamelog end ----

Recent news messages:

*** End of OpenTTD Crash Report ***
```

**Comment by LordAro** [comment] 2021-04-13 13:16
Very strange that something like that would be MacOS specific. Can you try a nightly build? https://www.openttd.org/downloads/openttd-nightlies/latest.html They have a few extra debugging features enabled which may help work out what's going on

**Comment by xelnod** [comment] 2021-04-13 14:30
TBH I'm not 100% sure it's exactly MacOS specific, since the other machine has another hardware, another amount of RAM etc.
I was able to reproduce the issue with the nightly build, though it didn't generate .sav and .log automatically. How do I use the debugging features?
Also I was unable to reproduce on the later save in the same game (either with the stable build or with nightly) which tells me it's probably unrelated to the number of objects or hideous amount of signs and seems more like connected to the specific game state.

**Comment by TrueBrain** [comment] 2021-05-27 12:07
Sadly, I fail to reproduce this problem. I tried various of OSes, compilers, compile-settings, etc, but when following the steps above, it "just works". The `crash.log` suggests you were running a server, but that too makes no difference for me, and I fail to get it to crash.

That makes me rather sad, as if we cannot reproduce it, we cannot diagnose it :( 

Given you managed to continue on and newer saves do not show this problem, I am somewhat tempted to close it as "cannot reproduce". Please do reopen it if you happen to run into this again (and attach the crash information again), or if anyone else manages to reproduce it.

Tnx, and tnx for the report!

**Closed as completed by TrueBrain** 2021-05-27 12:07 UTC
