### ISSUE TITLE
[Crash]: 

### ISSUE THREAD

**Issue by SammieBiscuits** [OpenTTD/OpenTTD#11332] opened 2023-09-22 14:39 UTC
### Version of OpenTTD

13.0, Windows 10

### Steps to reproduce

1. Open game and load attached save.
2. The game will crash with error "Assertion failed at line 228 of D:\a\OpenTTD\OpenTTD\src\road.h: roadtype < ROADTYPE_END"

### Upload crash files

[crash20230922142715.zip](https://github.com/OpenTTD/OpenTTD/files/12701912/crash20230922142715.zip)
Save file and errors are included. No crash.sav was generated by the game.

P.S. Game seems to work on the mobile version of OpenTTD version 13.0

**Comment by PeterN** [comment] 2023-09-22 15:22
Duplicate of #11319, corrupted savegame.

**Closed as completed by PeterN** 2023-09-22 15:22 UTC
