### ISSUE TITLE
suddenly it crashes without any reason

### ISSUE THREAD

**Issue by Teletoby12000** [OpenTTD/OpenTTD#7543] opened 2019-04-25 22:15 UTC
## Version of OpenTTD
20190425-master-g5b0ce8c214
[crash.log](https://github.com/OpenTTD/OpenTTD/files/3119048/crash.log)
![crash](https://user-images.githubusercontent.com/48702858/56771871-458ca780-67b8-11e9-864a-3c026e467a1f.png)

## Actual result
Assertion failed at line 213 of /Users/vsts/agent/2.150.0/work/1/s/src/core/kdtree.hpp: next != INVALID_NODE## Steps to reproduce

**Comment by LordAro** [comment] 2019-04-25 22:18
Thanks for the report, looks like this is a duplicate of either #7481 or #7530

**Comment by Teletoby12000** [comment] 2019-04-25 22:23
> Thanks for the report, looks like this is a duplicate of either #7481 or #7530

it happens irregularly, even when i do nothing in the game. after a few minutes it crashes. But it happens only in the latest nightly build.

**Comment by Gymnasiast** [comment] 2019-04-26 19:01
@Teletoby12000 For me, it also happens when I do nothing. Research done in #7481 suggests it might be down to how the game handles an Oil Rig closing down -- something that happens even when you do nothing.

**Comment by LordAro** [comment] 2019-04-26 19:06
Given #7530 was closed as duplicate, I shall assume that this is the same issue as well, lacking any other information

**Closed as completed by LordAro** 2019-04-26 19:06 UTC
