### ISSUE TITLE
[Bug]: Useless buttons when founding town in game

### ISSUE THREAD

**Issue by hpiirai** [OpenTTD/OpenTTD#10287] opened 2022-12-27 17:06 UTC
### Version of OpenTTD

20221226-master-g6caed5f15e, Debian GNU/Linux bookworm/sid

### Expected result

The game shows only user interface elements that might actually be used during a game.

### Actual result

When founding towns in the game is allowed, the in-game **Found town** dialogue displays UI elements that don’t make sense outside the scenario editor; specifically **Random Town**, **Many random towns**, **Expand all towns**, and the **Large** town size:
![Unnamed, 1950-01-11](https://user-images.githubusercontent.com/45715592/209690143-04d9475c-5b93-4cf9-9156-9576ba8b5fe7.png)

Moreover, when the setting is  **Allowed** rather than **Allowed, custom town layout**, the entire **Town road layout** section is useless:
![Unnamed, 1950-01-18](https://user-images.githubusercontent.com/45715592/209690147-68f5ba14-a8eb-4496-86dd-f7f9d33ed1fe.png)

### Steps to reproduce

1. On the main screen, open **Settings**.
2. Find the setting **Founding towns in game** and set it to **Allowed** or **Allowed, custom town layout**.
3. Start a new game.
4. Open the **Found town** dialogue.

**Comment by redone9211** [comment] 2023-01-22 05:34
i would like to contribute to this issue , can you let me know how i can solve it.

**Comment by 2TallTyler** [comment] 2023-01-24 23:40
@LC-Zorg - Do you have any ideas for redesigning this window? It's currently a mess of unrelated buttons, some toggles and some actions...and I'm about to add another button to load a list of towns from an external file. I thought maybe you have mockups floating around your hard drive already. 😃

**Comment by LC-Zorg** [comment] 2023-01-27 00:11
I don't have. I think once I was wondering if something could be changed here, but I didn't have any good idea and to be honest I'm not even sure if it really makes sense to change anything here. Ok, this window during the game could look a bit simpler, i.e. without options that the player can't use anyway. Maybe I'll glue something together, but not today and probably not tomorrow.

In addition, there is one significant problem when creating scenarios that is worth solving: you can accidentally press Many random towns, which is very burdensome to undo. I can't see it, but I suppose you added/will add a location import button below that button. You press a few pixels higher and... you have a disaster. ;D It's worth adding a confirmation window there. Possibly, I also thought that instead of the red confirmation window, a window would appear to indicate the number of cities that would be generated, but I don't know if this is really needed by anyone. I think a simple confirmation would suffice.

Ok, I made a quick sketch with mentioned suggestion. :)

![Town generation window v1 1](https://user-images.githubusercontent.com/67662046/214977894-efed79ab-6c76-4e0d-bc6b-bfb6cdf3282a.png)

I don't know if it makes sense to provide the Large and Random size options during the game - it could also be hidden (cost of random is the same as medium - that way it doesn't make sense to keep it). If you can't choose the layout of the roads, the whole part could be hidden too.

**Comment by JoostKingma** [comment] 2023-05-25 13:23
@LC-Zorg , @2TallTyler I would love to try and pick this issue up if that's alright and still available?
If I could also make a suggestion? I would split it up into 3 different version since it has 3 different use cases:
![image](https://github.com/OpenTTD/OpenTTD/assets/56867318/b9594f03-f5d4-4f7f-bc21-cef891752520)
(Appologies for the less fancy sketch in excel)

The first 2 screens are for creating a single town in their respective mode. With seperate titles depending on the mode, I would argue to remove the Large/Random from the in game menu since these are irrelavant for the player but keep the road layout and grey this out when it's disabled.

Instead of a toggle for city I would create 2 buttons for creating a town or city to have a more clear disticntion between the 2 options. During the game I think this should also show a price before you're building it like it does with funding industries.

The extra screen on the right are for the situations where you're creating/generating more than 1 single town and this could later maybe be expended to give more control over this generation? (ratios between town vs city, distrubtion of population)

**Comment by 2TallTyler** [comment] 2023-05-25 13:49
Yes to all of the above. Town generation could definitely use some love. We don't really design by committee here: more often someone comes along with a vision and we just help mesh it into the game. Put together your ideal UI and open a PR, we can discuss specifics there!

Side note, we don't have a "load from file" feature but #10409 will eventually do this. I got stuck finding a suitable JSON library but TrueBrain needed one for something else so now the hard work is done for me. 😄 Don't wait for me though, just leave out the button for now and I'll add it in my PR.

**Comment by 2TallTyler** [comment] 2023-10-16 16:14
@JoostKingma: Are you still interested in working on this? I've made some progress on #10409 so resolving this would be helpful. 😃

**Comment by 2TallTyler** [comment] 2023-12-23 23:08
This is not a bug, but a suggestion...and the issue tracker is not the place for those. I welcome any PRs to improve this GUI, but I'm closing this ticket. 🙂

**Closed as not planned by 2TallTyler** 2023-12-23 23:08 UTC
Labels: good first issue, component: interface, enhancement
