### ISSUE TITLE
[Bug]: New Oil Wells do not spawn in Temperate

### ISSUE THREAD

**Issue by heresyh** [OpenTTD/OpenTTD#11042] opened 2023-06-19 12:02 UTC
### Version of OpenTTD

13.3

### Expected result

New Oil Wells should spawn until 1950.

### Actual result

New Oil Wells are not spawning.

### Steps to reproduce

Noticed someone on the forum saying they were not getting new Oil Well spawns in Temperate and I did some testing.
This was on a fresh download of 13.3, only changed Economy setting to Frozen to disable closures.

All 256x256 maps.
Sub-Arctic. Start with 4 Oil Wells in 1860, 14 in 1950.
Sub-Tropical. Start with 2 Oil Wells in 1860, 8 in 1950.
Temperate. Start with 4 Oil Wells in 1860, 4 in 1950.

Sub-Arctic. Start with 6 Oil Wells in 1800, 18 in 1950.
Sub-Tropical. Start with 2 Oil Wells in 1800, 10 in 1950.
Temperate. Start with 3 Oil Wells in 1800, 3 in 1950.

Behaviour seemed the same in previous versions also, I tested 13.3, 12.2, 1.11.2 and 1.10.3 (though, here I only let it run for about 20 years, as lack of uncapped fast forwarding made it slower to test).

**Comment by rubidium42** [comment] 2023-07-06 17:24
This is the behaviour since the first revision in this code repository.

In https://github.com/OpenTTD/OpenTTD/blob/efaeb275f78e18d594d9ee8ff04eccd2dc59512c/industry_cmd.c#L1694 a random element from the array at https://github.com/OpenTTD/OpenTTD/blob/efaeb275f78e18d594d9ee8ff04eccd2dc59512c/industry_cmd.c#L1682 is chosen to build as industry. Oil wells are index number 11, which you'll find in the second and third row of the table corresponding with arctic and tropical. It does not appear to be the case for the first row, which corresponds with the temperate climate.

Digging further you'll find that the default properties for industries are defined for NewGRFs in https://newgrf-specs.tt-wiki.net/wiki/IndustryDefaultProps#Appearance_Chances. These are the defaults of TTDPatch, and as such the original Transport Tycoon Deluxe. Here you will see that the in-game spawn chance of oil wells in temperate at 0.

I do agree the behaviour is unexpected, but it has probably been a conscious design choice to not give it any chance of spawning.

**Comment by 2TallTyler** [comment] 2023-08-11 14:04
Closing as this is intended design, and not a bug.

I tested [OpenGFX+ Industries](https://www.tt-forums.net/viewtopic.php?t=54187) to see if if has an in-game spawn chance, but at least on the default settings it does not. Other settings may, or it would be easy to make a NewGRF that overrides the oil well industry and simply changes the spawn chance.

**Closed as completed by 2TallTyler** 2023-08-11 14:04 UTC
