### ISSUE TITLE
[Bug]: Trains become lost and randomly reverse direction despite there being no signal

### ISSUE THREAD

**Issue by Krakabraka** [OpenTTD/OpenTTD#9916] opened 2022-06-06 17:34 UTC
### Version of OpenTTD

Steam, Windows 11

### Expected result

I decide I want to replace a tunnel with tracks above ground, but some houses are in the way.
I delete the houses and claim the land above using signs.
I build tracks and everything works nicely.

### Actual result

I decide I want to replace a tunnel with tracks above ground, but some houses are in the way.
I delete the houses and claim the land above using signs.
After I place the signs and build the tracks, the game treats them as if they did not exist and makes the train lost.

### Steps to reproduce

[KrakaCorp2.zip](https://github.com/OpenTTD/OpenTTD/files/8846360/KrakaCorp2.zip)
Try unpausing the game and starting train `#2`, the one just outside Grudgrove station.

**Comment by glx22** [comment] 2022-06-06 17:49
Wrong track type, it's an electric train and it's reversing because it can't enter on non electrified track.

**Comment by LC-Zorg** [comment] 2022-06-11 20:31
I would have two questions about this situation:
1. Should the trains stop and don't move then?
2. Should there be adequate information about the cause?

I'm not entirely sure if it's good, but I think it would be better for the train to stop and not rotate in such a situation, additionaly show the information about waiting for the path in the window and send a message about getting lost.

Another solution could be that the train will enter a non-electrified line, power is reduced to 0KM, stop and then report a power failure problem - the information in the train window will clearly indicate the problem. The disadvantage of this solution may be that the player may not have the money to rebuild and will not be able to move the train (but at the same time it would be a fairly interesting new feature;)

Regarding adding more specific warns, including the reason for getting lost, before someone starts looking for a solution to adding new one, I'd like to point out the problem of complete chaos in the message settings - nothing works properly there. The problem is described here: #9698.

**Comment by LordAro** [comment] 2022-08-29 17:50
Closing as wontfix, though electric lines causing issues is a common problem. There's no good solution really though - I quite like Zorg's suggestion above (can enter, but 0 power), but it would require running the pathfinder multiple times for all lost trains, something that's already quite expensive

**Closed as not planned by LordAro** 2022-08-29 17:50 UTC
