### ISSUE TITLE
[Crash]: Crash after clicking a Local authority action while not having joined any company

### ISSUE THREAD

**Issue by nugel** [OpenTTD/OpenTTD#10562] opened 2023-03-11 11:19 UTC
### Version of OpenTTD

OpenTTD 13.0, Arch Linux

### Steps to reproduce

1. connect to a multiplayer server
2. do not join a company
3. click any town
4. select Local Authority
5. click any greyed out action

### Upload crash files

[crash20230311111107.zip](https://github.com/OpenTTD/OpenTTD/files/10948339/crash20230311111107.zip)

**Comment by glx22** [comment] 2023-03-11 11:36
Duplicate of #10461

**Closed as completed** 2023-03-11 11:36 UTC
