### ISSUE TITLE
[Bug]: station coverage map persistence issue

### ISSUE THREAD

**Issue by mrslate420** [OpenTTD/OpenTTD#13091] opened 2024-11-17 17:36 UTC
### Version of OpenTTD

14.1, Windows 11 24H2

### Expected result

When enabling the Coverage Area view, I would expect it to remain persistent until the station dialog box is closed, or the option is switched off.

### Actual result

When examining the stations coverage map, where its indicating weather or not certain squares are in a catchment area via red/grey highlighting, the coverage is not persistent after setting a new station down and disappears when you hover over another station either accidentally or on purpose.  I am not sure if this behavior is expected or if its indeed a bug, but it either way it would be very nice to be able to keep the coverage map persistent while placing stations. 

### Steps to reproduce

1. Click on a station
2. Click Coverage to enable Coverage View
3. Start placing stations
4. Simply hover your cursor over an existing station
5. Be frustrated that the Coverage Map has now disappeared.
6. Re-click Coverage to enable view and continue.

**Comment by PeterN** [comment] 2024-11-17 17:46
Duplicate of #12654

**Closed as completed** 2024-11-17 18:37 UTC
