### ISSUE TITLE
[Bug]: SH '125' train engine does not have MU flag set

### ISSUE THREAD

**Issue by koroal** [OpenTTD/OpenTTD#10194] opened 2022-11-27 04:24 UTC
### Version of OpenTTD

OpenTTD 12.2 on Gentoo Linux

### Expected result

SH '125' color scheme follows the "DMU" rule.

### Actual result

SH '125' color scheme follows the "Diesel Engine" rule instead.

### Steps to reproduce

1. Open the "Color Scheme" window.
2. On the "train color schemes" tab change the "DMU" value.
3. The colors of ungrouped SH '125' trains in game or in the menus stay the same.
4. On the "train color schemes" tab change the "Diesel Engine" value.
5. The colors of ungrouped SH '125' trains in game and in the menus change.

I have attached a patch file with the line of code that controls this behavior:
[SH_125_patch.txt](https://github.com/OpenTTD/OpenTTD/files/10097508/SH_125_patch.txt)
As far as I can tell, this does not affect anything except the color category of the train engine.

The commit [12b6fe47c7eeb020f983d2dff813fa0b77ea2a25](https://github.com/OpenTTD/OpenTTD/commit/12b6fe47c7eeb020f983d2dff813fa0b77ea2a25) has set this flag for all the default "double headed" train engines which otherwise categorize as "Diesel Engine" or "Electric Engine", except for the SH '125' for some reason. I am not sure if this is intended or not.

**Comment by andythenorth** [comment] 2022-11-27 08:09
This is almost certainly intended.  The SH 125 will usually have passenger coaches added, and if the DMU rule is used, the coaches won't match.

**Comment by 2TallTyler** [comment] 2022-11-27 16:37
Since you have the code to change this already, a better place to discuss this might be a PR that makes said change. 🙂

**Comment by PeterN** [comment] 2022-11-27 16:39
Setting that flag could upset NewGRFs that inadvertently inherit it. Not to mention the real-life argument of "is the Intercity 125 a locomotive or a DEMU?"

**Comment by 2TallTyler** [comment] 2022-11-27 16:44
True, but there are other real-world locomotives which have the MU flag set, including the Turner Turbo (UAC TurboTrain) and the T.I.M. (TGV Sud-Est).

I'm also not convinced of the "We can't fix anything that NewGRFs might inherit, even if it's wrong" argument — see #9832. 😛

**Comment by PeterN** [comment] 2022-11-27 16:48
T.I.M. does not have the MU flag set either? Turner Turbo does though.

![image](https://user-images.githubusercontent.com/639850/204148738-3754af9d-40ec-447b-90eb-4602f6999e33.png)

Is the top SH 125 loco part of a DMU?

**Comment by PeterN** [comment] 2022-11-27 16:50
(And the lack of 8/8 thing is a feature to make sure you place your station closer to the industry, imho)

**Comment by FLHerne** [comment] 2022-11-27 17:24
In real life, the HST (SH 125) and TGV Atlantique (T.I.M.) power cars are self-contained vehicles that can be easily uncoupled from the carriages between and carry no passengers.

HST power cars can be used as ordinary locomotives to haul other stock, for example: https://www.youtube.com/watch?v=lJYbXNy5cWQ or https://youtu.be/WJWkx14MTU8?t=85

(I couldn't find a similar example with TGV power cars and don't know if it's possible to haul other stock, but they can be separated and operated as pairs: https://i0.wp.com/www.pbase.com/andybasford/image/170804125/original.jpg )

The real-life TurboTrain was an articulated set with engines in the end vehicles that also carry passengers. It would be impossible to separate the drive vehicles without lifting equipment, or to operate them without equipment (including wheelsets!) shared with the other carriages.

The question of whether irl HSTs are "DEMUs" or "loco + carriages" has been debated ever since they were introduced 50 years ago, so there's clearly no definitive 'right' answer.

OpenTTD's current behaviour seems consistent with a reasonable definition of "locomotive" vs "MU" (can be easily separated and operated without the intermediate carriages) so this might as well be closed as "works as intended" IMO.

**Comment by 2TallTyler** [comment] 2022-11-27 17:27
Fair enough. Let's call it "works as intended," then.

**Closed as completed by 2TallTyler** 2022-11-27 17:27 UTC
