### ISSUE TITLE
[Bug]: Mouse click panning not working on Wayland

### ISSUE THREAD

**Issue by gimix311** [OpenTTD/OpenTTD#10470] opened 2023-02-12 14:22 UTC
### Version of OpenTTD

13.0

### Expected result

Right click (right click drag) panning should work. Left click panning should work with right click button emulation (ctrl + left click drag).

### Actual result

The pointer stays in the middle as it's supposed to. The map starts to move, but keeps getting pulled back in place, with the net effect of zero movement / panning.

### Steps to reproduce

Using Wayland compositor hyprland on Archlinux.

https://user-images.githubusercontent.com/64981927/218317119-2c8a253b-a2c3-429e-8397-6d6f190bb70b.mp4

**Comment by LordAro** [comment] 2023-02-12 14:27
That video is all white to me, but probably a duplicate of #10140 ?

**Comment by gimix311** [comment] 2023-02-12 14:31
Sorry, I've updated the clip. It was in hevc format.

**Comment by LordAro** [comment] 2023-02-12 14:34
Yeah, definitely looks like #10140 . There's a few workarounds / patches mentioned in the associated #10141 (which for whatever reason seems to have been used as an issue thread...), can you try those and report back?

**Comment by gimix311** [comment] 2023-02-12 14:55
Going by the video posted on that #10140, yes, this looks like the same problem, and possibly linked to sdl with the wayland backend, as mentioned on #10141.

I'm not savvy enough to patch and recompile, but I can confirm that my Archlinux installation is using SDL2 2.26.3. I hadn't noticed the 'Viewport scroll behaviour' option before. For now, I've used 'Move map with RMB/LMB' as a workaround. Would be great if that conditional patch for wayland could be merged.

**Comment by TrueBrain** [comment] 2023-06-03 18:20
As expected, duplicate of #10140. Let's continue there :)

**Closed as not planned by TrueBrain** 2023-06-03 18:20 UTC
Labels: bug, OS: Linux
