### ISSUE TITLE
Game crashes on launch on OS X

### ISSUE THREAD

**Issue by magnus-forsberg** [OpenTTD/OpenTTD#8090] opened 2020-04-18 14:00 UTC
I just downloaded the latest version of the game for OS X and replaced a previous installation from several years back. On launch I get the message "A serious fault condition occured in the game. The game will be shut down." Here's a copy of the crash report:

*** OpenTTD Crash Report ***

Crash at: Sat Apr 18 13:51:36 2020
In game date: 0-01-01 (0)

Crash reason:
 Signal:  Segmentation fault: 11 (11)
 Message: <none>

OpenTTD version:
 Version:    1.10.1 (0)
 NewGRF ver: 1a086d64
 Bits:       64
 Endian:     little
 Dedicated:  no
 Build date: Apr 13 2020 19:14:25

Stacktrace:
 [00] openttd              0x000000010aa0c6a8 (SelectCompanyLiveryWindow::GroupNameSorter(Group const* const&, Group const* const&) + 68168)

Operating system:
 Name:     Mac OS X
 Release:  10.12.6
 Machine:  Intel x86-64h Haswell
 Min Ver:  1090
 Compiler: GCC 4.2.1 "4.2.1 Compatible Apple LLVM 11.0.0 (clang-1100.0.33.17)"

Configuration:
 Blitter:      32bpp-anim
 Graphics set: none (4294967295)
 Language:     /private/var/folders/mw/gw7mjttd2y16qyrkblc3xyvm0000gn/T/AppTranslocation/7875D2A8-1171-4A93-820E-9E905255E708/d/OpenTTD.app/Contents/Resources/lang/swedish.lng
 Music driver: none
 Music set:    none (4294967295)
 Network:      no
 Sound driver: none
 Sound set:    none (4294967295)
 Video driver: cocoa

Fonts:
 Small:  sprite
 Medium: sprite
 Large:  sprite
 Mono:   sprite

AI Configuration (local: 0) (current: 0):

Libraries:
 FreeType:   2.10.1
 LZMA:       5.2.5
 LZO:        2.10
 PNG:        1.6.37
 Zlib:       1.2.8

---- gamelog start ----
---- gamelog end ----

Recent news messages:

*** End of OpenTTD Crash Report ***

**Comment by nielsmh** [comment] 2020-04-18 14:05
Duplicate of #8066

**Closed as completed by nielsmh** 2020-04-18 14:05 UTC
