### ISSUE TITLE
[Crash]: GS - Story GUI

### ISSUE THREAD

**Issue by andythenorth** [OpenTTD/OpenTTD#10385] opened 2023-01-21 22:57 UTC
### Version of OpenTTD

~13, patched client

### Steps to reproduce

Repro isn't reliable.

Add attached GS.

Run game, wait a month for storybook page to be added.

Open story book.  Put game in ffwd.  Click 'nuke' button a lot.

_Might_ be related to the GS removing and re-adding the story page every month.  That exists purely because I wanted to learn how to do it.  Might also be unrelated.

Crash save is attached, but can also start from a fresh game.

I've also seen a segfault from doing the same interactions, but different crash log.

### Upload crash files

[firs-gs.zip](https://github.com/OpenTTD/OpenTTD/files/10473257/firs-gs.zip)
[crash20230121225057.sav.zip](https://github.com/OpenTTD/OpenTTD/files/10473264/crash20230121225057.sav.zip)

**Comment by TrueBrain** [comment] 2024-02-11 19:35
Seems to be a duplicate of #10566. As that ticket has more information, going to close this one up!

**Closed as completed by TrueBrain** 2024-02-11 19:35 UTC
Labels: needs triage
