### ISSUE TITLE
[Crash]: Assertion failed at line 180 of file src\strings_internal.h: n < this->parameters.size()

### ISSUE THREAD

**Issue by ghost** [OpenTTD/OpenTTD#11978] opened 2024-02-04 04:45 UTC
### Version of OpenTTD

openttd-14.0-beta1-windows-win64

### Steps to reproduce

I was just about to test out a new locomotive I was offered a year early than the market.

<img width="907" alt="oops" src="https://github.com/OpenTTD/OpenTTD/assets/573315/4dfc0da8-d619-4501-972c-1c9e7ae082f2">

### Upload crash files

[OpenTTD.zip](https://github.com/OpenTTD/OpenTTD/files/14155531/OpenTTD.zip)

**Comment by TrueBrain** [comment] 2024-02-04 08:49
Thank you for the report! What you didn't know, but this is a duplicate of #11968, fixed with #11973. And we hope to bring this soon to you in a new release!

**Closed as completed by TrueBrain** 2024-02-04 08:49 UTC
