### ISSUE TITLE
[Crash]: 

### ISSUE THREAD

**Issue by wazzan** [OpenTTD/OpenTTD#9960] opened 2022-07-28 13:26 UTC
### Version of OpenTTD

MAC OS X 12.4 (21F79)

### Steps to reproduce

Game crashed upon startup

### Upload crash files

[Archive.zip](https://github.com/OpenTTD/OpenTTD/files/9210054/Archive.zip)

**Comment by glx22** [comment] 2022-07-28 20:17
Likely duplicate of #9956 (same trace)

**Comment by wazzan** [comment] 2022-07-29 09:55
This is fresh start of the game, cannot even get to the menu page or start page.

**Comment by LordAro** [comment] 2022-08-29 17:36
Duplicates #9876

**Closed as not planned by LordAro** 2022-08-29 17:36 UTC
