### ISSUE TITLE
Bug? Train Depots not working as expected

### ISSUE THREAD

**Issue by Brandonlk** [OpenTTD/OpenTTD#7645] opened 2019-07-10 21:08 UTC
## Version of OpenTTD: 1.9.1
two bugs here

1: When i clone a new train (or make a new train) in a depot the stop/start box for that train doesnt appear and i have to click on the train to open the box (and if im using the cloning tool thats a few extra clicks so i dont clone another train)

2: Cant scroll to see rest of train in depot menu, is annoying when shuffling long trains on a small monitor where you cant expand the window too easily

**Comment by Eddi-z** [comment] 2019-07-10 21:25
Can you post a screenshot?

**Comment by Brandonlk** [comment] 2019-07-10 21:30
An edit to the first one, it only doesnt appear when holding control to clone
![image](https://user-images.githubusercontent.com/52762241/61006389-1ec72180-a362-11e9-8cc5-51cd35d54050.png)
And the second one seems to have resolved itself 

![image](https://user-images.githubusercontent.com/52762241/61006466-4b7b3900-a362-11e9-987d-d8473fc594e9.png)
But what did happen was that bar was not there to scroll, so i couldnt see the end of my trains

**Comment by Eddi-z** [comment] 2019-07-10 21:38
As for 1: that there is no separate train window appearing when ctrl+cloning is intentional (there's probably a setting for that). you can start/stop the train from that little icon in front of the train in the depot window directly, so most people don't need the extra train window in this situation.

As for 2: dunno what you were or weren't seeing

**Comment by Brandonlk** [comment] 2019-07-10 22:00
I wasnt seeing the bar at the bottom of the depot menu where you can scroll left and right for long trains.
also, the seperate window when control cloning used to be a thing any idea why they removed it? it was rather helpful

**Comment by Eddi-z** [comment] 2019-07-10 22:15
There's two problems with that:
1) since you can start/stop directly from the depot, the extra window is usually just noise and requires an extra click and some mouse movement to close
2) when you clone lots of vehicles, the screen gets filled up, and it closes the oldest window, which is the depot window you're cloning from, interrupting anything you were doing.

like i said, there is probably a setting if you really want it back, but for most people it's better this way.

**Comment by nielsmh** [comment] 2019-07-11 09:46
The vehicle window showing when Ctrl-cloning from the depot window was removed to be consistent with the Clone button in the vehicle window (which only appears when the vehicle is stopped in depot). The idea is that when you Ctrl-clone you likely do not want to edit anything about the new vehicle, since it has shared orders, while if you make a plain clone with copied orders there is a good chance you want to edit the orders or similar.

**Comment by nielsmh** [comment] 2019-09-01 13:42
Closing this as "by design", and there have been no further comments from the submitter.

**Closed as completed by nielsmh** 2019-09-01 13:42 UTC
