### ISSUE TITLE
time of last update online content

### ISSUE THREAD

**Issue by mauro-miatello** [OpenTTD/OpenTTD#6852] opened 2018-07-15 07:49 UTC
when i try to download a new content, there are so much !
i can could be useful a field "last update" to understand which are updated/maintained

**Comment by planetmaker** [comment] 2018-07-15 10:46
While that might be possible, and I see where the desire comes from - and it might be a good thing to add some age or review / starring system. IMHO it probably is of limited value: just because a NewGRF, AI, script or scenario is old, does not mean that it is bad or unfit to play. And on good NewGRFs the view can also be divided :)

**Comment by TrueBrain** [comment] 2018-07-15 11:47
Last update information is displayed on the website (https://content.openttd.org/); but I think everyone agrees that is far from ideal. As I just wrote in #6853 :

I think everyone agrees the online content service can use some work. What work exactly, widely difference between who you ask. Internally, the online content service is called BaNaNaS, and the current version is roughly 10 years old.

There have been some efforts to completely rewrite the current version with something new, that can support a bit more, and is a bit more user friendly. It also addresses several of the points mentioned by you. If you like to participate in those efforts (either by ideas, by code, by design, ..), best you can do is drop by our IRC (irc.oftc.net, #openttd), or you can checkout out the initial start for this at @frosch123 his repo:

https://github.com/frosch123/bananas2

Any help is welcome! In the meantime I am going to close this ticket, as your point is already addressed in the design document of the above mentioned repository. If you feel it is not, please do contribute in that repository! Thank you! :)

**Closed as completed by TrueBrain** 2018-07-15 11:47 UTC
