### ISSUE TITLE
[Crash]: OpenTTD crashes right after I launch it

### ISSUE THREAD

**Issue by DonaldDuck313** [OpenTTD/OpenTTD#9695] opened 2021-11-14 12:48 UTC
### Version of OpenTTD

12.0, Windows 11

### Steps to reproduce

No idea, I just launched OpenTTD.

### Upload crash files

[crash.zip](https://github.com/OpenTTD/OpenTTD/files/7533719/crash.zip)

**Comment by nielsmh** [comment] 2021-11-14 12:53
There are some bugs fixed in version 12.1, please try upgrading first.

**Comment by LordAro** [comment] 2021-11-14 14:06
Almost certainly duplicate of #9622

**Comment by glx22** [comment] 2021-11-14 15:45
Yup duplicate, I checked the callstack.

**Closed as completed by glx22** 2021-11-14 15:45 UTC
