### ISSUE TITLE
[Bug]: Opening the Operating profit graph window requires selection from list

### ISSUE THREAD

**Issue by LC-Zorg** [OpenTTD/OpenTTD#10266] opened 2022-12-20 20:54 UTC
### Version of OpenTTD

13.0-beta2

### Expected result

As before 13.0-beta2, clicking the graph icon opens the Operating profit graph by default - this is how the other buttons work.

### Actual result

As of 13.0-beta2, opening the Operating profit graph window requires a click and selection from a list.

### Steps to reproduce

1. Compare the behavior between 13.0-beta2 and 12.2 or even 13.0-beta1
2. Pay attention to how the other icons work

**Comment by ldpl** [comment] 2022-12-20 20:56
Duplicate of #10214 so should be fixed already.

**Comment by LordAro** [comment] 2022-12-20 20:57
Duplicate of #10214

**Closed as not planned by LordAro** 2022-12-20 20:57 UTC

**Comment by LC-Zorg** [comment] 2022-12-20 21:03
> Duplicate of https://github.com/OpenTTD/OpenTTD/issues/10214

True, thanks :)
