### ISSUE TITLE
[Bug]: Debug() redirection to TCP does not work when running as dedicated server

### ISSUE THREAD

**Issue by Mixu78** [OpenTTD/OpenTTD#11590] opened 2023-12-15 06:42 UTC
### Version of OpenTTD

13.4, Windows 10

### Expected result

The `-l` option should redirect all log output to the specified ip and port regardless of whether the game is in client or dedicated server mode. Logging should also start much sooner, early logs are never sent to the given ip and port.

### Actual result

The `-l` option only redirects log output to the given ip and port if the game is running as a client. Logging also starts very late, after the main menu has loaded.

### Steps to reproduce

1. Start the game with parameters like `-D -d 9 -l 127.0.0.1`
2. Notice that no connection is made to a listener on the default/specified port

**Comment by rubidium42** [comment] 2024-01-14 20:03
Both issues are caused by essentially the same root cause.

That the logging is starting so late is due to the way the networking code has been written. It is asynchronous, so it does not block on resolving network addresses and trying to connect. However, to prevent threading issues, the result of the asynchronous address resolving is checked from the main loop. This effectively means that the log redirecting is started fairly early, but only after everything is initialised it gets to the main loop and starts processing the resolved network addresses. If it gets multiple addresses, then it will try the first one and after 250 ms try the next and so on. This can take a while.

That is works in client and not in dedicated isn't quite true, because if you join a client quickly enough it might also trigger. The main reason for it not working in the dedicated server is because starting a new network game (as server, or joining as client) stops any asynchronous network things, like resolving the address of the debug-server and connecting to it. In other words, before the address was resolved, the resolving gets killed.
Under normal circumstances the killing of resolving is exactly what it needs to do, except for the debug redirect.

So essentially, when debug redirecting it should not use anything asynchronous but instead just block on everything. That way you get debug redirected from way earlier in the process. The only problem I see is that it means special casing a lot of code. Given it "works" like this for about 15 years, the debug redirecting seems a very unused piece of functionality.

**Closed as completed** 2024-01-14 21:14 UTC
Labels: needs triage
