### ISSUE TITLE
[Bug]: Delivering cargo at shared train stations does not work

### ISSUE THREAD

**Issue by Spounka** [OpenTTD/OpenTTD#12804] opened 2024-06-23 15:33 UTC
### Version of OpenTTD

14.1

### Expected result

When having a station shared between multiple industries that accept the same cargo all industries should receive the cargo 

This has occured mainly since in the FISR NewGRF both Iron Mines and Coal Mines accept engineering supplies
If a station is put between them both and engineering supplies get delivered, usually only the Iron mines get supplied

[openttd-bug.zip](https://github.com/user-attachments/files/15945189/openttd-bug.zip)

### Actual result

Only one industry accepts the cargo, no matter how much cargo gets delivered

### Steps to reproduce

Note: Easier to reproduce with FISR NewGRF, however i have a scenario set-up
1. Build a train line between two industries that accept the same cargo (for example two Factories)
2. Deliver some cargo at the station shared
Only one gets the cargo.

**Comment by krysclarke** [comment] 2024-06-24 00:31
I raised this exact thing back in September 2022, on [tt-forums.net](https://www.tt-forums.net/viewtopic.php?p=1255238#p1255238)
Kamnet responded that this is normal for vanilla OTTD, and provided suggestions on how to resolve it.

**Comment by 2TallTyler** [comment] 2024-06-24 02:24
This is intended behavior: the closest accepting industry tile to the station sign gets all the cargo. See #9536 for more discussion.

That said, I could imagine a setting to change this behavior. The obvious alternative seems to be to split cargo between all accepting industries in the station's catchment area. Feel free to open a PR, if you're interested. 😄

**Comment by 2TallTyler** [comment] 2024-07-29 19:40
Closing this as it is not a bug, but intended behavior.

**Closed as completed by 2TallTyler** 2024-07-29 19:40 UTC
