### ISSUE TITLE
Ship can't decide whether or not it wants to go for maintenance

### ISSUE THREAD

**Issue by DonaldDuck313** [OpenTTD/OpenTTD#8912] opened 2021-03-30 11:00 UTC
## Version of OpenTTD

1.10.0

## Expected result

When a ship wants to go for maintenance, it should go to the nearest depot, and shouldn't suddenly decide while it's heading for the depot that actually it doesn't want to go for maintenance.

## Actual result

If the nearest depot and the ship's destination are in opposite directions, the ship first decides it wants to go to maintenance, so it turns around to head for the nearest depot, which I guess is expected behavior. The problem is that after it has turned around, while it's heading for the depot, it suddenly decides that it doesn't want to go for maintenance, so it turns around again to go to its destination. Then when it's heading for its destination, it changes its mind again and decides that it wants to go for maintenance. So it gets stuck in an infinite loop.

## Steps to reproduce

1. Download and unzip [this saved game](https://github.com/OpenTTD/OpenTTD/files/6228338/Bellwood.Transport.zip).
2. In order to open the game, you will need to install the following NewGRFs:
    - ALe426/506 'TAF' 1.1a
    - Ansaldo/TIBB E652 0.0.1
    - E.44R 'Tartaruga' 1.0
    - B 82500
    - Generic Tram Set v0.4
    - US Town Names v0.31 (20 Apr 2005)
    - FIRS Industry Replacement Set 2.1.5
    - Original vehicles cargo set
    - Snow Line Mod 1.0.2
    
    They can all be installed by going to NewGRF Settings > Check Online Content.
3. Open the saved game.
4. Go to the list of ships and open the information window for Ship 16.
5. Observe what Ship 16 is doing. It's stuck in an infinite loop, and can't decide whether it wants to go for maintenance at Bay Minette Ship Depot or if it wants to go directly to its destination at Norman Center Industrial Park.

I realize that in this specific case I can easily fix the problem by building a new ship depot closer to where Ship 16 is stuck (and that's what I will do in the game), but it would still be nice if you could fix this so that ships don't do that in future versions of OpenTTD.

**Comment by LordAro** [comment] 2021-04-12 12:51
Duplicate of #8022

**Closed as completed by LordAro** 2021-04-12 12:51 UTC
Labels: component: pathfinder, needs triage
