### ISSUE TITLE
[Crash]: On startup within a few seconds

### ISSUE THREAD

**Issue by Linkgold** [OpenTTD/OpenTTD#9671] opened 2021-11-04 17:01 UTC
### Version of OpenTTD

12.0

### Steps to reproduce

1: Open de the game and white a few seconds (15 more or less)

### Upload crash files

*** OpenTTD Crash Report ***

Crash at: 2021-11-04 16:03:11 (UTC)
In game date: 2185-12-02 (40)

Crash reason:
 Exception: C0000005
 Location:  00007FF7D7AB18C7
 Message:   <none>

OpenTTD version:
 Version:    12.0 (0)
 NewGRF ver: 1c086d64
 Bits:       64
 Endian:     little
 Dedicated:  no
 Build date: Oct 17 2021 09:35:11

Registers:
 RAX: 0000000000000000 RBX: 0000016980FDD31C RCX: 0000000000FF605C RDX: 0000000000000000
 RSI: 0000016980919F60 RDI: 00000169E75D0000 RBP: 00000000FFC9E642 RSP: 0000000AB37FEC70
 R8:  00000000000000FF R9:  000000000000001C R10: 000000000000005C R11: 0000000000000060
 R12: 00000169E6849A08 R13: 00007FF7D82E1980 R14: 00000169A36A6000 R15: 0000000000000000
 RIP: 00007FF7D7AB18C7 EFLAGS: 00010216

 Bytes at instruction pointer:
 41 88 06 49 FF C6 8B 03 48 83 C3 04 89 07 48 83 C7 04 83 C5 FF 75 E2 E9

Stack trace:
 00000000 00000000 B37FED88 0000000A 00000002 00000000 B37FEE58 0000000A
 00000002 00000000 E684C008 00000169 A3345002 00000169 80256BAC 00000169
 80256BAC 00000169 00000000 00000000 E8843AC0 00000169 00000000 00000000
 0000003A 00000000 E6844800 00000169 00000000 00000000 00000001 00000000
 B37FED60 0000000A E8A73F10 00000169 00000000 00000000 D7AB08CB 00007FF7
 FF97835B 00000169 B37FED60 0000000A FF000000 00003BE2 FF605C1C 00007FF7
 D9BD2220 00007FF7 D7D13FF4 00007FF7 00000002 00000000 B37FEDA0 0000000A
 80255038 00000169 B37FEDF8 0000000A 80255040 00000169 8000AF19 00000169
 00000000 0000003A 00000080 00000004 00000100 0000007C 00000002 00000000
 E6844800 00000169 00000A00 00000000 A0CF9200 00000169 00000000 00000000
 0000056B 00000000 B37FF130 0000000A 00000FB3 00000000 00003080 00000000
 FFFFAB80 00000000 D7D1159C 00007FF7 00000000 00000000 00000000 00000000
 B99552AE 00009A3D 00000000 0000000A 00000000 00000000 00000FB3 00000000
 00003001 00000000 FFFFAB80 00000000 00000000 00000000 D7D11340 00007FF7
 B37FED80 0000000A B37FEE50 0000000A B37FEDC8 0000000A 00000EC0 00000014
 00000000 00000000 00000FB3 00000420 AAAD69A8 00000169 D7F6017B 00007FF7
 AAAD30D8 00000169 00000000 00000000 00000001 00000000 E85E6610 00000169
 00000000 00000000 D9BD2220 00007FF7 E85E6610 00000169 D7F60F89 00007FF7
 D9BD2220 00007FF7 D9BD2201 00007FF7 E85E6610 00000169 00000000 00000000
 006D0061 00690073 0064002E 006C006C B37FEF50 0000000A D7D047E0 00007FF7
 00003BCB 00000000 00000000 00000000 0000056B 00000000 E85E6610 00000169
 00000000 00000000 D7F6130C 00007FF7 B37FF0D0 0000000A B37FF130 0000000A
 00000000 00000000 000000A4 00000000 00003BCB 00000169 2D6FB86B 00007FFC
 00000009 00000000 E87F13E2 000000F6 E85E6610 00000169 00000000 00000000

Operating system:
 Name:     Windows
 Release:  10.0.19043 ()
 Compiler: MSVC 1929

Configuration:
 Blitter:      40bpp-anim
 Graphics set: OpenGFX (5580)
 Language:     D:\Juegos\OpenTTD\lang\catalan.lng
 Music driver: dmusic
 Music set:    OpenMSX (96)
 Network:      no
 Sound driver: xaudio2
 Sound set:    OpenSFX (87)
 Video driver: win32-opengl

Fonts:
 Small:  sprite
 Medium: sprite
 Large:  sprite
 Mono:   sprite

AI Configuration (local: 0) (current: 0):
  0: Human

Libraries:
 LZMA:       5.2.5
 LZO:        2.10
 PNG:        1.6.37
 Zlib:       1.2.11

Module information:
 D:\Juegos\OpenTTD\openttd.exe handle: 00007FF7D7910000 size: 10626232 crc: EE4A3ABF date: 2021-10-17 09:42:12
 C:\WINDOWS\SYSTEM32\ntdll.dll handle: 00007FFC2D6D0000 size: 2024736 crc: AC0D6C38 date: 2021-10-23 08:11:24
 C:\Program Files\Avast Software\Avast\aswhook.dll handle: 00007FFC0C000000 size: 70224 crc: 5892F636 date: 2021-09-29 15:01:26
 C:\WINDOWS\System32\KERNEL32.DLL handle: 00007FFC2C100000 size: 770144 crc: FA1448A7 date: 2021-09-15 16:48:27
 C:\WINDOWS\System32\KERNELBASE.dll handle: 00007FFC2B450000 size: 2923944 crc: 94A57AAB date: 2021-09-15 16:48:42
 C:\WINDOWS\System32\WS2_32.dll handle: 00007FFC2CC80000 size: 427200 crc: 6E37A637 date: 2021-06-02 18:23:16
 C:\WINDOWS\System32\RPCRT4.dll handle: 00007FFC2CB40000 size: 1215376 crc: E3F196C3 date: 2021-10-23 08:11:25
 C:\WINDOWS\System32\IMM32.dll handle: 00007FFC2B720000 size: 185448 crc: 36F61BF6 date: 2021-06-02 18:23:16
 C:\WINDOWS\System32\USER32.dll handle: 00007FFC2BEC0000 size: 1708056 crc: 5F218ED6 date: 2021-09-15 16:48:33
 C:\WINDOWS\System32\win32u.dll handle: 00007FFC2AE80000 size: 132760 crc: 1E5F4FEA date: 2021-10-23 08:11:17
 C:\WINDOWS\System32\GDI32.dll handle: 00007FFC2C2A0000 size: 166312 crc: 14C3761F date: 2021-09-15 16:48:31
 C:\WINDOWS\SYSTEM32\OPENGL32.dll handle: 00007FFC0A5A0000 size: 1062400 crc: 4851A8A2 date: 2021-07-10 14:32:12
 C:\WINDOWS\System32\gdi32full.dll handle: 00007FFC2B010000 size: 1075864 crc: 76B8C2AF date: 2021-07-20 14:38:43
 C:\WINDOWS\System32\msvcrt.dll handle: 00007FFC2CCF0000 size: 637360 crc: 072737D9 date: 2021-06-02 18:23:15
 C:\WINDOWS\SYSTEM32\WINMM.dll handle: 00007FFC200F0000 size: 147200 crc: 18D40339 date: 2021-06-02 18:22:44
 C:\WINDOWS\System32\msvcp_win.dll handle: 00007FFC2B250000 size: 634760 crc: E6732639 date: 2021-06-02 18:23:14
 C:\WINDOWS\System32\ADVAPI32.dll handle: 00007FFC2D0B0000 size: 689552 crc: 289FF2C9 date: 2021-06-15 15:09:33
 C:\WINDOWS\System32\ucrtbase.dll handle: 00007FFC2B150000 size: 1044888 crc: D3CA62A3 date: 2021-06-02 18:23:14
 C:\WINDOWS\System32\sechost.dll handle: 00007FFC2D570000 size: 625496 crc: E09B47D4 date: 2021-06-02 18:23:16
 C:\WINDOWS\System32\PSAPI.DLL handle: 00007FFC2CD90000 size: 19144 crc: 6E06CEEB date: 2021-06-02 18:23:12
 C:\WINDOWS\System32\combase.dll handle: 00007FFC2D160000 size: 3507520 crc: A3138694 date: 2021-10-23 08:11:23
 C:\WINDOWS\System32\SHELL32.dll handle: 00007FFC2C400000 size: 7632280 crc: 6B4C3839 date: 2021-10-23 08:11:30
 C:\WINDOWS\System32\ole32.dll handle: 00007FFC2CE00000 size: 1214264 crc: D2E575DB date: 2021-09-15 16:48:40
 C:\WINDOWS\SYSTEM32\USP10.dll handle: 00007FFC0E0E0000 size: 79360 crc: 9A7F7CC2 date: 2021-06-02 18:23:17
 C:\WINDOWS\SYSTEM32\GLU32.dll handle: 00007FFC20310000 size: 164352 crc: 753BF23B date: 2021-07-10 14:32:12
 C:\WINDOWS\SYSTEM32\windows.storage.dll handle: 00007FFC28EF0000 size: 7964464 crc: 08C12EBC date: 2021-10-23 08:11:16
 C:\WINDOWS\SYSTEM32\Wldp.dll handle: 00007FFC2A7D0000 size: 173016 crc: C5218D0B date: 2021-06-02 18:23:14
 C:\WINDOWS\System32\SHCORE.dll handle: 00007FFC2D4C0000 size: 702920 crc: F2556683 date: 2021-10-23 08:11:20
 C:\WINDOWS\System32\shlwapi.dll handle: 00007FFC2B900000 size: 342416 crc: 9A2DABFF date: 2021-06-08 16:12:02
 C:\WINDOWS\system32\uxtheme.dll handle: 00007FFC28720000 size: 629248 crc: 00DA3B1B date: 2021-10-23 08:11:29
 C:\WINDOWS\System32\MSCTF.dll handle: 00007FFC2CF90000 size: 1126488 crc: 15BE0388 date: 2021-09-15 16:48:43
 C:\WINDOWS\System32\OLEAUT32.dll handle: 00007FFC2BDF0000 size: 831544 crc: 121679A3 date: 2021-06-02 18:23:14
 C:\WINDOWS\SYSTEM32\kernel.appcore.dll handle: 00007FFC29690000 size: 60464 crc: 7039ACC9 date: 2021-06-02 18:23:03
 C:\WINDOWS\System32\bcryptPrimitives.dll handle: 00007FFC2ADF0000 size: 529968 crc: C2847DA4 date: 2021-09-15 16:48:42
 C:\WINDOWS\System32\clbcatq.dll handle: 00007FFC2C350000 size: 672976 crc: AD4CB4A3 date: 2021-06-02 18:23:12
 C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_1c83a5d7cffd7bff\nvoglv64.dll handle: 00007FFBD0F10000 size: 43326872 crc: 0D29ADFB date: 2020-10-07 12:34:32
 C:\WINDOWS\System32\SETUPAPI.dll handle: 00007FFC2B970000 size: 4687256 crc: B09EE1D3 date: 2021-09-15 16:48:46
 C:\WINDOWS\System32\cfgmgr32.dll handle: 00007FFC2AEB0000 size: 305264 crc: E7B66256 date: 2021-08-16 06:34:09
 C:\WINDOWS\System32\bcrypt.dll handle: 00007FFC2B120000 size: 146248 crc: 1E652D42 date: 2021-06-08 16:11:55
 C:\WINDOWS\SYSTEM32\WTSAPI32.dll handle: 00007FFC26540000 size: 67192 crc: 7604358D date: 2021-06-02 18:22:48
 C:\WINDOWS\SYSTEM32\VERSION.dll handle: 00007FFC24950000 size: 31496 crc: 546E295F date: 2021-06-02 18:23:24
 C:\WINDOWS\SYSTEM32\msasn1.dll handle: 00007FFC2A9D0000 size: 64072 crc: FDFACF86 date: 2021-06-02 18:23:14
 C:\WINDOWS\SYSTEM32\cryptnet.dll handle: 00007FFC24700000 size: 191632 crc: A629A63C date: 2021-06-02 18:23:14
 C:\WINDOWS\System32\CRYPT32.dll handle: 00007FFC2B2F0000 size: 1383144 crc: A1AC66A4 date: 2021-09-15 16:48:41
 C:\WINDOWS\SYSTEM32\cryptbase.dll handle: 00007FFC2A6C0000 size: 34152 crc: CC386121 date: 2021-06-02 18:23:15
 C:\WINDOWS\System32\DEVOBJ.dll handle: 00007FFC2AB90000 size: 202984 crc: 3082EEAC date: 2021-08-16 06:34:09
 C:\WINDOWS\System32\WINTRUST.dll handle: 00007FFC2AFB0000 size: 382712 crc: 10196261 date: 2021-10-23 08:11:16
 C:\WINDOWS\SYSTEM32\ntmarta.dll handle: 00007FFC29AE0000 size: 191656 crc: B2A51DA2 date: 2021-06-02 18:23:14
 C:\WINDOWS\SYSTEM32\dxcore.dll handle: 00007FFC258B0000 size: 219016 crc: 72966353 date: 2021-06-02 18:22:54
 C:\WINDOWS\SYSTEM32\dwmapi.dll handle: 00007FFC28A40000 size: 168408 crc: BE283206 date: 2021-06-02 18:23:12
 C:\WINDOWS\SYSTEM32\powrprof.dll handle: 00007FFC2A980000 size: 295464 crc: 74230007 date: 2021-06-02 18:23:14
 C:\WINDOWS\SYSTEM32\UMPDC.dll handle: 00007FFC2A960000 size: 64552 crc: B19D9CE1 date: 2021-06-02 18:22:44
 C:\WINDOWS\SYSTEM32\WINSTA.dll handle: 00007FFC2A770000 size: 351200 crc: D09048B8 date: 2021-06-02 18:22:48
 C:\WINDOWS\SYSTEM32\textinputframework.dll handle: 00007FFC206E0000 size: 1015952 crc: EC117624 date: 2021-10-23 08:11:16
 C:\WINDOWS\SYSTEM32\CoreMessaging.dll handle: 00007FFC28320000 size: 986464 crc: EDF107E3 date: 2021-06-02 18:23:13
 C:\WINDOWS\SYSTEM32\CoreUIComponents.dll handle: 00007FFC27FC0000 size: 3537520 crc: 78335519 date: 2021-06-02 18:22:59
 C:\WINDOWS\SYSTEM32\wintypes.dll handle: 00007FFC278F0000 size: 1394008 crc: 921239E5 date: 2021-09-15 16:48:40
 C:\WINDOWS\system32\mswsock.dll handle: 00007FFC2A4D0000 size: 418416 crc: 7609CC3B date: 2021-06-02 18:23:14
 C:\WINDOWS\SYSTEM32\xaudio2_8.dll handle: 00000169E2C60000 size: 3584 crc: BC198863 date: 2019-12-07 09:08:07
 C:\WINDOWS\SYSTEM32\xaudio2_9.DLL handle: 00007FFC1C580000 size: 623616 crc: 59BDDEA7 date: 2021-10-23 08:11:04
 C:\WINDOWS\SYSTEM32\MMDevAPI.DLL handle: 00007FFC20A60000 size: 529416 crc: AB26C562 date: 2021-06-08 16:11:40
 C:\WINDOWS\SYSTEM32\AVRT.dll handle: 00007FFC25650000 size: 30480 crc: D6790ED2 date: 2021-06-02 18:22:43
 C:\WINDOWS\SYSTEM32\AUDIOSES.DLL handle: 00007FFC07880000 size: 1566608 crc: 6CEAB80E date: 2021-06-08 16:11:40
 C:\WINDOWS\SYSTEM32\resourcepolicyclient.dll handle: 00007FFC28830000 size: 71784 crc: 38C47F6A date: 2021-06-02 18:22:52
 C:\WINDOWS\System32\dmusic.dll handle: 00007FFC202E0000 size: 136192 crc: BDA2573A date: 2019-12-07 09:09:37
 C:\WINDOWS\SYSTEM32\winmmbase.dll handle: 00007FFC16670000 size: 144592 crc: B331D5DD date: 2019-12-07 09:08:07
 C:\WINDOWS\System32\ksuser.dll handle: 00007FFC202D0000 size: 23264 crc: A73C3DE9 date: 2019-12-07 09:08:07
 C:\WINDOWS\System32\DSOUND.dll handle: 00007FFC07D20000 size: 615424 crc: 1C78A884 date: 2019-12-07 09:08:07
 C:\WINDOWS\System32\MSACM32.dll handle: 00007FFC1D290000 size: 112080 crc: 7C3515A4 date: 2019-12-07 09:08:07
 C:\WINDOWS\SYSTEM32\wdmaud.drv handle: 00007FFC1D020000 size: 259584 crc: DB966BEF date: 2019-12-07 09:08:07
 C:\WINDOWS\SYSTEM32\msacm32.drv handle: 00007FFC1FF60000 size: 30208 crc: 414EBD44 date: 2021-06-02 18:22:43
 C:\WINDOWS\SYSTEM32\midimap.dll handle: 00007FFC1FC60000 size: 26624 crc: C81948B1 date: 2021-06-02 18:22:43
 C:\WINDOWS\System32\dmsynth.dll handle: 00007FFC1D260000 size: 126464 crc: 2A50C1AD date: 2019-12-07 09:09:37
 C:\Windows\System32\Windows.UI.dll handle: 00007FFC1E250000 size: 1317544 crc: C59FEC4F date: 2021-06-02 18:23:08
 C:\Windows\System32\InputHost.dll handle: 00007FFC1D610000 size: 1378064 crc: FEEFA38C date: 2021-06-02 18:23:01
 C:\Windows\System32\WindowManagementAPI.dll handle: 00007FFC24A80000 size: 657464 crc: 832F1552 date: 2021-06-08 16:11:48
 C:\Windows\System32\PROPSYS.dll handle: 00007FFC25A30000 size: 1003048 crc: ACD2EDD8 date: 2021-06-08 16:11:48
 C:\WINDOWS\SYSTEM32\twinapi.appcore.dll handle: 00007FFC24740000 size: 2100112 crc: EC7D9A03 date: 2021-06-02 18:22:53

---- gamelog start ----
Tick 0: new game started
Tick 1280: game loaded
Tick 1280: game loaded
Tick 1280: game loaded
Tick 10478: game loaded
Tick 13584: game loaded
Tick 47111: game loaded
Tick 51965: game loaded
Tick 62555: game loaded
Tick 63600: game loaded
Tick 49396: game loaded
Tick 62604: game loaded
Tick 64272: game loaded
Tick 6006: game loaded
Tick 17767: game loaded
Tick 49394: game loaded
Tick 30847: game loaded
Tick 60372: game loaded
Tick 62318: game loaded
Revision text changed to 12.0, savegame version 299, not modified, _openttd_newgrf_version = 0x1c086d64
New game mode: 0 landscape: 1
---- gamelog end ----

Recent news messages:

*** End of OpenTTD Crash Report ***

Decoded stack trace:
[00] openttd              0x00007FF7D7AB18C7
[01] openttd              0x00007FF7D7AB08CB
[02] openttd              0x00007FF7D7D13FF4
[03] openttd              0x00007FF7D7D1159C
[04] openttd              0x00007FF7D7D11340
[05] openttd              0x00007FF7D7F6017B
[06] openttd              0x00007FF7D7F60F89
[07] openttd              0x00007FF7D7F6130C
[08] openttd              0x00007FF7D7F759C5
[09] openttd              0x00007FF7D7F73B7C
[10] openttd              0x00007FF7D7F72B29
[11] openttd              0x00007FF7D7D7331E
[12] openttd              0x00007FF7D7F79FF4
[13] openttd              0x00007FF7D7F7A0F5
[14] openttd              0x00007FF7D7D12327
[15] openttd              0x00007FF7D7F5DAE2
 <infinite loop>

*** End of additional info ***

**Comment by LordAro** [comment] 2021-11-04 17:04
Likely duplicate of #9622 - try setting zoom_min to 0 or 1 in [gui] section of openttd.cfg

**Comment by Linkgold** [comment] 2021-11-04 19:36
Yes I didn't find that it had already reported, thanks and sorry for the inconvenience.

**Closed as completed** 2021-11-06 13:16 UTC
