### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Infinix1w** [OpenTTD/OpenTTD#9078] opened 2021-04-21 23:47 UTC
## Version of OpenTTD
1.11 no se que chucha
## Expected result
no se
## Actual result
no se
## Steps to reproduce
no se puede
![f63682b2-f2ee-49c2-8c1c-c64baf761539](https://user-images.githubusercontent.com/82983963/115635730-f9ef3480-a2d1-11eb-9d08-cd1763a2766d.jpg)

**Comment by James103** [comment] 2021-04-22 04:13
Do you have the `crash.log`, `crash.png`, and `crash.dmp`? If so, can you please zip the files then attach the zip here? They can usually be found in `%USERPROFILE%/Documents/OpenTTD`.

**Comment by Infinix1w** [comment] 2021-04-22 15:33
I have only crash.log

*** OpenTTD Crash Report ***

Crash at: Wed Apr 21 23:45:53 2021
In game date: 2095-05-19 (20)

Crash reason:
 Exception: C0000005
 Location:  00007FF6E8544CAD
 Message:   <none>

OpenTTD version:
 Version:    1.11.1 (0)
 NewGRF ver: 1b086d64
 Bits:       64
 Endian:     little
 Dedicated:  no
 Build date: Apr 18 2021 21:16:51

Registers:
 RAX: 00000000FF000000 RBX: 00000000000DB288 RCX: 00000000000DB288 RDX: 0000000000000000
 RSI: 00000000000002A6 RDI: 0000000000000000 RBP: 000000000000052C RSP: 000000CB32C2F350
 R8:  0000000000000004 R9:  0000000000000018 R10: 0000000000000004 R11: 0000000000000018
 R12: 00000000000DB288 R13: 000000000000052C R14: 0000000000000020 R15: 000000000036CA20
 RIP: 00007FF6E8544CAD EFLAGS: 00010206

 Bytes at instruction pointer:
 F3 AB B9 EC 88 00 00 48 8B 5C 24 30 48 83 C4 20 5F 48 FF 25 DB 64 E4 01

Stack trace:
 000002A6 00000000 000DB288 00000000 0000052C 00000000 000DB288 00000000
 34888CA0 000000CB E85417FB 00007FF6 370C58D0 000000CB 000002A6 00000000
 370C58D0 000000CB 34888CA0 000000CB 00000000 00000000 00000002 00000000
 00000000 00000000 9505A4B8 00007FFB E893FE50 00007FF6 3483E8B0 000000CB
 E893FE50 00007FF6 3892BFE0 000000CB 000002A6 00000000 00000001 00000000
 0000052C 00000000 E8549F61 00007FF6 34888CA0 000000CB 3483E8B0 000000CB
 E893FE10 00007FF6 FF000000 00007FF6 E8929028 00007FF6 E8548BCD 00007FF6
 FFFFFFFF FFFFFFFF E8928210 00007FF6 34888CA0 000000CB E854B5BD 00007FF6
 00000001 00000000 E8549EA9 00007FF6 34888CD0 000000CB 00000000 00000000
 E893FE10 00007FF6 E8929028 00007FF6 E8929028 00007FF6 E854C0AC 00007FF6
 FFFFFFFF FFFFFFFF 34888CE0 000000CB FFFFFFFF FFFFFFFF E8928210 00007FF6
 00000000 000000CB 70623034 6E612D70 32006D69 000000CB 0000000A 00000000
 0000000F 00000000 BE881B96 00004838 FFFFFFFF FFFFFFFF E893FE10 00007FF6
 00000000 00000000 34888CE0 000000CB 34888CA0 000000CB E854C3BF 00007FF6
 3730A890 000048CA 32C2F670 000000CB 34888D30 000000CB 32C2F670 000000CB
 00000000 00000000 E8548B9F 00007FF6 34888D30 000000CB 34888CE0 000000CB
 34888CA0 000000CB 00000000 00000000 34888000 000000CB E8689CD9 00007FF6
 34888000 000000CB 34888000 000000CB 00000000 00000000 00000000 00000000
 0000000C 00000000 BE881A06 00004838 32C2F520 000000CB 00000000 00000000
 0000000A 00000000 32C2F500 000000CB 00000000 00000001 E74CD000 00007FF6
 00000000 00000000 00000000 00000000 00000000 00007FFB 32C2FA68 000000CB
 E88FF350 00007FF6 00000000 00000000 00000000 00000000 32C2FA60 000000CB
 00000000 00000000 E84B5D74 00007FF6 0000027F 00000000 00000000 00000000
 00000000 00000000 00001FA0 0000FFFF 00000000 00000000 00000000 00000000

Operating system:
 Name:     Windows
 Release:  6.3.9600 ()
 Compiler: MSVC 1928

Configuration:
 Blitter:      40bpp-anim
 Graphics set: OpenGFX (7761)
 Language:     C:\Program Files (x86)\Steam\steamapps\common\OpenTTD\lang\spanish_MX.lng
 Music driver: dmusic
 Music set:    OpenMSX (7761)
 Network:      no
 Sound driver: xaudio2
 Sound set:    OpenSFX (7758)
 Video driver: win32-opengl

Fonts:
 Small:  sprite
 Medium: sprite
 Large:  sprite
 Mono:   sprite

AI Configuration (local: 0) (current: 0):
  0: Human
  1: Human
  2: Human
  3: Human
  4: Human
  5: Human

Libraries:
 LZMA:       5.2.5
 LZO:        2.10
 PNG:        1.6.37
 Zlib:       1.2.11

Module information:
 C:\Program Files (x86)\Steam\steamapps\common\OpenTTD\openttd.exe handle: 00007FF6E82C0000 size: 8553984 crc: 9A796EBF date: 2021-04-21 18:47:06
 C:\WINDOWS\SYSTEM32\ntdll.dll handle: 00007FFB97E30000 size: 1737520 crc: B7C920A5 date: 2021-04-10 11:30:41
 C:\WINDOWS\system32\KERNEL32.DLL handle: 00007FFB977E0000 size: 1311776 crc: 6A8DFB9D date: 2021-04-10 11:31:02
 C:\WINDOWS\system32\KERNELBASE.dll handle: 00007FFB95050000 size: 1135696 crc: 972E51AF date: 2021-04-10 11:30:41
 C:\WINDOWS\SYSTEM32\OPENGL32.dll handle: 00007FFB8D350000 size: 1091584 crc: E10509E5 date: 2014-11-22 01:19:57
 C:\WINDOWS\system32\WS2_32.dll handle: 00007FFB95AE0000 size: 363104 crc: 6C5849EE date: 2021-04-10 12:05:55
 C:\WINDOWS\SYSTEM32\WINMM.dll handle: 00007FFB8AD20000 size: 126056 crc: 7659EB7B date: 2014-11-22 01:19:18
 C:\WINDOWS\system32\IMM32.dll handle: 00007FFB95B40000 size: 210744 crc: 7F26DDC8 date: 2014-11-22 01:19:56
 C:\WINDOWS\system32\USER32.dll handle: 00007FFB95BE0000 size: 1542696 crc: 90DDB08C date: 2021-04-10 11:31:28
 C:\WINDOWS\system32\GDI32.dll handle: 00007FFB97B80000 size: 1378384 crc: 8E293691 date: 2021-04-10 11:31:27
 C:\WINDOWS\system32\SHELL32.dll handle: 00007FFB95DC0000 size: 22382424 crc: 6CBC83AD date: 2021-04-10 11:31:20
 C:\WINDOWS\system32\ole32.dll handle: 00007FFB954B0000 size: 1665104 crc: 7C984C94 date: 2021-04-10 11:31:07
 C:\WINDOWS\system32\ADVAPI32.dll handle: 00007FFB97930000 size: 685440 crc: AF9D203F date: 2021-04-10 11:32:16
 C:\WINDOWS\SYSTEM32\USP10.dll handle: 00007FFB8DAC0000 size: 77312 crc: BCF4262F date: 2014-11-22 01:19:54
 C:\WINDOWS\system32\msvcrt.dll handle: 00007FFB979E0000 size: 687496 crc: AB7BF219 date: 2014-11-22 01:19:03
 C:\WINDOWS\SYSTEM32\GLU32.dll handle: 00007FFB8DA90000 size: 165888 crc: 2A58BB46 date: 2014-11-22 01:19:57
 C:\WINDOWS\SYSTEM32\DDRAW.dll handle: 00007FFB7E3A0000 size: 594944 crc: F38B0F9A date: 2014-11-22 01:19:53
 C:\WINDOWS\system32\NSI.dll handle: 00007FFB97920000 size: 24800 crc: EA0F476C date: 2014-11-22 01:19:02
 C:\WINDOWS\system32\RPCRT4.dll handle: 00007FFB976A0000 size: 1303632 crc: 25986FF8 date: 2021-04-10 11:30:41
 C:\WINDOWS\SYSTEM32\WINMMBASE.dll handle: 00007FFB8ACC0000 size: 161120 crc: 43BDBD7D date: 2014-11-22 01:19:18
 C:\WINDOWS\system32\MSCTF.dll handle: 00007FFB97CD0000 size: 1384648 crc: FDB8CFE6 date: 2021-04-10 11:31:28
 C:\WINDOWS\SYSTEM32\combase.dll handle: 00007FFB97300000 size: 2173392 crc: A8BC61F9 date: 2021-04-10 11:30:41
 C:\WINDOWS\system32\SHLWAPI.dll handle: 00007FFB97B00000 size: 339312 crc: 557A1A0C date: 2014-11-22 01:19:48
 C:\WINDOWS\SYSTEM32\sechost.dll handle: 00007FFB95D60000 size: 357824 crc: 8CDA6A3F date: 2021-04-10 11:30:41
 C:\WINDOWS\SYSTEM32\DCIMAN32.dll handle: 00007FFB93150000 size: 14848 crc: 99021C7D date: 2014-11-22 01:19:56
 C:\WINDOWS\system32\SspiCli.dll handle: 00007FFB95020000 size: 179248 crc: 46C026A4 date: 2021-04-10 11:44:04
 C:\WINDOWS\SYSTEM32\cfgmgr32.dll handle: 00007FFB95220000 size: 315576 crc: C6A55E14 date: 2014-11-22 01:19:03
 C:\WINDOWS\SYSTEM32\DEVOBJ.dll handle: 00007FFB93DA0000 size: 155456 crc: 027D4AD1 date: 2014-11-22 01:19:03
 C:\Program Files (x86)\Steam\gameoverlayrenderer64.dll handle: 00007FFB7CBB0000 size: 1809640 crc: 8A9EFDDF date: 2021-04-12 20:03:30
 C:\WINDOWS\system32\PSAPI.DLL handle: 00007FFB958E0000 size: 17560 crc: 4B24A606 date: 2014-11-22 01:19:24
 C:\WINDOWS\SYSTEM32\SHCORE.dll handle: 00007FFB934F0000 size: 723008 crc: 84D104EB date: 2021-04-10 11:31:20
 C:\WINDOWS\system32\uxtheme.dll handle: 00007FFB93BF0000 size: 1191936 crc: 1F395F77 date: 2021-04-10 11:31:19
 C:\WINDOWS\system32\dwmapi.dll handle: 00007FFB932F0000 size: 125504 crc: F24873F8 date: 2014-11-22 01:19:57
 C:\WINDOWS\SYSTEM32\ig4icd64.dll handle: 00007FFB75FA0000 size: 13037568 crc: 761175AA date: 2015-06-02 02:00:24
 C:\WINDOWS\SYSTEM32\kernel.appcore.dll handle: 00007FFB93BC0000 size: 33064 crc: 46564BB7 date: 2014-11-22 01:19:24
 C:\WINDOWS\SYSTEM32\CRYPTBASE.dll handle: 00007FFB94E20000 size: 31528 crc: 48DECD65 date: 2014-11-22 01:19:03
 C:\WINDOWS\SYSTEM32\bcryptPrimitives.dll handle: 00007FFB94DB0000 size: 397224 crc: 7E397873 date: 2021-04-10 11:30:41
 C:\WINDOWS\SYSTEM32\clbcatq.dll handle: 00007FFB97520000 size: 730824 crc: 0EAA7D4E date: 2014-11-22 01:19:27
 C:\WINDOWS\System32\MMDevApi.dll handle: 00007FFB91E20000 size: 444728 crc: 9D748D54 date: 2014-11-22 01:19:18
 C:\WINDOWS\SYSTEM32\AUDIOSES.DLL handle: 00007FFB861D0000 size: 500464 crc: 3B50CAA9 date: 2021-04-10 11:31:00
 C:\WINDOWS\system32\OLEAUT32.dll handle: 00007FFB95650000 size: 805672 crc: 0A43682A date: 2021-04-10 11:30:43
 C:\WINDOWS\SYSTEM32\powrprof.dll handle: 00007FFB94EF0000 size: 277368 crc: 7D42587C date: 2014-11-22 01:19:03
 C:\WINDOWS\system32\mswsock.dll handle: 00007FFB94790000 size: 339456 crc: EDC7B46F date: 2021-04-10 12:05:55
 C:\WINDOWS\SYSTEM32\xaudio2_8.dll handle: 00007FFB8D920000 size: 293376 crc: D267343F date: 2014-11-22 01:19:18
 C:\WINDOWS\SYSTEM32\AVRT.dll handle: 00007FFB93120000 size: 35664 crc: 93162AF9 date: 2014-11-22 01:19:38
 C:\WINDOWS\System32\dmusic.dll handle: 00007FFB8CCD0000 size: 134144 crc: 028EA41D date: 2014-11-22 01:19:18
 C:\WINDOWS\System32\ksuser.dll handle: 00007FFB904C0000 size: 22208 crc: 52213363 date: 2014-11-22 01:19:19
 C:\WINDOWS\System32\MSACM32.dll handle: 00007FFB8CB90000 size: 106384 crc: CAA1FA35 date: 2014-11-22 01:19:19
 C:\WINDOWS\System32\DSOUND.dll handle: 00007FFB884E0000 size: 620544 crc: 1B751C15 date: 2014-11-22 01:19:19
 C:\WINDOWS\SYSTEM32\wdmaud.drv handle: 00007FFB863A0000 size: 228864 crc: B12B8E56 date: 2014-11-22 01:19:19
 C:\WINDOWS\SYSTEM32\msacm32.drv handle: 00007FFB91160000 size: 26624 crc: DB5F4CD1 date: 2014-11-22 01:19:19
 C:\WINDOWS\SYSTEM32\midimap.dll handle: 00007FFB8D710000 size: 23552 crc: 5011F5F8 date: 2014-11-22 01:19:19
 C:\WINDOWS\System32\dmsynth.dll handle: 00007FFB8C8E0000 size: 118784 crc: 12A34253 date: 2014-11-22 01:19:18

---- gamelog start ----
Tick 0: new game started
Revision text changed to 1.10.3, savegame version 218, not modified, _openttd_newgrf_version = 0x1a086d64
New game mode: 1 landscape: 2
Tick 1280: game loaded
New game mode: 2 landscape: 2
Tick 1280: game loaded
New game mode: 1 landscape: 2
Tick 39224: game loaded
New game mode: 2 landscape: 2
Tick 39224: game loaded
New game mode: 1 landscape: 2
Tick 60493: settings changed
Setting changed: vehicle.never_expire_vehicles : 0 -> 1
Tick 52147: game loaded
New game mode: 2 landscape: 2
Tick 52147: game loaded
New game mode: 1 landscape: 2
Tick 39493: game loaded
New game mode: 2 landscape: 2
Tick 39493: game loaded
New game mode: 1 landscape: 2
Tick 29222: game loaded
New game mode: 2 landscape: 2
Tick 29222: game loaded
New game mode: 1 landscape: 2
Tick 29222: game loaded
Revision text changed to 1.11.1, savegame version 290, not modified, _openttd_newgrf_version = 0x1b086d64
New game mode: 0 landscape: 2
---- gamelog end ----

Recent news messages:

*** End of OpenTTD Crash Report ***

Decoded stack trace:
[00] openttd              0x00007FF6E8544CAD
[01] openttd              0x00007FF6E85417FB
[02] openttd              0x00007FF6E8549F61
[03] openttd              0x00007FF6E8548BCD
[04] openttd              0x00007FF6E8549EA9
[05] openttd              0x00007FF6E854C0AC
[06] openttd              0x00007FF6E854C3BF
[07] openttd              0x00007FF6E8548B9F
[08] openttd              0x00007FF6E8689CD9
[09] openttd              0x00007FF6E84C0CF8
[10] openttd              0x00007FF6E8827E92
[11] KERNEL32             0x00007FFB977E13F2 BaseThreadInitThunk + 34
[12] ntdll                0x00007FFB97E454F4 RtlUserThreadStart + 52

*** End of additional info ***

**Comment by nielsmh** [comment] 2021-04-22 15:35
I see `ig4icd64.dll` in the module list, making it another likely OpenGL-related crash.

The workaround for now is to launch the game with `-v win32` on the commandline options, to force non-accelerated video.

**Comment by Infinix1w** [comment] 2021-04-22 15:39
a bueno

**Comment by LordAro** [comment] 2021-04-22 15:43
Closing as a duplicate of #8969

**Closed as completed by LordAro** 2021-04-22 15:43 UTC
