### ISSUE TITLE
[Bug]: You can load a game script in the intro game.

### ISSUE THREAD

**Issue by James103** [OpenTTD/OpenTTD#9636] opened 2021-10-20 18:17 UTC
### Version of OpenTTD

e68a51e on Windows 10, 64-bit

### Expected result

When saving the intro game, the currently-selected game script for new games is not saved, meaning that loading the intro game does not load the game script.

### Actual result

When saving the intro game, the currently-selected game script and all its parameters is saved into the intro game. Upon loading the newly-created savegame, the game script is loaded.

### Steps to reproduce

1. Add a Game Script inside the AI/Game Script Settings.
2. Save the intro game (`save a`).
3. Load the intro game (`load a`).
4. The Game Script are now active in the intro game.

NOTE: This may apply to AIs as well.

**Comment by LordAro** [comment] 2022-08-29 19:24
This... makes sense? You're saving the currently running game (which just happens to be the intro game) with the currently set settings

Feel free to disagree, but I'm going to close this as "working as intended", if a little weird

**Closed as not planned by LordAro** 2022-08-29 19:24 UTC
