### ISSUE TITLE
[Crash]: It crashes immediately upon launch.

### ISSUE THREAD

**Issue by fhrk-78** [OpenTTD/OpenTTD#12926] opened 2024-09-05 13:55 UTC
### Version of OpenTTD

1.14.1, Windows 11 23H2

### Steps to reproduce

Launch "openttd.exe" (I tried Steam Edition and OpenTTD Homepage Edition)

### Upload crash files

[202409052241.zip](https://github.com/user-attachments/files/16894563/202409052241.zip)
I can't find ".sav" file

**Comment by Squall-Leonhart** [comment] 2024-11-04 13:24
You have a 13600, might be degraded due to the intel bug.

**Comment by glx22** [comment] 2024-11-04 13:50
```
 	[Cadre en ligne] openttd.exe!google_breakpad::ExceptionHandler::WriteMinidump() Ligne 747	C++
 	openttd.exe!google_breakpad::ExceptionHandler::WriteMinidump(const std::wstring & dump_path, bool(*)(const wchar_t *, const wchar_t *, void *, _EXCEPTION_POINTERS *, MDRawAssertionInfo *, bool) callback, void * callback_context, _MINIDUMP_TYPE dump_type) Ligne 773	C++
 	openttd.exe!CrashLogWindows::WriteCrashDump() Ligne 113	C++
 	[Cadre en ligne] openttd.exe!std::_Func_class<bool>::operator()() Ligne 854	C++
 	openttd.exe!CrashLogWindows::TryExecute(std::basic_string_view<char,std::char_traits<char>> section_name, std::function<bool __cdecl(void)> && func) Ligne 124	C++
 	openttd.exe!CrashLog::MakeCrashLog() Ligne 294	C++
 	openttd.exe!ExceptionHandler(_EXCEPTION_POINTERS * ep) Ligne 341	C++
 	[Code externe]	
 	[Cadre en ligne] openttd.exe!std::filesystem::path::{ctor}(const std::string &) Ligne 655	C++
 	openttd.exe!TarScanner::AddFile(const std::string & filename, unsigned __int64 __formal, const std::string & tar_filename) Ligne 534	C++
 	openttd.exe!ScanPath(FileScanner * fs, const char * extension, const char * path, unsigned __int64 basepath_length, bool recursive) Ligne 1189	C++
 	openttd.exe!FileScanner::Scan(const char * extension, Subdirectory sd, bool tars, bool recursive) Ligne 1234	C++
 	openttd.exe!TarScanner::DoScan(Subdirectory sd) Ligne 433	C++
 	openttd.exe!TarScanner::DoScan(TarScanner::Mode mode) Ligne 443	C++
>	openttd.exe!openttd_main(int argc, char * * argv) Ligne 683	C++
 	openttd.exe!WinMain(HINSTANCE__ * __formal, HINSTANCE__ * __formal, char * __formal, int __formal) Ligne 85	C++
 	[Code externe]	
```

Probable duplicate of #12648. Please test a nighly build (available in steam via beta tab in properties).

**Comment by fhrk-78** [comment] 2024-11-05 12:48
Thank you
We were able to play this beta build successfully

**Comment by 2TallTyler** [comment] 2024-11-22 17:13
Thanks for confirming, @fhrk-78. 🙂

**Closed as completed by 2TallTyler** 2024-11-22 17:13 UTC
Labels: needs triage
