### ISSUE TITLE
Feature request: Add automatic demolition of supply chain when an industry is depleted

### ISSUE THREAD

**Issue by quantuumsnot** [OpenTTD/OpenTTD#6944] opened 2018-10-25 15:58 UTC
Sometimes when an industry is depleted (like a forest directly wiped out from the map) we cannot translocate the whole railway-based transport chain to another and the only financially justifiable solution is to demolish the railroad station/rails/depot ... But this is done manually which wastes a lot of time, during the player receives a lot more information like new subsidiary offers.

It will be super good if we have a button which removes that chain - only the chosen parts ...

**Comment by nielsmh** [comment] 2018-10-25 18:08
You mean a kind of follow-the-track self-driving bulldozer?

**Comment by Eddi-z** [comment] 2018-10-25 18:19
i could imagine either that (similar to auto-building signals, it follows the track until there is a junction) or a "selective" bulldozer where you drag over an area and it only removes rail infrastructure (not any trees, houses, roads, etc.)

**Comment by quantuumsnot** [comment] 2018-10-25 18:37
> You mean a kind of follow-the-track self-driving bulldozer?

Yes, playing original TTD since 1996 and this manual demolishing always gave me a seizure

**Comment by andythenorth** [comment] 2018-10-25 18:39
I am curious what the cause for this need is? :)

- if serviced industries are closing, that's a bug (except oil wells in some climates)
- if sawmill runs out of trees, there is the option to plant more 
- if it's newgrf industries, then it's a problem with the newgrf

**Comment by quantuumsnot** [comment] 2018-10-25 18:46
Had an old 1.7.0 version and decided to update it to 1.8.0 but not touching anything in settings, just pressed a default New Scenario and started to play. During gameplay some industries (oil wells, forest and coal mine) wiped from the map. Some from already developed spots, others after a period without usage

**Comment by nielsmh** [comment] 2018-10-25 18:54
Primary industries do close if their production drops too low. That typically only happens if they don't receive frequent service. However Oil Wells on temperate climate maps is special, in that they will always run dry eventually.

**Comment by TrueBrain** [comment] 2018-11-25 11:10
Thank you for your suggestion. We consider part of the rebuilding as part of the game, and as such are not much in favour of this request. Of course, you are always free to make a (code) proposal and make a Pull Request to show us wrong ;)

So I am sorry, but I am going to close this ticket for now. Feel free to drop by our chat channel (IRC, irc.oftc.net, #openttd) to talk more about it :)

**Closed as completed by TrueBrain** 2018-11-25 11:10 UTC
