### ISSUE TITLE
Game crashes on startup

### ISSUE THREAD

**Issue by Elhison** [OpenTTD/OpenTTD#8158] opened 2020-05-18 00:20 UTC
## Version of OpenTTD
1.10.1
## Expected result
Being able to play the game
## Actual result
Crashes immediately when I try to open it.
## Steps to reproduce
Open the game.

I'm on macOS 10.12.6 (Sierra).

[crash.log](https://github.com/OpenTTD/OpenTTD/files/4641399/crash.log)

**Comment by James103** [comment] 2020-05-18 00:27
Known issue in 1.10.0+ with macOS earlier than 10.13 (#8066). Either play 1.9.x or earlier, upgrade macOS to 10.13+, or use a different OS.

**Comment by glx22** [comment] 2020-05-18 00:39
Duplicate of #8066

**Closed as completed by glx22** 2020-05-18 00:39 UTC
