### ISSUE TITLE
[Bug]: Large town doesn't build houses as dense as usual

### ISSUE THREAD

**Issue by DonaldDuck313** [OpenTTD/OpenTTD#11599] opened 2023-12-18 17:05 UTC
### Version of OpenTTD

13.4, Windows 11

### Expected result

Large towns should use all available tiles near their center to build houses, like this:

![image](https://github.com/OpenTTD/OpenTTD/assets/40611243/10e8bbb9-2d97-4f24-8d06-68a8b4070a2b)

### Actual result

One large town has a lot of empty tiles near its center, like this:

![image](https://github.com/OpenTTD/OpenTTD/assets/40611243/fc8c89f1-2ba6-4316-b1de-da7d7a9ea9b6)

I'm not sure why this is happening, this town used to be very dense ([here is a screenshot from the same town 140 years earlier](https://github.com/OpenTTD/OpenTTD/assets/40611243/91502934-4e9b-4db9-8cf3-606080347ebc), from the savegame attached to [this bug report](https://github.com/OpenTTD/OpenTTD/issues/11340)), but when I looked at it today, there were a lot of empty tiles near its center. I've never seen this before. I didn't destroy any houses in that town recently, and I'm the only player, so there is no other play that could have destroyed them either. So it seems like this town has for some reason been destroying its own houses without rebuilding them.

### Steps to reproduce

1. Download and extract [Stora Miggsvall Transport.zip](https://github.com/OpenTTD/OpenTTD/files/13706492/Stora.Miggsvall.Transport.zip) (sorry it's in a ZIP file, but GitHub won't let me attach SAV files).
2. Download the necessary NewGRFs (they're probably not relevant to this bug report, but OpenTTD crashed when I tried to remove them).
3. Look at the town Stora Miggsvall, there are a lot of empty tiles near its center where it should be building houses but doesn't.

**Comment by ldpl** [comment] 2023-12-18 17:20
You've nuked the town center. Roads need to be connected to one of the 13 central tiles for town to grow. Your closest road is one tile too far it looks like.

**Comment by DonaldDuck313** [comment] 2023-12-18 17:29
Which exactly are the 13 central tiles?

**Comment by 2TallTyler** [comment] 2023-12-19 16:29
The town has a central tile that the town label appears above. The tile search checks that tile and some surrounding tiles, described here: https://github.com/OpenTTD/OpenTTD/blob/master/src/town_cmd.cpp#L1762-L1776

One of those tiles needs to be a road in order for the town to grow properly. You'll notice that the town's central tile is always a road, unless you bulldoze it.

This is not a bug, so I am closing the ticket. 😃

**Closed as completed by 2TallTyler** 2023-12-19 16:29 UTC
