### ISSUE TITLE
[Bug]: Max zoom in level setting affects interface size

### ISSUE THREAD

**Issue by ldpl** [OpenTTD/OpenTTD#9985] opened 2022-08-30 07:22 UTC
### Version of OpenTTD

12.2, master(5a0dd7e322eac9228b5be79b6a31898f94736e3b)

### Expected result

Changing "Max zoom in level" setting only limits how far you can zoom in the viewport.

### Actual result

It limits zoom level but also changes the interface size if it's higher than zoom in level. Only affects the actual size, interface size setting stays the same and has to be changed back and forth to update if zoom in level is restorted. 

### Steps to reproduce

1. Set quad interface size.
2. Set max zoom in level to normal.

**Comment by ldpl** [comment] 2022-08-30 07:32
Oh, it's apparently a "feature" as it does grey out higher interface zoom options after it butchers the interface.
Still, I can guess why they're related but I bet any normal player will be very confused.

**Comment by PeterN** [comment] 2022-09-28 07:55
"Maximum zoom in level" is actually there (and the descriptions mentions) to mitigate the additional memory usage caused by using zoomed in sprites. This applies to all sprites, so affects the GUI elements too.

This is somewhat improved in my GUI-scale branch as, although the GUI sprite size will still be limited, the widgets themselves still scale up.

**Comment by 2TallTyler** [comment] 2022-11-14 17:19
@PeterN Is this fixed by your interface scaling branch?

**Comment by PeterN** [comment] 2022-11-14 17:25
I believe so, or at least it is mitigated in a usable way. The interface is still scaled up, but the smaller sprites are centred in their place:

![image](https://user-images.githubusercontent.com/639850/201725658-aed63efb-34ed-49e7-a63e-9fe10662140c.png)

**Comment by 2TallTyler** [comment] 2022-11-14 17:37
In that case I'll mark this as closed by #10114, but if @ldpl disagrees feel free to re-open. 🙂

**Closed as completed by 2TallTyler** 2022-11-14 17:37 UTC
Labels: needs triage
