### ISSUE TITLE
[Crash]: 

### ISSUE THREAD

**Issue by Pinstar1** [OpenTTD/OpenTTD#11056] opened 2023-06-22 01:55 UTC
### Version of OpenTTD

1.13.3

### Steps to reproduce

Not exactly sure what I was doing at the time. 

### Upload crash files

*** OpenTTD Crash Report ***

Crash at: 2023-06-22 01:50:54 (UTC)
In game date: 1962-01-16 (31)

Crash reason:
 Exception: C0000005
 Location:  00007FF6CDA2FAA4
 Message:   <none>

OpenTTD version:
 Version:    13.3 (0)
 NewGRF ver: 1d386d64
 Bits:       64
 Endian:     little
 Dedicated:  no
 Build date: Jun 11 2023 16:45:39

Registers:
 RAX: 000001DDCB5EFC70 RBX: 000001DDCB3E1970 RCX: 0104020300020101 RDX: 0000000000000001
 RSI: 0000000000000000 RDI: 0000000000000000 RBP: 0000000000000000 RSP: 00000096AB6FF868
 R8:  0000000000000000 R9:  0000000000000008 R10: 00007FF6CDDBC9F8 R11: 000000000000006B
 R12: 0000000000000000 R13: 0000000000000000 R14: 0000000000000000 R15: 0000000000000000
 RIP: 00007FF6CDA2FAA4 EFLAGS: 00010246

 Bytes at instruction pointer:
 48 85 91 78 1E 00 00 74 03 B0 01 C3 32 C0 C3 CC CC CC CC CC CC CC CC CC

Stack trace:
 CDA2FB08 00007FF6 00000000 00000000 CDBA6700 00007FF6 00000031 00000000
 A8648480 000001DD 00000000 00000000 CDA3F2B0 00007FF6 00000113 000001DD
 CDB3CC3F 00007FF6 00000000 00000000 A851FDE0 000001DD A87D3340 000001DD
 CDBA60E1 00007FF6 00000015 00000000 CDB3BB0F 00007FF6 CB3E1970 000001DD
 00000000 00000000 00000201 00000000 00000000 00000000 00000015 00000000
 CDB3D1C7 00007FF6 CB3E1970 000001DD 00000000 00000000 00000000 00000000
 0000000E 00000000 0000011D 00000000 CDBAAF69 00007FF6 00000000 00000000
 CDBAC76A 00007FF6 A83CC840 000001DD CDBA6700 00007FF6 00000049 00000000
 A8649030 000001DD A851FDE0 000001DD CD8754E7 00007FF6 A83CC840 000001DD
 00000000 00000000 A8649000 000001DD A87D3060 000001DD A87D3001 000001DD
 CDBA63FC 00007FF6 A851FDE0 000001DD CDBAB386 00007FF6 00000201 00000008
 00000000 00000000 A851FDE0 000001DD 00000000 00000000 A851FDE0 000001DD
 CDBACE70 00007FF6 A87D30B0 000001DD A851FDE0 000001DD 00000000 00000000
 00000000 00000000 0000011D 00007FF6 00000057 000001DD A8649000 000001DD
 CB5EA300 000001DD A8797F60 000001DD CDBAD9A4 00007FF6 A851FDE0 000001DD
 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
 00000000 00000000 CF817EC0 00007FF6 CDA0A3C2 00007FF6 A851FDE0 000001DD
 A851FDE0 000001DD A8797F60 000001DD CDC96FBF 00007FF6 00000000 00000000
 000000D8 00000000 CDF1B860 00007FF6 00989680 00000000 00000000 00000000
 CDA0B0AE 00007FF6 A851FDE0 000001DD 00008679 00000000 A8797F60 000001DD
 00000013 00000000 A8797F60 000001DD CDA0B475 00007FF6 A851FDE0 000001DD
 A2B93F80 000001DD E548FF6A 00006222 48507943 00000019 A2B93F80 000001DD
 CDA1A57D 00007FF6 00000000 00000000 00000000 00000000 00989680 00000000
 00000000 00000000 00000000 00000000 00000000 00000000 0000000C 00000000

Operating system:
 Name:     Windows
 Release:  10.0.19045 ()
 Compiler: MSVC 1935

Configuration:
 Blitter:      40bpp-anim
 Graphics set: OpenGFX (7938)
 Language:     C:\Program Files\OpenTTD\lang\english_US.lng
 Music driver: dmusic
 Music set:    Modern Motion (1)
 Network:      no
 Sound driver: xaudio2
 Sound set:    OpenSFX (7974)
 Video driver: win32-opengl (NVIDIA GeForce GTX 1080/PCIe/SSE2, 4.5.0 NVIDIA 516.94)

Fonts:
 Small:  sprite
 Medium: sprite
 Large:  sprite
 Mono:   sprite

AI Configuration (local: 0) (current: 16):
  0: Human

Libraries:
 LZMA:       5.4.1
 LZO:        2.10
 PNG:        1.6.39
 Zlib:       1.2.13

Module information:
 C:\Program Files\OpenTTD\openttd.exe handle: 00007FF6CD3E0000 size: 12496336 crc: 4D5CD869 date: 2023-06-11 16:58:38
 C:\WINDOWS\SYSTEM32\ntdll.dll handle: 00007FFBE8F70000 size: 2029448 crc: CCCCAC5A date: 2023-06-16 05:33:59
 C:\WINDOWS\System32\KERNEL32.DLL handle: 00007FFBE8760000 size: 773808 crc: 3970C075 date: 2023-06-16 05:34:42
 C:\WINDOWS\System32\KERNELBASE.dll handle: 00007FFBE6910000 size: 3113968 crc: E04BDEA8 date: 2023-06-16 05:34:10
 C:\WINDOWS\System32\WS2_32.dll handle: 00007FFBE86C0000 size: 427200 crc: 6E37A637 date: 2021-02-27 09:01:21
 C:\WINDOWS\System32\RPCRT4.dll handle: 00007FFBE6FD0000 size: 1200384 crc: E7389FFB date: 2023-05-12 07:41:25
 C:\WINDOWS\System32\IMM32.dll handle: 00007FFBE8730000 size: 189264 crc: A386F1AB date: 2023-03-17 08:50:11
 C:\WINDOWS\System32\USER32.dll handle: 00007FFBE7D30000 size: 1694632 crc: D944768E date: 2023-04-13 21:03:46
 C:\WINDOWS\SYSTEM32\OPENGL32.dll handle: 00007FFBB8870000 size: 1061888 crc: 5A0D4564 date: 2022-11-09 01:08:48
 C:\WINDOWS\System32\msvcrt.dll handle: 00007FFBE7C90000 size: 637360 crc: 072737D9 date: 2021-02-27 09:01:20
 C:\WINDOWS\System32\win32u.dll handle: 00007FFBE6DB0000 size: 133784 crc: BCA0403B date: 2023-06-16 05:33:38
 C:\WINDOWS\SYSTEM32\WINMM.dll handle: 00007FFBD91C0000 size: 147200 crc: 18D40339 date: 2021-02-27 09:00:17
 C:\WINDOWS\System32\GDI32.dll handle: 00007FFBE7AB0000 size: 167896 crc: 198E4CFB date: 2023-05-12 07:41:03
 C:\WINDOWS\System32\ADVAPI32.dll handle: 00007FFBE8610000 size: 704552 crc: 3031F8E7 date: 2023-05-12 07:40:45
 C:\WINDOWS\System32\gdi32full.dll handle: 00007FFBE66F0000 size: 1118776 crc: 20EF85EE date: 2023-05-12 07:41:30
 C:\WINDOWS\System32\sechost.dll handle: 00007FFBE72C0000 size: 631240 crc: 37BF5D44 date: 2023-05-12 07:41:25
 C:\WINDOWS\System32\msvcp_win.dll handle: 00007FFBE6C10000 size: 634760 crc: E6732639 date: 2021-02-27 09:01:17
 C:\WINDOWS\System32\ucrtbase.dll handle: 00007FFBE6CB0000 size: 1044888 crc: D3CA62A3 date: 2021-02-27 09:01:17
 C:\WINDOWS\System32\combase.dll handle: 00007FFBE8A90000 size: 3502920 crc: B8DFE769 date: 2023-04-13 21:03:59
 C:\WINDOWS\System32\PSAPI.DLL handle: 00007FFBE7ED0000 size: 19144 crc: 6E06CEEB date: 2021-02-27 09:01:11
 C:\WINDOWS\System32\SHELL32.dll handle: 00007FFBE7360000 size: 7650440 crc: 2C0B78F4 date: 2023-06-16 05:34:12
 C:\WINDOWS\System32\ole32.dll handle: 00007FFBE7F00000 size: 1214808 crc: 422ED188 date: 2023-05-12 07:41:21
 C:\WINDOWS\SYSTEM32\GLU32.dll handle: 00007FFBDEB90000 size: 164352 crc: CB5B87FE date: 2022-11-09 01:08:48
 C:\WINDOWS\SYSTEM32\USP10.dll handle: 00007FFBC8990000 size: 79360 crc: 9A7F7CC2 date: 2021-02-27 09:01:25
 E:\Program Files (x86)\Steam\gameoverlayrenderer64.dll handle: 00007FFBB86E0000 size: 1416040 crc: 56B40268 date: 2023-06-16 02:47:44
 C:\WINDOWS\System32\OLEAUT32.dll handle: 00007FFBE8960000 size: 831544 crc: 121679A3 date: 2021-05-12 13:52:49
 C:\WINDOWS\SYSTEM32\windows.storage.dll handle: 00007FFBE44F0000 size: 7981984 crc: F5AF7C81 date: 2023-04-13 21:03:44
 C:\WINDOWS\SYSTEM32\Wldp.dll handle: 00007FFBE60A0000 size: 179248 crc: 91770800 date: 2023-04-13 21:03:59
 C:\WINDOWS\System32\SHCORE.dll handle: 00007FFBE7210000 size: 700896 crc: 9800D9CA date: 2022-08-10 21:14:41
 C:\WINDOWS\System32\shlwapi.dll handle: 00007FFBE71B0000 size: 343480 crc: 13DB2CD7 date: 2022-10-11 20:59:55
 C:\WINDOWS\system32\uxtheme.dll handle: 00007FFBE3D80000 size: 627200 crc: 9D2579C7 date: 2022-11-09 01:08:09
 C:\WINDOWS\System32\MSCTF.dll handle: 00007FFBE8840000 size: 1126504 crc: 33A08FCC date: 2023-03-17 08:50:11
 C:\WINDOWS\SYSTEM32\kernel.appcore.dll handle: 00007FFBE4EE0000 size: 60464 crc: 7039ACC9 date: 2021-02-27 09:00:57
 C:\WINDOWS\System32\bcryptPrimitives.dll handle: 00007FFBE6DE0000 size: 527904 crc: 2F728DEC date: 2023-01-15 06:05:11
 C:\WINDOWS\System32\clbcatq.dll handle: 00007FFBE7100000 size: 674024 crc: D2596FD8 date: 2023-02-15 23:41:35
 C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispig.inf_amd64_ee20464bb4ac57f4\nvoglv64.dll handle: 00007FFB6D8C0000 size: 51423232 crc: B8B5ED5A date: 2022-08-24 04:23:02
 C:\WINDOWS\System32\SETUPAPI.dll handle: 00007FFBE81A0000 size: 4647472 crc: A9ADBABC date: 2022-11-09 01:08:09
 C:\WINDOWS\System32\bcrypt.dll handle: 00007FFBE66C0000 size: 147800 crc: 0A12FB58 date: 2023-01-15 06:05:08
 C:\WINDOWS\SYSTEM32\VERSION.dll handle: 00007FFBE0510000 size: 31496 crc: 546E295F date: 2021-02-27 09:01:43
 C:\WINDOWS\SYSTEM32\WTSAPI32.dll handle: 00007FFBE2E00000 size: 67192 crc: 7604358D date: 2021-02-27 09:00:28
 C:\WINDOWS\SYSTEM32\CRYPTBASE.DLL handle: 00007FFBE5FF0000 size: 34152 crc: CC386121 date: 2021-02-27 09:01:21
 C:\WINDOWS\System32\cfgmgr32.dll handle: 000001DDA3160000 size: 306312 crc: 2E7EFA92 date: 2022-04-13 04:49:04
 C:\WINDOWS\SYSTEM32\msasn1.dll handle: 00007FFBE6230000 size: 65152 crc: 0015F0DF date: 2022-11-09 01:07:57
 C:\WINDOWS\SYSTEM32\cryptnet.dll handle: 00007FFBE0100000 size: 191632 crc: A629A63C date: 2021-04-14 05:01:25
 C:\WINDOWS\System32\CRYPT32.dll handle: 00007FFBE6E70000 size: 1419312 crc: 47D91932 date: 2023-06-16 05:33:55
 C:\WINDOWS\SYSTEM32\drvstore.dll handle: 00007FFBDFFB0000 size: 1327472 crc: 9F0C5683 date: 2023-02-15 23:42:07
 C:\WINDOWS\SYSTEM32\devobj.dll handle: 00007FFBE6400000 size: 166888 crc: 2B5F92C4 date: 2022-04-13 04:49:04
 C:\WINDOWS\System32\WINTRUST.dll handle: 00007FFBE6650000 size: 414760 crc: 9F0B2D8A date: 2023-05-12 07:41:06
 C:\WINDOWS\SYSTEM32\ntmarta.dll handle: 00007FFBE5740000 size: 191656 crc: B2A51DA2 date: 2021-02-27 09:01:19
 C:\WINDOWS\SYSTEM32\dxcore.dll handle: 00007FFBDECA0000 size: 219016 crc: 72966353 date: 2021-02-27 09:00:39
 C:\WINDOWS\system32\nvspcap64.dll handle: 00007FFB919E0000 size: 2838384 crc: 7D7E49DE date: 2021-06-09 14:17:09
 C:\WINDOWS\SYSTEM32\profapi.dll handle: 00007FFBE6590000 size: 115728 crc: 89AB86D7 date: 2021-03-10 07:22:16
 C:\WINDOWS\SYSTEM32\dwmapi.dll handle: 00007FFBE3F60000 size: 168408 crc: BE283206 date: 2021-02-27 09:01:12
 C:\WINDOWS\SYSTEM32\powrprof.dll handle: 00007FFBE5C10000 size: 295464 crc: 74230007 date: 2021-02-27 09:01:19
 C:\WINDOWS\SYSTEM32\UMPDC.dll handle: 00007FFBE5A80000 size: 64552 crc: B19D9CE1 date: 2021-02-27 09:00:18
 C:\WINDOWS\SYSTEM32\WINSTA.dll handle: 00007FFBE5600000 size: 388464 crc: 3586480B date: 2022-10-11 21:00:05
 C:\WINDOWS\SYSTEM32\textinputframework.dll handle: 00007FFBD8F80000 size: 1017528 crc: D87ED252 date: 2023-06-16 05:33:31
 C:\WINDOWS\SYSTEM32\CoreUIComponents.dll handle: 00007FFBE3550000 size: 3537520 crc: 78335519 date: 2021-02-27 09:00:46
 C:\WINDOWS\SYSTEM32\CoreMessaging.dll handle: 00007FFBE38B0000 size: 984952 crc: 8AFC31A6 date: 2022-11-09 01:07:55
 C:\WINDOWS\SYSTEM32\wintypes.dll handle: 00007FFBE2500000 size: 1398160 crc: 34C3F983 date: 2023-04-13 21:04:00
 C:\WINDOWS\System32\MMDevApi.dll handle: 00007FFBE0D80000 size: 529416 crc: 2326B336 date: 2022-02-09 14:04:02
 C:\WINDOWS\SYSTEM32\AUDIOSES.DLL handle: 00007FFBE0E10000 size: 1568176 crc: 707BB7BD date: 2022-12-22 22:26:09
 C:\Windows\System32\PROPSYS.dll handle: 00007FFBE14E0000 size: 1004104 crc: B38922A6 date: 2022-06-17 12:31:14
 C:\WINDOWS\system32\mswsock.dll handle: 00007FFBE5E00000 size: 418416 crc: 7609CC3B date: 2021-02-27 09:01:17
 C:\WINDOWS\SYSTEM32\xaudio2_8.dll handle: 000001DDA6020000 size: 3584 crc: BC198863 date: 2019-12-07 09:08:07
 C:\WINDOWS\SYSTEM32\xaudio2_9.DLL handle: 00007FFBC1C30000 size: 638464 crc: 89BD4C30 date: 2023-05-12 07:40:43
 C:\WINDOWS\SYSTEM32\AVRT.dll handle: 00007FFBE0A30000 size: 30480 crc: D6790ED2 date: 2021-02-27 09:00:16
 C:\WINDOWS\SYSTEM32\resourcepolicyclient.dll handle: 00007FFBE3E60000 size: 71784 crc: 38C47F6A date: 2021-02-27 09:00:37
 C:\WINDOWS\System32\dmusic.dll handle: 00007FFBD5BA0000 size: 137216 crc: C0DB649B date: 2023-06-16 05:35:28
 C:\WINDOWS\SYSTEM32\winmmbase.dll handle: 00007FFBBD490000 size: 144592 crc: B331D5DD date: 2019-12-07 09:08:07
 C:\WINDOWS\System32\ksuser.dll handle: 00007FFBA82F0000 size: 23264 crc: A73C3DE9 date: 2019-12-07 09:08:07
 C:\WINDOWS\System32\DSOUND.dll handle: 00007FFBBCEE0000 size: 615424 crc: 03EE2A8B date: 2023-03-17 08:49:22
 C:\WINDOWS\System32\MSACM32.dll handle: 00007FFBB7220000 size: 112080 crc: 7C3515A4 date: 2019-12-07 09:08:07
 C:\WINDOWS\SYSTEM32\wdmaud.drv handle: 00007FFBA8300000 size: 259584 crc: DB966BEF date: 2019-12-07 09:08:07
 C:\WINDOWS\SYSTEM32\msacm32.drv handle: 00007FFBB7240000 size: 30208 crc: 414EBD44 date: 2021-02-27 09:00:16
 C:\WINDOWS\SYSTEM32\midimap.dll handle: 00007FFBB7210000 size: 26624 crc: C81948B1 date: 2021-02-27 09:00:16
 C:\WINDOWS\System32\dmsynth.dll handle: 00007FFBD5990000 size: 126464 crc: B838E118 date: 2023-06-16 05:35:27
 C:\Windows\System32\Windows.UI.dll handle: 00007FFBDC710000 size: 1317544 crc: C59FEC4F date: 2021-02-27 09:01:06
 C:\Windows\System32\WindowManagementAPI.dll handle: 00007FFBE0140000 size: 657464 crc: 832F1552 date: 2021-06-09 14:44:12
 C:\Windows\System32\InputHost.dll handle: 00007FFBDC5B0000 size: 1379112 crc: 865C4B22 date: 2022-06-17 12:31:06
 C:\WINDOWS\SYSTEM32\twinapi.appcore.dll handle: 00007FFBE2070000 size: 2129496 crc: 19E43178 date: 2023-06-16 05:33:09

---- gamelog start ----
Tick 0: new game started
Revision text changed to 13.3, savegame version 302, not modified, _openttd_newgrf_version = 0x1d386d64
New game mode: 1 landscape: 0
---- gamelog end ----

Recent news messages:
(1962-01-01) StringID: 713, Type: 11, Ref1: 2, 548, Ref2: 0, 4294967295
(1962-01-01) StringID: 713, Type: 11, Ref1: 2, 547, Ref2: 0, 4294967295
(1962-01-01) StringID: 713, Type: 11, Ref1: 2, 546, Ref2: 0, 4294967295
(1962-01-01) StringID: 713, Type: 11, Ref1: 2, 538, Ref2: 0, 4294967295
(1962-01-01) StringID: 713, Type: 11, Ref1: 2, 532, Ref2: 0, 4294967295
(1962-01-01) StringID: 713, Type: 11, Ref1: 2, 530, Ref2: 0, 4294967295
(1962-01-01) StringID: 713, Type: 11, Ref1: 2, 475, Ref2: 0, 4294967295
(1962-01-01) StringID: 713, Type: 11, Ref1: 2, 472, Ref2: 0, 4294967295
(1962-01-01) StringID: 713, Type: 11, Ref1: 2, 471, Ref2: 0, 4294967295
(1962-01-01) StringID: 713, Type: 11, Ref1: 2, 461, Ref2: 0, 4294967295
(1962-01-01) StringID: 713, Type: 11, Ref1: 2, 422, Ref2: 0, 4294967295
(1962-01-01) StringID: 713, Type: 11, Ref1: 2, 421, Ref2: 0, 4294967295
(1962-01-01) StringID: 713, Type: 11, Ref1: 2, 420, Ref2: 0, 4294967295
(1962-01-01) StringID: 713, Type: 11, Ref1: 2, 353, Ref2: 0, 4294967295
(1962-01-01) StringID: 713, Type: 11, Ref1: 2, 251, Ref2: 0, 4294967295
(1962-01-01) StringID: 713, Type: 11, Ref1: 2, 250, Ref2: 0, 4294967295
(1962-01-01) StringID: 713, Type: 11, Ref1: 2, 249, Ref2: 0, 4294967295
(1962-01-01) StringID: 713, Type: 11, Ref1: 2, 236, Ref2: 0, 4294967295
(1962-01-01) StringID: 713, Type: 11, Ref1: 2, 226, Ref2: 0, 4294967295
(1962-01-01) StringID: 713, Type: 11, Ref1: 2, 225, Ref2: 0, 4294967295
(1962-01-01) StringID: 713, Type: 11, Ref1: 2, 224, Ref2: 0, 4294967295
(1962-01-01) StringID: 713, Type: 11, Ref1: 2, 181, Ref2: 0, 4294967295
(1962-01-01) StringID: 713, Type: 11, Ref1: 2, 141, Ref2: 0, 4294967295
(1962-01-01) StringID: 713, Type: 11, Ref1: 2, 123, Ref2: 0, 4294967295
(1962-01-01) StringID: 713, Type: 11, Ref1: 2, 106, Ref2: 0, 4294967295
(1962-01-01) StringID: 713, Type: 11, Ref1: 2, 70, Ref2: 0, 4294967295
(1962-01-01) StringID: 713, Type: 11, Ref1: 2, 26, Ref2: 0, 4294967295
(1962-01-01) StringID: 727, Type: 14, Ref1: 4, 18, Ref2: 4, 39
(1962-01-01) StringID: 725, Type: 14, Ref1: 5, 21, Ref2: 5, 7
(1962-01-01) StringID: 698, Type: 10, Ref1: 4, 3, Ref2: 0, 4294967295
(1961-11-02) StringID: 723, Type: 13, Ref1: 3, 5, Ref2: 0, 4294967295
(1961-11-01) StringID: 725, Type: 14, Ref1: 5, 7, Ref2: 5, 4

*** End of OpenTTD Crash Report ***

Decoded stack trace:
[00] openttd              0x00007FF6CDA2FAA4
[01] openttd              0x00007FF6CDA2FB08
[02] openttd              0x00007FF6CDA3F2B0
[03] openttd              0x00007FF6CDB3BB0F
[04] openttd              0x00007FF6CDB3D1C7
[05] openttd              0x00007FF6CDBAAF69
[06] openttd              0x00007FF6CD8754E7
[07] openttd              0x00007FF6CDBAB386
[08] openttd              0x00007FF6CDBACE70
[09] openttd              0x00007FF6CDBAD9A4
[10] openttd              0x00007FF6CDA0A3C2
[11] openttd              0x00007FF6CDA0B0AE
[12] openttd              0x00007FF6CDA0B475
[13] openttd              0x00007FF6CDA1A57D
[14] openttd              0x00007FF6CDA1A90B
[15] openttd              0x00007FF6CD873A53
[16] openttd              0x00007FF6CD873AB8
[17] openttd              0x00007FF6CD87439A
[18] openttd              0x00007FF6CD874859
[19] openttd              0x00007FF6CDC70E76
[20] KERNEL32             0x00007FFBE8777614 BaseThreadInitThunk + 20
[21] ntdll                0x00007FFBE8FC26F1 RtlUserThreadStart + 33

*** End of additional info ***

**Comment by James103** [comment] 2023-06-22 01:56
Do you have the crash dump and screenshot? If so, can you please zip them first and post the resulting zip here?

**Comment by Pinstar1** [comment] 2023-06-22 02:05
[OpenTTDCrashZip.zip](https://github.com/OpenTTD/OpenTTD/files/11827968/OpenTTDCrashZip.zip)

**Comment by PeterN** [comment] 2023-06-22 05:21
Thank you for the report. This is a duplicate of #11044

**Closed as completed by PeterN** 2023-06-22 05:21 UTC
