### ISSUE TITLE
[Bug]: incorrect resolution set with multiple monitors

### ISSUE THREAD

**Issue by Lamrr** [OpenTTD/OpenTTD#11353] opened 2023-10-06 00:18 UTC
### Version of OpenTTD

13.4, nightly 20231004; Fedora 38; NVIDIA propriety drivers

### Expected result

I have a multi-monitor setup with two displays, one with a resolution of 1920 x 1080 and another with a resolution of 1680 x 1050.

When configuring OpenTTD I expect to be able to run the game full-screen in the 1080p monitor at its native resolution.

### Actual result

Resolution is consistently limited to the resolution of the other monitor (i.e. 1680 x 1050) when using wayland. Under X11, the resolution is forced to the combined size (i.e. 3600 x 1080) of the monitors. If the resolution is manually set to 1920 x 1080 using openttd.cfg it gets overridden when the game launches.

Using 13.4 build distributed by Fedora;
`openttd -ddriver2`

```
dbg: [driver] Successfully loaded blitter '32bpp-anim'
dbg: [driver] Resolution for display: 1920x1080 [1]
dbg: [driver] SDL2: Mouse is at (0, 0), use display 1 (0, 0, 1920, 1080) [2]
dbg: [driver] SDL2: using mode 1680x1050 [3]
dbg: [driver] SDL2: using driver 'wayland'
dbg: [driver] OpenGL driver: NVIDIA Corporation - NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2 (4.6.0 NVIDIA 535.113.01)
dbg: [driver] OpenGL shading language version: 4.60 NVIDIA, texture units = 192
dbg: [driver] Successfully probed video driver 'sdl-opengl'
dbg: [driver] Successfully probed sound driver 'sdl'
dbg: [driver] Fluidsynth: sf (null)
dbg: [driver] Fluidsynth: samplerate 44100
dbg: [driver] Successfully probed music driver 'fluidsynth'
dbg: [driver] using thread for game-loop
dbg: [driver] Switching blitter from '32bpp-anim' to '40bpp-anim'...
dbg: [driver] Successfully loaded blitter '40bpp-anim'
dbg: [driver] Successfully switched to 40bpp-anim.
dbg: [driver] SDL2: using mode 1680x1050
dbg: [driver] SDL2: using mode 1680x1050
```
Resolution is initially set to 1920x1080 at [1], the right display is grabbed at [2] but the mode used is the maximum resolution of the other display [3].

Using nightly 20231004 precompiled generic linux binaries (seemingly compiled without wayland support, thus running on x11);
`./openttd -ddriver2`

```
dbg: [driver] Successfully loaded blitter '32bpp-anim'
dbg: [driver] Resolution for display: 1920x1080 [1]
dbg: [driver] SDL2: Mouse is at (900, 620), use display 0 (0, 0, 3600, 1080) [2]
dbg: [driver] SDL2: using mode 3600x1080
dbg: [driver] SDL2: using driver 'x11'
dbg: [driver] OpenGL driver: NVIDIA Corporation - NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2 (4.6.0 NVIDIA 535.113.01)
dbg: [driver] OpenGL shading language version: 4.60 NVIDIA, texture units = 192
dbg: [driver] Successfully probed video driver 'sdl-opengl'
dbg: [driver] Successfully probed sound driver 'sdl'
dbg: [driver] Fluidsynth: sf (null)
dbg: [driver] Fluidsynth: samplerate 44100
dbg: [driver] Successfully probed music driver 'fluidsynth'
dbg: [driver] using thread for game-loop
dbg: [driver] Switching blitter from '32bpp-anim' to '40bpp-anim'...
dbg: [driver] Successfully loaded blitter '40bpp-anim'
dbg: [driver] Successfully switched to 40bpp-anim.
dbg: [driver] SDL2: using mode 3600x1080
dbg: [driver] SDL2: using mode 3600x1080
```
Again, resolution is initially set to 1920x1080 at [1], however the display grabbed at [2] is the combined resolution of both displays.

And finally, using 13.4 generix linux binaries with the same result as above;
`./openttd -ddriver2`

```
dbg: [driver] Successfully loaded blitter '32bpp-anim'
dbg: [driver] Resolution for display: 1920x1080
dbg: [driver] SDL2: Mouse is at (1089, 519), use display 0 (0, 0, 3600, 1080)
dbg: [driver] SDL2: using mode 3600x1080
dbg: [driver] SDL2: using driver 'x11'
dbg: [driver] OpenGL driver: NVIDIA Corporation - NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2 (4.6.0 NVIDIA 535.113.01)
dbg: [driver] OpenGL shading language version: 4.60 NVIDIA, texture units = 192
dbg: [driver] Successfully probed video driver 'sdl-opengl'
dbg: [driver] Successfully probed sound driver 'sdl'
dbg: [driver] Fluidsynth: sf (null)
dbg: [driver] Fluidsynth: samplerate 44100
dbg: [driver] Successfully probed music driver 'fluidsynth'
dbg: [driver] using thread for game-loop
dbg: [driver] Switching blitter from '32bpp-anim' to '40bpp-anim'...
dbg: [driver] Successfully loaded blitter '40bpp-anim'
dbg: [driver] Successfully switched to 40bpp-anim.
dbg: [driver] SDL2: using mode 3600x1080
dbg: [driver] SDL2: using mode 3600x1080
```

Screenshots for further reference;
under x11
![Screenshot from 2023-10-06 11-05-56](https://github.com/OpenTTD/OpenTTD/assets/96937466/09584078-84ed-4d2d-b889-d1fa5d1a2bac)

under wayland
![Screenshot from 2023-10-06 11-05-21](https://github.com/OpenTTD/OpenTTD/assets/96937466/bf8c4441-9ba4-4984-8e67-b63993e2f065)

Some research notes;

- From my novice reading of the code, it seems like resolution is handled in [sdl2_v.cpp](https://github.com/OpenTTD/OpenTTD/blob/89acfc7ff9994cb1f1124dcebd02750f2474da70/src/video/sdl2_v.cpp).
- The gathering of valid display modes seems to happen in FindResolutions()
- It seems like, from reading line 64, that it is hard-coded to get the display modes of display index 0, regardless of which display is used or intended to be used.

### Steps to reproduce

1. Launch a instance of Fedora 38 Workstation within a variable resolution multi-monitor setup.
2. Run OpenTTD (nightly, steam, generic or distro-specific) and attempt to set resolution to the display's native resolution.
3. Under wayland you may be locked to the maximum resolution of one display (regardless of the intended display), under X11 you may be locked to the combined resolution of your entire setup.

**Comment by glx22** [comment] 2023-10-06 01:09
Resolution list is get from display 0 https://github.com/OpenTTD/OpenTTD/blob/master/src/video/sdl2_v.cpp#L64
Startup display is determined based on mouse location https://github.com/OpenTTD/OpenTTD/blob/master/src/video/sdl2_v.cpp#L113 and can be overridden with driver parameter https://github.com/OpenTTD/OpenTTD/blob/master/src/video/sdl2_v.cpp#L540
Resolutions are found before display selection https://github.com/OpenTTD/OpenTTD/blob/master/src/video/sdl2_v.cpp#L527
The window is created using startup display size https://github.com/OpenTTD/OpenTTD/blob/master/src/video/sdl2_v.cpp#L146
The surface size is set using found resolutions (ie display 0) https://github.com/OpenTTD/OpenTTD/blob/master/src/video/sdl2_v.cpp#L182

So yeah, it seems there are some potential problems.

In your logs [1] is the resolution from config, [2] is the resolution of startup display (SDL might be wrong here, I don't know), [3] is the resolution selected from the list of display 0.

**Comment by Lamrr** [comment] 2023-10-06 01:33
> In your logs [1] is the resolution from config, [2] is the resolution of startup display (SDL might be wrong here, I don't know), [3] is the resolution selected from the list of display 0.

SDL seems to get the right startup display under wayland (i.e. display 1 (0, 0, 1920, 1080)), however it does not correctly get the mouse position i.e. the mouse position is always 0, 0, so it just happens to coincide that 0, 0 is the location of the correct display in this case.

This doesn't matter much for this exact issue however, as it seems like this knowledge isn't used at all to set the resolution, only the size of the window (which does work fine, it takes up the whole screen-space given by the monitor).

**Comment by sjoerd0301** [comment] 2023-10-13 15:11
I've run into the same issue, but I think it resolved itself after I manually installed the OpenGFX graphics set and set the `graphicsset = "OpenGFX"` and `resolution = 3440,1440`.

`openttd -ddriver=2`
`dbg: [driver] Successfully loaded blitter '32bpp-anim'
dbg: [driver] Resolution for display: 3440x1440
dbg: [driver] SDL2: Mouse is at (0, 0), use display 0 (0, 0, 3440, 1440)
dbg: [driver] SDL2: using mode 3440x1440
dbg: [driver] SDL2: using driver 'wayland'
dbg: [driver] OpenGL driver: NVIDIA Corporation - NVIDIA GeForce GTX 1060/PCIe/SSE2 (4.6.0 NVIDIA 535.113.01)
dbg: [driver] OpenGL shading language version: 4.60 NVIDIA, texture units = 192
dbg: [driver] Successfully probed video driver 'sdl-opengl'
dbg: [driver] Successfully probed sound driver 'sdl'
dbg: [driver] Fluidsynth: sf (null)
dbg: [driver] Fluidsynth: samplerate 44100
dbg: [driver] Successfully probed music driver 'fluidsynth'
dbg: [driver] using thread for game-loop
dbg: [driver] Switching blitter from '32bpp-anim' to '40bpp-anim'... 
dbg: [driver] Successfully loaded blitter '40bpp-anim'
dbg: [driver] Successfully switched to 40bpp-anim.
dbg: [driver] SDL2: using mode 3440x1440
dbg: [driver] SDL2: using mode 3440x1440`

I still can't switch the resolution via the ingame settings though, when I try it just does this:
(not that it matters, but still, thought it was worth a mention.)
`dbg: [driver] SDL2: using mode 864x486
dbg: [driver] SDL2: using mode 3440x1440
dbg: [driver] SDL2: using mode 1024x768
dbg: [driver] SDL2: using mode 3440x1440`

**Comment by Lamrr** [comment] 2023-10-14 04:11
> 



> I've run into the same issue, but I think it resolved itself after I manually installed the OpenGFX graphics set and set the `graphicsset = "OpenGFX"` and `resolution = 3440,1440`.
> 

This has not worked for me, I think the difference is the monitor you're running it on has been assigned display index 0, while in my case it has been assigned display index 1. I'm not sure how these indexes are assigned (the system under Wayland seems less transparent then X11) however whichever monitor is assigned as primary does not seem to affect things.

However I have found that by manually changing the hard-coded display index in `FindResolutions()` from `0` to `1`, I am able to get OpenTTD to work correctly in full screen.

Line 62
`for (int i = 0; i < SDL_GetNumDisplayModes(0); i++) {` -> `for (int i = 0; i < SDL_GetNumDisplayModes(1); i++) {`

Line 64
`SDL_GetDisplayMode(0, i, &mode);` -> `SDL_GetDisplayMode(1, i, &mode);`

```
dbg: [driver] Successfully loaded blitter '32bpp-anim'
dbg: [driver] Resolution for display: 1920x1080
dbg: [driver] SDL2: Mouse is at (0, 0), use display 1 (0, 0, 1920, 1080)
dbg: [driver] SDL2: using mode 1920x1080
dbg: [driver] SDL2: using driver 'wayland'
dbg: [driver] OpenGL driver: NVIDIA Corporation - NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2 (4.6.0 NVIDIA 535.113.01)
dbg: [driver] OpenGL shading language version: 4.60 NVIDIA, texture units = 192
dbg: [driver] Successfully probed video driver 'sdl-opengl'
dbg: [driver] Successfully probed sound driver 'sdl'
dbg: [driver] Fluidsynth: sf (null)
dbg: [driver] Fluidsynth: samplerate 44100
dbg: [driver] Successfully probed music driver 'fluidsynth'
dbg: [driver] using thread for game-loop
dbg: [driver] Switching blitter from '32bpp-anim' to '40bpp-anim'...
dbg: [driver] Successfully loaded blitter '40bpp-anim'
dbg: [driver] Successfully switched to 40bpp-anim.
dbg: [driver] SDL2: using mode 1920x1080
dbg: [driver] SDL2: using mode 1920x1080
```
I think this confirms my research earlier that OpenTTD does not get use the resolutions from the startup display but instead which ever display `0` is. I'm no CPP coder, but I think this needs to be changed so `FindResolutions()` uses the display index found in `FindStartupDisplay()`.

They may be further problems with the video driver code as well, as I was still only able to get full screen working at the correct resolution by manually editing `openttd.cfg`, in _addition_ to the code changes above. The in game resolution selection menu does not work well.

**Comment by sjoerd0301** [comment] 2023-10-18 09:18
Turns out the issue is back after a restart. Apparently it resolves itself after unplugging your second monitor, and starting OpenTTD, after which you can plug in your second monitor again.
Even after closing and reopening with the second monitor plugged in it still works.
It's quite a  hacky way to get around this issue.

Maybe I'll take a look later, to see if I can fix it.

**Comment by sjoerd0301** [comment] 2023-10-18 11:14
Addition:
On wayland it's impossible to get the current mousepointer location. Maybe Gnome has it's own api for it, but that needs to be fixed in SDL I think.
Also; because wayland is just a protocol, and that protocol supports multiple mouse pointer (IDK why, seems useless) It would be a problem determining what the current mousepointer is.

Maybe we can find another way to figure out on which monitor OpenTTD is located and use that instead, but that seems to need including wayland or X11 deps, so I think that might  need to come from SDL al well.

**Comment by Lamrr** [comment] 2023-10-18 11:31
> Addition: On wayland it's impossible to get the current mousepointer location. Maybe Gnome has it's own api for it, but that needs to be fixed in SDL I think. Also; because wayland is just a protocol, and that protocol supports multiple mouse pointer (IDK why, seems useless) It would be a problem determining what the current mousepointer is.
> 
> Maybe we can find another way to figure out on which monitor OpenTTD is located and use that instead, but that seems to need including wayland or X11 deps, so I think that might need to come from SDL al well.

Perhaps the easiest and most fail-proof way of doing this is letting the user manually select which display to use from the settings menu.  Such an approach can be implemented through SDL by iterating through [SDL_GetNumVideoDisplays](https://wiki.libsdl.org/SDL2/SDL_GetNumVideoDisplays).

An example of how it could work, taken from Team Fortress 2's video settings;
![Screenshot from 2023-10-18 22-27-48](https://github.com/OpenTTD/OpenTTD/assets/96937466/a7901dda-1ed4-4240-a518-1577f5d21fc8)

**Comment by TrueBrain** [comment] 2024-01-14 21:42
Okay, this ticket was a bit hard to decypher, but I think it is because there are actually three bugs being reported. And it took me a while to figure that out :) So correct me if am wrong, but let's test if I understood this correctly.

Bug `#1`: we have the issue that on Wayland you cannot select the resolution of the second monitor, but only that of the first.
Bug `#2`: on X11, the first display has a resolution that is a combination of both displays.
Bug `#3`: via the generic-linux drivers only X11 works, not wayland.

The second one is easiest to explain. On X11, often `xinerama` is used for multi-monitor. `(xinerama) is an extension to the X Window System that enables X applications and window managers to use two or more physical displays as one large virtual display.` In other words: it picks up your two displays, and makes a single virtual display out of it. This is reported to SDL, and as such, reported to us. So, on X11, we only detect a single display, which is of the wrong resolution (the two combined).

There is nothing we can do about this. It is a problem with X11, and you would have to fix the X11 configuration to get this working.

The third one is interesting .. I wonder if it just defaults to X11, or if wayland is actually not working. You can test this by starting OpenTTD like: `SDL_VIDEODRIVER=wayland ./openttd -ddriver=2`. Would you be able to tell me if that switches to wayland? As in that case it is likely Fedora patched SDL to pick wayland over X11, but that SDL upstream still picks X11 over wayland. At least, that would make the most sense to me :)

The first bug, however, is the one I think you were talking about in your comments. On startup, we only iterate over the first display to fetch all the resolutions, and don't bother with any other display. So if your second display has a resolution not in the list of the first, it will not be listed. And this of course is a bit weird :)

In total, this first bug has three sub-bugs:
- Only the resolutions of the first display are listed.
- We always assume that requesting a fullscreen on SDL is always done on the first display. But in your case it is done on the second display.
- Wayland always reports the mouse is at `0,0`, which means our detection for what display to start OpenTTD on fails.

The last one is rather unrelated, and not really important. The first one is kinda important, as you explored, but not in the way you think. The second one is the actual culprit. When we go fullscreen, we try to find the best resolution that matches. In your suggestion, you changed that to only contain the resolution of the second display, so that is used. But that only works if you start in fullscreen. When you toggle to it, it will still set the resolution to the first display.


Anyway, long story short: a total of 5 bugs that make this ticket a bit confusing to understand and figure out. To summarize:

Bug `#1.1`: I will fix this in a bit. It will not fix your issue, as both resolutions of both displays will be listed. This will still cause fullscreen on startup to pick the wrong resolution.
Bug `#1.2`: I need to investigate if we can request somewhere what display is going to be used for fullscreen. This would actually fix your problem (I think).
Bug `#1.3`: Needs a bit of investigation if this is possible at all, or whether we simply can't detect what display to start on on Wayland, and it will always be display that covers pixel `(0,0)`.
Bug `#2`: this is an X11 issue, and nothing we can do to fix it.
Bug `#3`: please check with `SDL_VIDEODRIVER=wayland ./openttd -ddriver=2` if it selects Wayland. If so, not a bug on our side.

Let me know if I said something you disagree with; we have to figure this out together! :D

**Comment by Lamrr** [comment] 2024-01-14 23:32
Thank you for going through this, I think you've hit most of the issues which make up this.

> The third one is interesting .. I wonder if it just defaults to X11, or if wayland is actually not working. You can test this by starting OpenTTD like: `SDL_VIDEODRIVER=wayland ./openttd -ddriver=2`. Would you be able to tell me if that switches to wayland? As in that case it is likely Fedora patched SDL to pick wayland over X11, but that SDL upstream still picks X11 over wayland. At least, that would make the most sense to me :)

This doesn't work for me.

```
dbg: [driver] Successfully loaded blitter '32bpp-anim'
dbg: [driver] Probing video driver 'sdl-opengl' failed with error: wayland not available
dbg: [driver] Probing video driver 'sdl' failed with error: wayland not available
Error: Couldn't find any suitable video driver
```
Both the Fedora distributed and my locally built versions of OpenTTD do work with that however. You can see the [spec file](https://src.fedoraproject.org/rpms/openttd/tree/rawhide) both them and I use, I don't think there is anything that is intentionally patched so I suspect it might have something to do with the sdl2 dep which is used at build time.

> The second one is easiest to explain. On X11, often `xinerama` is used for multi-monitor. `(xinerama) is an extension to the X Window System that enables X applications and window managers to use two or more physical displays as one large virtual display.` In other words: it picks up your two displays, and makes a single virtual display out of it. This is reported to SDL, and as such, reported to us. So, on X11, we only detect a single display, which is of the wrong resolution (the two combined).
> 
> There is nothing we can do about this. It is a problem with X11, and you would have to fix the X11 configuration to get this working.

Okay things get a bit strange here, now returning back to our Fedora distributed copy of OpenTTD we find X11 now works somewhat correctly,  successfully using the fullscreen resolution specified in `openttd.cfg`. (I unfortunately didn't test this earlier as I've only recently switched back to X11)  Only the generic linux binary forces us to use the 'xinerama' virtual display.

Fedora

```
dbg: [driver] Successfully loaded blitter '32bpp-anim'
dbg: [driver] Resolution for display: 1920x1080
dbg: [driver] SDL2: Mouse is at (428, 531), use display 0 (0, 0, 1920, 1080)
dbg: [driver] SDL2: using mode 1920x1080
dbg: [driver] SDL2: using driver 'x11'
dbg: [driver] Successfully probed video driver 'sdl'
```
Generic

```
dbg: [driver] Successfully loaded blitter '32bpp-anim'
dbg: [driver] Resolution for display: 1920x1080
dbg: [driver] SDL2: Mouse is at (681, 928), use display 0 (0, 0, 3600, 1080)
dbg: [driver] SDL2: using mode 3600x1080
dbg: [driver] SDL2: using driver 'x11'
dbg: [driver] Successfully probed video driver 'sdl'
```
Using a basic python script we can confirm that under X11 both of my displays and their modes are exposed to SDL, but the xinerama virtual display is not. 

```
Display index 0 has modes:
 [SDL_DisplayMode(1920x1080 @ 60Hz), SDL_DisplayMode(1920x1080 @ 50Hz), SDL_DisplayMode(1920x1080 @ 30Hz), SDL_DisplayMode(1920x1080 @ 25Hz), SDL_DisplayMode(1680x1050 @ 60Hz), SDL_DisplayMode(1440x900 @ 60Hz), SDL_DisplayMode(1280x1024 @ 75Hz), SDL_DisplayMode(1280x1024 @ 60Hz), SDL_DisplayMode(1280x960 @ 60Hz), SDL_DisplayMode(1280x720 @ 60Hz), SDL_DisplayMode(1280x720 @ 50Hz), SDL_DisplayMode(1024x768 @ 75Hz), SDL_DisplayMode(1024x768 @ 70Hz), SDL_DisplayMode(1024x768 @ 60Hz), SDL_DisplayMode(800x600 @ 75Hz), SDL_DisplayMode(800x600 @ 72Hz), SDL_DisplayMode(800x600 @ 60Hz), SDL_DisplayMode(800x600 @ 56Hz), SDL_DisplayMode(720x576 @ 50Hz), SDL_DisplayMode(720x480 @ 60Hz), SDL_DisplayMode(640x480 @ 75Hz), SDL_DisplayMode(640x480 @ 73Hz), SDL_DisplayMode(640x480 @ 60Hz)]
Display index 1 has modes:
 [SDL_DisplayMode(1680x1050 @ 75Hz), SDL_DisplayMode(1680x1050 @ 60Hz), SDL_DisplayMode(1600x900 @ 60Hz), SDL_DisplayMode(1440x900 @ 75Hz), SDL_DisplayMode(1440x900 @ 60Hz), SDL_DisplayMode(1280x1024 @ 75Hz), SDL_DisplayMode(1280x1024 @ 72Hz), SDL_DisplayMode(1280x1024 @ 60Hz), SDL_DisplayMode(1280x720 @ 60Hz), SDL_DisplayMode(1280x720 @ 50Hz), SDL_DisplayMode(1152x864 @ 75Hz), SDL_DisplayMode(1024x768 @ 75Hz), SDL_DisplayMode(1024x768 @ 70Hz), SDL_DisplayMode(1024x768 @ 60Hz), SDL_DisplayMode(800x600 @ 75Hz), SDL_DisplayMode(800x600 @ 72Hz), SDL_DisplayMode(800x600 @ 60Hz), SDL_DisplayMode(720x576 @ 50Hz), SDL_DisplayMode(720x480 @ 60Hz), SDL_DisplayMode(640x480 @ 75Hz), SDL_DisplayMode(640x480 @ 73Hz), SDL_DisplayMode(640x480 @ 60Hz)]
 ```
 This seems a bit confusing and strange, I'm suspecting is has something to do with the SDL library itself and differences in the build environment that is perhaps changing something somewhere?

**Comment by TrueBrain** [comment] 2024-01-14 23:40
As we compile a generic linux binary that has to work on rather old Linux systems, we cannot depend on the X11 libraries on the system. They are compiled in that binary. And so I would guess that the X11 version used is a bit older than Fedora uses, and doesn't support this. That is why in general the version build by vendors are better :) That said, I will see if I can find out if that is solvable.

And indeed, we do not compile `wayland` support into SDL. This is because of the oldness of the system we have to build on. It has Wayland 1.15, and SDL needs at least 1.18 for Wayland support to work. Also something I will look further into.

But in better news, if you would compile the latest master yourself, the problems you ran into (bug `#1.1` and `#1.2`) should be solved :) If you could try that, that would be much appreciated.

**Comment by Lamrr** [comment] 2024-01-15 00:16
> But in better news, if you would compile the latest master yourself, the problems you ran into (bug `#1.1` and `#1.2`) should be solved :) If you could try that, that would be much appreciated.

X11 works the same as I described above, Wayland however;

```
dbg: [driver] Successfully loaded blitter '32bpp-anim'
dbg: [driver] Resolution for display: 1920x1080
dbg: [driver] SDL2: Mouse is at (0, 0), use display 1 (0, 0, 1920, 1080)
dbg: [driver] SDL2: using mode 1920x1080
Error: SDL2: Couldn't get window surface:
```
Might be related to #11714 will need to investigate more later today.

**Comment by TrueBrain** [comment] 2024-01-15 00:45
I get the same error with `sdl` now, when I compile against the latest LibSDL. When I use a slightly older version, it works. So something there broke something. I will investigate a bit further too.

A workaround for now is to use `-v sdl-opengl`, which does seem to work fine.

In other news, I managed to create a generic Linux binary, with a somewhat newer libc demand (one from 2018, instead of 2012), which does have wayland support and does indeed also fix the X11 issue. I will prepare an example binary this week or so for you to test.

**Comment by TrueBrain** [comment] 2024-01-15 08:05
Okay, I created / reopened some tickets to keep sanity. I think the point of this ticket is fixed by the above mentioned PRs. But there are three open SDL bugs:

- https://github.com/OpenTTD/OpenTTD/issues/11781 - No Wayland support in our Linux Generic binaries
- https://github.com/OpenTTD/OpenTTD/issues/11714 - Error `Couldn't get window surface` when using software rendering on Wayland - workaround: use hardware rendering
- https://github.com/OpenTTD/OpenTTD/issues/11767 - No xrandr support for X11, causing virtual desktops

And let this ticket be about fullscreen on Wayland not using the correct resolution. If you can confirm whether that is actually fixed (whenever you have time, ofc), we can close this issue, and track the rest in the other tickets :)


Always nice, when multiple bugs stack on top of each other .. but I think we now know why they all happen :)

**Comment by Lamrr** [comment] 2024-01-23 06:20
I've finally been able to revisit this after getting a new graphics card and returning to Wayland as default. I can confirm that nightly `20240122-master-g75f21065c9` has mostly resolved this issue, however with a few caveats.

1) Generic builds now can run Wayland, however they will default to using X11 (/XWayland) even in a Wayland windowing system. I had to use `SDL_VIDEODRIVER=wayland` to change this. This is more of a side note, but it would probably be ideal if the video driver used matched your windowing system.

2) More crucially, the in-game resolution options do not work. If I launch the game with `resolution = ` blank, the game will default to 640x480 and I am unable to change this in-game.

```
dbg: [driver] Successfully loaded blitter '32bpp-anim'
dbg: [driver] Resolution for display: 640x480
dbg: [driver] SDL2: Mouse is at (0, 0), use display 1 (0, 0, 1920, 1080)
dbg: [driver] SDL2: using mode 640x480
dbg: [driver] SDL2: using driver 'wayland'
dbg: [driver] OpenGL driver: AMD - AMD Radeon RX 6600 XT (radeonsi, navi23, LLVM 17.0.6, DRM 3.54, 6.6.12-200.fc39.x86_64) (4.6 (Compatibility Profile) Mesa 23.3.3)
dbg: [driver] OpenGL shading language version: 4.60, texture units = 192
dbg: [driver] Successfully probed video driver 'sdl-opengl'
dbg: [driver] Successfully probed sound driver 'sdl'
dbg: [driver] Fluidsynth: sf (null)
dbg: [driver] Fluidsynth: samplerate 44100
dbg: [driver] Successfully probed music driver 'fluidsynth'
dbg: [driver] using thread for game-loop
dbg: [driver] Switching blitter from '32bpp-anim' to '40bpp-anim'...
dbg: [driver] Successfully loaded blitter '40bpp-anim'
dbg: [driver] Successfully switched to 40bpp-anim.
dbg: [driver] SDL2: using mode 640x480
dbg: [driver] SDL2: using mode 640x480
dbg: [driver] SDL2: using mode 1920x1080
dbg: [driver] SDL2: using mode 640x480
```

However if I set `resolution = 1920,1080`, the game will successfully launch with that resolution. However I am still unable to change it in-game. I can use any resolution here and the same will happen.

```
dbg: [driver] Successfully loaded blitter '32bpp-anim'
dbg: [driver] Resolution for display: 1920x1080
dbg: [driver] SDL2: Mouse is at (0, 0), use display 1 (0, 0, 1920, 1080)
dbg: [driver] SDL2: using mode 1920x1080
dbg: [driver] SDL2: using driver 'wayland'
dbg: [driver] OpenGL driver: AMD - AMD Radeon RX 6600 XT (radeonsi, navi23, LLVM 17.0.6, DRM 3.54, 6.6.12-200.fc39.x86_64) (4.6 (Compatibility Profile) Mesa 23.3.3)
dbg: [driver] OpenGL shading language version: 4.60, texture units = 192
dbg: [driver] Successfully probed video driver 'sdl-opengl'
dbg: [driver] Successfully probed sound driver 'sdl'
dbg: [driver] Fluidsynth: sf (null)
dbg: [driver] Fluidsynth: samplerate 44100
dbg: [driver] Successfully probed music driver 'fluidsynth'
dbg: [driver] using thread for game-loop
dbg: [driver] Switching blitter from '32bpp-anim' to '40bpp-anim'...
dbg: [driver] Successfully loaded blitter '40bpp-anim'
dbg: [driver] Successfully switched to 40bpp-anim.
dbg: [driver] SDL2: using mode 1920x1080
dbg: [driver] SDL2: using mode 1920x1080
dbg: [driver] SDL2: using mode 1680x1050
dbg: [driver] SDL2: using mode 1920x1080
```
This is not problem when the game is running under X11 (or XWayland I suppose), the window will automatically use the correct resolution for whichever monitor it is on. However the resolution still cannot be changed in game, even under X11.

Nonetheless, despite these caveats, I think the issue has been resolved as it is now at least _possible_ for the correct full screen resolution to be used, even if that involves some manual config editing. Perhaps new feature requests and / or issues should be opened for these other issues?

**Closed as completed** 2024-01-23 08:02 UTC
