### ISSUE TITLE
OTTD crashes on start macosx . Log

### ISSUE THREAD

**Issue by saveinthesky** [OpenTTD/OpenTTD#8501] opened 2021-01-05 18:17 UTC
## Steps to reproduce

I paste here below the crash log, I hope someone can help. Thanks

*** OpenTTD Crash Report ***

Crash at: Tue Jan  5 18:09:58 2021
In game date: 0-01-01 (0)

Crash reason:
 Signal:  Segmentation fault: 11 (11)
 Message: <none>

OpenTTD version:
 Version:    1.10.3 (0)
 NewGRF ver: 1a086d64
 Bits:       64
 Endian:     little
 Dedicated:  no
 Build date: Aug  9 2020 18:00:43

Stacktrace:
 [00] openttd              0x00000001083ba968 (Pool<Company, Owner, 1ul, 15ul, (PoolType)1, false, true>::CleanPool() + 101176)

Operating system:
 Name:     Mac OS X
 Release:  10.12.6
 Machine:  Intel x86-64h Haswell
 Min Ver:  1090
 Compiler: GCC 4.2.1 "4.2.1 Compatible Apple LLVM 11.0.0 (clang-1100.0.33.17)"

Configuration:
 Blitter:      32bpp-anim
 Graphics set: OpenGFX (5580)
 Language:     /Applications/OpenTTD.app/Contents/Resources/lang/italian.lng
 Music driver: none
 Music set:    none (4294967295)
 Network:      no
 Sound driver: none
 Sound set:    none (4294967295)
 Video driver: cocoa

Fonts:
 Small:  sprite
 Medium: sprite
 Large:  sprite
 Mono:   sprite

AI Configuration (local: 0) (current: 0):

Libraries:
 FreeType:   2.10.2
 LZMA:       5.2.5
 LZO:        2.10
 PNG:        1.6.37
 Zlib:       1.2.8

---- gamelog start ----
---- gamelog end ----

Recent news messages:

*** End of OpenTTD Crash Report ***

**Comment by TrueBrain** [comment] 2021-01-05 18:20
Would you mind trying out our latest nightly, to see if the problem still happens?

https://www.openttd.org/downloads/openttd-nightlies/latest.html

Tnx!

**Comment by andythenorth** [comment] 2021-01-05 18:21
Possibly https://github.com/OpenTTD/OpenTTD/issues/8066

**Comment by saveinthesky** [comment] 2021-01-06 16:06
Oh yes now it works!! thank you very very much

Il giorno mar 5 gen 2021 alle ore 19:20 Patric Stout <
notifications@github.com> ha scritto:

**Comment by LordAro** [comment] 2021-01-06 16:13
Excellent

Closing as duplicate of #8066

**Closed as completed by LordAro** 2021-01-06 16:13 UTC
Labels: OS: MacOS

**Comment by saveinthesky** [comment] 2021-01-10 17:15
Hello, sorry for disturb, now, the game works ( with that nightly build)
but the multiplayer function doesn't work, it say the servers has different
version and put a red dot.
I suppose it is because of the build? is there a way to resolve that?
Thank you very much and sorry for the disturb


Il giorno mer 6 gen 2021 alle ore 17:14 Charles Pigott <
notifications@github.com> ha scritto:

**Comment by TrueBrain** [comment] 2021-01-10 19:37
Indeed, nightlies cannot play together with for example 1.10.3. But don't worry, soon (in a few weeks) we will release a new stable which includes this fix!

Till that time, you are sadly either bound to single-player, or you have to ask your fellow players to also upgrade to the same nightly.

**Comment by saveinthesky** [comment] 2021-01-11 14:53
Ok.  Thank you very much!

Il giorno dom 10 gen 2021 alle ore 20:37 Patric Stout <
notifications@github.com> ha scritto:
