### ISSUE TITLE
Track 00 of the "All" programme in the jazz jukebox doesn't play

### ISSUE THREAD

**Issue by TriggeredSnake** [OpenTTD/OpenTTD#9399] opened 2021-06-25 01:59 UTC
## Version of OpenTTD
1.10.3, Windows 10 (This bug appeared a few updates ago I think, after I updated from 1.9.X, and still occurs in 1.11.X)

## Expected result
Starting the jazz jukebox should play every song in a programme, including track 00 which in the "All" programme is OpenTTD journey.

## Actual result
Track 00 of the "All" programme in the jazz jukebox doesn't play even when using the skip keys, sometimes it plays when using shuffle but the skip keys don't seem to trigger it that way. Creating a custom programme including the track will allow it to play during gameplay. (I wonder if this was intentional, to keep the default track 00 "OpenTTD Journey" reserved for the title screen?)

## Steps to reproduce
Start a new game or load a save, and press play on the jazz jukebox.

**Comment by glx22** [comment] 2021-06-25 02:07
Duplicate of #8946. It's done intentionally as track 00 is for the main menu. But you can create a custom playlist with all songs including track 00.

**Comment by LordAro** [comment] 2021-07-17 14:14
Closing, as this is working as intended

**Closed as completed by LordAro** 2021-07-17 14:14 UTC
