### ISSUE TITLE
Kdtree is built too early in savegame loading process

### ISSUE THREAD

**Issue by PeterN** [OpenTTD/OpenTTD#7371] opened 2019-03-13 03:01 UTC
## Version of OpenTTD

20190312-master-gdea7f078f4

## Expected result

Old savegame is loaded the same as before implementation of k-d trees.

## Actual result

Assertion failure on loading old savegame during building of k-d tree structures.

`openttd: src/core/pool_type.hpp:113: Titem *Pool<Object, unsigned int, 64, 16711680, PoolType::PT_NORMAL, false, true>::Get(size_t) [Titem = Object, Tindex = unsigned int, Tgrowth_step = 64, Tmax_size = 16711680, Tpool_type = PoolType::PT_NORMAL, Tcache = false, Tzero = true]: Assertion `index < this->first_unused' failed.`

## Steps to reproduce

Download "Public Server Game 201 Final" from https://wiki.openttdcoop.org/PublicServer:Archive_-_Games_201_-_210#gameid_201
Load save game

Crash occurs because building k-d tree structure accesses map array before map array has been updated. In this particular case it is because the accessing the map array before SLV_186 conversion results in invalid object index, however there are likely more causes.

Before savegame data is converted, normal game accessors should not be used, but k-d tree uses these to build its structures. These lines are unsafe in their current position:

        RebuildTownKdtree();
        RebuildStationKdtree();
        /* This needs to be done even before conversion, because some conversions will destroy objects
         * that otherwise won't exist in the tree. */
        RebuildViewportKdtree();

**Comment by nielsmh** [comment] 2019-03-13 11:51
I originally tried building the trees late in the loading, but that ended up crashing for different reasons, when converting a very old save (the master title screen).

**Comment by nielsmh** [comment] 2019-03-13 12:19
I'm not sure I see why SLV_186 should be relevant, it only seems to concern map objects, not towns, stations, or signs.

**Comment by PeterN** [comment] 2019-03-13 12:23
Town signs can be on a tile that has been replaced with an object. During the test for sign position, it queries the tile to get foundation status, and that depends on the object information, which depends on the object ID, which SLV_186 shuffles about. This is just one particular case, of course. Town signs could be on other tile types of course.

**Comment by PeterN** [comment] 2019-03-13 12:31
I was able to get this savegame to load by deferring k-d tree generation til the end of `AfterLoadGame`, with a simple guard to make sure no k-d tree functions were called whilst still within `AfterLoadGame`. I had to make CalcClosestTown... fallback to the original method for this.

**Comment by PeterN** [comment] 2019-03-14 10:19
Here's my branch with the test code in place. This is obviously not production ready! https://github.com/PeterN/OpenTTD/commits/fix-7371

**Comment by nielsmh** [comment] 2019-03-23 10:04
The absolutely simplest fix is changing the sign location calculation so it does not depend on foundations status at all. It might make some town signs sit in a "wrong" location, but would that really be a problem?

**Comment by JGRennison** [comment] 2019-04-01 16:20
Leaving `RebuildTownKdtree` and `RebuildStationKdtree` at the start, and moving `RebuildViewportKdtree` to the end, is sufficient to resolve the issue (for this particular save game at least).

_viewport_sign_kdtree is not read during `AfterLoadGame`, and therefore does not need to be initialised before conversion.
_town_kdtree is required for `CalcClosestTown` and such during conversion, but this does not inspect tile contents, foundations, etc.

**Comment by nielsmh** [comment] 2019-04-01 16:23
I think there were some situations where stations and/or waypoints are created or removed during conversion, which will trigger an update of the viewport sign tree, which will fail if it wasn't built beforehand.

**Comment by JGRennison** [comment] 2019-04-01 16:46
Removing a non-existent key from an empty kd tree isn't an error, likewise adding a key to the kd tree before it is otherwise filled is also harmless.

`MoveWaypointsToBaseStations` and `MoveBuoysToWaypoints` appear to be the functions in question. The former doesn't appear to use _viewport_sign_kdtree. The latter appears to perform harmless removals from _viewport_sign_kdtree. In both cases the kd tree isn't added to and so RebuildViewportKdtree should be called afterwards.

**Comment by nielsmh** [comment] 2019-04-01 19:24
Right now, my k-d tree code considers it an error it attempt removing an element that does not exist, and will assert.

https://github.com/OpenTTD/OpenTTD/blob/92d5835495f56a0f145a18d428764737d39be920/src/core/kdtree.hpp#L211-L215

This is under the assumption that it's an error in the upper layer if the tree is not correctly maintained.

**Comment by JGRennison** [comment] 2019-04-01 19:41
Asserting on removing a non-existing key is very surprising behaviour, and contradicts the documentation of the `Remove` method.

The savegame update code requires further changes if this is the intended behavour.

**Comment by LordAro** [comment] 2019-04-27 13:57
In the interests of reproducibility, I found the following 64x64 save that also crashes on load, and is fixed by #7398 
[pr7398.zip](https://github.com/OpenTTD/OpenTTD/files/3123924/pr7398.zip)

**Closed as completed** 2019-05-11 12:58 UTC
