### ISSUE TITLE
[Bug]: Sub-Arctic Food Plants

### ISSUE THREAD

**Issue by Lut3s** [OpenTTD/OpenTTD#11999] opened 2024-02-05 08:44 UTC
### Version of OpenTTD

14.0-beta2

### Expected result

Delivering livestock to a processing plant to manufacture food

### Actual result

No food is produced. Also, only livestock is produced by farms, but this might be intentional. Only affects new games.

### Steps to reproduce

[Food Production Bug.zip](https://github.com/OpenTTD/OpenTTD/files/14162540/Food.Production.Bug.zip)

**Comment by LordAro** [comment] 2024-02-05 10:11
Duplicate of #11995

**Closed as not planned by LordAro** 2024-02-05 10:11 UTC
