### ISSUE TITLE
1.9.3 Crash report

### ISSUE THREAD

**Issue by SamuXarick** [OpenTTD/OpenTTD#7766] opened 2019-10-09 17:40 UTC
## Version of OpenTTD
1.9.3
## Steps to reproduce
I set up some NewGRFs downloaded via online content, and ran some AIs. Game started in 1950, but crashed quite early, in 1955.

The Minimal GS is edited.
[Minimal GS.zip](https://github.com/OpenTTD/OpenTTD/files/3708709/Minimal.GS.zip)
[crash.zip](https://github.com/OpenTTD/OpenTTD/files/3708713/crash.zip)

**Comment by nielsmh** [comment] 2019-10-09 18:25
Offending function:
https://github.com/OpenTTD/OpenTTD/blob/f6643952ce53b1823c2273964466f785a907ec1a/src/script/api/script_order.cpp#L667-L677
Crash happens on line 670. `origin_tile` is 39971 (0x9C23) and that tile is a buoy.

![image](https://user-images.githubusercontent.com/1062071/66508975-63359b00-ead2-11e9-8a30-72ee3c6a2f98.png)

This causes a crash because a buoy is a station tile, but it's not a station (it's a waypoint), thus IsStationTile() returns true, but Station::GetByTile() returns nullptr. So you get a null pointer dereference looking up the airport station part location.

Fix would be replacing by something like this, no need to check for IsStationTile() since Station::GetByTile() already checks that:
```C++
Station * origin_station = ::Station::GetByTile(origin_tile);
if (origin_station != nullptr) origin_tile = origin_st->airport.tile;
```

There is also a bug in the AI doing this, since it's asking for aircraft distance from a buoy to somewhere else, and aircraft don't use buoys!

**Comment by glx22** [comment] 2019-10-09 18:58
Duplicate of #7593

**Closed as completed by glx22** 2019-10-09 18:58 UTC
