### ISSUE TITLE
OpenTTD failed to start on MacOS

### ISSUE THREAD

**Issue by buynov** [OpenTTD/OpenTTD#8075] opened 2020-04-10 19:05 UTC
## Version of OpenTTD

Latest, 1.10.0

## Expected result

The game to start

## Actual result

The game failed to start

## Steps to reproduce

Click on the game icon

[crash.log](https://github.com/OpenTTD/OpenTTD/files/4463003/crash.log)

![Screen Shot 2020-04-10 at 22 04 32](https://user-images.githubusercontent.com/503410/79016317-53793b00-7b77-11ea-9018-65c7354ac8d5.png)

**Comment by andythenorth** [comment] 2020-04-10 19:07
Which macOS? :)

**Comment by LordAro** [comment] 2020-04-10 19:09
crash.log isn't super useful, but it indicates a duplicate of #7838

**Comment by glx22** [comment] 2020-04-10 19:16
and duplicate of #8066

**Comment by buynov** [comment] 2020-04-10 19:17
MacOS Sierra, I think it is in the crash.log:
![Screen Shot 2020-04-10 at 22 17 20](https://user-images.githubusercontent.com/503410/79017057-1615ad00-7b79-11ea-8822-21d5a10a78dc.png)

**Comment by LordAro** [comment] 2020-04-10 19:22
OK, we'll follow up in #7838

**Closed as completed by LordAro** 2020-04-10 19:22 UTC

**Comment by glx22** [comment] 2020-04-10 20:04
Discussion will continue in #8066
