### ISSUE TITLE
[Crash]: Game crashes when opening "Replace vehicles"

### ISSUE THREAD

**Issue by DatOneTrainDude** [OpenTTD/OpenTTD#10587] opened 2023-03-30 19:42 UTC
### Version of OpenTTD

13.0, Windows 10

### Steps to reproduce

1. Clicked display list for Company's Trains
2. Clicked "Manage list"
3. Clicked "Replace vehicles"
4. Game crashes at "Assertion failed at Line 750"
![Screenshot 2023-03-29 153035](https://user-images.githubusercontent.com/129439765/228945873-1ece7492-d514-4f40-8ea6-0ce5fe36f78d.jpg)

### Upload crash files

[03-30-2023 Game Crash.zip](https://github.com/OpenTTD/OpenTTD/files/11115475/03-30-2023.Game.Crash.zip)

**Comment by glx22** [comment] 2023-03-30 19:57
Duplicate of #10554

**Closed as completed by glx22** 2023-03-30 19:57 UTC
