### ISSUE TITLE
[Bug]: Fast Forward stuck on at year end finance

### ISSUE THREAD

**Issue by quackersian** [OpenTTD/OpenTTD#10366] opened 2023-01-16 18:13 UTC
### Version of OpenTTD

12.2 Windows 10

### Expected result

Hold the "tab" button on the keyboard (fast forward) when the year rolls over and wait for the year end finance window to pop up, then release the "tab" button on the keyboard. The temporary fast forward should stop.

### Actual result

Hold the "tab" button on the keyboard (fast forward) when the year rolls over and wait for the year end finance window to pop up, then release the "tab" button on the keyboard. The temporary fast forward stays stuck on until pressing "tab" again.

### Steps to reproduce

[Lakeside Transport, 1950-07-04.zip](https://github.com/OpenTTD/OpenTTD/files/10428408/Lakeside.Transport.1950-07-04.zip)

**Comment by LordAro** [comment] 2023-01-16 18:15
Not year end finance, it's actually autosave. Luckily, already fixed in #10230

Duplicate of #10224

**Closed as not planned by LordAro** 2023-01-16 18:15 UTC

**Comment by quackersian** [comment] 2023-01-16 19:42
Nice!
