### ISSUE TITLE
Trains not unloading load at station to later go to the depot for maintenance

### ISSUE THREAD

**Issue by perezdidac** [OpenTTD/OpenTTD#8405] opened 2020-12-21 06:22 UTC
## Version of OpenTTD
1.10.3

## Expected result
A train always unloads its cargo to its destination, no matter whether it has to head to maintenance.

## Actual result
Trains do not unload their load at destination even if stopping at it, if they have to go to maintenance depot.

## Steps to reproduce
Have a loaded train head its destination through a single rail track making sure it's been long enough so it needs maintenance, and have the maintenance depot after the destination station. Observe how it stops in the destination station but doesn't unload, and instead proceeds to the maintenance depot after the station, but its next destination does not change, so it has to loop back to get back to the station.

![Amtrak, Feb 3rd, 1965](https://user-images.githubusercontent.com/2025406/102745717-7a485d80-4311-11eb-8a20-a2168a5507fc.png)

## Extra notes
* If this is working as intended, is there a discussion about it?
* I am a C++ developer and I'd love to contribute (just downloaded and built at head). If this is indeed a bug, I'd love to get guidance and fix it myself as a starting point :)

**Comment by perezdidac** [comment] 2020-12-21 06:31
I believe I found a duplicate: https://github.com/OpenTTD/OpenTTD/issues/7901

**Comment by TrueBrain** [comment] 2021-01-08 22:40
Indeed, duplicate of #7901 :) Tnx for the detailed report :D

**Closed as completed by TrueBrain** 2021-01-08 22:40 UTC
