### ISSUE TITLE
Crashes before opening on mac

### ISSUE THREAD

**Issue by bl501** [OpenTTD/OpenTTD#8202] opened 2020-06-07 13:00 UTC
[crash.log](https://github.com/OpenTTD/OpenTTD/files/4742098/crash.log)

**Comment by LordAro** [comment] 2020-06-07 13:02
Duplicate of #8066

**Comment by nielsmh** [comment] 2020-06-07 13:03
Duplicate of #8066

**Closed as completed by LordAro** 2020-06-07 13:02 UTC
