### ISSUE TITLE
[Crash]: Unsure of reason but may be related to upgrading monorail to maglev

### ISSUE THREAD

**Issue by electric-socket** [OpenTTD/OpenTTD#11077] opened 2023-06-28 02:32 UTC
### Version of OpenTTD

13.3 (o) of 64 bit build date 2023-06-11 Windows 10 

### Steps to reproduce

I have no idea why it crashed so I'm guessing that something "snapped" from upgrading tiles from Monorail to Maglev as Monorail was beyond end of service life and new locos can't be bought. For some reason the game up and died. This has happened three times - but not every time the game is run. Crash reports included. Also included is the last save I did if that helps.

Paul Robinson 
[OpenTTD Crash Report Robinson 2023-0623-28.zip](https://github.com/OpenTTD/OpenTTD/files/11889104/OpenTTD.Crash.Report.Robinson.2023-0623-28.zip)

### Upload crash files

Zip file uploaded in prior window

**Comment by glx22** [comment] 2023-06-28 10:47
Most likely duplicate of #11043

**Closed as completed** 2023-08-09 13:26 UTC
