### ISSUE TITLE
2way EOL inconsistency

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6637] opened 2017-11-09 15:03 UTC
**_V453000_ opened the ticket and wrote:**

> Hi,
> 
> 2way eol seems to be breaking in this specific setup, but just moving the depot behind a straight tile seems to fix it.
> 
> Looks like unexpected behaviour,
> 
> iz?
> 
> Thanks
> 
> V

**Attachments**
- [WTF-2wayeol.png](https://bugs.openttd.org/task/6637/getfile/10878/WTF-2wayeol.png) (358.63 KiB)
- [V453000 Transport_2wayeol_failing.sav](https://bugs.openttd.org/task/6637/getfile/10879/V453000+Transport_2wayeol_failing.sav) (968.80 KiB)
- [V453000 Transport_2wayeol_works.sav](https://bugs.openttd.org/task/6637/getfile/10880/V453000+Transport_2wayeol_works.sav) (968.74 KiB)

**Reported version**: _1.7.1_
**Operating system**: _All_

---

**Comment by TrueBrain** [comment] 2018-04-10 20:17
Related to #5944 ? (but with pictures! :D)

**Comment by LordAro** [comment] 2019-03-25 23:14
![image](https://user-images.githubusercontent.com/4007992/54960217-a58ef480-4f53-11e9-95a5-56319a51eeca.png)

Cannot reproduce any inconsistency with the layout as presented above.
`yapf.rail_firstred_twoway_eol = true` was set in the cfg

**Comment by TrueBrain** [comment] 2019-04-02 20:28
Guess that means it is save to close this issue :)

**Closed as completed by TrueBrain** 2019-04-02 20:28 UTC
Labels: flyspray, component: pathfinder, bug
