### ISSUE TITLE
[Bug]: Opening the Company League Table window requires selection from list

### ISSUE THREAD

**Issue by LC-Zorg** [OpenTTD/OpenTTD#10267] opened 2022-12-20 20:56 UTC
### Version of OpenTTD

13.0-beta2

### Expected result

As before 13.0 beta2, clicking the cup icon opens the Company League Table by default.

### Actual result

As of 13.0-beta2, opening the Company League Table requires a click and selection from a list.

### Steps to reproduce

1. Compare the behavior between 13.0-beta2 and 12.2 or even 13.0-beta1
2. Pay attention to how the other icons work

**Comment by LordAro** [comment] 2022-12-20 20:57
Duplicate of #10214

**Closed as not planned by LordAro** 2022-12-20 20:57 UTC
