### ISSUE TITLE
[Bug] [UI] signals pass over bridges / viaducts

### ISSUE THREAD

**Issue by Mondonno** [OpenTTD/OpenTTD#9875] opened 2022-05-02 11:37 UTC
### Version of OpenTTD

12.2

### Expected result

Signals should not pass over brigdes/viaducts

### Actual result

Signals pass over brigdes/viaducts:
![Zrzut ekranu 2022-05-2 o 12 57 22](https://user-images.githubusercontent.com/53169453/166223616-a13cd222-d9d8-493e-8f99-1c4b1a5cf35b.png)

### Steps to reproduce

1. Create a blank map
2. Build a viaduct (or bridge but on viaduct you can see it better) on 1 ft height
3. Under it, place rail track.
4. On rail track, place signals
5. Then you can see signals passing over viaduct

It is already reproduced on this saved game:
[BUG REPORT #1.sav.zip](https://github.com/OpenTTD/OpenTTD/files/8602432/BUG.REPORT.1.sav.zip)

**Comment by James103** [comment] 2022-05-02 11:46
Duplicate of #6616, which was closed for a reason equivalent to "Working as intended."

**Comment by Mondonno** [comment] 2022-05-02 11:51
@James103 As i see it got tagged as "know issue". Shouldn't it be fixed?

**Comment by LordAro** [comment] 2022-05-02 12:11
In an ideal world, yes. Unfortunately, to do so would likely require rewrites of significant parts of the program, which is almost certainly going to be too much effort for any single person to do. See also #119

**Closed as completed by LordAro** 2022-05-02 12:11 UTC
