### ISSUE TITLE
[Crash]: Leaving company

### ISSUE THREAD

**Issue by burninghey** [OpenTTD/OpenTTD#10521] opened 2023-02-28 15:06 UTC
### Version of OpenTTD

13.0, Windows 10

### Steps to reproduce

1. set another password
2. left company (switched to spectators)

- my company was the only one in a multiplayer game
- this Server: `HARD #4 | TwoTown | Economy | !wipe | NO-AIR | !help | by Marko | www.ottd.top`

### Upload crash files

[crash20230228145801.zip](https://github.com/OpenTTD/OpenTTD/files/10851709/crash20230228145801.zip)
![crash20230228145801](https://user-images.githubusercontent.com/29624928/221893647-e4078bde-3ed6-4328-8c67-61a15cf72571.png)

**Comment by glx22** [comment] 2023-02-28 16:44
Duplicate of #10461

**Closed as completed by glx22** 2023-02-28 16:44 UTC
