### ISSUE TITLE
[Bug]: "Your PC is too slow to keep up with this server" (2/6 Authorizing)

### ISSUE THREAD

**Issue by Azophyte** [OpenTTD/OpenTTD#9742] opened 2021-12-10 22:32 UTC
### Version of OpenTTD

Steam 12.1

### Expected result

Connects to my game

### Actual result

Gets stuck loading server at 2/6, then gives error saying "Your PC is too slow t o keep up with this server"

### Steps to reproduce

1. Have friend start an OpenTTD server, set to public with no password (Size of world and other settings don't seem to matter)
2. Find server in the server list, try to join.

This only happens on my friend's computer - we have no idea what's wrong. His computer is definitely more powerful than mine, and his internet is better too, so that's not the issue.

I'll update this with a link to my bug report when it gets approved by admins

**Comment by glx22** [comment] 2021-12-10 22:35
Single core speed is what matters for OpenTTD.
And if possible try to put the server on the less powerful machine.
Enabling "pause on join" may help too.

**Comment by nielsmh** [comment] 2021-12-10 22:36
It may seem counter-intuitive, but you're generally better off running an OpenTTD server on the *slowest* computer participating.
If the server simulates the world faster than clients are able to (which can happen when the game gets big/complex with lots of vehicles, or on large maps), the server will not wait for the clients that are falling behind, but instead kick them for being too slow.
Clients can wait for the server, but the server can't wait for clients. (If the server was able to wait for clients to catch up, that would be a way to grief games on public servers.)

What you can also try doing is putting the game on pause on the server, while clients are joining the game. That way the server won't be running the simulation while the clients are connecting, and the clients won't need to catch up with the server after downloading the game.

**Comment by James103** [comment] 2021-12-10 22:37
What CPU do you have and what CPU does your friend have? Please list the exact make and model if possible.

**Comment by Azophyte** [comment] 2021-12-10 22:51
Oh wow you guys responded fast! The forum post I've made hasn't been approved yet, so I'll post the whole thing here:

----
Hi, can't find any similar posts online relating to this issue - seems to be pretty rare.
Specs:

x64-based PC
Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz, 3601 Mhz, 4 Cores, 8 Logical processors
Installed Physical Memory (RAM): 16GB
His upload and download speeds are both higher than mine, at 85MB download and 265MB upload.

I'm going to be running a game this Sunday for my friends to play OpenTTD on one map, but he can't join for some reason. I've searched a while for a solution but none have worked. I'm hosting on steam.

Here are the things we have tried (that haven't worked):
-Setting affinity of OpenTTD to just one core (taskmanager)
-Setting priority value to high (taskmanager)
-I tried hosting a 64x64 map

This seems to be an issue with steam authorisation or something like that, as he gets stuck on the authorising page (2/6) when joining - even without a password. (Screenshots attached). He can join other lobbies that have a lot of people and much larger maps too, not sure why this is the case. Not all, just some.

The weirder thing is that when I tried to join his game, it worked. The obvious solution is to host the game on his server but we really don't want to do that.

If any of you are willing to chip in and suggest solutions - or even have had this problem yourself and are willing to help out - I'm all ears and I thank you greatly.

Here are the screenshots: https://imgur.com/a/nJiCR1V

Cheers everyone
----

> It may seem counter-intuitive, but you're generally better off running an OpenTTD server on the _slowest_ computer participating. If the server simulates the world faster than clients are able to (which can happen when the game gets big/complex with lots of vehicles, or on large maps), the server will not wait for the clients that are falling behind, but instead kick them for being too slow. Clients can wait for the server, but the server can't wait for clients. (If the server was able to wait for clients to catch up, that would be a way to grief games on public servers.)
> What you can also try doing is putting the game on pause on the server, while clients are joining the game. That way the server won't be running the simulation while the clients are connecting, and the clients won't need to catch up with the server after downloading the game.

The game was brand new and already paused. I'll see if I can dig up an old laptop and running it on there - we were hoping to run it on my end since I'll be the most active.




> Single core speed is what matters for OpenTTD
How can I check single core speed? Unless it's the speed I've already listed of course

Thanks for responding so quickly, I really appreciate it

**Comment by James103** [comment] 2021-12-10 23:07
Have you tried running the setup with non-Steam OpenTTD installs for both the client and server?
You can get a non-Steam install by downloading the right zip files from https://www.openttd.org/downloads/openttd-releases/latest or https://www.openttd.org/downloads/openttd-nightlies/latest and extracting each install into its own folder.

**Comment by Azophyte** [comment] 2021-12-10 23:19
I can try that tomorrow, but we were using the steam version since we didn't want to hassle with a third party program like hamachi or zerotier to play (none of us are very tech savvy and I don't think my friend will be comfortable sharing his IP I'm afraid). We'll give it a shot if it's necessary however.

**Comment by glx22** [comment] 2021-12-10 23:28
OpenTTD doesn't use steam network feature at all. Non-Steam and Steam executable are exactly the same.

**Comment by Azophyte** [comment] 2021-12-10 23:38
Oh right, I thought the public server setup was using steam... that's my bad. We'll try that tomorrow for sure, everyone else is asleep right now I'm afraid.

**Comment by TrueBrain** [comment] 2021-12-11 09:29
Next time you give this a try, please launch both server and client with `-dnet=6` as extra argument. You can do this via Steam, under Properties of the game, Launch Options.

This will open up a black window when starting the game. After trying to connect, it will have a lot of text in that window. Please copy/paste the full window of both the server and client and attach it to this ticket. That way we can see what is going on in the background, and hopefully get some inspiration what is going on :)

**Comment by Azophyte** [comment] 2021-12-11 15:19
Ok, we tried using the base non-steam version, but that didn't work. It also didn't include the sound set on my end and the graphics set on my friends end, and we're not sure why that happened.
We've reinstalled it on steam and tried the -dnet thing, this is what showed up:

On startup (my end):
```
dbg: [net] Starting network
dbg: [net] Loading windows socket library
dbg: [net] Initializing UDP listeners
dbg: [net] Network online, multiplayer available
dbg: [net] Detected broadcast addresses:
dbg: [net]   0) 192.168.1.255
dbg: [net]   1) 172.22.255.255
```

On startup (his end):
```
dbg: [net] Starting network
dbg: [net] Loading windows socket library
dbg: [net] Initializing UDP listeners
dbg: [net] Network online, multiplayer available
dbg: [net] Detected broadcast addresses:
dbg: [net]   0) 192.168.5.255
```

(After we did this, my game stopped responding and I'm not sure why, this also happened on his end).

On setting up the server and having him join:
<details>
  <summary>My end</summary>

```
dbg: [net] Starting network
dbg: [net] Loading windows socket library
dbg: [net] Initializing UDP listeners
dbg: [net] Network online, multiplayer available
dbg: [net] Detected broadcast addresses:
dbg: [net]   0) 192.168.1.255
dbg: [net]   1) 172.22.255.255
dbg: [net] 172.22.29.242:3979 resolved in:
dbg: [net] - 172.22.29.242:3979 (IPv4)
dbg: [net] Attempting to connect to 172.22.29.242:3979 (IPv4)
dbg: [net] Timeout while connecting to 172.22.29.242:3979
dbg: [net] Closed UDP listeners
dbg: [net] Initializing UDP listeners
dbg: [net] Closed UDP listeners
dbg: [net] Initializing UDP listeners
dbg: [net] Starting listeners for clients
dbg: [net] Listening on [::]:3979 (IPv6)
dbg: [net] Listening on 0.0.0.0:3979 (IPv4)
dbg: [net] Starting listeners for incoming server queries
dbg: [net] Listening on [::]:3979 (IPv6)
dbg: [net] Listening on 0.0.0.0:3979 (IPv4)
dbg: [net] Network revision name: 12.1
dbg: [net] coordinator.openttd.org:3976 resolved in:
dbg: [net] - 3.127.79.215:3976 (IPv4)
dbg: [net] - 3.64.192.117:3976 (IPv4)
dbg: [net] Attempting to connect to 3.127.79.215:3976 (IPv4)
dbg: [net] Connected to coordinator.openttd.org:3976
dbg: [net] - using 3.127.79.215:3976 (IPv4)
dbg: [net] stun.openttd.org:3975 resolved in:
dbg: [net] - 3.64.192.117:3975 (IPv4)
dbg: [net] stun.openttd.org:3975 did not resolve
dbg: [net] - 3.127.79.215:3975 (IPv4)
dbg: [net] Attempting to connect to 3.64.192.117:3975 (IPv4)
dbg: [net] Connected to stun.openttd.org:3975
dbg: [net] - using 3.64.192.117:3975 (IPv4)
dbg: [net] Game Coordinator registered our server with invite code '+TEFqD2W'
dbg: [net] Sending server update to Game Coordinator
dbg: [net] Sending server update to Game Coordinator
dbg: [net] stun.openttd.org:3975 resolved in:
dbg: [net] stun.openttd.org:3975 did not resolve
dbg: [net] - 3.64.192.117:3975 (IPv4)
dbg: [net] - 3.127.79.215:3975 (IPv4)
dbg: [net] Attempting to connect to 3.64.192.117:3975 (IPv4)
dbg: [net] Connected to stun.openttd.org:3975
dbg: [net] - using 3.64.192.117:3975 (IPv4)
dbg: [net] 31.210.27.208:64783 resolved in:
dbg: [net] - 31.210.27.208:64783 (IPv4)
dbg: [net] Attempting to connect to 31.210.27.208:64783 (IPv4)
dbg: [net] Connected to 31.210.27.208:64783
dbg: [net] - using 31.210.27.208:64783 (IPv4)
dbg: [net] [server] Client connected from 31.210.27.208 on frame 1275
dbg: [net] Client 2 made an error and has been disconnected: general timeout
dbg: [net] [server] Client #2 closed connection
dbg: [net] Sending server update to Game Coordinator
dbg: [net] stun.openttd.org:3975 did not resolve
dbg: [net] stun.openttd.org:3975 resolved in:
dbg: [net] - 3.64.192.117:3975 (IPv4)
dbg: [net] - 3.127.79.215:3975 (IPv4)
dbg: [net] Attempting to connect to 3.64.192.117:3975 (IPv4)
dbg: [net] Connected to stun.openttd.org:3975
dbg: [net] - using 3.64.192.117:3975 (IPv4)
dbg: [net] 31.210.27.208:64798 resolved in:
dbg: [net] - 31.210.27.208:64798 (IPv4)
dbg: [net] Attempting to connect to 31.210.27.208:64798 (IPv4)
dbg: [net] Connected to 31.210.27.208:64798
dbg: [net] - using 31.210.27.208:64798 (IPv4)
dbg: [net] [server] Client connected from 31.210.27.208 on frame 2561
dbg: [net] Client 3 made an error and has been disconnected: general timeout
dbg: [net] [server] Client #3 closed connection
dbg: [net] stun.openttd.org:3975 did not resolve
dbg: [net] stun.openttd.org:3975 resolved in:
dbg: [net] - 3.64.192.117:3975 (IPv4)
dbg: [net] - 3.127.79.215:3975 (IPv4)
dbg: [net] Attempting to connect to 3.64.192.117:3975 (IPv4)
dbg: [net] Connected to stun.openttd.org:3975
dbg: [net] - using 3.64.192.117:3975 (IPv4)
dbg: [net] 31.210.27.208:64801 resolved in:
dbg: [net] - 31.210.27.208:64801 (IPv4)
dbg: [net] Attempting to connect to 31.210.27.208:64801 (IPv4)
dbg: [net] Connected to 31.210.27.208:64801
dbg: [net] - using 31.210.27.208:64801 (IPv4)
dbg: [net] [server] Client connected from 31.210.27.208 on frame 2911
dbg: [net] Client 4 made an error and has been disconnected: general timeout
dbg: [net] [server] Client #4 closed connection
dbg: [net] Sending server update to Game Coordinator
```

</details>

<details>
  <summary>My friend's end</summary>

```
dbg: [net] Starting network
dbg: [net] Loading windows socket library
dbg: [net] Initializing UDP listeners
dbg: [net] Network online, multiplayer available
dbg: [net] Detected broadcast addresses:
dbg: [net]   0) 192.168.5.255
dbg: [net] coordinator.openttd.org:3976 resolved in:
dbg: [net] - 3.64.192.117:3976 (IPv4)
dbg: [net] - 3.127.79.215:3976 (IPv4)
dbg: [net] Attempting to connect to 3.64.192.117:3976 (IPv4)
dbg: [net] Connected to coordinator.openttd.org:3976
dbg: [net] - using 3.64.192.117:3976 (IPv4)
dbg: [net] stun.openttd.org:3975 did not resolve
dbg: [net] stun.openttd.org:3975 resolved in:
dbg: [net] - 3.127.79.215:3975 (IPv4)
dbg: [net] - 3.64.192.117:3975 (IPv4)
dbg: [net] Attempting to connect to 3.127.79.215:3975 (IPv4)
dbg: [net] Connected to stun.openttd.org:3975
dbg: [net] - using 3.127.79.215:3975 (IPv4)
dbg: [net] 86.29.29.179:62725 resolved in:
dbg: [net] - 86.29.29.179:62725 (IPv4)
dbg: [net] Attempting to connect to 86.29.29.179:62725 (IPv4)
dbg: [net] Connected to 86.29.29.179:62725
dbg: [net] - using 86.29.29.179:62725 (IPv4)
dbg: [net] Failed to resolve DNS for zS273FJ:3979
dbg: [net] Network revision name: 12.1
dbg: [net] Closed UDP listeners
dbg: [net] Initializing UDP listeners
dbg: [net] stun.openttd.org:3975 resolved in:
dbg: [net] - 3.127.79.215:3975 (IPv4)
dbg: [net] stun.openttd.org:3975 did not resolve
dbg: [net] - 3.64.192.117:3975 (IPv4)
dbg: [net] Attempting to connect to 3.127.79.215:3975 (IPv4)
dbg: [net] Connected to stun.openttd.org:3975
dbg: [net] - using 3.127.79.215:3975 (IPv4)
dbg: [net] 86.29.29.179:62728 resolved in:
dbg: [net] - 86.29.29.179:62728 (IPv4)
dbg: [net] Attempting to connect to 86.29.29.179:62728 (IPv4)
dbg: [net] Connected to 86.29.29.179:62728
dbg: [net] - using 86.29.29.179:62728 (IPv4)
dbg: [net] Closed client connection 0
```

</details>

I will mention the game was really unstable with the console open and crashed a few times, so it took us a few attempts to get all this. I'm just mentioning that incise it's significant.

His username was: Sten
Mine was: Azophyte

Server was called: MurlocCringe
No password was set
World was default settings, no newgrfs.

I hope this helps! Thanks for taking your time on this.

**Comment by Azophyte** [comment] 2021-12-11 15:45
Small update: we found the 'hardware acceleration' game option. His was turned off for some reason, so we tried turning his on, which didn't work. Tried turning mine off, didn't work either. Just something to note.

Also, I hosted a server with a newGRF installed (Total Bridge Renewal Set 1.2 - Modified for UKRS), and he got the option to downoad it, which he did. I hope that helps narrow down the issue

**Comment by 55TeMeR55** [comment] 2022-02-14 22:50
command in console "max_join_time 9999"

**Comment by Azophyte** [comment] 2022-02-18 11:32
> 

Hi, tried that but it didn't work
![image](https://user-images.githubusercontent.com/89142695/154674689-c8c2722b-2bb8-4bea-96f4-68984471c604.png)
It still says it won't let the user in because it took them longer than 100 ticks to start joining, on his end it still gets stuck authorising then says "can't keep up with the server's computer".

**Comment by James103** [comment] 2022-06-04 21:12
Are you still able to reproduce this in 12.2 or the latest nightly?
If so, try also running the following command line: `set network.max_init_time 2000`, which should give the remote client a full minute to "start the joining process".

**Comment by ExistingProgrammer** [comment] 2022-12-26 01:56
> Are you still able to reproduce this in 12.2 or the latest nightly? If so, try also running the following command line: `set network.max_init_time 2000`, which should give the remote client a full minute to "start the joining process".

Not the author but this issue is happening to us in 12.2 aswell. Game gets stuck in 2/6: Authorizing. I tried increasing the max join time, but then, the connection just gets stuck for more time before dropping. Tried on both mine and my friends computers. Do note that we are using TURN to connect, as both of our servers are behind NAT.

**Comment by squeeglii** [comment] 2023-12-25 14:00
Experiencing this in 13.4 - the host used the Add Server button with a public game. 

They and a friend could join but I couldn't. I tried a full reinstall of the game (configs & all), switching devices, & switching networks. No luck. They tried restarting the server too.

It's weird because I've joined on this device before just fine.

**Comment by TrueBrain** [comment] 2024-01-30 16:54
Been looking at what possible flows can lead up to this.

Basically, if you get stuck on "2/6 Authorizing", and then the server times you out with the error ending on `to start the joining process`, it means a few things:

The server thinks the client is still in state `STATUS_AUTHORIZED`, which is set when the welcome packet is sent. The server is waiting for the client to request the map, and either queues the client or sends them the map.

The client shows "2/6 Authorizing" when it received the welcome packet from the server, and it is requesting the map. If either "you are queued" or the first map packet arrives, the status changes to "3/6 Waiting" or "4/6 Downloading map".

For some reason this breaks down, and then after 100 ticks (~2 seconds) the server says: this took too long, and drops the client.

Now the problem can be in three places:
- The server never received the `GETMAP`.
- The client never received the queue packet or the map.
- The server miscalculates the 100 ticks for one reason or the other, and drops the connection too quickly.

I validated the third, and it seems we are doing all the right things here. Which would mean the issue is actually with the first or second. And that sounds very much like a connectivity issue. This needs a bit more investigation, but without a way to reproduce it, it is very much looking at code in the hope you spot something that could explain this. Being realistic, this doesn't have a very high probability of happening. But who knows .. we keep on looking at least!

**Comment by TrueBrain** [comment] 2024-01-30 19:15
Okay, so if a client joins a server without password and NewGRF, the flow is actually pretty straightforward:

- Client send `CLIENT_JOIN`
- Server receives it, processes it, and sends back a `SERVER_WELCOME`
- Client received `SERVER_WELCOME`, processes it, and sends back a `GETMAP`
- Server receives it, and at this point it cannot be the problem OP is reporting.

So the problem here is between 2 packets, and, more exact, the initial packet. Which makes it really likely it is an issue with the TCP connection itself.

We make use of STUN, which is tricking the router a bit into a state where we can create a bi-directional connection that is not actually there. To be more exact: both parties create an outgoing connection to one of our STUN servers, and then we connect both connections together so to say, and act like they were always connected like that.

Although we probe if the router allows for this behaviour, and 90% of the routers do, it seems it sometimes fails to detect it wouldn't work, causing the above described problem. So I wonder if we can improve the detection on our side, to detect earlier when STUN is not actually going to work, and fall back to TURN (which should always work, unless a firewall is blocking it; but that is a more obvious cause).

The other thing worth of note is that we read that if A connects to B, it fails. But if B connects to A, it works. As both times STUN is used, with the same trick, it seems to indicate it also has to do with who sends the initial packet (the client is always the first one to send a packet).

I can imagine this being the case if one of the two routers has a slightly broken implementation of the standard, which means that if B sends a packet first, A happily accepts it over the STUN connects. But if A sends a packet first, the router on either A or B's side is rather confused and says: this is not right, and drops the packet.

But, as I really lack detailed information, it is just a hunch. What I am going to do for 14.0 is add a tons more debug statement, which can be enabled on-demand, to have someone with this issue try out and report back. That way, we can know for sure what is going on.

As for anyone else reading this thread in a later time: please always attach a `-dnetwork=9` log to your report; without it, it is really not all that useful to say: I have it to! As we don't know what is causing it, we need more information from more people :) But, wait for 14.0, as it will contain a lot more data :)

**Comment by TrueBrain** [comment] 2024-02-02 19:59
Anyone in this topic still experiencing this issue, and has control over both the server and client? I would love to receive a `-dnet=9` from both server and client while this is happening.

Important, this is about 2/6 being stuck. Not about any other issue.

The `-dnet=9` is bulky, so please either upload it as file, or between [summary](https://gist.github.com/scmx/eca72d44afee0113ceb0349dd54a84a2) blocks. Thank you!

**Comment by TrueBrain** [comment] 2024-02-11 20:35
Just a reminder to anyone who might be able to help out. As we are closing in on our next release, now is the ideal moment to help us with debugging information. I do have a potential fix, but I am not willing to apply it until I know it is actually an issue :) Tnx!

**Closed as not planned** 2024-02-26 21:26 UTC
Labels: needs triage
