### ISSUE TITLE
Fast-forward speed limit is stored as 16-bit integer instead of 32 bits.

### ISSUE THREAD

**Issue by James103** [OpenTTD/OpenTTD#8768] opened 2021-02-28 20:12 UTC
## Version of OpenTTD
1.11.0-beta2

## Expected result
Fast-forward speed limit is stored as a 32-bit unsigned integer, allowing for game speeds of several in-game years per second.

## Actual result
Fast-forward speed limit is stored as 16-bit unsigned integer, limiting game speed to 655.35x normal if the fast-forward speed limiter is enabled.

## Steps to reproduce
1. Set fast-forward speed limit to 80355% of normal game speed (1 in-game year per second).
2. Notice that the speed limit is instead set to 14819% of normal game speed (67 in-game days per second).

**Comment by LordAro** [comment] 2021-02-28 20:14
I would be impressed if you could find a computer where you could actually manage 655x speed

**Comment by TrueBrain** [comment] 2021-02-28 20:17
This is fully intended. You can always set it to 0 to go as fast as you can, but having the limit to 655x is already not a useful value to have. Soon there will be a GUI (I hope :P), which limits the speeds to something like 2x/4x/8x/16x/32x .. but not much more. It simply doesn't become useful from that moment on.

If you have a good argument why faster than, say, 128x is useful, I would love to hear. But I am going to close this ticket for now, as we consider this "working as intended" :) Sorry :)

**Closed as completed by TrueBrain** 2021-02-28 20:17 UTC

**Comment by James103** [comment] 2021-02-28 20:18
Map settings:
![image](https://user-images.githubusercontent.com/37945304/109432145-76028580-79cf-11eb-8148-fdfa8caf79a0.png)

OS: Windows 10
CPU: Intel Core i5-9400F @ 2.9 GHz (boosts up to 3.8 GHz)
GPU: Nvidia GTX 1660

Video driver: `win32-opengl` (autodetected)
Blitter: `40bpp-anim` (autodetected)

Test results with given setup:
![image](https://user-images.githubusercontent.com/37945304/109432289-1789d700-79d0-11eb-923b-a1fee5f83813.png)
(Actual game speed is close to or even above 400,000 ticks per second under optimal conditions with the given setup)

**Comment by TrueBrain** [comment] 2021-02-28 20:23
> 
> 
> Map settings:
> ![image](https://user-images.githubusercontent.com/37945304/109432145-76028580-79cf-11eb-8148-fdfa8caf79a0.png)
> 
> OS: Windows 10
> CPU: Intel Core i5-9400F @ 2.9 GHz (boosts up to 3.8 GHz)
> GPU: Nvidia GTX 1660
> 
> Video driver: `win32-opengl` (autodetected)
> Blitter: `40bpp-anim` (autodetected)
> 
> Test results with given setup:
> ![image](https://user-images.githubusercontent.com/37945304/109432289-1789d700-79d0-11eb-923b-a1fee5f83813.png)
> (Actual game speed is close to or even above 400,000 ticks per second under optimal conditions with the given setup)

LOL! I did not know it could get that insane :D Nice :D

**Comment by TrueBrain** [comment] 2021-02-28 20:42
What did strike me odd about your story, that the value overflowed. This was unintended, and fixed with https://github.com/OpenTTD/OpenTTD/pull/8769. If you meant to say that, sorry, I did not pick up on that from this ticket :) you reported a solution, so it was a bit hard to backtrack to a problem :D
