### ISSUE TITLE
Crash when creating a new group

### ISSUE THREAD

**Issue by willem6956** [OpenTTD/OpenTTD#8271] opened 2020-07-13 20:38 UTC
## Version of OpenTTD

1.10.2

## Expected result

No crash when creating a new group

## Actual result

Crash when creating a new group

## Steps to reproduce

Could not reproduce (sorry)

[crash.log](https://github.com/OpenTTD/OpenTTD/files/4914954/crash.log)

[crash.zip](https://github.com/OpenTTD/OpenTTD/files/4914978/crash.zip)

**Comment by James103** [comment] 2020-07-13 20:41
Is this related to #7838?

**Comment by LordAro** [comment] 2020-07-13 20:44
Quite likely, which itself was fixed with #8223. I'll wait for someone to read the dmp and verify though...

**Comment by glx22** [comment] 2020-07-14 14:17
```
>	openttd.exe!VehicleGroupWindow::GroupNameSorter(const Group * const & a, const Group * const & b) Ligne 158	C++
 	[Code externe]	
 	[Cadre en ligne] openttd.exe!std::sort(const std::_Vector_iterator<std::_Vector_val<std::_Simple_types<Group const *>>>) Ligne 4034	C++
 	openttd.exe!GUIList<Group const *,char const *>::Sort(bool(*)(const Group * const &, const Group * const &) compare) Ligne 276	C++
 	openttd.exe!VehicleGroupWindow::BuildGroupList(Owner owner) Ligne 190	C++
 	openttd.exe!VehicleGroupWindow::OnPaint() Ligne 515	C++
 	openttd.exe!DrawOverlappedWindow(Window * w, int left, int top, int right, int bottom) Ligne 949	C++
 	[Cadre en ligne] openttd.exe!DrawOverlappedWindowForAll(int) Ligne 974	C++
 	openttd.exe!RedrawScreenRect(int left, int top, int right, int bottom) Ligne 1432	C++
 	openttd.exe!DrawDirtyBlocks() Ligne 1528	C++
 	openttd.exe!UpdateWindows() Ligne 3204	C++
 	openttd.exe!VideoDriver_Win32::MainLoop() Ligne 1282	C++
 	openttd.exe!openttd_main(int argc, char * * argv) Ligne 861	C++
 	openttd.exe!WinMain(HINSTANCE__ * hInstance, HINSTANCE__ * hPrevInstance, char * lpCmdLine, int nCmdShow) Ligne 442	C++
 	[Code externe]	
```
Same dump as #7838.

**Comment by LordAro** [comment] 2020-07-14 14:21
Thanks glx, closing as duplicate of #7838

**Closed as completed by LordAro** 2020-07-14 14:21 UTC
