### ISSUE TITLE
Wrong vehicle order - picture and name doesn't match actual properties

### ISSUE THREAD

**Issue by Afoklala** [OpenTTD/OpenTTD#7455] opened 2019-04-01 14:59 UTC
## Version of OpenTTD
openttd-20190331-master-gcb449049ff-windows-win64
## Expected result
Cole truck carries cole, paper truck carries paper etc.
## Actual result
Cole truck carries alcohol, paper truck carries food etc.
## Steps to reproduce
See included savegame and screenshots
![Afbeelding1](https://user-images.githubusercontent.com/40867134/55337568-39eedf00-549f-11e9-9866-66ed57caa3cd.jpg)
![Afbeelding2](https://user-images.githubusercontent.com/40867134/55337569-3a877580-549f-11e9-9549-732f2da18750.jpg)
[NL+FIRS, 1969-09-26.zip](https://github.com/OpenTTD/OpenTTD/files/3030046/NL%2BFIRS.1969-09-26.zip)

**Comment by nielsmh** [comment] 2019-04-01 15:17
Was it this way when you started the game, or only after updating your OpenTTD version?

**Comment by nielsmh** [comment] 2019-04-01 15:39
I tried loading the save in a build of the 2019-02-27 revision (adb50cebcc8e2) as well as the 2019-02-19 revision (21d863672295f62a315), both listed in the gamelog, and the issue is present in both revisions. It's most likely caused by NewGRFs not working well together, therefore closing this as not a bug.

I imagine that in particular the ancient "Paper on temperate" and "Cargo set" NewGRFs may be causing problems together with FIRS, but all in all this combination of files looks risky.
![image](https://user-images.githubusercontent.com/1062071/55340447-fdbe7d00-54a4-11e9-8884-13fd26004998.png)

**Closed as completed by nielsmh** 2019-04-01 15:39 UTC
