### ISSUE TITLE
Pathfinder doesn't consider blocked tiles past destination station

### ISSUE THREAD

**Issue by dpk** [OpenTTD/OpenTTD#11506] opened 2023-11-27 22:16 UTC
### Version of OpenTTD

13.4, Mac OS 14.1.1

### Expected result

Train 3 in the save file 
[Stanbourne Transport, 13th Aug 1923.sav.zip](https://github.com/OpenTTD/OpenTTD/files/13481060/Stanbourne.Transport.13th.Aug.1923.sav.zip) should move into one of the free platforms ahead of it, but doesn’t

### Actual result

The train is stuck at a red path signal

### Steps to reproduce

See savegame. No idea what specifically about my ro-ro layout is causing this.

**Comment by glx22** [comment] 2023-11-27 22:20
Usually caused by a "non reachable" red signal exit signal in the same block.

**Comment by JGRennison** [comment] 2023-11-27 22:22
It's the same as this issue: #7941.

Move signals at 484 x 120, 484 x 121 one tile closer to the station so that trains waiting there are still occupying the platform instead of only the signal beyond it.

**Comment by PeterN** [comment] 2023-11-27 22:22
This is path signals not pre-signals. It's because the signal just after the station platform is red, but the platform itself is free.

This means the reserved station penalty is not applied, so the cost of the junction tiles before the station comes into effect.

![image](https://github.com/OpenTTD/OpenTTD/assets/639850/0cbb97e9-ad81-42fb-88c5-a43c85700570)

**Comment by 2TallTyler** [comment] 2023-11-28 14:12
> Move signals at 484 x 120, 484 x 121 one tile closer to the station so that trains waiting there are still occupying the platform instead of only the signal beyond it.

Or move them one tile further away so that they aren't blocking the signal. Block both or neither, it's blocking the signal and not the platform that's the problem here.

This is a legitimate bug, but I am closing this issue as a duplicate of #7941, because duplicate open tickets is confusing. 🙂

**Closed as not planned by 2TallTyler** 2023-11-28 14:12 UTC
Labels: component: pathfinder
