### ISSUE TITLE
Default openttd.cfg world gen settings don't allow Forests in Sub-Arctic

### ISSUE THREAD

**Issue by SamuXarick** [OpenTTD/OpenTTD#7872] opened 2019-12-22 22:57 UTC
## Version of OpenTTD
1.10.0-beta1
## Expected result
Forests are generated

## Actual result
Forests fail to generate

## Steps to reproduce
- Install a fresh OpenTTD
- Run OpenTTD
- Click New game
- Select Sub-Arctic
- Click Generate

I have in mind an easy fix for this, which would be decreasing the default Snowline to height 7 from 15, and change terrain type from Flat to Hilly.
Seems to never fail to generate forests this way. It also slightly improves Sub-Tropic landscape a tiny bit, with more rainforest area, instead of everything being desert.
EDIT: Actually, it's even better than I thought. With Flat terrain, it wasn't generating rivers in Sub-Tropic, but with Hilly, it does!

**Comment by SamuXarick** [comment] 2019-12-22 23:30
Others with same problem: #6448, #6392, #6337, #6072, #6035, #2148, #2128

Perhaps, another idea is making so that when terrain type is set to Flat, Very Flat (or even Hilly, Mountainous…) the snowline height gets automatically adjusted in order to be able to generate those industries.

**Comment by James103** [comment] 2019-12-22 23:48
For an adaptive method, maybe add a flag, which when set (by the user), will adjust the snowline height based on the highest land height used by the map multiplied by a user-configurable percentage. For example: if the adaptive snowline level is set, the snowline height is set to 80%, and world landscape gen ends with a maximum land height of 20, then the snowline height will get set to 16, as that is 20 * 80%.

**Comment by SamuXarick** [comment] 2019-12-23 15:57
Some more findings. Variety distribution is off, map size is 256x256 with water on 4 borders.

TerraGenesis:
- Very Flat terrain type fails to generate both Farms and Forests on Sub-Arctic. The height is not high enough.
- Flat terrain type is sufficient to generate Farms and Forests with a snowline height ranging from 3 to 5.
- Hilly terrain type is sufficient to generate Farms and Forests with a snowline height ranging from 3 to 7.
- Mountainous terrain type is sufficient to generate Farms and Forests with a snowline height ranging from 3 to 13.

Original:
- A snowline height must be a minimum of 4 or else Farms fail to generate, and a maximum of 13, or else Forests fail to generate, which means, ranging from 4 to 13.

**Comment by SamuXarick** [comment] 2019-12-27 21:04
https://github.com/SamuXarick/OpenTTD/commit/0217d1ffb6cfbcb6a936d9b8570601c9dd2c8b3e

This is a patch which auto determines snow line height upon map generation. Since this discards user defined values, Snow Line Height is also removed from World Generation GUI.

In short, it tries to accomodate the snow line to a land mass of 50% snow but also ensures that all industries (namely farms and forests) can be generated on the map, giving them priority.

In general, Very Flat, and to a minor extent, Flat terrain types didn't have the required max height to accomodate Farms and Forests, so in order to have them on the map, these presets are generating higher heights than what's usual on the other landscape (non Sub-Arctic).

**Comment by James103** [comment] 2019-12-27 21:26
@SamuXarick Applying this patch will mean that you will no longer be able to manually set the snowline height on world creation. Is there any way to only activate this patch on a user-defined basis? For example: "Snow line height = Auto" (which can be set by setting "Snow line height" to -1 or 0 (your choice)) will have the game automatically determine the snowline height, but "Snow line height = 10" will put the snow line at tile height 10.

**Comment by sheepo99** [comment] 2019-12-28 21:32
@James103 I'm personally fine with this, given that we don't get the option to pick the desert line in subtropical landscapes either. I favor a nice balance that always allows me to play the game to its fullest (loading all the industries proper in balanced amounts), over having a user-regulated setting that's prone to rendering a map unplayable, which is just bad design, IMO.

**Comment by SamuXarick** [comment] 2019-12-28 23:02
@James103 That can be done, ~~but then there is a problem whenever you want it to always 'auto'. It wouldn't be able to remember that. Unless you add a new setting, a bool "auto_snow_level" on/off, to tell whether to use "snow_line_height" value or auto determine it.~~ Nevermind, it actually remembers, because it's on a different category of settings (_settings_newgame vs _settings_game).

**Comment by TrueBrain** [comment] 2021-01-03 11:30
Duplicate of #6337 (kept the oldest of the duplicates).

**Closed as completed by TrueBrain** 2021-01-03 11:30 UTC
