### ISSUE TITLE
Number of towns is limited if town name generator runs out of names

### ISSUE THREAD

**Issue by Wuzzy2** [OpenTTD/OpenTTD#8634] opened 2021-02-01 17:53 UTC
## Version of OpenTTD
1.9.3

## Steps to reproduce
* Select French town names.
* Start a game with 5000 towns (the allowed maximum) on a flat 4096×4096 map.

## Expected result
5000 French towns.

## Actual result
Only about 70 French towns spawn. There's also no error message at all.

## For comparison
Select English town names instead. You'll get (ca.) 5000 towns. That's a huge difference,

## Analysis
Apparently the French town generator only has 70 possible town names in total. https://www.tt-forums.net/viewtopic.php?f=29&t=88477

## Possible solutions

The goal should be to always guarantee that the full amount of towns can be built and is never limited by the selected town name generator. In other words, it should not matter what town name generator the player chose, you always get the full amount (of course, the towns might still be limited by other things such as map size).

* Update all town name generators to guarantee at least 5,000 unique names
* When the town name generator runs out of names, start to generate fallback names (appending numbers to existing names, etc.), possibly with warning
* When the town name generator runs out of names, fall back to English (which has over 60,000 unique names), possibly with warning

**Comment by LordAro** [comment] 2021-02-01 18:04
Duplicate of #8088

**Closed as completed by LordAro** 2021-02-01 18:04 UTC
