### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by any-text** [OpenTTD/OpenTTD#9082] opened 2021-04-22 19:48 UTC
## Version of OpenTTD
1.11.1

## Expected result
The game crashes right after starting the openttd.exe

## Actual result
*** OpenTTD Crash Report ***

Crash at: Thu Apr 22 19:36:14 2021
In game date: 0-01-01 (0)

Crash reason:
 Exception: C0000005
 Location:  00007FF782DE3820
 Message:   <none>

OpenTTD version:
 Version:    1.11.1 (0)
 NewGRF ver: 1b086d64
 Bits:       64
 Endian:     little
 Dedicated:  no
 Build date: Apr 18 2021 21:16:51

Registers:
 RAX: 0000000000000001 RBX: 000000000000023F RCX: 00000000FF737573 RDX: 0000000000000000
 RSI: 0000004E2DD73A70 RDI: 0000000000000001 RBP: 0000000000000007 RSP: 0000004E2DB5F180
 R8:  0000004E31270040 R9:  0000000000008007 R10: 0000000000000000 R11: 0000004E31270040
 R12: 0000000000000000 R13: 0000000000000000 R14: 0000000000008000 R15: 000000000000023F
 RIP: 00007FF782DE3820 EFLAGS: 00010282

 Bytes at instruction pointer:
 89 0A 48 8D 52 04 FF C8 66 45 89 08 4D 8D 40 02 85 C0 7F EC 44 8B 0D 9D

Stack trace:
 00000000 00000000 00000000 00007FF8 2DB5F2B0 0000004E 80000003 00000000
 00000028 00000000 00000008 00000000 2DD73A70 0000004E 82FAC563 00007FF7
 00000000 00000000 00000001 00000000 2DB5F490 0000004E 00000000 00000000
 98C12D07 00007FF8 00000000 00000000 0000023F 00000000 000003FF 00000000
 00000000 00000000 00000001 00000000 0000018A 00000000 00000000 00000000
 00000000 00000000 83186434 00007FF7 00000000 00007FF8 00000000 00000000
 00000008 0000001F 00000408 0000025F 00000007 00000000 00000000 00000000
 00000005 00000003 00000007 00007FF8 00000000 00000000 00000000 00000000
 32289420 0000004E 00000276 00000000 3176A2B0 0000004E 83189E07 00007FF7
 32289420 0000004E 0000018A 00000000 00000240 00000000 00000000 00000002
 00000006 00000000 00000000 0000001F 00000408 0000025F 00040622 00000000
 00000000 00000000 000003FF 0000023F 7F3BD5DA 000027EB 00000000 00000000
 32289420 0000004E 8318831C 00007FF7 00000000 00000000 3B055827 00002ABF
 00000276 00000000 3176A2B0 0000004E 000000E7 00000000 83187619 00007FF7
 2DB5F490 0000004E 00000001 00000000 00000000 00000000 85A21047 00007FF8
 00000000 00000000 2DD7A960 0000004E 2DB5F498 0000004E 00000001 00000000
 2DB5F498 0000004E 2DB5F438 0000004E 00000158 00000000 8318E27C 00007FF7
 00000002 0000001D 40001E82 00000000 0000E19F 00000000 00000002 0000001D
 2DD7A800 0000004E 00000001 00000001 00000000 00000000 00000000 00000000
 00000240 00000000 00000400 00000000 000000E7 00000000 8318E19A 00007FF7
 32289420 0000004E 0000018A 00000000 00000158 00000000 00000276 00000000
 00000240 0000004E BD011A00 FFFFFFFF 834613C0 00007FF7 00000000 00000000
 00000400 00000000 00000240 00000000 00000400 00000000 8318E34D 00007FF7
 32289420 0000004E 32289420 0000004E 00000000 00000000 00000240 00000000

Operating system:
 Name:     Windows
 Release:  6.3.9600 ()
 Compiler: MSVC 1928

Configuration:
 Blitter:      32bpp-anim
 Graphics set: none (4294967295)
 Language:     C:\Program Files\OpenTTD\lang\english_US.lng
 Music driver: none
 Music set:    none (4294967295)
 Network:      no
 Sound driver: none
 Sound set:    none (4294967295)
 Video driver: win32-opengl

Fonts:
 Small:  Sakkal Majalla
 Medium: Sakkal Majalla
 Large:  Sakkal Majalla
 Mono:   sprite

AI Configuration (local: 0) (current: 0):

Libraries:
 LZMA:       5.2.5
 LZO:        2.10
 PNG:        1.6.37
 Zlib:       1.2.11

Module information:
 C:\Program Files\OpenTTD\openttd.exe handle: 00007FF782CA0000 size: 8553984 crc: 9A796EBF date: 2021-04-18 21:22:06
 C:\WINDOWS\SYSTEM32\ntdll.dll handle: 00007FF89DD30000 size: 1738016 crc: BFF44449 date: 2021-04-01 04:34:28
 C:\WINDOWS\system32\KERNEL32.DLL handle: 00007FF89BC40000 size: 1311776 crc: CC096A46 date: 2021-04-01 04:54:49
 C:\WINDOWS\system32\KERNELBASE.dll handle: 00007FF89B290000 size: 1135696 crc: 972E51AF date: 2020-05-20 15:20:26
 C:\WINDOWS\SYSTEM32\OPENGL32.dll handle: 00007FF8859F0000 size: 1091584 crc: E10509E5 date: 2014-10-29 02:42:10
 C:\WINDOWS\system32\WS2_32.dll handle: 00007FF89B3C0000 size: 363104 crc: 6C5849EE date: 2016-05-14 20:01:15
 C:\WINDOWS\SYSTEM32\WINMM.dll handle: 00007FF897470000 size: 126056 crc: 7659EB7B date: 2014-10-29 03:52:43
 C:\WINDOWS\system32\IMM32.dll handle: 00007FF89DCF0000 size: 210744 crc: 7F26DDC8 date: 2014-10-29 04:00:23
 C:\WINDOWS\system32\USER32.dll handle: 00007FF89B700000 size: 1542696 crc: 90DDB08C date: 2021-01-08 04:49:00
 C:\WINDOWS\system32\GDI32.dll handle: 00007FF89B930000 size: 1377872 crc: 21BEDF1C date: 2021-03-09 09:57:01
 C:\WINDOWS\system32\SHELL32.dll handle: 00007FF89C1C0000 size: 22382424 crc: 6CBC83AD date: 2020-08-20 20:54:41
 C:\WINDOWS\system32\ole32.dll handle: 00007FF89DB20000 size: 1665112 crc: CE6E383C date: 2021-04-01 04:37:07
 C:\WINDOWS\system32\ADVAPI32.dll handle: 00007FF89B880000 size: 685440 crc: AF9D203F date: 2018-01-02 06:37:24
 C:\WINDOWS\SYSTEM32\USP10.dll handle: 00007FF899C10000 size: 77312 crc: BCF4262F date: 2014-10-29 02:48:40
 C:\WINDOWS\system32\msvcrt.dll handle: 00007FF89B650000 size: 687496 crc: AB7BF219 date: 2014-10-29 03:53:30
 C:\WINDOWS\SYSTEM32\GLU32.dll handle: 00007FF894B10000 size: 165888 crc: 2A58BB46 date: 2014-10-29 02:44:35
 C:\WINDOWS\SYSTEM32\DDRAW.dll handle: 00007FF8850A0000 size: 594944 crc: F38B0F9A date: 2014-10-29 01:07:31
 C:\WINDOWS\system32\NSI.dll handle: 00007FF89BBC0000 size: 24800 crc: EA0F476C date: 2014-10-29 03:51:53
 C:\WINDOWS\system32\RPCRT4.dll handle: 00007FF89BA80000 size: 1284488 crc: F082039A date: 2021-04-01 04:33:20
 C:\WINDOWS\SYSTEM32\WINMMBASE.dll handle: 00007FF897500000 size: 161120 crc: 43BDBD7D date: 2014-10-29 03:52:43
 C:\WINDOWS\system32\MSCTF.dll handle: 00007FF89B4F0000 size: 1384648 crc: FDB8CFE6 date: 2020-05-20 15:25:17
 C:\WINDOWS\SYSTEM32\combase.dll handle: 00007FF89BD80000 size: 2174408 crc: 7000DCB4 date: 2021-04-01 04:37:07
 C:\WINDOWS\system32\SHLWAPI.dll handle: 00007FF89DAC0000 size: 339312 crc: 557A1A0C date: 2014-10-29 03:57:40
 C:\WINDOWS\SYSTEM32\sechost.dll handle: 00007FF89BFA0000 size: 357824 crc: 8CDA6A3F date: 2020-06-09 05:05:06
 C:\WINDOWS\SYSTEM32\DCIMAN32.dll handle: 00007FF898BD0000 size: 14848 crc: 99021C7D date: 2014-10-29 02:44:43
 C:\WINDOWS\system32\SspiCli.dll handle: 00007FF89B100000 size: 179248 crc: 46C026A4 date: 2016-08-22 16:06:11
 C:\WINDOWS\SYSTEM32\cfgmgr32.dll handle: 00007FF89B190000 size: 315576 crc: C6A55E14 date: 2014-10-29 04:09:27
 C:\WINDOWS\SYSTEM32\DEVOBJ.dll handle: 00007FF899690000 size: 155456 crc: 027D4AD1 date: 2014-10-29 04:09:23
 C:\WINDOWS\SYSTEM32\SHCORE.dll handle: 00007FF898E10000 size: 723008 crc: 84D104EB date: 2020-06-11 05:03:21
 C:\WINDOWS\system32\uxtheme.dll handle: 00007FF899510000 size: 1191936 crc: 1F395F77 date: 2019-12-17 01:19:30
 C:\WINDOWS\system32\dwmapi.dll handle: 00007FF898C10000 size: 125504 crc: F24873F8 date: 2014-10-29 04:00:24
 C:\WINDOWS\SYSTEM32\ig7icd64.dll handle: 0000000180000000 size: 7885824 crc: 420B2E4C date: 2014-01-23 05:51:44
 C:\WINDOWS\SYSTEM32\igdusc64.dll handle: 00007FF897F70000 size: 4474368 crc: 7FE45937 date: 2014-01-23 05:35:08
 C:\WINDOWS\SYSTEM32\powrprof.dll handle: 00007FF89ADF0000 size: 277368 crc: 7D42587C date: 2014-10-29 04:09:26
 C:\WINDOWS\SYSTEM32\kernel.appcore.dll handle: 00007FF8996E0000 size: 33064 crc: 46564BB7 date: 2014-10-29 04:09:27
 C:\WINDOWS\SYSTEM32\CRYPTBASE.dll handle: 00007FF89ACC0000 size: 31528 crc: 48DECD65 date: 2014-10-29 03:51:52
 C:\WINDOWS\SYSTEM32\bcryptPrimitives.dll handle: 00007FF89AC50000 size: 397224 crc: 7E397873 date: 2018-01-02 07:56:21
 C:\Program Files\ThinkPad\Bluetooth Software\btmmhook.dll handle: 00007FF88B930000 size: 247000 crc: 0C751818 date: 2014-04-01 15:50:48
 C:\WINDOWS\system32\OLEAUT32.dll handle: 00007FF89B420000 size: 805672 crc: 0A43682A date: 2021-01-12 13:27:03
 C:\WINDOWS\system32\PSAPI.DLL handle: 00007FF89D6F0000 size: 17560 crc: 4B24A606 date: 2014-10-29 04:09:24
 C:\WINDOWS\system32\mswsock.dll handle: 00007FF89A690000 size: 339456 crc: EDC7B46F date: 2016-05-13 21:58:54

---- gamelog start ----
---- gamelog end ----

Recent news messages:

*** End of OpenTTD Crash Report ***

Decoded stack trace:
[00] openttd              0x00007FF782DE3820
[01] openttd              0x00007FF782FAC563
[02] openttd              0x00007FF783186434
[03] openttd              0x00007FF783189E07
[04] openttd              0x00007FF78318831C
[05] openttd              0x00007FF783187619
[06] openttd              0x00007FF78318E27C
[07] openttd              0x00007FF78318E19A
[08] openttd              0x00007FF78318E34D
[09] openttd              0x00007FF782FAEFC7
[10] openttd              0x00007FF782FAF130
[11] openttd              0x00007FF783191BFE
[12] openttd              0x00007FF782F2C405
[13] openttd              0x00007FF782F28B9F
[14] openttd              0x00007FF782F414A0
[15] openttd              0x00007FF78306998A
[16] openttd              0x00007FF782EA0CF8
[17] openttd              0x00007FF783207E92
[18] KERNEL32             0x00007FF89BC413F2 BaseThreadInitThunk + 34
[19] ntdll                0x00007FF89DD454F4 RtlUserThreadStart + 52

*** End of additional info ***

## Steps to reproduce

any ideas what i could do?

**Comment by James103** [comment] 2021-04-22 19:52
What happens if you run `openttd -v win32` (suggested option from #9078)?

**Comment by any-text** [comment] 2021-04-22 20:00
https://github.com/OpenTTD/OpenTTD/issues/8969#issuecomment-817143064

this worked for me.

**Comment by LordAro** [comment] 2021-05-03 19:16
Duplicate of #8969. Should be fixed in 1.11.2, released now!

**Closed as completed by LordAro** 2021-05-03 19:16 UTC
