### ISSUE TITLE
[Crash]: 

### ISSUE THREAD

**Issue by tonym0** [OpenTTD/OpenTTD#11171] opened 2023-08-09 05:46 UTC
### Version of OpenTTD

13.3 (0), Windows 10

### Steps to reproduce

Played game until 2019, clicked railway construction icon. It popped up the menu and then crashed.

### Upload crash files

[OpenTTDCrash.zip](https://github.com/OpenTTD/OpenTTD/files/12298713/OpenTTDCrash.zip)

**Comment by James103** [comment] 2023-08-09 05:51
Please update to version 13.4 or later before continuing; the bug is already fixed.

**Comment by 2TallTyler** [comment] 2023-08-09 13:22
Duplicate of #11043 and fixed in 13.4. 😃

**Closed as completed by 2TallTyler** 2023-08-09 13:22 UTC
