### ISSUE TITLE
[Crash]: Placing signal on a train station and then crashed

### ISSUE THREAD

**Issue by joaojesus81** [OpenTTD/OpenTTD#11990] opened 2024-02-04 20:20 UTC
### Version of OpenTTD

14.0-beta1, Windows 10

### Steps to reproduce

1. Select a railway signal
2. Click on a station instead of a line

### Upload crash files

[OpenTTD.zip](https://github.com/OpenTTD/OpenTTD/files/14158373/OpenTTD.zip)

**Comment by LordAro** [comment] 2024-02-04 22:04
Duplicate of #11982 , fixed by #11977

**Closed as not planned by LordAro** 2024-02-04 22:04 UTC
