### ISSUE TITLE
Chinese(simplified) can not be shown correctly

### ISSUE THREAD

**Issue by clzls** [OpenTTD/OpenTTD#7567] opened 2019-05-04 15:52 UTC
## Version of OpenTTD
openttd-1.9.1-windows-win64
Note: 20190503-master-g6f33cfd059 has the same problem.

## Expected result
Readable Chinese in my previous 1.8.0 version.
![image](https://user-images.githubusercontent.com/16474386/57181332-d6543900-6ec4-11e9-9ce5-9522c8e60d9a.png)

## Actual result
This awful unreadable UI and everything. Even 'OpenTTD' above is ruined. (shifted by 3 in ASCII code?)
![UnreadablePage](https://user-images.githubusercontent.com/16474386/57181312-91c89d80-6ec4-11e9-9af1-8747a0dca2f7.png)

## Steps to reproduce
Just change language to Chinese(Simplified). Note that Chinese(Traditional) is working properly.

**Comment by kiwitreekor** [comment] 2019-05-04 16:31
Isn't this duplicate of #7511?

**Comment by nielsmh** [comment] 2019-05-04 18:48
Yes, duplicate of #7511 
Based on that report, the issue might be related to the Windows ANSI codepage setting.

**Closed as completed by nielsmh** 2019-05-04 18:48 UTC

**Comment by clzls** [comment] 2019-05-05 12:17
> Yes, duplicate of #7511
> Based on that report, the issue might be related to the Windows ANSI codepage setting.

Because both Chinese(traditional) and Japanese are readable in 1.9.1, I did not figure it was about CJK characters and codepage settings...
