### ISSUE TITLE
Out of memory error in AI's ::Save() corrupts the emergency save.

### ISSUE THREAD

**Issue by James103** [OpenTTD/OpenTTD#7862] opened 2019-12-17 21:28 UTC
## Version of OpenTTD
2019-12-07 master (win7 32-bit)

## Expected result
When an AI triggers an out of memory error when the game is saved, the emergency save is successful. When the emergency save is loaded, the AI that triggered the out of memory error is reloaded without saved data (as if a different AI was loaded in its place).

## Actual result
When an AI triggers an out of memory error when the game is saved, the emergency save triggers the same out of memory error. The emergency save is empty.

## Steps to reproduce
1. Put the following code in an AI (or Game Script):
```
function AIController::Save() {
	array(1e9);
}
```
2. Run the AI with the above code.
3. The game will crash with an Out of Memory error.
4. Attempt an emergency save.
5. The game will crash again with the same Out of Memory error.
6. Check the emergency save. The file is empty (size: 0 bytes).

**Comment by LordAro** [comment] 2019-12-28 17:24
Duplicate of #7641 
The result is a little different, as now the game is crashing while trying to write the crash data...

**Closed as completed by LordAro** 2019-12-28 17:24 UTC
