### ISSUE TITLE
inflation setting incorrectly affects starting loan and vehicle costs

### ISSUE THREAD

**Issue by 0xBEEF7AC0** [OpenTTD/OpenTTD#9083] opened 2021-04-22 21:35 UTC
## Version of OpenTTD

1.11.1

--downloaded content-- 
AI : Admiral AI, trAIns
AILibrary : Queue.FibonacciHeap (version 2)

--resources-
ttdx DOS graphics
ttdx DOS audio
ttdx Windows music

## Expected result

inflation : enabled
A. player should start with the maximum loan amount
B. vehicles should start at their "base" cost (year : 1950)

## Actual result

inflation : enabled
A. player can start with more than maximum loan amount
B. vehicles cost multiple times more than "base" cost (year : 1950)

## Scenario 1

settings:

  - currency unit : USD
  - inflation : enabled
  - interest rate : 4%
  - maximum loan : $200,000

expected :

  - maximum loan is $200,000
  - player starts with $200,000 loan
 
actual :

  - maximum loan is $600,000
  - player starts with $600,000 loan

## Scenario 2

settings:

 - currency unit : USD
 - inflation : enabled
 - interest rate : 4%
 - maximum loan : $75,000

expected : 

  - assuming max loan amount hard coded to $100,000 intervals
  - assuming max loan amount cannot be $0
  - the maximum loan should be $100000
  - the player should start with $100000

actual :

  - maximum loan is $200,000
  - player starts with a $600,000 loan (yes, above the maximum)

## Scenario 3

settings:

 - currency unit : USD
 - inflation : enabled
 - interest rate : 4%
 - maximum loan : $75,000

expected :

 - MPS Regal Bus costs $14,764 at start of new game

actual :

 - MPS Regal Bus costs $48,196 at start of new game

**Comment by James103** [comment] 2021-04-23 09:11
Caused by #7589

**Comment by 2TallTyler** [comment] 2022-10-19 15:02
This is a duplicate of #8932, and a solution is proposed there, so I'll close this one.

**Closed as completed by 2TallTyler** 2022-10-19 15:02 UTC
