### ISSUE TITLE
[UI] Online players window's button size is not updated when resizing to double/quad interface size

### ISSUE THREAD

**Issue by telk5093** [OpenTTD/OpenTTD#9363] opened 2021-06-13 05:29 UTC
## Version of OpenTTD
20210612-master-g8dd846bad4

## Expected result
Buttons are resized properly

## Actual result
![image](https://user-images.githubusercontent.com/10726524/121796371-73acfa00-cc53-11eb-94f6-64ee810254d1.png)

## Steps to reproduce
1. ``set zoom_min 0``
2. Set Interface size as Double or Quad size
3. Open Online players window

**Comment by TrueBrain** [comment] 2021-06-16 18:56
Works for me in the steps you mention to reproduce.

The thing that does break, is when you change the Interface size while you have the Online players windows open. In that case the buttons are not recalculated in size. Closing and opening the GUI does fix that problem (at least, for me it does).

Am I correct in that this is the case for you too?

**Comment by telk5093** [comment] 2021-06-17 00:44
Yes, you're right. Re-opening the window resizes the buttons for me, too.

**Closed as completed** 2022-08-30 12:56 UTC
Labels: bug, priority: low
