### ISSUE TITLE
[Bug]: Transfer Credits not accruing

### ISSUE THREAD

**Issue by Bonehead-101** [OpenTTD/OpenTTD#12223] opened 2024-03-05 17:27 UTC
### Version of OpenTTD

13.4

### Expected result

I expected my transfer credits to accrue.

### Actual result

Transfer credits were not being added to my total balance.

### Steps to reproduce

[no transfer credit.zip](https://github.com/OpenTTD/OpenTTD/files/14499086/no.transfer.credit.zip)  Attached is the save game I noticed the issue. 
I was creating a transfer run from my goods inland to a ferry terminal, and then sending the ferry to transfer to another dock and ship the goods from that dock to the required location.

**Comment by 2TallTyler** [comment] 2024-03-05 17:54
If I'm understanding you correctly, this is intended behavior. Transfer Credits are virtual and exist only so that vehicles in a multi-step delivery don't get marked as unprofitable. 

You still only get paid when the cargo is delivered to its final destination (industry, house, or company HQ).

**Comment by Bonehead-101** [comment] 2024-03-05 17:58
I did not know that thank you for letting me know. You may disregard this issue

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Closed as completed** 2024-03-05 18:01 UTC
