### ISSUE TITLE
Crash while 'search internet in multiplayer'

### ISSUE THREAD

**Issue by saveinthesky** [OpenTTD/OpenTTD#8844] opened 2021-03-11 11:24 UTC
## Expected result
search internet for multiplayer

## Actual result
Crash and quit

## Steps to reproduce
Open multiplayer , click 'search internet'

My pc is a mac osx Sierra 10.12.6

[crash.log](https://github.com/OpenTTD/OpenTTD/files/6122596/crash.log)
![crash](https://user-images.githubusercontent.com/77020351/110780123-a2868f00-8264-11eb-960b-4bcdf18017e1.png)

**Comment by TrueBrain** [comment] 2021-03-11 11:25
Duplicate of #8799 / #8807 and already fixed in latest nightly.

**Closed as completed by TrueBrain** 2021-03-11 11:25 UTC

**Comment by saveinthesky** [comment] 2021-03-11 13:45
Oh Sorry i didn't saw, thank you

Il gio 11 mar 2021, 12:25 Patric Stout ***@***.***> ha
scritto:
