### ISSUE TITLE
[Crash]: 

### ISSUE THREAD

**Issue by KLZBLZ** [OpenTTD/OpenTTD#10080] opened 2022-10-13 12:21 UTC
### Version of OpenTTD

12.2 Beta

### Steps to reproduce

1. Open Steam
2. Click Launch game

I tried with different versions.

### Upload crash files

[Archive.zip](https://github.com/OpenTTD/OpenTTD/files/9776517/Archive.zip)

**Comment by PeterN** [comment] 2022-10-13 12:28
Can you please try with the nightly release (this can be chosen from within Steam on a Betas tab of the game properties.)

The crash may still occur, but it should provide better debugging information.

**Comment by KLZBLZ** [comment] 2022-10-13 12:33
Sure, here you go:


[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
13/10/22,
13:32:24

**Comment by KLZBLZ** [comment] 2022-10-13 12:43
[Archive 2.zip](https://github.com/OpenTTD/OpenTTD/files/9776739/Archive.2.zip)

**Comment by PeterN** [comment] 2022-10-13 12:46
Thanks for that. This is a duplicate of #9876.

**Comment by KLZBLZ** [comment] 2022-10-13 12:53
Thanks!

**Comment by LordAro** [comment] 2022-10-13 13:09
Duplicate!

**Closed as not planned by LordAro** 2022-10-13 13:09 UTC
