### ISSUE TITLE
OpenTTD Crash

### ISSUE THREAD

**Issue by bazzlewazzle** [OpenTTD/OpenTTD#8148] opened 2020-05-14 16:08 UTC
[crash.log](https://github.com/OpenTTD/OpenTTD/files/4629552/crash.log)

**Comment by nielsmh** [comment] 2020-05-14 16:11
Most likely a duplicate of #8066 since the crash log indicates macOS 10.12.6 and there is a known crash bug on startup on macOS versions earlier than 10.13.

If this is not a crash on start of the game please provide more information.

**Closed as completed by nielsmh** 2020-05-14 16:11 UTC

**Comment by bazzlewazzle** [comment] 2020-05-14 16:18
It sounds the same but I've read that thread and I don't see how to solve
the problem. Is there a way?

Barry

**Comment by nielsmh** [comment] 2020-05-14 16:20
Current known workarounds:
- Upgrade to macOS 10.13 or newer
- Play OpenTTD 1.10.0-RC1 or earlier

**Comment by bazzlewazzle** [comment] 2020-05-14 16:24
Thanks, where do I find an older version? I had a look for the archives
but couldn't find it.

Barry

**Comment by nielsmh** [comment] 2020-05-14 16:25
It's linked in the #8066 discussion too: https://cdn.openttd.org/openttd-releases/1.10.0-RC1/
