### ISSUE TITLE
New clients can't join (desync) after funding an industry

### ISSUE THREAD

**Issue by ldpl** [OpenTTD/OpenTTD#8137] opened 2020-05-11 12:26 UTC
## Version of OpenTTD
39092ee13b44573d1b8111a5d2ee1d46990f239f and 1.10.1

## Expected result
No desync

## Actual result
Connected clients stay, new clients desync almost instantly.

## Steps to reproduce
Fund a coal mine as shown on the screenshot and start taking coal from the station.
![Screenshot from 2020-05-11 15-18-05](https://user-images.githubusercontent.com/413570/81561329-b68b0700-939b-11ea-8e62-fef87a19a203.png)

**Comment by SamuXarick** [comment] 2020-05-11 12:57
According to the new coverage rule changes, coal shouldn't be moving to the station, but it is. :(

**Comment by JGRennison** [comment] 2020-05-11 16:05
I did some quick testing on my own patchpack but was not able to reproduce this. Looking back I'd already made a change to address this here: https://github.com/JGRennison/OpenTTD-patches/commit/92c48d6897b05132e39764cab80b4c1adaa8b7f8, reverting this change causes the desync behaviour above and output from CheckCaches.

If this general approach is acceptable I can turn it into a PR.

**Closed as completed** 2020-05-13 07:43 UTC
