### ISSUE TITLE
Build failture in Slackware 14.2

### ISSUE THREAD

**Issue by rammfire** [OpenTTD/OpenTTD#6855] opened 2018-07-19 09:34 UTC
I'm try to build this game from source, version 1.8.0.
Build stop with error
```
openttd-1.8.0/src/language.h:108:8: error: ‘Collator’ does not name a type; did you mean ‘UCollator’?
 extern Collator *_current_collator;
        ^~~~~~~~
        UCollator
[SRC] Compiling driver.cpp
make[1]: *** [Makefile:235: crashlog.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/home/denis/bfold/openttd/openttd-1.8.0/objs/release'
make: *** [Makefile:56: all] Error 1
```

**Comment by LordAro** [comment] 2018-07-19 11:18
Duplicate of #6690 - already fixed in master, upgrade your source checkout or compile without ICU

**Closed as completed by LordAro** 2018-07-19 11:18 UTC
