### ISSUE TITLE
Crash in kdtree.hpp when removing track in development version

### ISSUE THREAD

**Issue by Gymnasiast** [OpenTTD/OpenTTD#7530] opened 2019-04-20 16:07 UTC
OS: Ubuntu 19.04, AMD64.
OpenTTD version: 20190402-master-gcebdd72146

The mentioned OpenTTD version has crashed twice on me. As far as I can remember I was removing track on both occasions. The crashes also happened within 15 tiles from each other.

**EDIT**: The crash also happens when just load my save and do nothing.

Crash.log, crash.sav and crash.png are here:

[crash.zip](https://github.com/OpenTTD/OpenTTD/files/3100330/crash.zip)

![crash](https://user-images.githubusercontent.com/1478678/56459662-e03f4d80-6396-11e9-8d18-1143f0f58c91.png)

**Comment by Wormnest** [comment] 2019-04-24 18:56
I got a crash that sounds similar.
Assertion failed at line 213 of d:\a\1\s\src\core\kdtree.hpp: next != INVALID_NODE

The log of WormAI shows that the last thing it was doing was removing a route.

**Comment by nielsmh** [comment] 2019-04-25 20:19
When you say the crash happens just loading your save, is that the crash.sav you attached, or an earlier save? I don't reproduce the crash loading crash.sav.

**Comment by Gymnasiast** [comment] 2019-04-25 21:03
My earlier save. I'll upload it as soon as possible (tomorrow evening hopefully).

**Comment by Gymnasiast** [comment] 2019-04-26 18:12
As promised, my save. Loading it up (and unpausing it) makes it crash within five seconds for me.

[British Rail, 14 Sep 2011-1.9+.zip](https://github.com/OpenTTD/OpenTTD/files/3122517/British.Rail.14.Sep.2011-1.9%2B.zip)

**Comment by nielsmh** [comment] 2019-04-26 18:44
Yep it's caused by a station sign having moved since it was last updated in the kdtree, same as #7481 is about. The cause is not you removing track, but rather an oil rig closing down and its station being deleted.
Closing this ticket to avoid tracking the same issue with two numbers.

It's very useful having a savegame that will consistently trigger the bug, so thank you for providing that.

**Closed as completed by nielsmh** 2019-04-26 18:44 UTC
