### ISSUE TITLE
Road vehicle pathing cache does not always pick up changes in road network

### ISSUE THREAD

**Issue by SamuXarick** [OpenTTD/OpenTTD#7670] opened 2019-07-27 17:41 UTC
## Version of OpenTTD
Custom one based on 20190722, https://github.com/SamuXarick/OpenTTD/tree/SamuPatchPackRebase
## Expected result
YAPF should have a lower average ms than NPF
## Actual result
YAPF has a higher average ms time than NPF
## Steps to reproduce
Load savegame and open framerate window, then switch to NPF and notice the difference.

[road vehicle ticks.zip](https://github.com/OpenTTD/OpenTTD/files/3438432/road.vehicle.ticks.zip)

YAPF: ~135 ms
NPF: ~35 ms

This system has windows 7, 4GB RAM, Celeron E1400, 2 cores @ 2.00 GHz

**Comment by SamuXarick** [comment] 2019-07-27 17:59
[18:52] <Samu> looks like the company affected is that of Terron
[18:52] <Samu> Company 4 killed and ms went all the way down to 16 ms

**Comment by LordAro** [comment] 2019-07-27 17:59
First off, do not submit issues relating to custom versions of OTTD, they are unsupported, especially when they contain a savegame bump and the provided save cannot be loaded in unmodified OTTD

Second, while 35ms vs 135ms is a big change, "YAPF is slower than NPF" is not an issue in itself - YAPF is designed to be "better" than NPF, but that does not necessarily mean "faster".

I'll give you... let's say a day to submit an actual reproducing savegame that I can actually load in master.

**Comment by James103** [comment] 2019-07-27 20:29
Here are my tests for [Wentbourne](https://fuzzle.org/~petern/ottd/wentbourne.sav) savegame. The test was ran in 20190723-master-g2e686ad5d5-windows-win32 using an Intel(R) Core(TM)2 Duo CPU T5800 @ 2.00GHz and 3 GB of RAM. Times are in milliseconds per tick (mspt).

| Category  | YAPF time | NPF time  |
| --------- | --------- | --------- |
| Trains    | 250±10 ms | 265±10 ms |
| Road vehs | 70±5 ms   | 140±10 ms |
| Ships     | 19±1 ms   | 600±50 ms |

Edit: added link to save game

**Comment by MingweiSamuel** [comment] 2019-07-28 02:47
> Category 	YAPF time 	NPF time
> Road vehs 	70±5 ms 	140±10 ms

Looks like YAPF is better than NPF on vanilla? So this may be an issue with your patch pack.

If thats a typo then you should provide the .sav as well to see if others can reproduce.

**Comment by SamuXarick** [comment] 2019-07-28 10:01
from irc: https://webster.openttdcoop.org/index.php?channel=openttd&date=1564185600#1564261315

The problem seems to be very specific to unconnected roads that I assume were connected at first. AI detected road vehicles crash there, and so it removed the roads, probably attempting to build a bridge over it.

I really doubt my custom build has any influence in that, with like 99.9% certainty. It's a build that reworks AI GUI windows and AI max ops. It doesn't touch anything related to YAPF or NPF nor any commands. of that nature.
![Hercules, 1982-11-10](https://user-images.githubusercontent.com/43006711/62005241-4cfd7d00-b128-11e9-9040-903e869523da.png)

**Comment by SamuXarick** [comment] 2019-07-28 10:46
Before connecting the roads, ~160 ms:
![screenshot#1](https://user-images.githubusercontent.com/43006711/62005579-3ad20d80-b12d-11e9-8810-de4954c1ab67.png)

After connecting the roads, ~17 ms:
![Hercules, 1982-06-22](https://user-images.githubusercontent.com/43006711/62005581-3e659480-b12d-11e9-9782-f76391c1fc0e.png)

**Comment by SamuXarick** [comment] 2019-07-28 12:33
I stopped all vehicles in the game (~about 5000 road vehicles), except one, and found where the problem occurs.
I let vehicle 368 to move around that area, until it reached that exact location, moving at 0 km/s. It has at least 2 or more vehicles ahead of it, (36 and 115) stopped, blocking access to the presumably last tile it can walk to before turning back.
![Hercules, 1983-03-22](https://user-images.githubusercontent.com/43006711/62006626-0bc29880-b13b-11e9-9b9c-e521afaf814b.png)

 During the time it is "moving" at 0 km/s, the pathfinder is being constantly called every tick:
dbg: [yapf] [YAPFr]! 368- 37672 us - 10001 rounds - 63 open - 10000 closed - CHR
  0.0% - C -1 D -1 - c0(sc0, ts0, o0) --
dbg: [yapf] [YAPFr]! 368- 34459 us - 10001 rounds - 63 open - 10000 closed - CHR
  0.0% - C -1 D -1 - c0(sc0, ts0, o0) --
dbg: [yapf] [YAPFr]! 368- 42715 us - 10001 rounds - 63 open - 10000 closed - CHR
  0.0% - C -1 D -1 - c0(sc0, ts0, o0) --
dbg: [yapf] [YAPFr]! 368- 33536 us - 10001 rounds - 63 open - 10000 closed - CHR
  0.0% - C -1 D -1 - c0(sc0, ts0, o0) --
dbg: [yapf] [YAPFr]! 368- 39387 us - 10001 rounds - 63 open - 10000 closed - CHR
  0.0% - C -1 D -1 - c0(sc0, ts0, o0) --
dbg: [yapf] [YAPFr]! 368- 34812 us - 10001 rounds - 63 open - 10000 closed - CHR
  0.0% - C -1 D -1 - c0(sc0, ts0, o0) --
dbg: [yapf] [YAPFr]! 368- 35434 us - 10001 rounds - 63 open - 10000 closed - CHR
  0.0% - C -1 D -1 - c0(sc0, ts0, o0) --
dbg: [yapf] [YAPFr]! 368- 35560 us - 10001 rounds - 63 open - 10000 closed - CHR
  0.0% - C -1 D -1 - c0(sc0, ts0, o0) --
dbg: [yapf] [YAPFr]! 368- 34105 us - 10001 rounds - 63 open - 10000 closed - CHR
  0.0% - C -1 D -1 - c0(sc0, ts0, o0) --
dbg: [yapf] [YAPFr]! 368- 46388 us - 10001 rounds - 63 open - 10000 closed - CHR
  0.0% - C -1 D -1 - c0(sc0, ts0, o0) --
dbg: [yapf] [YAPFr]! 368- 33735 us - 10001 rounds - 63 open - 10000 closed - CHR
  0.0% - C -1 D -1 - c0(sc0, ts0, o0) --
dbg: [yapf] [YAPFr]! 368- 38073 us - 10001 rounds - 63 open - 10000 closed - CHR
  0.0% - C -1 D -1 - c0(sc0, ts0, o0) --

After a few days, vehicle 368 finally moves on to the tile ahead, walking through the two vehicles ahead. When it does this, no more pathfinder calls are done, until it reaches the end of the entered tile, calling it again, but only once, then walking back and away towards the northwest of the road, until it eventually comes back again to this same situation.

The reason the spike is so noticeable is due to the road network the vehicle is in being so large, a congregation of multiple AIs connected roads, augmented by the constant calls to the pathfinder every tick.

**Comment by SamuXarick** [comment] 2019-07-28 15:25
new savegame, reproduced the scenario.
OpenTTD 20190723-g2e686ad5d5
[Henfingburg Transport, 1951-03-15.zip](https://github.com/OpenTTD/OpenTTD/files/3439310/Henfingburg.Transport.1951-03-15.zip)

**Comment by SamuXarick** [comment] 2019-11-02 23:00
a better savegame, based on the previous one, but only requiring 2 vehicles to trigger the issue, with a giant road network.

[2 vehicles only.zip](https://github.com/OpenTTD/OpenTTD/files/3801034/2.vehicles.only.zip)

**Comment by SamuXarick** [comment] 2019-11-02 23:13
The problem is the combination of line 1381 and 1398 in roadveh_cmd.cpp. At 1381 it calls the pathfinder, and at 1398 the vehicle finds itself blocked, so there's no update to the vehicle position on the current tick.
Next tick it repeats again, constantly doing this until front->blocked_ctr times out.

https://github.com/OpenTTD/OpenTTD/blob/460f73cd2d615e39079950a92956e81cbd42baea/src/roadveh_cmd.cpp#L1381

https://github.com/OpenTTD/OpenTTD/blob/460f73cd2d615e39079950a92956e81cbd42baea/src/roadveh_cmd.cpp#L1398

The issue is also happening with NPF, not just YAPF. NPF is just less cpu intensive about it, but still noticeable.

**Comment by nielsmh** [comment] 2020-02-09 17:32
Fixing this (at least as suggested in #7822) requires bumping the savegame version, will that prevent it from being fixed in 1.10 now that it has branched?

**Closed as completed** 2021-01-14 17:41 UTC

**Comment by JGRennison** [comment] 2021-03-06 18:36
Looking at the attached savegame (road vehicle ticks.zip), all the pf settings have totally incorrect values.
In the past, some users cargoculted the idea that the settings should all be set to the extreme range of their settings to improve pathfinding. However this creates many strange pathfinding bugs and doesn't actually improve anything.
Probably the pathfinder penalty settings should be removed entirely.

See also: https://github.com/JGRennison/OpenTTD-patches/commit/bb363695fc3abc59d42733071ea1ce3f1b842bba
