### ISSUE TITLE
UI elements (incl. news message) do not resize properly on font size change, causing graphical glitches

### ISSUE THREAD

**Issue by James103** [OpenTTD/OpenTTD#8099] opened 2020-04-26 08:46 UTC
## Version of OpenTTD
OpenTTD: 1.10.0 and 20200426-master
Windows 10
Font: MS Gothic + spritefont

## Expected result
News message resizes properly in response to the changed font.

## Actual result
News message does not resize properly, causing graphical glitches similar to #6527
![image](https://user-images.githubusercontent.com/37945304/80302470-e0271a00-876f-11ea-82b7-4d1c04b3ecec.png)

## Steps to reproduce
1. Install the MS Gothic font (if it didn't already come with Windows 10).
2. Open the title game as a savegame (execute console commands `save a` and `load a` from the main menu).
3. Make sure that vehicle notifications are turned on.
4. Switch language to Japanese.
5. Wait until a news message pops up.
6. Switch language to English.
7. Notice the graphical glitches.

**Comment by nielsmh** [comment] 2020-04-26 11:54
Am I understanding right that this only applies to windows that are already open while the font is changed?
If that's the case, my proposed fix would be to close all open windows (regardless of sticky or not) when the font changes.

**Comment by James103** [comment] 2020-05-01 10:45
I agree with you, @nielsmh. Newly opened news message windows after a font change look normal, but existing news message windows break on a font change. I can reproduce this in master as well.
(Note that this really only breaks news windows.)

**Comment by glx22** [comment] 2020-05-01 13:59
On language change (and many other cases), all windows are re-initialized. I tried to reproduce, but I failed.

**Comment by TrueBrain** [comment] 2021-02-27 13:23
I too could not reproduce this issue with latest master. Can you still reproduce it @James103 ?

**Comment by TrueBrain** [comment] 2021-02-27 13:26
Okay, with some more toying around, I can trigger it .. but not by going to English. I had to go to Greek, for example.

**Comment by James103** [comment] 2021-02-27 13:35
* What OS were you running?
* Which font did OpenTTD use for Japanese?
* Which font did OpenTTD use for Greek?
* What video driver were you using?

**Comment by TrueBrain** [comment] 2021-02-27 13:36
I was doing exactly what you told in the topic :) So all these questions are answered there :D

Important part is that I can reproduce it, and I am sure others can too with this information :)

**Comment by James103** [comment] 2021-02-27 13:40
Also note that by having a news window open and switching from English to Japanese (smaller font to bigger font), it pushes the news window viewport above where it is supposed to go and not below. See images:

| Smaller font to larger font | Larger font to smaller font |
| --- | --- |
| e.g. English to Greek | Japanese to Dutch |
| ![image](https://user-images.githubusercontent.com/37945304/109388776-c219d100-78ce-11eb-9ae2-56973e945d98.png) | ![image](https://user-images.githubusercontent.com/37945304/109388797-ef667f00-78ce-11eb-9824-0abb6112847b.png) |

Can also reproduce the same results by not changing the language, but instead changing the "Font size" in Game Options.
* Set Font Size to Normal, bring up the news message, then set Font Size to Double to reproduce like in the first image.
* Set Font Size to Double, bring up the news message, then set Font Size to Normal to reproduce like in the second image.

Hypothesis (backed by above evidence): Font size changes aren't properly handled in the news windows.

**Comment by James103** [comment] 2022-08-20 20:51
This is still an issue on 88a046a7 as described above.

**Comment by PeterN** [comment] 2022-10-21 13:46
Fixed by #10005 .

**Closed as completed by PeterN** 2022-10-21 13:46 UTC
Labels: needs triage
