### ISSUE TITLE
[Bug]: spritecache excessive size

### ISSUE THREAD

**Issue by tamlin-mike** [OpenTTD/OpenTTD#11488] opened 2023-11-24 06:20 UTC
### Version of OpenTTD

1.13.4-64, Win10-64

### Expected result

A reasonable amount of sprite cache being allocated.

### Actual result

768 MB (8.05*10^6 bytes) of spritecache is allocated on startup.

Three quarter of a gigabyte. For OpenTTD's default tileset.

On entry of `GfxInitSpriteCache`, `_sprite_cache_size` is 128, which while quite excessive already (considering the default is still claimed in the code to be 4MB), this value is quadrupled by running on a 32bpp display.

`IniLoadSettings` updates it to 128. Since I have not modified anything, I didn't bother digging deeper into it than setting a data breakpoint and find where it was modified from.

Assuming a normal (by todays standards) 32bpp output device;

1. The comment for `_sprite_cache_size` in spritecache.cpp claims it's number of MB, which it's clearly not. It's mega _pixels_. Well, it's 66% of the megapixels actually allocated.
2. In `GfxInitSpriteCache()`, `_allocated_sprite_cache_size` (and a few local variables holding the same value) are all uint. Should `_sprite_cache_size` ever be > 512, the code would overflow `target_size` and therefore `_allocated_sprite_cache_size`.
4. Actually, since the code is growing it by _another_ 50%, it would cause meltdown with `_sprite_cache_size` >= 342, I think.

### Steps to reproduce

1. Run openttd.exe.
2. Done.

**Comment by TrueBrain** [comment] 2023-11-24 08:12
We are a bit puzzled .. what is the actual problem you found here? Why is the default not "reasonable"? By which standard is that measured?
The tone of your whole post reads very passive aggressive, like we made the worst sin possible, but I fail to see what we actually did wrong :) So I will classify it as a language barrier :) But please do help us out understanding what you actually find troubling.

Anyway, to answer your questions:

1. The `_sprite_cache_size` comment is written in a time of 8bpp. With 32bpp, it is no longer true. But it is also not in mega pixels. It is in the amount of bytes a pixel consumes. So Mega Pixels Bytes? MPB! Anyway, this means it is 1/8th of the amount of pixels, not 66% :) Or, if you add the extra 50% we might allocate: 1/8th + 1/16th = 3/16th of the amount of pixels. So yeah, the comment in the code is not correct; this could be fixed.
2. The overflow happens on 1024, not 512. `512 * 32 / 8 * 1024 * 1024` is `2**31`, which ofc fits easily in `2**32`. The issue is on multiplier of two higher. And by no accident, you cannot set `_sprite_cache_size` higher than 512. So this overflow is, without modifying of the code, not possible. If I got my math wrong, let me know!
3. Now we know the maximum of the setting is 512, we can also see that with the extra 50% it still fits: `512 * 1.5 = 768`, which fits in `1024`. Or more explicit: `512 * 32 / 8 * 1024 * 1024 * 1.5 < 2**32`.

Anyway, curious why you think 768MB is not reasonable, and what you expected there :) Tnx!

**Comment by tamlin-mike** [comment] 2023-11-24 15:05
> what is the actual problem you found here? 

Allocation of 768 MB instead of 16 MB (or however much is really required).

> The tone of your whole post reads very passive aggressive

That was never my intent, rather to just provide the relevant context.

> `_sprite_cache_size` ... But it is also not in mega pixels. It is in the amount of bytes a pixel consumes

This is an example of what I define as unreasonable. A pixel consuming 128 bytes. Really? :-)

No, it's in megapixels.

https://github.com/OpenTTD/OpenTTD/blob/47eabe0cd9fdb5e6dcd9b2c22f00e54564baba73/src/spritecache.cpp#L969-L970

`bpp` is bits-per-pixel, therefore `bpp / 8` is bytes-per-pixel. According to your claim that `_sprite_cache_size` is bytes-per-pixel, `target_size` would now become `bytes_per_pixel^2 * 1024^2`, which is nonsense.

Perhaps a more correct interpretation of the code is that `_sprite_cache_size` is nowadys indeed in the unit mega _pixels_ ?
It started its life in the age of 8bpp gfx, where 1 pixel == 1 byte, meaning 1 megabyte == 1 megapixel.
Some time later `GfxInitSpriteCache()` added target bitdepth scaling, but did not update the comment to reflect this fact.

Doesn't this sound like a more plausible scenario than completely turning the unit of that variable on its head, making it be bytes-per-pixel?

> not 66%

66 * 1.5 = 100. Yes, 66% (knowing fully well this is +/- 1 due to integer math).

> The overflow happens on 1024, not 512.

Sorry, my train of thought was already way ahead of what I wrote, and I completely forgot to add the required context.

When you run it as a 32-bit application, specifically on a 32-bit Windows (*), the application address space is by default 2GB. Any allocation attempt larger than (2GB - overhead) will fail. Yes, the code handles it and cuts the requested amount in half (iteratively). That's not my point.

If we limit ourselves to arithmetic overflow on the size calculation, the max value of `_sprite_cache_size` is 682 (683 will overflow), which is put to rest by:
> And by no accident, you cannot set _sprite_cache_size higher than 512.

Thanks.

> curious why you think 768MB is not reasonable, and what you expected there :)

To waste almost three quarters of a gigabyte memory (virtual or not) that will forever go unused is an example of what I call unreasonable.

What I expected is to only allocate the amount of memory actually required.
I had hoped this would be obvious.

The cache can grow should it need to. If chunked (even by some existing container like `std::queue`), chances are good (1) it would be non-measurable access overhead while allowing it two grow on demand, but most importantly not over-allocate like crazy.

Sidenote: 768 MB is enough memory to run over fourty instances of my previous OpenTTD build (from back in the SVN days). I just verified. :-)

(1) Speculative statement. Actual profiling would be required.

(*) "Please Wait..." is a registered trademark of Microsoft Corporation. It does not apply to train signals.

**Comment by TrueBrain** [comment] 2023-11-24 15:38
Thank you for your detailed reply; it gives much more context to the initial text :)

To summarize, you agree that there are no code-wise flaws, there are no overflows, nothing breaks in any situation, and even Win32 still works as expected. So that is good.

Which brings us to the summary of the reason you opened this issue, I guess: you consider allocating (virtual) memory of 768MB excessive.

Personally, on any machine of the last, what, 10 years, I do not see why this would be any issue. So from my perspective (and this is not a bad thing, just an observation), the argument is more about the purity of it all, rather than any actual issue you are having, right?

In that case, all I can say is: we are more than happy to accept any Pull Request to improve the situation. So if you are up for it, give it a spin, and see if you can do it without any (significant) performance penalty. Most of us actually enjoy a discussion about the purity of it all, so it would be welcomed.

That said, OpenTTD tries to balance performance in all kinds of different ways; having a decent-sized sprite-cache helps a lot in many situations, like max-zoom-out, etc, to get more fps.
Sadly, we once upon a blue moon thought: let's add zoom-in sprites up to 4x! And we all regretted it since (not really, but it hurts memory-usage a lot).
Which brings us to today, where we reserve 768MB of memory, to make sure we can render most common situations with good performance. It is a balance. Could it be improved? Sure! Without performance penalty .. maybe? But nobody has bothered to proof that, one way or the other.

Either way, as this is a mostly virtual allocation, and it doesn't use the actual 768MB of memory on startup, I personally don't see a big issue here. You can still run those 40 instances of OpenTTD in the same amount of memory as before (ignoring any other parts of the game that might have increased in (actual) memory consumption), so I have a hard time seeing an actual problem here that requires attention. If you feel otherwise, please do disagree with me, that is more than fine :)

But as mentioned, it for sure could be done better, and as mentioned, PRs are more than welcome :)

**Comment by TrueBrain** [comment] 2023-11-26 09:43
Seems someone took me up on the offer of `we are more than happy to accept any Pull Request to improve the situation` :D #11495 reworks how we manager the sprite cache.

Either way, going to close this issue, as it is not a bug (rather an opinion). As mentioned, we are not in disagreement in the purity of it all, and we always love a good discussion about that. Sadly, this bug-tracker is not the place for that discussion, as we would like to keep it for bugs as much as possible. It is easy to lose sight of what is actual a bug and what is not otherwise :)

Feel free to join us on Discord to have these conversations, as there you also see we actually enjoy a good conversation about these things :D And if we missed an actual bug here, ofc, let us know too!

**Closed as not planned by TrueBrain** 2023-11-26 09:43 UTC
