### ISSUE TITLE
[Bug]: Train can't find the route to local depot

### ISSUE THREAD

**Issue by ldpl** [OpenTTD/OpenTTD#10565] opened 2023-03-12 18:12 UTC
### Version of OpenTTD

12.2, 13.0, master(be69aa6257717025a236ecd7d08664d1dc25faf4)

### Expected result

Train goes to the closest depot when send to depot button is clicked.

### Actual result

Game shows the error "Unable to find route to local depot".
Possibly caused by train already having reserved path past the closest depot.

### Steps to reproduce

1. Load the attached savegame
2. Send train to the depot
[depot-bug-test.zip](https://github.com/OpenTTD/OpenTTD/files/10951632/depot-bug-test.zip)

**Comment by 2TallTyler** [comment] 2023-03-13 14:01
Duplicate of #9817, which was closed as "won't, or can't, fix" after some discussion. Feel free to reopen if you disagree.

![path](https://user-images.githubusercontent.com/55058389/224722797-a1a04c0c-d244-45ad-9623-b22578536bc5.png)

**Closed as not planned by 2TallTyler** 2023-03-13 14:01 UTC
