### ISSUE TITLE
Ships saying they are lost

### ISSUE THREAD

**Issue by Bmo006** [OpenTTD/OpenTTD#8937] opened 2021-04-03 13:49 UTC
## Expected result 
I expect the ships to not constantly say that they're lost

## Actual result 
The ships sometimes pop up with a message saying that they're lost no matter how many bouys i route them through. Even though they say that they're lost they don't act like it. They move to and from the stops I've set for them without problems and they make money. It's not all the ships that do this, only the ones that travel long distance. I do place bouys if they have to travel far.
![Pic1](https://user-images.githubusercontent.com/81863632/113480275-d33c9b80-9493-11eb-8f98-f51f3deb58ae.png)
Ship says that it's lost
![Pic2](https://user-images.githubusercontent.com/81863632/113480100-f0249f00-9492-11eb-98da-b25b2b2eaff4.png)
Ship leaves oil platforms full
![Pic3](https://user-images.githubusercontent.com/81863632/113480101-f0bd3580-9492-11eb-87f8-eb96c71f3cea.png)
Makes it's way towards refinery
![Pic4](https://user-images.githubusercontent.com/81863632/113480102-f155cc00-9492-11eb-88f3-e627476c8f18.png)
Unloads at refinery
![Pic5](https://user-images.githubusercontent.com/81863632/113480103-f155cc00-9492-11eb-98d9-a6687ea5a764.png)
Makes it's way back without problem

## Steps to reproduce
Create long distance lines for the ships and after a while there will pop up a message saying that Ship#X is lost.

**Comment by James103** [comment] 2021-04-03 15:31
As a workaround, can you try adding buoys along the route that the ships are supposed to take? Remember to place the buoys then add them to the ship's orders, so that the ship can use them.

**Comment by LordAro** [comment] 2021-04-04 11:42
Duplicate of #8001

**Closed as completed by LordAro** 2021-04-04 11:42 UTC
