### ISSUE TITLE
Ship is said to be lost when it find its way just fine

### ISSUE THREAD

**Issue by DonaldDuck313** [OpenTTD/OpenTTD#8086] opened 2020-04-14 14:58 UTC
## Version of OpenTTD
1.10.0

## Expected result
It shouldn't say a ship is lost when it's not.

## Actual result
It says the ship is lost, but then it finds its way to its destination just fine. Maybe that has something to do with that its destination is on a river? But I also have another ship with a destination on a river (ship 19 in the saved game that can be downloaded below) and it never says that ship is lost.

## Steps to reproduce
1. Open the saved game that can be downloaded [here](https://gofile.io/?c=bGvBq4).
2. Wait for ship 21 to leave Österbro oil rig.
3. It will say ship 21 is lost. Do nothing.
4. After a while, it will find its way to its destination, Österbro oljeraffinaderi, just fine without doing anything. So it isn't lost.

**Comment by LordAro** [comment] 2020-04-14 15:02
We're aware of the issue. Duplicate of #8001

**Closed as completed by LordAro** 2020-04-14 15:02 UTC

**Comment by andythenorth** [comment] 2020-04-14 15:05
Thanks for letting us know, appreciated.
