### ISSUE TITLE
Crash when loading Multiplayer list

### ISSUE THREAD

**Issue by GuideRail** [OpenTTD/OpenTTD#7854] opened 2019-12-03 05:55 UTC
1.9.1 Version of OpenTTD (Mac)

Expected result: The Multiplayer list should have opened and allowed me to choose a game

Actual result: The list loaded but the game shutdown and bug report came up

Steps to reproduce: Open the Multiplayer menu and click "find servers" at the bottom and it crashes.

This problem has been present for a while now, it happens every time and I cannot play multiplayer because of it
[crash.log](https://github.com/OpenTTD/OpenTTD/files/3914840/crash.log)
![crash](https://user-images.githubusercontent.com/58458200/70024136-22936300-15e5-11ea-9dc4-d4950d78523b.png)

The last autosave was autosave 0

**Comment by nielsmh** [comment] 2019-12-03 07:02
Known bug, was fixed in version 1.9.3

**Closed as completed by nielsmh** 2019-12-03 07:02 UTC

**Comment by andythenorth** [comment] 2019-12-04 07:04
Thanks for reporting :)

**Comment by LordAro** [comment] 2019-12-04 07:11
Duplicate of #7704, specifically
