### ISSUE TITLE
Cannot open the file when starting AI downloaded via online service

### ISSUE THREAD

**Issue by SamuXarick** [OpenTTD/OpenTTD#8230] opened 2020-06-19 21:31 UTC
## Version of OpenTTD
1.10.2
## Expected result
Script starts normaly
## Actual result
Script error with: cannot open the file
## Steps to reproduce
Download NotPerfectAI from the online service, set it up and start a new game.

![Unnamed, 1950-01-09](https://user-images.githubusercontent.com/43006711/85180918-909b3100-b27c-11ea-8f69-c9203f6c9116.png)

**Comment by James103** [comment] 2020-06-19 22:31
Have you tried manually downloading the package from outside of OpenTTD's internal online content downloader and checking that it works there? This could be related to #6969.

**Comment by LordAro** [comment] 2020-06-19 22:59
Curious, but seems very unlikely to be (directly) related to #6969

**Comment by glx22** [comment] 2020-06-19 23:05
I'm trying to trace it

**Comment by glx22** [comment] 2020-06-19 23:32
I think it's because 
```
require("../enginemanager.nut");
require("../utils.nut");
require("../investment.nut");
require("../industry.nut");
require("../town.nut");
```

**Comment by LordAro** [comment] 2020-06-19 23:34
Can you elaborate?

**Comment by glx22** [comment] 2020-06-19 23:57
The "cannot open the file" error is thrown when trying to open "notperfectai-1.0\\transportplan\\..\\enginemanager.nut" because https://github.com/OpenTTD/OpenTTD/blob/9aca6ff971e95fbeaff9302cf5d8d44a80ed0206/src/fileio.cpp#L501 can't find it in the tar.

**Comment by James103** [comment] 2020-06-20 00:03
Is the file actually present in the tar and just not being detected by OpenTTD's code?

**Comment by nielsmh** [comment] 2020-06-20 06:32
Based on glx's comment I understand the issue to be that OpenTTD is looking for a file named `notperfectai-1.0\transportplan\..\enginemanager.nut` but the tar contains a file named `notperfectai-1.0\enginemanager.nut` - i.e. the issue is that OpenTTD is not resolving relative paths by collapsing the subdirectory and up-directory in the path to nothing.
So the solution would be to look for `..` path components and have them remove the previous path component.

**Closed as completed** 2020-06-22 12:21 UTC
Labels: bug
