### ISSUE TITLE
Game cutting of savefile name after charecters with diacritics.

### ISSUE THREAD

**Issue by Bertik23** [OpenTTD/OpenTTD#8292] opened 2020-08-10 11:16 UTC
## Version of OpenTTD
1.10.2, 1.10.3

## Expected result
Saving the game in a `testík.sav` file

## Actual result
The game was saved in a `test` file

## Steps to reproduce
1. Make a new game, or open a savefile.
1. Try to save the game.
1. Use a name that contains a character with diacritics like ěščřžýáíéťůúňď eg. `testík`
1. Look at the savefile folder, there should be a file with no the name you used, but cut of after the first character with diacritics eg. `test` instead of the name with the `.sav` ending eg. `testík.sav`

## System info
Operating System: Kubuntu 20.04
KDE Plasma Version: 5.18.5
KDE Frameworks Version: 5.68.0
Qt Version: 5.12.8
Kernel Version: 5.4.0-42-generic
OS Type: 64-bit
Processors: 4 × Intel® Core™ i3-2328M CPU @ 2.20GHz
Memory: 3,7 GiB

**Comment by stormcone** [comment] 2020-09-21 17:06
On my system I can not reproduce this with OpenTTD 1.10.3.

Operating System: Fedora 32
KDE Plasma Version: 5.18.5
KDE Frameworks Version: 5.70.0
Qt Version: 5.14.2
Kernel Version: 5.8.9-200.fc32.x86_64
OS Type: 64-bit
File system: ext4

Maybe something is misconfigured on your system. 

![openttd_save](https://user-images.githubusercontent.com/48624099/93798087-5fe0e400-fc3d-11ea-8d08-376d3f794048.png)

**Comment by UnsuspiciousGooball** [comment] 2020-12-28 13:13
Works for me
![image](https://user-images.githubusercontent.com/67861995/103216506-871f0f80-4916-11eb-8f9e-bad040a3a87b.png)
Operating System: Debian GNU/Linux
KDE Plasma Version: 5.19.5
KDE Frameworks Version: 5.74.0
Qt Version: 5.15.2
Kernel Version: 5.7.0-1-amd64
OS Type: 64-bit
Processors: 8 × AMD Ryzen 7 3700U with Radeon Vega Mobile Gfx
Memory: 13.6 GiB of RAM
Graphics Processor: AMD Radeon™ Vega 10 Graphics

**Comment by LordAro** [comment] 2021-02-21 16:57
Failing any success in reproducing this, I'm going to close the issue. Let us know if you can work out what about your system is different

**Closed as completed by LordAro** 2021-02-21 16:57 UTC
