### ISSUE TITLE
[Bug]: Dedicated server disconnecting from game coordinator all the time

### ISSUE THREAD

**Issue by masterofobzene** [OpenTTD/OpenTTD#10693] opened 2023-04-22 18:21 UTC
### Version of OpenTTD

13.1 Windows 10 x64

### Expected result

For some reason, it loses connectivity to game coordinator, stopping the users from being able to join.

`dbg: [net] Connection with Game Coordinator lost; reconnecting...`

This happens all the time and seems random. Sometimes the server goes offline in the server list, sometimes it is there but no one can join.

My internet connection is stable. DNS is cloudflare and secondary is Quad9.

Can you tell me if there are other connections going on? all the documentation says the game only uses port 3979, but I see ports 3974 - 3979 being used on the server log. Could some "keep alive" connections being firewalled?

### Actual result

```
dbg: [net] Connection with Game Coordinator lost; reconnecting...
dbg: [net] Connected to coordinator.openttd.org:3976
dbg: [net] Connected to stun.openttd.org:3975
```
After the "reconnection" the server is still not accesible.

### Steps to reproduce

Just let a server running.

**Comment by TrueBrain** [comment] 2023-05-26 18:32
I am sorry to read nobody replied to this ticket; but obvious #10877 is a duplicate of this :) So closing this now :)

**Closed as not planned by TrueBrain** 2023-05-26 18:32 UTC

**Comment by PeterN** [comment] 2023-06-23 13:41
This was separate issue with the game coordinator service which has been resolved this morning.
