### ISSUE TITLE
[Crash]: Click on OpenTTD to start it but it doesn't run

### ISSUE THREAD

**Issue by OldLegendElf** [OpenTTD/OpenTTD#12713] opened 2024-05-23 10:29 UTC
### Version of OpenTTD

OpenTTD 14.1 / Windows 10 22H2(Chinese (Traditional)

### Steps to reproduce

I'm using NB and the monitor resolution is only 1360x768 max, I installed OpenTTD from microsoft store last year, and at that time it was normal to use the second monitor to resolve 1920x1080 for gaming.

Since then, I don't have a second monitor anymore, and I haven't opened OpenTTD until yesterday, when I used the NB's native screen to play a game, and opened it once, but when it ran the window, the game closed and crashed on its own before it even got to the screen, and when I tried to start it up again after that, it didn't even produce a working window.

I tried various administrator rights and compatibility settings, but I couldn't get the window to open again, so I had to remove the game.
I had to remove the game. After reinstalling the game, the game window would not show up again, and Win10 seemed to recognize it as unbootable.

Then I found other versions on the OpenTTD forums and tried to run them, but all of them only showed the execution window once, but before I could change the resolution, the window closed.
There is nothing I can do but post a message asking for help, thank.

### Upload crash files

I can't find the crash report file.

**Comment by glx22** [comment] 2024-05-23 17:10
Could be a duplicate of #12648.
There's a link to a test build in this issue. Please try it.

**Comment by OldLegendElf** [comment] 2024-05-24 03:23
> 可能是 #12648 的副本。本期中有一個指向測試版本的連結。請嘗試一下。

It's working. Thank you

**Comment by 2TallTyler** [comment] 2024-07-29 19:42
I am closing this since the author has not responded. @OldLegendElf, if you're still having trouble, let us know and I'll reopen the ticket. 🙂

**Closed as completed by 2TallTyler** 2024-07-29 19:42 UTC
Labels: waiting on author
