### ISSUE TITLE
Cant find multiplayer servers on mac

### ISSUE THREAD

**Issue by Smashby7** [OpenTTD/OpenTTD#7722] opened 2019-09-06 01:02 UTC
## Steps to reproduce - Open the game on the latest version (or version of the date above) on Mac OS X. Click multiplayer. It should open a blue menu. At the bottom you will see 4 buttons: "Find Server", "Add Server", "Start Server", and "Cancel". Hit Find server. I'm not entirely sure what causes the crash, and the crash report just says that there was a fatal error, to report the crash here, and says it opened 3 crash related files. I'm not really sure what to do, so let me know if you can figure it out.

**Comment by glx22** [comment] 2019-09-06 01:12
Duplicate of #7704

**Closed as completed by glx22** 2019-09-06 01:12 UTC
