### ISSUE TITLE
Game crashes after alt-tabbing

### ISSUE THREAD

**Issue by witchcult** [OpenTTD/OpenTTD#8811] opened 2021-03-06 15:07 UTC
## Version of OpenTTD
1.11.0-beta2
## Expected result
Alt-tab back to the game
## Actual result
Game crashes after switching windows between OpenTTD and other apps. Initially it only occured when I paused the game and alt-tabbed after that but later I've realized it also crashes without pausing.
## Steps to reproduce
0. Load a game
1. (optional) Pause a game
2. Change windows (alt-tab)
3. While trying to open OpenTTD back, the game crashes.
[crash.log](https://github.com/OpenTTD/OpenTTD/files/6095554/crash.log)

**Comment by James103** [comment] 2021-03-06 15:11
Duplicate of #8775
To prevent this kind of crash, update to the latest OpenTTD nightly (more specifically: c656633 or later)

**Closed** 2021-03-06 15:24 UTC
