### ISSUE TITLE
OnHundredthTick() not called once per 100 ticks

### ISSUE THREAD

**Issue by floodious** [OpenTTD/OpenTTD#7904] opened 2020-01-05 21:43 UTC
## Versions
1.10.0-RC1

## Expected result
OnHundredthTick() should be called once for every 100 ticks.

## Actual result
OnHundredthTick() is called once every 3 seconds.

## Steps to reproduce
Where a tick takes any time other than exactly 30 ms to process, the assumption PER_TICK == 30 is false. To simulate such a condition add sleep(1000 ms) inside GameLoop().

https://github.com/OpenTTD/OpenTTD/blob/5b52f25902dad09e2f237ce798e9873a4ac42f4f/src/window.cpp#L3128-L3132

https://github.com/OpenTTD/OpenTTD/blob/5b52f25902dad09e2f237ce798e9873a4ac42f4f/src/window.cpp#L3179-L3186

**Comment by TrueBrain** [comment] 2021-01-06 22:04
Although one can say that #6780 should have renamed the function when the implementation got changed, by no means this is a bug. It might be confusing to the reader, and as such we would accept a PR to rename this function into a proper name (and in fact, we would welcome that!).

However, to be clear, we are not going to change the implementation to comply with the name :D That would be silly ;)

Anyway, as this is not a bug, I am going to close this issue. If you feel up for it, please do make a PR. Otherwise, one of the devs will come around doing that sooner or later :)

Tnx!

**Closed as completed by TrueBrain** 2021-01-06 22:04 UTC
