### ISSUE TITLE
Presignal doesn't work on long distance

### ISSUE THREAD

**Issue by ale84s** [OpenTTD/OpenTTD#7087] opened 2019-01-23 18:41 UTC
Presignal become green altough signal exit is red on long distance. 
![presignal-not-work](https://user-images.githubusercontent.com/46973574/51629014-d6987c00-1f46-11e9-8370-93bec3de4788.png)

**Comment by Eddi-z** [comment] 2019-01-23 21:50
You have two exit signals in this block, the entry signal will only get red if BOTH are red. block signals will never work properly in such a two-way setup, and you should be using path signals instead.

IIRC there is a distance where presignals stop working, but that should be 256 tiles or something like that, nothing that should apply to your situation here

**Comment by andythenorth** [comment] 2019-01-23 21:52
Closing, per Eddi's comments.  Thanks for contributing!

**Comment by ale84s** [comment] 2019-01-23 22:07
> You have two exit signals in this block, the entry signal will only get red if BOTH are red. block signals will never work properly in such a two-way setup, and you should be using path signals instead.
> 
> IIRC there is a distance where presignals stop working, but that should be 256 tiles or something like that, nothing that should apply to your situation here

No, there's only one exit signal into the block, after the pre-signal: on short distance this configuration work properly, it stop working when the distance between pre-signal and exit signal increase. The railway line into the screenshot is created only to show the issue.

**Comment by planetmaker** [comment] 2019-01-23 22:20
Can you provide a savegame which shows the behaviour?

**Comment by glx22** [comment] 2019-01-23 22:20
The non reachable signal 2 tiles away is probably green, pre-signals don't check if exit signal is reachable, only the connection of the track tiles. This behaviour is often abused to make priority tracks.
https://wiki.openttd.org/Signals#Limitation

**Comment by ale84s** [comment] 2019-01-24 00:07
> Can you provide a savegame which shows the behaviour?


[Nufingley Market Transport, 23 Mag 1951.zip](https://github.com/OpenTTD/OpenTTD/files/2789656/Nufingley.Market.Transport.23.Mag.1951.zip)

**Comment by PeterN** [comment] 2019-01-25 23:37
Your savegame confirms there are two exit signals in this block, and the one nearest Train 2 is green, as glx22 wrote. This is not a bug, this is how pre-signals work. Switch to using path signals for a solution that will work as you expect.

**Closed as completed by PeterN** 2019-01-25 23:37 UTC
