### ISSUE TITLE
Can't insert new order... Vehicle can't go to that station (Maglev Train)

### ISSUE THREAD

**Issue by aljowen** [OpenTTD/OpenTTD#7897] opened 2020-01-04 15:19 UTC
## Version
OpenTTD 1.9.3 (may be present in other versions, haven't tested)
Please note that NewGRF's "FIRS 3.0.10" and "Original vehicles cargo set" are in use on this save file. I am not familiar enough with OpenTTD to know if they are the cause of the issue, It's plausible that they may be.

## Expected:
For the station to be added to a trains orders

## Error message:
![image](https://user-images.githubusercontent.com/16223353/71767326-38a58380-2f03-11ea-9a89-298347d38852.png)

## Steps to reproduce
Select any train (use train 869 to make things easy), open the "show trains orders" window, use the "Go To" button to add a new order for "Pesdale East" (located just north-east of the depot containing train 869), the error message will be received.

I have found that cloning another trains orders ("Go To" and select another train rather than a station) functions as a workaround. But that does of course have limitations for creating lines that could go between two affected stations.

There are multiple stations with this issue, "Pintditch Stores" is another example. However, I haven't tested every station on the map since there is quite a few. I haven't spotted any pattern.
[Nantberg Transport, 1st Aug 2556.zip](https://github.com/OpenTTD/OpenTTD/files/4022055/Nantberg.Transport.1st.Aug.2556.zip)

**Comment by nielsmh** [comment] 2020-01-04 15:22
Duplicate of #7881.
Known bug in 1.9.3, workaround is to make sure the tile below the station sign belongs to the station in question.

**Closed as completed by nielsmh** 2020-01-04 15:22 UTC

**Comment by aljowen** [comment] 2020-01-04 15:23
Amazed that issue didn't surface in search results. Thanks for the reply :)

EDIT: Just gonna repeat myself by stating that there is another workaround, since you probably spotted the issue without reading into the body of text.

"I have found that cloning another trains orders functions as a workaround."

**Comment by zilti** [comment] 2021-04-26 13:53
That bug is in 1.10.3 as well.

**Comment by James103** [comment] 2021-04-26 13:57
@zilti Did you try reproducing this in 1.11.1 as well? If you can reproduce it, can you please make a new bug report about whatever bug you're experiencing?

**Comment by LordAro** [comment] 2021-04-26 14:01
This issue was very definitely fixed in 1.10. Whatever you're seeing is a different issue

**Comment by maaaaaaaaaad** [comment] 2022-04-02 19:56
Not sure if this is related to the previous bug but I get the same error message when trying to assign a truck to a loading bay. 

<img width="1291" alt="Screen Shot 2022-04-02 at 3 52 05 PM" src="https://user-images.githubusercontent.com/39970290/161399011-9ef51734-91e5-4f5a-963e-0ebd431a7041.png">

**Comment by nielsmh** [comment] 2022-04-02 20:08
That looks like you're sending an articulated (or long) truck into a loading bay instead of a truck stop. That's intentional. Use a drive-through truck stop instead.

**Comment by maaaaaaaaaad** [comment] 2022-04-02 20:24
Got it, haven't played in a while.
