### ISSUE TITLE
[Crash]: Crash on title / configurations

### ISSUE THREAD

**Issue by nplemonsCW** [OpenTTD/OpenTTD#9685] opened 2021-11-09 17:55 UTC
### Version of OpenTTD

12.0, Windows 10

### Steps to reproduce

1.  Open the game
2.  Wait 20-30 seconds

It doesn't matter if I just sit on the intro screen or if I try to work with any of the sub-menus, I've got about 20-30 seconds before it crashes, every single time.  If I very quickly start a new game or load an old saved game it will proceed and appears to be stable.

I have found this crash to be 100% repeatable, unfortunately.

System Specs:
Intel i9-9900K
64 GB RAM
ASUS WS Z390 Pro
EVGA GeForce RTX 3080
Windows 10 Pro - Build 20H2

[crashlog.zip](https://github.com/OpenTTD/OpenTTD/files/7506953/crashlog.zip)

**Comment by LordAro** [comment] 2021-11-09 18:15
Duplicate of #9622 - Upgrade to 12.1 !

**Closed as completed by LordAro** 2021-11-09 18:15 UTC
