### ISSUE TITLE
[Bug]: Initializing available engine GUI forces selection of top vehicle, even if it's an unavailable variant

### ISSUE THREAD

**Issue by George-VB** [OpenTTD/OpenTTD#10371] opened 2023-01-18 10:40 UTC
### Version of OpenTTD

n20230115

### Expected result

additional_text is the same for the vehicle (when building a new one) regardless the conditions of viewing 

### Actual result

additional_text is not displayed for vehicle, that is a vehicle group and not available
BUT, if  the filters and the sort order makes it the first one in the list, when you open the build new vehicle window in the depot, additional_text is displayed.

I suppose that it was intended to not display it in all the cases, but it would be better to display it always. In case the GRF author wishes to display no text, he can simply fail additional_text callback

![image](https://user-images.githubusercontent.com/43310520/213149660-c1f13943-3418-4cc2-a85b-00d9f8396a02.png)
![image](https://user-images.githubusercontent.com/43310520/213149754-ac96bc6e-940c-4726-94e2-687245d52f4b.png)

### Steps to reproduce

1) Crate a new game after 1965 with xussrset
2) Build a 3KV DC depot
3) Open the new vehicles window and specify running cost from 0 up as sorting rule
4) Reopen the new vehicles window. You see ER2 on the first line with some additional text provided
5) Choose over vehicle, then go back to ER2. You see no additional text
    
[xussr.zip](https://github.com/OpenTTD/OpenTTD/files/10444902/xussr.zip)

**Comment by 2TallTyler** [comment] 2023-01-22 13:01
In the second screenshot, no vehicle is selected for purchase. Notice how the action buttons are greyed out.

**Comment by George-VB** [comment] 2023-01-22 13:19
> In the second screenshot, no vehicle is selected for purchase. Notice how the action buttons are greyed out.
As soon as you click the group with the mouse pointer, you get the situation, represented in the screenshot.
OTTD behaves this way

**Comment by 2TallTyler** [comment] 2023-01-22 14:09
I can't reproduce using the attached NewGRF -- the ER2 isn't the top vehicle and following your instructions doesn't have the same result. Could you record a screen capture, perhaps?

**Comment by George-VB** [comment] 2023-01-23 17:22
https://user-images.githubusercontent.com/43310520/214106372-327a5290-399a-4aa2-8e7a-a702685dbea4.mp4

sure.

**Comment by 2TallTyler** [comment] 2023-01-23 19:47
The problem isn't the additional_text callback, it's that reinitializing the window (by re-opening it or clicking `Available Trains`) is forcibly selecting the top vehicle, even if it's an unavailable variant.

Paging @PeterN... 🙂

**Comment by George-VB** [comment] 2023-01-23 21:54
Well, if it would be possible, it would be nice to have addition text displayed even for unavailable vehicle (I could put some group description there)

**Comment by 2TallTyler** [comment] 2023-01-23 22:32
For text to be displayed, the vehicle would have to be selectable even if unavailable. In my view, allowing an unavailable vehicle to be selected is the bug which needs to be fixed here.

**Comment by 2TallTyler** [comment] 2023-01-24 12:51
Fixed by #10404

**Closed as completed** 2023-01-24 12:51 UTC
Labels: bug
