### ISSUE TITLE
In MacOS, the interface is incredibly small

### ISSUE THREAD

**Issue by giordy** [OpenTTD/OpenTTD#8786] opened 2021-03-01 18:30 UTC
## Version of OpenTTD

1.11.0-beta2
MacOS Big Sur 11.2.2

## Expected result
I expected the game to have an interface similar to version 1.10.3

## Actual result
The font and the controls are incredibly small and the mouse moves somewhat sluggishly.

## Steps to reproduce
Because of #8785 I could not start clean and I had to reuse the resources that I had available on disk from 1.10.3.
I don't know if this is a factor in the bug.

This is how the game looks:
https://user-images.githubusercontent.com/6016950/109541721-67e26100-7ac4-11eb-8348-95a43043a8cf.mp4

Towards the end you can see how the mouse cursor changes between desktop and OpenTTD, hopefully it helps assessing the difference in scale.

**Comment by LordAro** [comment] 2021-03-01 18:33
This will be a consequence of #8519. If you switch both GUI & font size options to "auto detect" it should increase the scaling of the windows as appropriate

**Comment by LordAro** [comment] 2021-03-01 18:36
If that's still unacceptable to you, there's the config file setting `allow_hidpi`. Set that to false to restore the previous behaviour.

As this is working as intended, I'm going to close this now

**Closed as completed by LordAro** 2021-03-01 18:36 UTC

**Comment by giordy** [comment] 2021-03-01 18:41
Ah you're right, switching both GUI & font size options to "auto detect" worked and fixed the issue, thanks! 👍🏻 

<img width="1440" alt="dimension fixed" src="https://user-images.githubusercontent.com/6016950/109543001-16d36c80-7ac6-11eb-9a85-e923c8bc4999.png">

**Comment by scovit** [comment] 2021-03-06 21:56
I think this issue should not be closed since when upgrading from version 1.10.3 the settings are not the defaults.
